### ISSUE TITLE
Intl.DateTimeFormat() TimeZoneName options not working as expected. 

### ISSUE THREAD

**Issue by gustavoccintrao** [facebook/hermes#1001]
My app brokes when I try to use 'shortOffset' as an TimeZoneName option. 

`com.facebook.hermes.intl.JSRangeErrorException: String option expected but not found.`

As a workaround we are using 'short' instead. What bugs me is that 'short', according to MDN,  should return the localized form and instead it's just returning the short localized GMT format (which was exactly what shortOffset should return). 

For example: 

-  In iOS, using 'America/Manaus' and 'shortOffset' it returns 'GMT-4', but using 'short' it just returns 'AMT'. Which is the expected return.
-  In Android using the same configuration ('America/Manaus', 'shortOffset') the app just crashes with the error above. But using 'short' returns 'GMT-4' (which is what we want but not the correct way according to the documentation).

**Comment by neildhar** [comment]
Thank you for finding and reporting this, we will have a fix shortly.
