### ISSUE TITLE
Any plan to support promise and async function?

### ISSUE THREAD

**Issue by mko-io** [facebook/hermes#101]
Hi Team, 
I  know Hermes is targeting ES6 for simplicity and performance reason, but without Promise and async function will make a lot things hard to do, because Web Devs are getting used to these features now. Any plan in the future to support them?

**Comment by avp** [comment]
`Promise` is part of the ES6 spec and we're investigating it. We're determining what the best way of providing support for it will be in Hermes. 

While `async` is part of a later version of the spec, we do plan on updating Hermes to be as compliant as we can without sacrificing code quality, performance, and memory usage; this means that we're also investigating what we can do to add support for `async` natively.

That being said, remember that code provided to Hermes via React Native via the default pipeline undergoes Babel transformation, so the particular set of features we support natively shouldn't stop developers from using these features when actually writing code. See [this comment](https://github.com/facebook/hermes/issues/57#issuecomment-513381978) for elaboration.

**Comment by mko-io** [comment]
I just think these 2 patterns are so common I'd prefer not transpile them, thank for the explanation.
