### ISSUE TITLE
Using hermes c/c++ api

### ISSUE THREAD

**Issue by David00154** [facebook/hermes#1010]
How do i use hermes with c/c++ ????

**Comment by tmikov** [comment]
If you mean "how to use Hermes directly from c/c++, without React Native", then the answer is that Hermes is a C++ library intended to be used from C++. You can find more information about using it without React Native in the answers to these previous questions: https://github.com/facebook/hermes/issues/43, https://github.com/facebook/hermes/issues/56, https://github.com/facebook/hermes/issues/326, https://github.com/facebook/hermes/issues/958.
