### ISSUE TITLE
Missing ToNumber calls

### ISSUE THREAD

**Issue by gibson042** [facebook/hermes#1013]
## Bug Description

https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-arraysetlength requires two uses of ToNumber when setting an array's length (the first in step 3 ToUint32 and the second in step 4), but Hermes performs only one.

- [x] I have ~~run `gradle clean` and~~ confirmed this bug does not occur with JSC

Hermes version: 0.11.0

## Steps To Reproduce

code example:
```js
const spy = {
  [Symbol.toPrimitive](hint) {
    print(`toPrimitive ${hint}`);
    return hint === "number" ? 4 : "done";
  },
};
print(String([].length = spy));
```

## The Expected Behavior
```
toPrimitive number
toPrimitive number
toPrimitive string
done
```

**Comment by tmikov** [comment]
It is a deliberate design decision to not support this legacy behavior. Thank you for pointing it out, I will add it to the "features" doc. 

Is it creating an actual problem, or is this just a theoretical issue?

**Comment by tmikov** [comment]
On second thought, we will fix it, since it is a very cheap fix (even if it makes no sense).
