### ISSUE TITLE
Lower frequency of compacting in Hades GC compared to GenGC, resulting in higher average memory usage in the Android App

### ISSUE THREAD

**Issue by EndSmile** [facebook/hermes#1017]
## Describe

We have recently upgraded the Hermes version in our Android application from 0.5.1 to 0.71 and have encountered some issues while conducting memory comparison tests.

1. According to the memory data printed in the HermesGC logs, the new version saves 30% of memory.
2. However, when we look at the memory statistics via **`adb shell dumpsys meminfo`**, we noticed that GenGC always returns memory to the system during each full GC. In contrast, HadesGC doesn't.

Memory usage increases over time as shown in the following image:
![image](https://github.com/facebook/hermes/assets/15260299/172ef9b6-030c-4d71-bff6-6c098ff5de14)
The segments' memory is classified as 'other'. As can be seen:

- In the older Hermes version (yellow line), there are significant fluctuations, with memory being returned to the OS during full GC.
- In the new Hermes version (orange line), the trend is much smoother, with memory almost never being returned to the OS.

### Log
Here are the logs for HadesGC:
I printed **`totalBytes`** and **`threshold`** from **`HadesGC::prepareCompactee`** and found that it always falls short of the standard for compacting.

```
prologCopy code
HermesGC: prepareCompactee totalBytes:33442 threshold:37234
HermesGC: collection:young, elapsed wall time = 3 ms,cpu time = 3041,used 3926KB -> 820KB, heap size 36864KB -> 36864KB, tags:[old gen start]
HermesGC: collection:young, elapsed wall time = 4 ms,cpu time = 4400,used 3152KB -> 1009KB, heap size 36864KB -> 36864KB, tags:[complete marking]
HermesGC: collection:old, elapsed wall time = 1514 ms,cpu time = 1037,used 28721KB -> 24470KB, heap size 36864KB -> 36864KB, tags:[]

```

For GenGC, the logs trigger **`Removed OG heap extents`**:

```
prologCopy code
05-26 15:34:31.632 14426 14857 I HermesGC: YoungGen collection[RN]: elapsed wall time = 14.636693 ms, cpu time = 14.600000 ms
05-26 15:34:31.632 14426 14857 I HermesGC:     used = 288246920, heap size = 295796736.
05-26 15:34:33.086 14426 14857 I HermesGC: Full collection[RN]: elapsed wall time = 1177.213461 ms, cpu time = 1154.512000 ms
05-26 15:34:33.086 14426 14857 I HermesGC:     used = 159429749, heap size = 320446464.
05-26 15:34:33.086 14426 14857 I HermesGC: Removed OG heap extents for 40
05-26 15:34:33.086 14426 14857 I HermesGC: Removed OG heap extents for 50
05-26 15:34:33.086 14426 14857 I HermesGC: Removed OG heap extents for 60

```

Note: The RuntimeConfig parameters were not modified for both old and new versions and the default values were used.

## Problem

Upon reading the source code of HadesGC and GenGC, it appears that the trigger for compacting in HadesGC is more strict, requiring memory to be larger than targetSize, while GenGC will always compact during full GC.

Here are my questions:

1. Is this behavior in HadesGC intentional, reducing the frequency of returning memory to the OS, to lessen the cost of re-allocating memory?
2. Since memory is not returned to the OS, when externally testing the average memory usage of an Android application, the average memory usage of the new Hermes version is higher. Is this what the designers anticipated, or is this issue triggered only due to the specificity of my test cases?
3. As the JS used heap has indeed decreased, the actual memory peak has also declined. Does Hermes pay more attention to the average memory usage or the peak usage?

**Comment by EndSmile** [comment]
Thank you very much for your response, I understand now.

Additionally, to correct a minor detail, the current new version of the Hermes branch is based on rn/0.71-stable. My earlier mention of 0.71 might not have been accurate, and I apologize for this.

Lastly, regarding OccupancyTarget, I've noticed that this configuration seems to be consistently set at 0.5. Has there been any attempts internally at Meta to adjust this value?

**Comment by neildhar** [comment]
Thank you for clarifying regarding the version, I misread it as Hermes 0.7.1, but I realise you're referring to the RN version (which makes sense now that Hermes releases are cut alongside RN).

> Has there been any attempts internally at Meta to adjust this value

Yes. In situations where low memory consumption takes precedence over performance, it makes sense to raise the occupancy ratio above 0.5. This increases the frequency of collections, but is the primary knob for controlling the heap size.
