### ISSUE TITLE
A possible bug about calling eval in strict mode

### ISSUE THREAD

**Issue by YaoHouyou** [facebook/hermes#102]
### Testcase:
````
var NISLFuzzingFunc = function() {
    "use strict";
    eval("var public = 1;");
};
NISLFuzzingFunc();
````

### Command:
`./build/bin/hermes -w testcase.js`

### Output:
````
````

### Expected output:
Throw SyntaxError on Line 3

### Description:
According to the ES standard, eval code is strict mode code if the call to eval is contained in strict mode code. In the testcase above, the eval code should be strict mode code, and the reserved word "public" cannot be used as a variable name in strict mode, so a SyntaxError should be thrown on Line 3. However, Hermes did not throw any exceptions when running the above testcase.
The reference of the ES standard is as follows:
`http://www.ecma-international.org/ecma-262/6.0/index.html#sec-strict-mode-code`

**Comment by ykabusalah** [comment]
Can I take this?

**Comment by tmikov** [comment]
@YaoHouyou thank you for catching this! It does indeed look like a bug. BTW, please keep in mind that Hermes does not currently fully support local eval(), so for example it can't access local variables.

**Comment by tmikov** [comment]
@ykabusalah we are happy to accept community contributions. 

While conceptually simple, fixing this issue requires changes in several places in the compiler and the interpreter, so it may be challenging if you are not already familiar with the code base. Here is what we need to do:  we need to add a new operand "strictMode" to the `DirectEvalInst` instruction, which we then have to pass as an additional parameter to evalInEnvironment().

If you like, feel free to give it a try.

**Comment by fbmal7** [comment]
Propagating function strictness to direct `eval`s is now implemented in https://github.com/facebook/hermes/commit/f6b56d334467555b634f54bd18900d7ef8408eba
