### ISSUE TITLE
defineProperty() proxy hook called with symbol instead of property name in some cases

### ISSUE THREAD

**Issue by farwayer** [facebook/hermes#1025]
## Bug Description

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: hermes-2023-03-07-RNv0.71.4-31fdcf738940875c9bacf251e149006cf515d763
React Native version (if any): 0.71.8
OS version (if any): android
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce

1. set `defineProperty` proxy hook
2. DO NOT set `set` proxy hook
3. assign property `test` (or any other) to the proxy
4. `defineProperty` hook called with symbol `Symbol(test)` instead of property name `test`

code example:

```js
let p = new Proxy({}, {
  defineProperty(target, property, attributes) {
    console.log(property, typeof property)
    return Reflect.defineProperty(target, property, attributes)
  },
})

p.test = 1
// Symbol(test) symbol 
```

Interesting fact is that if `set` hook attached the behavior is correct:
```js
let p = new Proxy({}, {
  defineProperty(target, property, attributes) {
    console.log(property, typeof property)
    return Reflect.defineProperty(target, property, attributes)
  },
  set(target, property, newValue, receiver) {
    return Reflect.set(target, property, newValue, receiver)
  },
})

p.test = 1
// test string 
```

## The Expected Behavior

`defineProperty` hook should be called with property name in all cases (with or without `set` hook attached)

**Comment by mattbfb** [comment]
I can reproduce this behavior locally. Thanks for reporting.

The behavior does seem a bit odd (and I've verified does differ from other engines). I'm not sure if the spec requires a specific type (i.e. string). I think this is worth investigating.

**Comment by ljharb** [comment]
The spec absolutely requires that `p.test` be the string 'test', and `p[Symbol('test')]` would need to pass a symbol.

**Comment by tmikov** [comment]
Proxy is the gift that keeps giving :-) Both extremely slow and complex.

**Comment by fbmal7** [comment]
Fixed with https://github.com/facebook/hermes/commit/a9eeba949ce15ffd29f77b3eeca818ddf9a788eb
