### ISSUE TITLE
Array.prototype.join() with this === arg1

### ISSUE THREAD

**Issue by AidPaike** [facebook/hermes#1043]
# Version

Version: 0.12.0 ( [265d0d9](https://github.com/facebook/hermes/commit/265d0d9e78167bb4d96b00123566046b529fff43) )

# Execution steps

/root/hermes_workingdir/build/bin/hermes Testcase.js

# Test case 1

```javascript
var a = [0,1]
var b = Array.prototype.join.call(a, a);
print(a)
print(b)
```

# Output

```
0,1
01
```

# Test case 2

```javascript
var a = [0,1]
var b = Array.prototype.join.call(a, [0,1]);
print(b)
```

# Output

```
00,11
```

# Expected behavior

```
00,11
```

# Test case 3

```javascript
var a = [0,1]
var c = [0,1,2,3]
var b = Array.prototype.join.call(a, c);
// print(a)
print(b)
```

# Output

```
00,1,2,31
```

# Description

When using the `Array.prototype.join.call()` method, it  follows the standard behavior and returns properly when passed arguments such as lists or numbers (Test case 1). However, it does not return  properly when passed the `arguments` variable (Test case 2).  To verify if other variables can return properly (Test case 3 is a good  example), I suspect it may be related to the "this" context.

Hope hermes gets better and better  
Looking forward to your reply :)

**Comment by tmikov** [comment]
Minimal repro:
```
var a = [0,1]
print(a.join(a));
```

**Comment by AidPaike** [comment]
Thank you for your reminder, it may be related to cycle avoidance. Please refer to [A.p.join on cyclic arrays does not reflect web reality](https://github.com/tc39/ecma262/issues/289#top) for more information.  It's about 'check for cycles' :)

**Comment by tmikov** [comment]
@AidPaike I am sorry, what is your desired outcome here? Do you believe that this is a bug, a violation of EcmaScript, or is this a practical problem that you are having in existing software?

Given the esoteric nature of this case, and that both SM and JSC seem to share the Hermes behavior, and seeing that the linked tc39 issue is still open, I don't think there is a strong case for changing Hermes yet.

However I am happy to discuss it further.

**Comment by ljharb** [comment]
Indeed, until that ecma262 issue is resolved, implementations shouldn't do anything.

**Comment by AidPaike** [comment]
> @AidPaike I am sorry, what is your desired outcome here? Do you believe that this is a bug, a violation of EcmaScript, or is this a practical problem that you are having in existing software?
> 
> Given the esoteric nature of this case, and that both SM and JSC seem to share the Hermes behavior, and seeing that the linked tc39 issue is still open, I don't think there is a strong case for changing Hermes yet.
> 
> However I am happy to discuss it further.

During my initial journey in learning JavaScript syntax, I experimented with using the argument itself as a delimiter. However, I noticed that the engine automatically removed the delimiter from the returned result, which sparked my interest. Initially, I mistakenly assumed it was a bug, but thanks to your guidance, I discovered that this is a topic also being discussed in ecma262. I am delighted to have been able to explore such depths while still in the early stages of learning JS. Thank you very much for your assistance; I no longer have any doubts.
