### ISSUE TITLE
Does Hermes provide precompiled mac64arm binaries?

### ISSUE THREAD

**Issue by tmikov** [facebook/hermes#1044]
When running `jsvu` on Apple silicon, Hermes isn't installed, with the following error: 

```
📦 jsvu v2.1.0 — the JavaScript engine Version Updater 📦
✔ Read OS from config: mac64arm
✔ Read engines from config: chakra, hermes, javascriptcore, quickjs, spidermonkey, v8, v8-debug, xs
✔ Found latest Chakra version: v1.11.24.
❯ Predicting URL…
✖ Error: Chakra does not offer precompiled mac64arm binaries.
✔ Found latest Hermes version: v0.11.0.
❯ Predicting URL…
✖ Error: Hermes does not offer precompiled mac64arm binaries.
✔ Found latest JavaScriptCore version: v265644.
```

Is this a problem with Hermes or jsvu?

**Comment by neildhar** [comment]
Our releases contain universal binaries (both Apple Silicon and x86). jsvu should probably be updated to point to the same release for both mac64 and mac64arm.

**Comment by tmikov** [comment]
Right. The last release from Aug 22th 2022 contains universal binaries.

**Comment by tmikov** [comment]
See https://github.com/GoogleChromeLabs/jsvu/pull/139 .

However, jsvu still relies on npm versions:
https://github.com/GoogleChromeLabs/jsvu/blob/53bf88b2f58927f95f6c808716808783f2216de2/engines/hermes/get-latest-version.js

It also needs to be updated to pull the latest release from Github without paying attention to npm.
