### ISSUE TITLE
prettier-plugin-hermes-parser: incorrectly suggesting removal of () brackets

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/hermes#1047]
## Bug Description

I am trying to use `prettier-plugin-hermes-parser` in my project (because of [breaking changes in Prettier 3](https://github.com/prettier/prettier/pull/13687)) and everything seems to be working well except one thing:

```js
const _ = (path.join(__dirname, 'jest-setup.js') /*: string */)
```

Prettier together with `prettier-plugin-hermes-parser` suggest the following change:

```js
const _ = path.join(__dirname, 'jest-setup.js') /*: string */;
```

This is however not correct when running Flow:

```txt
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/sx-design/jest.config.js:5:49

Unexpected token :, expected the token ;

     2│
     3│ const path = require('path');
     4│
     5│ const _ = path.join(__dirname, 'jest-setup.js') /*: string */;
     6│
     7│ module.exports = {
     8│   rootDir: __dirname,

Found 1 error
```

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.14.0 (`prettier-plugin-hermes-parser`)
React Native version (if any):
OS version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. Try to format `const _ = (path.join(__dirname, 'jest-setup.js') /*: string */)` with Prettier using `prettier-plugin-hermes-parser` (for example: `npx prettier --config=./prettier.config.js src/sx-design/jest.config.js`)
2. 💥 

Here is the config I am currently trying to use:

```js
// @flow strict

module.exports = {
  bracketSpacing: true,
  printWidth: 100,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  quoteProps: 'consistent',
  plugins: ['prettier-plugin-hermes-parser'],
  overrides: [
    {
      files: ['*.js', '*.jsx', '*.flow'],
      options: {
        parser: 'hermes',
      },
    },
  ],
};
```

## The Expected Behavior

Prettier won't suggest the removal of "()" brackets in `const _ = (path.join(__dirname, 'jest-setup.js') /*: string */)` (no change should be suggested)

**Comment by pieterv** [comment]
This isn't really something we can support without heavy modifications to the prettier printer (the reason they also removed it), so it's not realistic for us to support this without forking prettier which we are not interested in doing.

However having done the prettier upgrade within Meta i have found this case pretty easy to work around by shifting the annotation location to the left hand side of the var, e.g. 

```
const _ /*: string */ = path.join(__dirname, 'jest-setup.js');
```
