### ISSUE TITLE
Missing Documentation on function start/end based Tracing 

### ISSUE THREAD

**Issue by jayshah123** [facebook/hermes#1048]
## Description

Current website docs do not suggest anything for tracing/profiling (especially of JS functions).

The documentation that might be slightly relevant would only be https://reactnative.dev/docs/profile-hermes.
Even this documentation mentions sampling profiler without any mention of exact tracing.

Would recommend to document (even if in beta) on how to trace JS which would be pretty relevant for any app developer.

Is there a way to get trace for every JS function executed?

**Comment by neildhar** [comment]
To clarify, your question is specifically about tracing every individual function call, as opposed to using sampling, right?

That is not a feature we currently support.

**Comment by jayshah123** [comment]
> To clarify, your question is specifically about tracing every individual function call, as opposed to using sampling, right?
> 
> That is not a feature we currently support.

Yes. Kind of like what chrome performance tab does by default in web.

If fully tracing all js functions is not possible, exposing some custom tracing API would be useful, something like : https://perfetto.dev/docs/instrumentation/tracing-sdk

**Comment by neildhar** [comment]
The profile produced by the sampling profiler can be used to create a timeline view, similar to what you get in Chrome. As far as I know, Chrome also runs a sampling profiler and then constructs the timeline, as opposed to tracing the start and end of every function call.

I'm not sure what the most up-to-date workflow is for running the profiler and viewing it though. @fbmal7 or @mattbfb may know more.

**Comment by jayshah123** [comment]
What is the sampling interval of the sampling profiler? Would it capture functions taking a duration of 0.1ms? Is the sampling interval configurable?

**Comment by fbmal7** [comment]
@jayshah123 You can find the constants that Hermes defines for the interval here https://github.com/facebook/hermes/blob/main/lib/VM/Profiler/SamplingProfilerSampler.cpp#L137-L138

So, on average, the sampling profiler will record a sample every 10ms. The whole point of a sampling profiler is to analyze the aggregate performance of your program. It is not meant to give you a complete, deterministic history of program execution. If a function runs once for 0.1ms there is a small likelihood it will show up in a trace. But, if this 0.1ms function is called very often in a bottleneck, it will show up in the trace.

This interval is not configurable. It is a compile time constant.

**Comment by jayshah123** [comment]
Got it.
In order to make hermes drop a trace for function, one would have to patch hermes with respective OS tracing sdk (e.g. Atrace on android) to put custom trace events for JS function executions right?
If that is the case, I can close this issue with this conculding comment.

**Comment by neildhar** [comment]
You could certainly instrument the Hermes source in some way to trace function execution. It is likely that the overhead of the instrumentation will distort the trace though.

Closing this for now.
