### ISSUE TITLE
The scope of the let  does not meet the ES standard

### ISSUE THREAD

**Issue by YaoHouyou** [facebook/hermes#105]
### Testcase:
````

1. var NISLFuzzingFunc = function() {
2.     var arr = [ "enum", "super"];
3.     var i = 50;
4.     for (let i in arr) {
5.         print(i);
6.     }
7.     print(i);
8. };
9. NISLFuzzingFunc();

````
### Command:
````
./build/bin/hermes -w testcase.js
````
### Output:
````
0
1
1
````

### Expected output:
````
0
1
50
````
### Description:
According to the ES 2016, the scope of `let` can only be in a block, which is different from the scope of `var`. In the testcase above, the value of `i`(Line 7) should be 50 instead of 1, while the output of Hermes is 1. Maybe, it is a bug of Hermes. What do you think about it?

**Comment by avp** [comment]
`let`, `const`, and block scoping are features that we're still working on fully supporting, and they're not complete yet. See [this document](https://github.com/facebook/hermes/blob/master/doc/Features.md) to see what features are still in progress.

That being said, remember that code provided to Hermes via React Native via the default pipeline undergoes Babel transformation, so the particular set of features we support natively shouldn't stop developers from using these features when actually writing code. See [this comment](https://github.com/facebook/hermes/issues/57#issuecomment-513381978) for elaboration.
