### ISSUE TITLE
Proxy defineProperty trap is triggered with incorrect descriptor

### ISSUE THREAD

**Issue by pastelmind** [facebook/hermes#1065]
## Bug Description

When a data property of a proxied object is assigned a new value, the `defineProperty` trap of `Proxy` is triggered with a descriptor with `configurable: false`, `enumerable: false`, and `writable: false`. However, [according to the ECMAScript spec](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinarysetwithowndescriptor) (see item 2.d.iii), the descriptor object must have no field other than `value`. This is problematic if the Proxy attempts to call `Reflect.defineProperty()` using the passed descriptor, as it unexpectedly "freezes" the property.

The issue was discovered in Expo SDK 48.0.0, which [claims to ship React Native 0.71.3](https://blog.expo.dev/expo-sdk-48-ccb8302e231). Unfortunately, I am currently unable to determine the exact version of Hermes.

<ins>Edit: I reproduced the issue in a React Native CLI-based project, this time on a real Android device.</ins>

I suspect that this is the root cause of #1063.

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 
React Native version (if any): 0.71.3, 0.72.2
OS version (if any): Android 13 (and possibly others)
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

code example:

```js
var a = new Proxy({}, {
  defineProperty: (obj, prop, desc) => {
    console.log("trap desc:", desc);
    console.log("before desc:", Object.getOwnPropertyDescriptor(obj, prop));
    const result = Reflect.defineProperty(obj, prop, desc);
    console.log("after desc:", Object.getOwnPropertyDescriptor(obj, prop));
    return result;
  },
});

a.foo = 1; // (1) Creates data property 'foo'
a.foo = 2; // (2) Updates the value of 'foo'; bugged
a.foo = 3; // (3) This is ignored in sloppy mode, but throws in strict mode
console.log('a.foo:', a.foo);
```

When executed in a Expo app (SDK version 48.0.0) <ins>or a React Native 0.72.2 app</ins>, the log looks like:

```
trap desc: {"configurable": true, "enumerable": true, "value": 1, "writable": true}
before desc: undefined
after desc: {"configurable": true, "enumerable": true, "value": 1, "writable": true}
trap desc: {"configurable": false, "enumerable": false, "value": 2, "writable": false}
before desc: {"configurable": true, "enumerable": true, "value": 1, "writable": true}
after desc: {"configurable": false, "enumerable": false, "value": 2, "writable": false}
a.foo: 2
```

The first three messages are logged by (1) `a.foo = 1`, which creates a new data property `foo` on the proxied object. Everything works fine up to this point.

The fourth message shows the descriptor object (`desc`) passed to the `defineProperty` trap when it is triggered by (2) `a.foo = 2`. This descriptor has the `configurable`, `enumerable`, and `writable` fields explicitly set to `false`, even though the spec says it should not have these fields. This difference has an observable effect when we call `Reflect.defineProperty()`, as it makes the property non-configurable, non-enumerable, and non-writable. Later, when we attempt to assign `a.foo` a new value (3), it fails silently (or throws if we run the code with `"use strict";`).

## The Expected Behavior

In standards-compliant engines (Chrome-V8, Firefox-SpiderMonkey), the above code outputs:

```
trap desc: {value: 1, writable: true, enumerable: true, configurable: true}
before desc: undefined
after desc: {value: 1, writable: true, enumerable: true, configurable: true}
trap desc: {value: 2}
before desc: {value: 1, writable: true, enumerable: true, configurable: true}
after desc: {value: 2, writable: true, enumerable: true, configurable: true}
trap desc: {value: 3}
before desc: {value: 2, writable: true, enumerable: true, configurable: true}
after desc: {value: 3, writable: true, enumerable: true, configurable: true}
a.foo: 3
```

Note that the descriptor passed to the `defineProperty` trap does not have any fields other than `value`, which is accordance with the spec.

**Comment by lovetingyuan** [comment]
I test the case with hermes-cli-darwin-v0.11.0, nodejs(18.15.0) and javascriptcore, the result is same as the issue described.

nodejs and jsc works well but hermes outputs the different result.

**Comment by tmikov** [comment]
Thank you for reporting this, looking into it.

**Comment by Bardiamist** [comment]
I have many `target property is non-configurable and non-writable, and get trap result differs from target property value` prod crashes.
Problems appeared in `react-native@0.72.1`
No problems in `react-native@0.71.11`

It's in different places. But it always when trying to get property from object which I get from api and store in redux without mapping.

**Comment by kristfal** [comment]
Hey,

[reselect V5](https://github.com/reduxjs/reselect/releases/tag/v5.0.0-beta.0) with 4.5m weekly downloads will use a new Proxy-based autotracking memoization system.

With this, redux-based react-native apps will start to use Proxy which will crash with Hermes due to the issues raised in this thread. It would be fantastic to get this fixed prior to V5 hitting public release.

**Comment by Bardiamist** [comment]
My users on the prod app got more than 500 crahes

**Comment by lovetingyuan** [comment]
I think we should prioritize this issue @tmikov

**Comment by farwayer** [comment]
Can confirm, just ran into the problem with RN 0.72.7

**Comment by kristfal** [comment]
FYI: [Reselect 5.0](https://github.com/reduxjs/reselect/releases/tag/v5.0.1) is now released. Expect many more issues around this. Would be fantastic to get this issue solved.

**Comment by tmikov** [comment]
This was fixed in https://github.com/facebook/hermes/commit/7d93640ee9000363fce313188f876ec3d4e8a4f1

**Comment by Bardiamist** [comment]
@tmikov Oh no, waited so long for this fix land but crash happened again https://valr.sentry.io/share/issue/104cecf04d8c4fd4a67c4465f451ffe9/ in `react-native@0.75.3`

**Comment by tmikov** [comment]
@Bardiamist if you can get a minimal repro, please open a new issue (it will be easier to track compared to re-opening this one).

**Comment by Bardiamist** [comment]
Unfortunately I can't repro this.

But good that now still have only one crash from react-native@0.75.3.
From react-native before 0.75 was received thousands of crashes.
