### ISSUE TITLE
Wrong DateTimeFormat for "en-IL"

### ISSUE THREAD

**Issue by lidord-wix** [facebook/hermes#1068]
## Bug Description
"Intl.DateTimeFormat" for "en-IL" returns the wrong value.
When running it on Chrome I'm getting:  `"25/07/2023"`
When running it in a React-Native app I'm getting: `"7/25/2023"`

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

React Native version (if any): 0.71.12

## Steps To Reproduce
Run `new Intl.DateTimeFormat('en-IL').format();` in a react native app (RN version 0.71.12)

## The Expected Behavior
Get the same value as Getting when running it on Chrome - `"25/07/2023"`

**Comment by tmikov** [comment]
What platform are you getting this on? This is important, since there are different Intl implementations.

**Comment by lidord-wix** [comment]
@tmikov
iOS simulator - iPhone 14 iOS 16.4
Android emulator - Pixel 6 API 33

**Comment by lidord-wix** [comment]
@neildhar Thank you for your reply, 
I checked on two real devices - `iPhone 13 Pro, iOS 16.5.1` & `Redmi Note 5, Android version 9`
The results are the same on both devices - `7/25/2023`
Also, when I checked `Intl.DateTimeFormat('en-IL').resolvedOptions().locale` on those devices and on the iOS simulator I got `"en"` 
In all the devices the region is `Israel` and the language is `English (United States)`, as you can see in the attached screenshot: 
![IMG_7053](https://github.com/facebook/hermes/assets/66782556/098e48f4-feaf-4e95-9ab4-bdc1c7bb7092)

**Comment by neildhar** [comment]
@lidord-wix It's odd that you're seeing the same issue across platforms. Could you confirm that there is no Intl polyfill involved, and (if possible) that the bug doesn't appear with JSC?

**Comment by lidord-wix** [comment]
Ok, I found out that we're overriding the global Intl with this [intl](https://github.com/andyearnshaw/Intl.js) package. 
Closing this issue for now.
Thanks!
