### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO) and LLVM BOLT

### ISSUE THREAD

**Issue by zamazan4ik** [facebook/hermes#1076]
## Problem

Just an idea of how to improve the Hermes tooling performance.

## Solution

Recently I checked Profile-Guided Optimization (PGO) improvements on multiple projects. The results are [here](https://github.com/zamazan4ik/awesome-pgo/).

Since PGO showed measurable improvements in compiler-like workloads (Clang, GCC, Rustc, etc.) I think it could be helpful to check PGO for the Hermes project too.

We need to perform PGO benchmarks on Hermes. And if it shows improvements - add a note to the documentation about possible improvements in Hermes performance with PGO. Providing an easier way (e.g. a build option) to build scripts with PGO can be useful for the maintainers and end-users too. Also, you could think about PGO optimizing provided to the users' binaries on some "generic-enough" workload - e.g. you can try to extract such a sample workload from your CI setup.

Also, since Facebook created BOLT (LLVM BOLT) I think would be great to see BOLT results on Hermes as well.

**Comment by tmikov** [comment]
Indeed, there is a reason to believe that PGO could improve Hermes interpreter performance up to 10% or more, though it is not clear how to integrate PGO into the RN build process, which is currently used to distribute Hermes. 

We don't have immediate plans to work on this, but it would be very interesting to see data if anyone in the community wants to try it. 

With regards to BOLT, I believe it supports Arm64 Linux binaries, so it could probably be used for 64-bit Android builds. BOLT is aimed more at server workloads, so it would be interesting to see how it performs on mobile devices. Could it cause excessive inlining and increased binary size?

**Comment by zamazan4ik** [comment]
> Could it cause excessive inlining and increased binary size?

Well, in theory, it *can*. But from my experience, often you can get even smaller binaries. Because with runtime profile information the compiler/optimizer can perform inlining only in necessary cases, not in all. So the cold partitions will be smaller -> whole binary will be smaller. But the actual results need to be tested for each application.
