### ISSUE TITLE
`for await` isn't handled well

### ISSUE THREAD

**Issue by LunatiqueCoder** [facebook/hermes#1089]
Hello 👋

## Problem

[`for await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of)  doesn't seem to be handled very well.

## Reproduction

It can be reproduced if you try to use [redux-devtools](https://github.com/reduxjs/redux-devtools). For additional context, I created a PR here: https://github.com/reduxjs/redux-devtools/pull/1430, but I believe it can be disregarded if this is fixed on Hermes Engine's side.

I can also provide a reproduction repository if needed.

**Comment by tmikov** [comment]
Hi, Hermes doesn't support async iterators yet (the feature is planned, but no release date yet), so `for await` is unsupported and produces the corresponding error message when encountered.

As you know, in RN apps JS code undergoes Babel transformations which should eliminate instances of `for await`.

**Comment by tmikov** [comment]
for await will be tracked as part of async iterators implementation

**Comment by christianarty** [comment]
@tmikov is there a public ticket/link for us to track the progress of the async iterators implementation? Thanks!

**Comment by melroy89** [comment]
It's actually still not fixed. I get: ` error: ';' expected`

**Comment by tmikov** [comment]
@melroy89 if you are getting that error, it is not coming from `for await`. This is the error Hermes generates:

<img width="451" alt="Screenshot 2024-04-19 at 5 47 55 PM" src="https://github.com/facebook/hermes/assets/7785196/1b40184d-4fb2-4a6c-8702-8afa9034aebd">

**Comment by melroy89** [comment]
Ow sorry yes I was talking about top level await I believe. Not for await
