### ISSUE TITLE
v0.2.1 not published to NPM

### ISSUE THREAD

**Issue by vitalyiegorov** [facebook/hermes#110]
Hi, according to https://www.npmjs.com/package/hermesvm the latest version available is v0.1.1 is this made intentionally? 

https://github.com/facebook/hermes/releases introduces new v0.2.1 with a huge amount of bugfixes and debug mode fix.

**Comment by darekg11** [comment]
Use `hermes-engine`:
https://www.npmjs.com/package/hermes-engine

**Comment by willholen** [comment]
This is indeed intentional. As https://www.npmjs.com/package/hermesvm says, we are migrating to a new NPM name `hermes-engine`. Sorry for the confusion!
