### ISSUE TITLE
How about using Rust instead of CPP to rewrite Hermes in the future?

### ISSUE THREAD

**Issue by cisen** [facebook/hermes#113]
Hi,

Because of CPP's black-magic techs and complex memory control，I am afraid that Hermes will be hard to maintain in the future. Comparing with others，I think Rust may be the best choice。

**Comment by willholen** [comment]
We don't plan on doing any complete rewrites of Hermes in the foreseeable future, but the team is following the development of Rust with interest.

**Comment by joeky888** [comment]
Facebook's HHVM begins seeing Rust rewrite.

https://www.phoronix.com/scan.php?page=news_item&px=Facebook-Rust-HHVM

**Comment by mishushakov** [comment]
Here's my Rust wrapper for Hermes: https://github.com/rust-hermes/rusty_hermes
