### ISSUE TITLE
prettier-plugin readme missing `plugins` key

### ISSUE THREAD

**Issue by Brianzchen** [facebook/hermes#1130]
## Description

The current docs recommend this

```
// .prettierrc
{
  "overrides": [
    {
      "files": ["*.js", "*.jsx", "*.flow"],
      "options": {
        "parser": "hermes"
      }
    }
  ]
}
```

But it also requires `"plugins": ["prettier-plugin-hermes-parser"]` to work otherwise I get plugin not found

**Comment by pieterv** [comment]
Thanks for the issue, this has been resolved via https://github.com/facebook/hermes/pull/1107 and will be included in the next release.
