### ISSUE TITLE
iOS locale is parsed as `und` when region is set

### ISSUE THREAD

**Issue by elliottkember** [facebook/hermes#1140]
I believe I've found a strange formatting bug related to locales and regions.

When using an iOS device with language set to English (New Zealand) but with region set to United States, the region string returned by ` [[NSLocale currentLocale] localeIdentifier]` is `en_NZ@rg=uszzzz`. I think this string is not being parsed correctly by Hermes, and the resulting region is the default `und`. This means `.toLocaleString()` does not format numbers.

Apparently this is in the specification for locale strings – they can have region information appended to them. The [documentation](https://developer.apple.com/documentation/foundation/nslocale/1416263-localeidentifier/) says this string may be formatted with a `@` symbol to denote extra information:  There is relevant code in the [Android repo](https://cs.android.com/android/platform/superproject/+/master:external/icu/icu4j/main/tests/core/src/com/ibm/icu/dev/test/util/CurrencyTest.java;l=754;drc=da0990f87c650bff952ed877c4bdf899de2c52c9)

```
Examples of locale identifiers include "en_GB", "es_ES_PREEURO", and "zh-Hant_HK_POSIX@collation=pinyin;currency=CNY".
```

I would have thought that the parser would be able to parse these regions, but I've consistently been able to replicate this with my language and region settings.

In react native, `NativeModules.SettingsManager.settings.AppleLocale` also resolves to `en_NZ@rg=uszzzz`.

https://github.com/facebook/hermes/blob/0b3ad4efa1a003f2079727cea17ecb67523d0ff9/lib/Platform/Intl/PlatformIntlApple.mm#L52-L69

But after this investigation, I've noticed that setting `Number Format` in the iOS settings is **never respected** – the format is the default for the locale (when that works) rather than the format specified. This seems like a bug over and above what's reported here – using the locale to assume number format settings is not the correct behaviour

**Comment by neildhar** [comment]
Thank you for reporting this, this looks like a legitimate bug in how we're handling the default locale returned by iOS. Extensions denoted after the `@` represent the old locale extension style which is not supported in JavaScript. It should be possible to convert such extensions into the correct style, but for now, the simplest solution is likely to just truncate the extensions after the `@`, so we at least retain the portion of the locale ID that we understand.

**Comment by elliottkember** [comment]
@neildhar Thanks for the reply. I believe this change started in iOS 17 – I have not been able to replicate this in any older OS. I agree truncating extensions is the simplest step and that should work great.

Ideally `toLocaleString` should respect the device's number formatting settings, but node itself doesn't do that on my mac so that might be a harder problem to solve.

**Comment by elliottkember** [comment]
@neildhar I'm afraid I don't have a code sample in a public app as this was for work. But I can try to summarize it – let me know whether this helps.

I put `(12345).toLocaleString()` in a JSX template in my React Native app. The expectation here was `12,345`. On older versions of iOS this worked fine, including the simulator, but on my physical phone and iPad it simply rendered `12345`. 

I discovered that this was because I had selected `English (New Zealand)` as my language of choice on these devices, while my region was still United States, where I live – and so the numbers were not formatted with separators: 12345. Changing the language and region to match each other resolved this. The deep dive led me to the `und` region.

**Comment by neildhar** [comment]
I see, it certainly makes sense that `und` and `en-US` would have different results. I'm wondering if you're expecting any difference between `en_NZ@rg=uszzzz`, and `en-NZ` (since you remarked that node would not reflect this difference either).

**Comment by elliottkember** [comment]
Ah, I get what you mean. Yes – in iOS, the "region" is where I am geographically located, whereas the language is how I want my content formatted. So `en-NZ` is correct in both situations.

But what would be most accurate would be to respect device _number formatting settings_, which is configured separately in settings. That's what I meant when I referred to node.

<img width="742" alt="image" src="https://github.com/facebook/hermes/assets/42827/7f7cfae1-1939-44e8-9a87-b941c36f4422">
