### ISSUE TITLE
Android/iOS: Intl.DisplayNames not working

### ISSUE THREAD

**Issue by lsarni** [facebook/hermes#1144]
## Bug Description

When trying to use `Intl.DisplayNames` just as the example [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames):
```
const regionNamesInEnglish = new Intl.DisplayNames(['en'], { type: 'region' });
```
It errors with `TypeError: Cannot read property 'prototype' of undefined` both on iOS and Android.

React Native version (if any): 0.72.4 (Expo SDK 49)

## Steps To Reproduce

The following code
```
import { Text, SafeAreaView } from 'react-native';

export default function App() {
  const regionNamesInEnglish = new Intl.DisplayNames(['en'], { type: 'region' });
  return (
    <SafeAreaView style={{flex: 1, justifyContent: 'center', alignContent: 'center'}}>
      <Text style={{textAlign: 'center', fontSize: 24}}>
        {regionNamesInEnglish.of('DE')}
      </Text>
    </SafeAreaView>
  );
}
```
throws this error
![image](https://github.com/facebook/hermes/assets/15196342/d1040c53-682f-41d6-90b0-bdbd4ca368cf)
![image](https://github.com/facebook/hermes/assets/15196342/2e3e6af4-0604-4374-b8e7-94f70509ea53)

### Snack example
[SNACK LINK](https://snack.expo.dev/@lsarni/intl-displaynames)

## The Expected Behavior
`Intl.DisplayNames` should be supported, and the app should show "Germany" like it does now on the web:
![image](https://github.com/facebook/hermes/assets/15196342/d0251e2e-4c4f-4201-8105-95a40e4f19ce)

**Comment by rolandvar** [comment]
Hi @lsarni,
I have the same problem, how did you solve it?

Greetings

**Comment by fernandopascoalbr** [comment]
DisplayNames is undefined. I searching any solutions today. Enabling JSC also not working.

**Comment by irg1008** [comment]
Did you find something?

**Comment by AlexErrant** [comment]
See this discussion for Intl details (spoiler: it's not lookin good) https://github.com/facebook/hermes/discussions/1211#discussioncomment-15108926
