### ISSUE TITLE
error: use of undeclared identifier 'assert'

### ISSUE THREAD

**Issue by codingBobo** [facebook/hermes#1149]
## Bug Description

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any):https://github.com/facebook/hermes/tarball/hermes-2023-04-13-RNv0.70.8-c9b539bf3d7bfa4143ff1a5751886c7b2dd728a2
OS version (if any): macos 13.5.2
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):arm64-v8a, armeabi-v7a, x86, x86_64

## Steps To Reproduce

1. download https://codeload.github.com/facebook/hermes/legacy.tar.gz/refs/tags/hermes-2023-04-13-RNv0.70.8-c9b539bf3d7bfa4143ff1a5751886c7b2dd728a2 
2. cmake   make
3. get error:  
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- The C compiler identification is AppleClang 15.0.0.15000040
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
-- Performing Test DEPRECATED_COPY_FLAG
-- Performing Test DEPRECATED_COPY_FLAG - Success
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG - Failed
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG - Success
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR - Success
-- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
-- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Success
-- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
-- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Success
-- Performing Test RANGE_ANALYSIS_FLAG
-- Performing Test RANGE_ANALYSIS_FLAG - Success
-- Found Python: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9 (found version "3.9.6") found components: Interpreter 
-- Performing Test HAVE_COMPUTED_GOTO
-- Performing Test HAVE_COMPUTED_GOTO - Success
-- Performing Test HAVE_GC_SECTIONS
-- Performing Test HAVE_GC_SECTIONS - Failed
-- Performing Test HAVE_ICF
-- Performing Test HAVE_ICF - Failed
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for errno.h
-- Looking for errno.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for link.h
-- Looking for link.h - not found
-- Looking for malloc.h
-- Looking for malloc.h - not found
-- Looking for malloc/malloc.h
-- Looking for malloc/malloc.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for signal.h
-- Looking for signal.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for sys/param.h
-- Looking for sys/param.h - found
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for termios.h
-- Looking for termios.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for valgrind/valgrind.h
-- Looking for valgrind/valgrind.h - not found
-- Looking for zlib.h
-- Looking for zlib.h - found
-- Looking for fenv.h
-- Looking for fenv.h - found
-- Looking for FE_ALL_EXCEPT
-- Looking for FE_ALL_EXCEPT - found
-- Looking for FE_INEXACT
-- Looking for FE_INEXACT - found
-- Looking for mach/mach.h
-- Looking for mach/mach.h - found
-- Looking for histedit.h
-- Looking for histedit.h - found
-- Looking for CrashReporterClient.h
-- Looking for CrashReporterClient.h - not found
-- Performing Test HAVE_CRASHREPORTER_INFO
-- Performing Test HAVE_CRASHREPORTER_INFO - Success
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for pthread_getspecific in pthread
-- Looking for pthread_getspecific in pthread - found
-- Looking for pthread_rwlock_init in pthread
-- Looking for pthread_rwlock_init in pthread - found
-- Looking for pthread_mutex_lock in pthread
-- Looking for pthread_mutex_lock in pthread - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for xar_open in xar
-- Looking for xar_open in xar - found
-- Looking for arc4random
-- Looking for arc4random - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include  
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Success
-- Looking for _Unwind_Backtrace
-- Looking for _Unwind_Backtrace - found
-- Looking for getpagesize
-- Looking for getpagesize - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for setrlimit
-- Looking for setrlimit - found
-- Looking for isatty
-- Looking for isatty - found
-- Looking for futimens
-- Looking for futimens - found
-- Looking for futimes
-- Looking for futimes - found
-- Looking for posix_fallocate
-- Looking for posix_fallocate - not found
-- Looking for lseek64
-- Looking for lseek64 - not found
-- Looking for mallctl
-- Looking for mallctl - not found
-- Looking for mallinfo
-- Looking for mallinfo - not found
-- Looking for malloc_zone_statistics
-- Looking for malloc_zone_statistics - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for posix_spawn
-- Looking for posix_spawn - found
-- Looking for pread
-- Looking for pread - found
-- Looking for realpath
-- Looking for realpath - found
-- Looking for sbrk
-- Looking for sbrk - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strerror_s
-- Looking for strerror_s - not found
-- Looking for setenv
-- Looking for setenv - found
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for dladdr
-- Looking for dladdr - found
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - not found
-- Looking for sched_getaffinity
-- Looking for sched_getaffinity - not found
-- Looking for CPU_COUNT
-- Looking for CPU_COUNT - not found
-- Looking for pthread_getname_np
-- Looking for pthread_getname_np - found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Performing Test LLVM_HAS_ATOMICS
-- Performing Test LLVM_HAS_ATOMICS - Success
-- Performing Test SUPPORTS_NO_PIE_FLAG
-- Performing Test SUPPORTS_NO_PIE_FLAG - Success
-- Performing Test SUPPORTS_VARIADIC_MACROS_FLAG
-- Performing Test SUPPORTS_VARIADIC_MACROS_FLAG - Success
-- Performing Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG
-- Performing Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG - Success
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Found ld64 - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
-- Could NOT find Python module pygments
-- Could NOT find Python module pygments.lexers.c_cpp
-- Could NOT find Python module yaml
-- CMAKE_HOST_SYSTEM_NAME = Darwin
-- CMAKE_SYSTEM_NAME = Darwin
-- HERMES_APPLE_TARGET_PLATFORM = 
-- CMAKE_CROSSCOMPILING = FALSE
-- Looking for readline
-- Looking for readline - found
-- Configuring done
-- Generating done

/Users/xxx/Downloads/facebook-hermes-c9b539b/lib/Support/Semaphore.cpp:35:3: error: use of undeclared identifier 'assert'
  assert(semPtr_ != nullptr && "sem_open should have succeeded");

code example:

**Comment by tmikov** [comment]
I am sorry, what exactly is the problem you are having with Hermes?

**Comment by tmikov** [comment]
So, the problem is that you are trying build Hermes and you are getting a build time error? Does the error exist in the latest version of Hermes?

**Comment by codingBobo** [comment]
> you are getting a build time error

The latest version doesn't have this problem, However, this issue exists in the branches of hermes-2023-04-13-RNv0.70.8-c9b539bf3d7bfa4143ff1a5751886c7b2dd728a2

**Comment by tmikov** [comment]
Hi, what problem are you trying to solve? 

As a rule, we don't maintain fixes for previous versions of Hermes, since releases are created by React Native. If fixing this is important to you, you should consider requesting a pick here: https://github.com/reactwg/react-native-releases/discussions .

**Comment by codingBobo** [comment]
> Hi, what problem are you trying to solve?
> 
> As a rule, we don't maintain fixes for previous versions of Hermes, since releases are created by React Native. If fixing this is important to you, you should consider requesting a pick here: https://github.com/reactwg/react-native-releases/discussions .

ok, I'm trying to fix it

**Comment by Edison4mobile** [comment]
I still have same issue.

**Comment by tmikov** [comment]
This should be very easy to fix: just add
```c
#include <cassert>
```
at the top.

**Comment by Edison4mobile** [comment]
It shouldn't be a solution.

**Comment by tmikov** [comment]
@Edison4mobile a solution for what? What is the problem you are having and what do you expect the Hermes team to do in order to address it?

**Comment by Edison4mobile** [comment]
I am trying to build react-native source code. and having problem with hermes.
and it is in node-module so I cannot add #include <cassert>

**Comment by tmikov** [comment]
@Edison4mobile open the file /Users/vilayhongbounthanh/Work/6.Task/metamask-mobile/node_modules/react-native/sdks/hermes/lib/Support/Semaphore.cpp with an editor, position the cursor at the top of the file and type the characters "#include <cassert>" and enter. Then save the file.

**Comment by kiranjd** [comment]
@tmikov  Did this. I still face the same error. The changes I made have been overwritten again

> @Edison4mobile open the file `/Users/vilayhongbounthanh/Work/6.Task/metamask-mobile/node_modules/react-native/sdks/hermes/lib/Support/Semaphore.cpp` with an editor, position the cursor at the top of the file and type the characters `#include <cassert>` and enter. Then save the file.

**Comment by tmikov** [comment]
@kiranjd I am sorry, we can't really help with things like npm package management.

Try a Google search for "how to have local modifications in node_modules folder" - there are many many hits, some of them probably provide an answer.

Or you can try updating to a newer version of RN or Hermes. This problem has been fixed there.

**Comment by yakubbaev** [comment]
You should probably use [REACT_NATIVE_OVERRIDE_HERMES_DIR](https://github.com/facebook/hermes/blob/main/doc/ReactNativeIntegration.md#using-a-custom-hermes-build-in-a-react-native-app) since Hermes is downloaded and unzipped

**Comment by player-steve** [comment]
> You should probably use [REACT_NATIVE_OVERRIDE_HERMES_DIR](https://github.com/facebook/hermes/blob/main/doc/ReactNativeIntegration.md#using-a-custom-hermes-build-in-a-react-native-app) since Hermes is downloaded and unzipped

this work for me: Adding
`export REACT_NATIVE_OVERRIDE_HERMES_DIR=hermes_path`
to environment, and add
`#include <cassert> `
to Semaphore.cpp:35
