### ISSUE TITLE
Add support for `atob()` and `btoa()` functions

### ISSUE THREAD

**Issue by jonkoops** [facebook/hermes#1178]
## Problem

Much of the existing code in the JavaScript ecosystem, such as packages on NPM contain code that uses the [`atob()`](https://developer.mozilla.org/en-US/docs/Web/API/atob) and [`btoa()`](https://developer.mozilla.org/en-US/docs/Web/API/btoa) global functions. And although [not strictly](https://html.spec.whatwg.org/multipage/webappapis.html#dom-atob-dev) part of the ECMAScript specification, it might be worthwhile to support these for the sake of compatibility with the rest of the ecosystem. Other runtimes that are also not strictly web-based such as Node.js, Bun and Deno all support these functions as well.

## Solution

Add support for the `atob()` and `btoa()` global functions to Hermes.

## Additional Context

I contribute to `jwt-decode`, a popular library (~5.7 million downloads per week) to decode JSON Web Tokens. One of the users logged an issue specifically referencing this issue in React Native, and by extension Hermes (see https://github.com/auth0/jwt-decode/issues/241).

**Comment by tmikov** [comment]
It seems that JSC supports these, which is a pretty strong argument in favor of adding them.

**Comment by neildhar** [comment]
@tmikov My understanding is that these were added to JSC relatively recently, and only to the CLI tool. (in https://github.com/WebKit/WebKit/commit/70ccbd9daaa2db326dfed9a1d84f7be4ffdddaa7). So RN users on JSC would likely still need an `atob` polyfill.

There seem to be three options:

1. Continue using the polyfill, which may be slow if the inputs are large.
2. Adding Base64 encoding and decoding to Hermes natively.
3. Add an implementation over JSI to RN. But this will be clumsy to write because JSI forces strings to be converted to UTF-8, which means we will force some unnecessary conversions for the binary string. If we do this, we should consider adding functions to convert to/from `std::u16string`.

**Comment by tmikov** [comment]
Issues like this will keep popping up. I think we need to figure out a general way to address them without the overhead of JSI. An optional "library" .so perhaps.

**Comment by shamilovtim** [comment]
I've been using the JSI based https://github.com/craftzdog/react-native-quick-base64

> Issues like this will keep popping up. I think we need to figure out a general way to address them without the overhead of JSI. An optional "library" .so perhaps.

The pure JS polyfills everyone recommends in these threads are even worse than JSI! 

> Issues like this will keep popping up. I think we need to figure out a general way to address them without the overhead of JSI. An optional "library" .so perhaps.

It's perplexing to me how long the RN runtime has existed without these critical Web APIs. I think it would be uncontroversial to say that the platform is critically incomplete without them. I know it doesn't belong in Hermes and you get these requests here. But why are the runtime team disregarding the lack of these APIs that exist in every web runtime and native platform?

**Comment by tmikov** [comment]
Good news, folks! We have decided to add these to Hermes. We should have them soon. We are also working on a way to handle this in general in Static Hermes, by automatically pulling such functions in only when they are needed.

Of course, we realize that after we commit these new functions, it then takes a significant time for them to actually be usable, because the next RN release needs to happen, and then users need to upgrade to it... 
We plan to also address this problem very soon by introducing a stable Hermes ABI, which will allow Hermes to be upgraded freely independently of RN.

**Comment by jonkoops** [comment]
That is great news, thanks so much for considering this and the quick and efficient handling of this issue!

**Comment by tmikov** [comment]
Implemented in https://github.com/facebook/hermes/commit/13fafde91368553c5ca223b2853c7afe2c377132 and https://github.com/facebook/hermes/commit/d2177c31b271e92d1725742605b53d7f6e8acf3e.

**Comment by Bardiamist** [comment]
Cool, I want to use it. How can I understand in which version it will land and which version used in a react-native project?

**Comment by tmikov** [comment]
@Bardiamist React Native automatically uses the latest Hermes version when they cut a release, so it will be in the next RN release, I guess 0.74.

**Comment by Bardiamist** [comment]
Is it possible to see versions? `0.12.0` is the latest version of Hermes? It's strage because of more than year ago.
And how to see hermes used version in react native?

**Comment by tmikov** [comment]
@Bardiamist for now Hermes is distributed as part of RN and has no independent distribution or version. You can see versions as branches in the Hermes repo:
<img width="406" alt="Screenshot 2024-01-17 at 7 55 56 AM" src="https://github.com/facebook/hermes/assets/7785196/e3c134f8-2848-49b4-a453-284d3460283d">

**Comment by jonkoops** [comment]
@tmikov just to verify, as I am having some trouble reading the changelog for React Native, has this been released in [version 0.73](https://github.com/facebook/react-native/releases/tag/v0.73.0)?

**Comment by jonkoops** [comment]
Thanks for checking that @Bardiamist. I'll assume this will be landing in version 0.74 then.

**Comment by TwistedMinda** [comment]
How do you check if atob is included ?

0.74 has released by now, would be nice to see if this is settled.
Thanks

**Comment by tmikov** [comment]
One simple way to see whether it is available using the CLI:
```sh
echo "print(typeof atob)" | hermes
```

**Comment by Bardiamist** [comment]
Now `atob` has issue https://github.com/reactwg/react-native-releases/issues/287
But should be fix will be cherry picked soon

**Comment by mauricedoepke** [comment]
@TwistedMinda I am using react-native 0.74.1 atob and btoa are now working for me.

**Comment by wh201906** [comment]
Hi there.
I wonder if it's possible to change the implementations of `atob()` and `btoa()` to some faster libraries, like [simdutf](https://github.com/simdutf/simdutf). This is used in Node.js and should be faster than the implementation in https://github.com/facebook/hermes/commit/13fafde91368553c5ca223b2853c7afe2c377132 and https://github.com/facebook/hermes/commit/13fafde91368553c5ca223b2853c7afe2c377132

**Comment by tmikov** [comment]
@wh201906 do you have a specific case where the performance of atob()/btoa() is unsatisfactory? On what platform?

The Hermes team doesn't have bandwidth to experiment with faster implementations of these. But if there is a PR that measurably improves performance on all supported platforms without dramatically increasing the binary size (which is very important for a mobile platform), we will consider it.

**Comment by aqigif** [comment]
hi @tmikov 
now it work on my mac running an android app with RN 0.76.x, but my friend with windows still not working with this, anyone encounter the same issue?

```
error Cannot read property 'decode' of null
```

i'm using `decode` function from react-native-pure-jwt

**Comment by tmikov** [comment]
> hi [@tmikov](https://github.com/tmikov) now it work on my mac running an android app with RN 0.76.x, but my friend with windows still not working with this, anyone encounter the same issue?
> 
> ```
> error Cannot read property 'decode' of null
> ```
> 
> i'm using `decode` function from react-native-pure-jwt

Which version of RN and Hermes? Microsoft is using a for of Hermes, I don't know how up to date it is. This is a good question.
