### ISSUE TITLE
Hermes enabled android bundle is causing white screen after downloading app from google play

### ISSUE THREAD

**Issue by ursNj** [facebook/hermes#118]
Hermes enabled android bundle is causing white screen after downloading app from google play

but if we manually create an APK its working fine.

i think there is a issue with google creating APK from app bundle with hermes.

please look into it at the earliest.

**Comment by mhorowitz** [comment]
Sorry you are having trouble using Hermes.  This sounds like a problem which has already been reported: https://github.com/facebook/react-native/issues/25927

If you are not using android app bundles, then please give more detailed instructions for reproducing your problem.

**Comment by kubilaykiymaci** [comment]
there is a workaround and it works. I tried. its soloader problem.

https://github.com/facebook/react-native/issues/26400#issuecomment-539395814
