### ISSUE TITLE
JS profiler cannot stop recording

### ISSUE THREAD

**Issue by hnicholls-rbi** [facebook/hermes#1187]
## Bug Description

I am able to connect Chrome DevTools to an instance of my app running in the Android simulator but cannot use the profiler.

I can start a recording but when I click "stop" the recording never ends.

I found there's an unhandled exception in the `stopRecordingProfile` function of DevTools UI:
```
Error: Expected profile to be non-null
```

Upon calling `invoke_stop` in the DevTools UI SDK the profile attribute is undefined.

I am also using Expo.

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 
React Native version (if any): 0.70.8
OS version (if any): 
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): 

## Steps To Reproduce

1. Run `npm start`
2. Start app in Android simulator
3. Open JS debugger
4. On JavaScript Profiler start recording a profile
5. Click "Stop"
6. The profiler will not stop recording and the Stop/Start button is disabled

code example:

[Minimal repro](https://github.com/hnicholls-rbi/hermes-js-profiler-issue)

## The Expected Behavior
Profiler stops recording and loads the JS profile.

**Comment by tmikov** [comment]
Does this happen with the latest version of RN? Our ability to investigate problems and provide fixes for old versions of Hermes is very limited.

**Comment by hnicholls-rbi** [comment]
We're using RN 0.70.8 and I'm going to build a small repro.

**Comment by hnicholls-rbi** [comment]
@tmikov I added a [minimal repro](https://github.com/hnicholls-rbi/hermes-js-profiler-issue) and updated the description above.

**Comment by stevekuznetsov** [comment]
@hnicholls-rbi does this still work for you? On Expo SDK 49 and React Native 0.72.6 the recording stops but Dev Tools gets stuck on the next step ... 
![Screenshot from 2024-01-24 19-33-08](https://github.com/facebook/hermes/assets/7328370/a3343998-240c-49ab-821b-6f6e70adbc74)

**Comment by hnicholls-rbi** [comment]
> @hnicholls-rbi does this still work for you? On Expo SDK 49 and React Native 0.72.6 the recording stops but Dev Tools gets stuck on the next step ... ![Screenshot from 2024-01-24 19-33-08](https://private-user-images.githubusercontent.com/7328370/299519110-a3343998-240c-49ab-821b-6f6e70adbc74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTg2ODQsIm5iZiI6MTcwNjE5ODM4NCwicGF0aCI6Ii83MzI4MzcwLzI5OTUxOTExMC1hMzM0Mzk5OC0yNDBjLTQ5YWItODIxYi02ZjZlNzBhZGJjNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMTU1OTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVlMDc5Y2ExMjcxNWVjZTg2MTI3Y2Q2YzUwNTNjMDdkZGI4YWY0ZDc3ZDg1YWMxZDY1OTZlZjY0NDJkOWI2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Ik8J8AkD4sX97yeob44Ez4H58LEAEuHq-kGNbe6N7Q)

It looks like you're using the Performance tab which is not supported. You need to open the JavaScript Profiler tab: cmd+shift+p > Search for `JavaScript Profiler` > open JS Profiler tab > Hit record button

**Comment by stevekuznetsov** [comment]
Such a rookie mistake on my end - sorry! Thanks for the pointers, I will try that.
