### ISSUE TITLE
The "'use strict';" statement does not seem to work when creating function by the Function constructor

### ISSUE THREAD

**Issue by YaoHouyou** [facebook/hermes#120]
### Testcase:
````
var NISLFuzzingFunc = function() {
    var f = new Function(" 'use strict'; var o = {};print('hello world'); with (o) {}; ");
    f();
    print(f);
};
NISLFuzzingFunc();
````
### Command:
`./build/bin/hermes -w testcase.js`
### Output:
````
hello world
function anonymous() { [bytecode] }
````
### Expected output:
Throw SyntaxError on line 2

### Description:
SyntaxError exception should be thrown when 'with' statement is contained in strict mode code. In the testcase above, SyntaxError exception should be thrown on Line 2, but hermes does not do like this. So, I suspect it is a bug of hermes.

**Comment by tmikov** [comment]
Thank you, for reporting this. You are correct, this is a bug. Hermes doesn't support the "with" statement, but we should be reporting an error.
