### ISSUE TITLE
App Never Starts When Hermes is Enabled

### ISSUE THREAD

**Issue by RomanScott** [facebook/hermes#121]
Hello,

I am having an issue while trying to build my app with Hermes. My app works fine when the Hermes Engine is not turned on. However, when I turn it on, my app ceases to work: when I try to launch the app, all it shows is a white screen and a grey navigation bar (none of the components are loaded) and no calls from within the app itself (initialization calls, for example) are being made.

I am using React Native 0.61 and am testing on a LG V20.

In my logs it says this: "libjsc.so not found" and that is the last log output from my app.

Any help would be greatly appreciated.  Thank you!

**Comment by avp** [comment]
Is this the same issue as the one reported here?

https://github.com/facebook/react-native/issues/25927

**Comment by Alaa-Ben** [comment]
Hi @RomanScott ! If you still have this issue, would you mind showing your app/build.gradle here please ? thanks !

**Comment by willholen** [comment]
Please reopen if this is still an issue.
