### ISSUE TITLE
Hermes should throw an exception when BigInts use unsigned shift

### ISSUE THREAD

**Issue by JimWongM** [facebook/hermes#1212]
## Bug Description

Hermes should throw an exception when BigInts use unsigned shift, but it did not because of Dead Code Elimination.

BinaryOperatorInst is Eliminated by DCE and does not throw an exception. This optimization changes the semantics of JavaSript program.

The problem may be related to the side effect of BigInt for UnsignedRightShiftKind.

Hermes version: ebf7889c4f7f944630caed4abfebe49ee90f691a (latest version)
OS version (if any): Linux, MacOS

## Steps To Reproduce

1. Build latest hermes
2. ./hermes -O test.js
3. ./hermes -O0 test.js

code example:
test.js
```
function main() {
    try {
      -2512320511n >>> -2512320511n;
      print("hello");
    } catch (e10) {print(e10)}
  }
  main();
```

## The Expected Behavior

The result of step 2 and step 3 is different. In full optimization level, Hermes shoud throw an exception "TypeError: BigInts have no unsigned shift".

**Comment by JimWongM** [comment]
This problem may also exists when BigInt mod zero.

**Comment by tmikov** [comment]
Wow, these never end, do they? :-) Thanks for reporting this, we will fix it.
