### ISSUE TITLE
simplifySwitchInst in SimplifyCFG ignores negative zero

### ISSUE THREAD

**Issue by JimWongM** [facebook/hermes#1215]
## Bug Description

I found an interesting bug which is related to negative zero. ```SimplifySwitchInst``` in ```SimplifyCFG``` incorrectly eliminate ```case``` because  this optimization ignores negative zero whose NumberType is ```Int | Uint | Double``` in Hermes.

Hermes version: 8a43722f7f80eff582452daa9d88a3a6635ab1c9 (latest version)
OS version (if any): MacOS, Linux
## Steps To Reproduce

1. build lastest hermes
2. ./hermes -O0 test.js
3. ./hermes -O test.js

code example:
test.js
```
let a = -0;
switch (a) {
  case 0:
    print("case")
    break;
  default:
    print("default")
    break;
}
```

## The Expected Behavior

The results of step 2 & 3 should be the same. However, they are different in current version.

**Comment by tmikov** [comment]
Thanks! I will check whether we have other places that might be ignoring the difference.
