### ISSUE TITLE
Instanceof check not working on release build ?

### ISSUE THREAD

**Issue by wynch** [facebook/hermes#122]
Hello,

I'm using Hermes with RN 0.60.5, and I found a small line of code that doesn't behave the same with / without Hermes enabled, and only for release builds. (it works with hermes-debug)

I'm using typescript.

The code behaving differently is basically a Promise for a network request (using RN fetch), and if the request isn't OK (HTTP 2xx), this Promise throws an instance of a subclass of Error.  (class CustomError extends Error)
This error is then intercepted in a redux-saga generator in a try / catch block, and this is where I used a check `if (error instanceof CustomError)` : this check passes as true without Hermes, but fails with it...

Any hints on what might be the difference ?
For now I can change my code, but this might point to an error ?

**Comment by avp** [comment]
I'm not able to reproduce this behavior with any of the simple `class` code I try transpiling into Hermes-compatible JS with TypeScript or with Babel. Hermes doesn't have full `class` support yet, so all source it ingests must be lowered by Babel (or in your case, TypeScript) first. As such, the code you write isn't the same as what is executed.

It would be helpful to have a clear test case with which to reproduce this; in particular, a single file `test.js` which can be run with `./hermes test.js` and produces the incorrect behavior would make it easier to help you. If that's not possible, you can also upload a small project to a public GitHub repository to allow us to see the full issue.
