### ISSUE TITLE
JSRangeErrorException setting maximumFractionDigits to 0 with Intl.NumberFormat currency style

### ISSUE THREAD

**Issue by jdconley** [facebook/hermes#1236]
## Bug Description

An exception occurs when attempting to create a currency formatter with no fraction digits.

This was identified in #990 but closed due to the report using a wrapper.

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.72.6
React Native version (if any): 0.72.6
OS version (if any): Android API 34
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a (Emulator and Google Pixel 8)

No exception on iOS. Functions as expected.

## Steps To Reproduce

1. Device locale set to en-US
2. Create a currency style formatter with maximumFractionDigits set to 0

code example:

```ts
    new Intl.NumberFormat(undefined, {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0
    });
```

## The Expected Behavior

No exception, and a formatter that outputs a string without fraction digits.

**Comment by dannysu** [comment]
Landed a fix with #1246
