### ISSUE TITLE
Update documentation on using custom Hermes builds

### ISSUE THREAD

**Issue by matias-la** [facebook/hermes#1241]
## Description

The [Using a custom Hermes build in a React Native app](https://github.com/facebook/hermes/blob/main/doc/ReactNativeIntegration.md#using-a-custom-hermes-build-in-a-react-native-app) documentation section hasn't been updated in a while. It dates back to the time when Hermes was shipped through a separate NPM package. But since the changes documented in [Bundled Hermes](https://reactnative.dev/architecture/bundled-hermes) occurred, this is no longer true and Hermes is bundled together with the react-native package. It isn't clear how it would be possible to run our application using a custom Hermes build.

Context about this request: we're running a security-sensitive RN app, so we'd like to apply some security hardening patches on top of the upstream Hermes version. But it's unclear how we'd be able to do this.

CC @cortinico

**Comment by tmikov** [comment]
IIRC, there is a way to tell RN to build Hermes from a different directory. I don't remember the details, but someone will probably chime in here.

BTW (and I don't know whether that is you use case), Hermes should not be used to run untrusted JS. For untrusted JS we have a security sandbox (which will make its way to GitHub soon).

**Comment by neildhar** [comment]
Hey @matias-la, we've recently discussed this in https://github.com/facebook/react-native/issues/38658. You should be able to follow the steps there to get Hermes building from source.

**Comment by matias-la** [comment]
Thanks! We ended up using an approach similar to `REACT_NATIVE_OVERRIDE_HERMES_DIR`, but patching react-native so it downloads the source from a trusted source and verifies its integrity. Seems to be working fine for now.

**Comment by leotm** [comment]
> so we'd like to apply some security hardening patches on top of the upstream Hermes version. But it's unclear how we'd be able to do this.

fwiw we're working on applying some security hardening patches (hardened JS / Secure EcmaScript) on top of the upstream Hermes version too via a shim (tracking [here](https://github.com/LavaMoat/docs/issues/12) if interested or any overlap), to trust the JS is free from prototype pollution (then sandbox RN app dependencies next)

**Comment by leotm** [comment]
> but patching react-native so it downloads the source from a trusted source and verifies its integrity. Seems to be working fine for now.

we had [success](https://github.com/MetaMask/metamask-mobile/blob/main/patches/react-native%2B0.71.15.patch#L133-L157) this way too ^ thought might be worth mentioning in case anyone thinking about cherry picking [static_h](https://github.com/facebook/hermes/tree/static_h) commits on top of your trusted source fork/repo, the change may not be backwards-compatible (we're working around this), but ofc Static Hermes [will be](https://github.com/facebook/hermes/issues/1371#issuecomment-2052057382) when it ships
