### ISSUE TITLE
SyntaxError: Invalid flags passed to RegEx

### ISSUE THREAD

**Issue by littletower** [facebook/hermes#128]
Hi,

I just enabled Hermes on our React-Native (0.61.2) app.
These regexs:

```javascript
let t = text.split(/(\#.*?(?:\s|\#|$))/gs)

if(item.match(/(\#.*?)(?:\s|\#|$)/gs))
{...}
```

throw the following error:

<img width="310" alt="Screen Shot 2019-10-11 at 17 52 10" src="https://user-images.githubusercontent.com/4551180/66666108-3dce9b80-ec50-11e9-9f1e-ae2358f2d92d.png">

When disabling Hermes, this error disappears.

Is this a bug in Hermes? Or am I doing something wrong?
Thanks

**Comment by ljharb** [comment]
The `s` (dotAll) flag was added in ES2018. I assume the response will be that hermes implements ES2015.

**Comment by avp** [comment]
@ljharb is correct. Hermes doesn't implement ES2018 RegExp yet. We're currently targeting ES6 (ES2015) and you can check our progress here: https://github.com/facebook/hermes/blob/master/doc/Features.md.

**Comment by tmikov** [comment]
Here is a document briefly describing which parts of RegExp are currently supported (all of ES6, some of ES9).
