### ISSUE TITLE
libc.so (SIGABRT, SIGSEGV)

### ISSUE THREAD

**Issue by cnx-caiobarroso** [facebook/hermes#1293]
## Bug Description

Firebase Crashlytics logs indicate an issue with probably hermes - react-native. I've commented on an closed issue on react-native github, but was said that the issue could be on hermes side and that without reproducable scenario it wouldn't be able to help.

As said previously, we can't reproduce this issue on our own, but the crash logs aren't on small numbers, so it is not a small deal. Below are some of the data collected from stack traces and react-native version used.

React Native version: 0.72.3
OS: Android 14, 13, 12 ,11 etc.

Hermes enabled.

Stack traces: 

[br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65bb775301b800011a8ea48afb4106a2_DNE_0_v2_stacktrace.txt](https://github.com/facebook/hermes/files/14127476/br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65bb775301b800011a8ea48afb4106a2_DNE_0_v2_stacktrace.txt)

[br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65b6d6740326000161818e5dcc410bc2_DNE_0_v2_stacktrace.txt](https://github.com/facebook/hermes/files/14127478/br.com.myapp_issue_eb3e8632316c0c4166e96a314b244953_crash_session_65b6d6740326000161818e5dcc410bc2_DNE_0_v2_stacktrace.txt)

**Comment by tmikov** [comment]
I am sorry, what makes you think that this is caused by Hermes. As far as I can tell, Hermes isn't even in the stack trace of the crashed threads:

```
Crashed: Thread: SIGABRT  0x0000000000000000
#00 pc 0x8d774 libc.so (BuildId: 449f781894033dce6346794a1ee593e0)
#01 pc 0x8d744 libc.so (BuildId: 449f781894033dce6346794a1ee593e0)
#02 pc 0x7716f0 libart.so (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#03 pc 0x357d0 libbase.so (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
#04 pc 0x34d58 libbase.so (BuildId: 6f67f69ff36b970d0b831cfdab3b578d)
#05 pc 0x3f599c libart.so (BuildId: 4cfdaa9e5146c43e20ae36ee1caf9b7f)
#06 pc 0x1cc848 libhermes_executor.so (BuildId: 57e4e5e068460e51)
#07 pc 0x886ac libreactnativejni.so (BuildId: 768f3e0508321b44)
#08 pc 0x81150 libreactnativejni.so (BuildId: 768f3e0508321b44)
#09 pc 0x15e84 libfbjni.so (BuildId: 27496b9e5551bff5c79496b936b663bf8868c68b)
#10 pc 0x15dfc libfbjni.so (BuildId: 27496b9e5551bff5c79496b936b663bf8868c68b)
#11 pc 0x79c03eb084
```

And

```
Crashed: Thread: SIGSEGV  0x0000007eca3ad580
#00 pc 0x86728 libc.so (BuildId: 270f0ac9b60bc2d5e50a8ffb6bbe9ca6)
#01 pc 0x35e4c libaaudio_internal.so (BuildId: d636424f25c25a14c9741b1dbec79997)
#02 pc 0x2bd30 libaaudio_internal.so (BuildId: d636424f25c25a14c9741b1dbec79997)
#03 pc 0x9a870 libaudioclient.so (BuildId: e0cfae51c59308e62e2a0daec5336956)
#04 pc 0x999b4 libaudioclient.so (BuildId: e0cfae51c59308e62e2a0daec5336956)
#05 pc 0x12f18 libutils.so (BuildId: a5ca39eaeeeb017be4afa358811e69fb)
#06 pc 0xcc150 libandroid_runtime.so (BuildId: 7e12f92b032cf1c04caa83150c134f98)
#07 pc 0xef578 libc.so (BuildId: 270f0ac9b60bc2d5e50a8ffb6bbe9ca6)
#08 pc 0x8c23c libc.so (BuildId: 270f0ac9b60bc2d5e50a8ffb6bbe9ca6)
```

**Comment by cnx-caiobarroso** [comment]
@tmikov 
I'm sorry for my lack of knowledge in the area, but isn't this hermes related?

#06 pc 0x1cc848 libhermes_executor.so (BuildId: 57e4e5e068460e51)

**Comment by neildhar** [comment]
`libhermes_executor.so` is a React Native library, so we unfortunately cannot provide much input here. RN may be able to help investigate this if you can obtain a symbolicated stack trace from that crash.

**Comment by tmikov** [comment]
@cnx-caiobarroso `libhermes_executor.so` is obviously related to Hermes, but it is not Hermes. Hermes is contained entirely  in `libhermes.so`. `libhermes_executor.so` is a part of React Native and provides some additional functionality: 

https://github.com/facebook/react-native/blob/3b6c522942ca1b3d3f5e2115e0a4e781063747d0/packages/react-native/ReactCommon/hermes/executor/HermesExecutorFactory.cpp

Besides, even `libhermes_executor.so` is not present in the second stack trace.

I see no evidence that this is caused by a bug in Hermes. I am curious to see the discussion in React Native that pointed you in this direction.

Two pieces of advice:
- By far the most common user mistake we see is people using Hermes simultaneously from two threads. If you can, make sure that isn't happening.
- You need a proper symbolicated stack trace to investigate this.
