### ISSUE TITLE
Is hermes really AOT?

### ISSUE THREAD

**Issue by yuanyan** [facebook/hermes#130]
Could hermes compile js to machine code for different arch like iOS?

**Comment by tmikov** [comment]
The Hermes compiler generates bytecode ahead of time which is later executed by a bytecode interpreter in the Hermes engine. So it can run on any platform for which the engine can be compiled.

You can see more details about Hermes in the second part of this [presentation](https://drive.google.com/open?id=1mgKxKlpgjm2_KX4TP-G7hUti-JKjR2Xv).

**Comment by yuanyan** [comment]
So is hermes could used in iOS?
