### ISSUE TITLE
Document Visual C++ requirement

### ISSUE THREAD

**Issue by cup** [facebook/hermes#131]
I see that Visual C++ 2015 (14.0) is required, but I dont see that documented
anywhere. These files are required for use:

~~~
msvcp140.dll
vcruntime140.dll
~~~

https://blogs.technet.microsoft.com/jagbal/2017/09/04/where-can-i-download

**Comment by tmikov** [comment]
Thank you for pointing this out. We are looking into it. Most likely we will ship the redistributable with our binaries.

**Comment by tmikov** [comment]
16be5573fe8ea5d865b9f40a8b100feccc26e84b addresses this, but we haven't made a new binary release with the new files yet.

**Comment by cup** [comment]
Thats an interesting commit - those files arent guarantee to exist in that folder

but perhaps they are on the build machine? Just wanted to point that out, thanks

**Comment by willholen** [comment]
Yes, this is the CircleCI build script which is exclusively used for (and highly tied to) the CircleCI environment.

The build files that someone would use to build their own local version of Hermes does not make any assumptions about the location or even existence of these files.
