### ISSUE TITLE
Wrong `DCMAKE_TOOLCHAIN_FILE` in docs

### ISSUE THREAD

**Issue by changwoolab** [facebook/hermes#1316]
## Description

docs link: https://hermesengine.dev/docs/emscripten/#setting-up-workspace-and-host-hermesc

I think DCMAKE_TOOLCHAIN_FILE should be 
`-DCMAKE_TOOLCHAIN_FILE=${EmscriptenRoot?}/cmake/Modules/Platform/Emscripten.cmake`

Because docs says
`$EmscriptenRoot = ~/emsdk/upstream/emscripten` and 
`-DCMAKE_TOOLCHAIN_FILE=${EmscriptenRoot?}/emscripten/cmake/Modules/Platform/Emscripten.cmake`
but there is no `~/emsdk/upstream/emscripten/emscripten/cmake/*` but `~/emsdk/upstream/emscripten/cmake/*`

I'm a noob to this and I could be wrong.
Thank you!

**Comment by neildhar** [comment]
Good catch, we'll fix it right away

**Comment by changwoolab** [comment]
Oh Thank you!
