### ISSUE TITLE
Does not compile in iOS

### ISSUE THREAD

**Issue by CyberMew** [facebook/hermes#1322]
## Bug Description

In Pods: [Hermes] Using the latest commit from main.

Showing Recent Issues
/Users/user/Downloads/AwesomeProject4/node_modules/react-native/ReactCommon/hermes/inspector-modern/InspectorState.cpp:225:40: No member named 'AsyncTrigger' in 'facebook::hermes::debugger::PauseReason'

/Users/user/Downloads/AwesomeProject4/node_modules/react-native/ReactCommon/hermes/inspector-modern/InspectorState.cpp:366:33: No member named 'AsyncTrigger' in 'facebook::hermes::debugger::PauseReason'

Also tried other RN versions https://github.com/facebook/react-native/issues/43082

Sidenote: CMAKE is apparently required but it is not part of any dependencies (something to take note of, otherwise the scripts cannot compile at all and error immediately)

- [x] I have confirmed this bug does not occur with JSC
- [x] The issue is reproducible with the latest version of React Native.

Hermes git revision (if applicable):
React Native version: 0.73.4
OS: macOS Sonama 14.3.1
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): Apple Silicon

## Steps To Reproduce

1. Init a new AwesomeProject for 0.73.4. 
2. Build iOS

code example: NA

## The Expected Behavior

Compiles successfully.

**Comment by neildhar** [comment]
Hey @CyberMew, it looks like the latest changes to our debugger API are not source compatible with older versions of React Native. We do maintain source compatibility for JSI, but we don't generally guarantee compatibility for the Hermes C++ API. That said, we are working towards a stable C-based binary interface that will allow new versions of Hermes to be dropped into older versions of RN.

Given that this change is relatively small, it may be possible to work around it by making some minor source modifications, or  building without debugging enabled.

**Comment by dannysu** [comment]
hi @CyberMew, I believe that file has been removed in newer React Native versions. And as @neildhar mentioned, our C++ API is not source compatible with older RN versions.

That said, the compilation problem is a simple one to fix. One workaround you can do is by modifying places that read `PauseReason::AsyncTrigger` to use `PauseReason::AsyncTriggerImplicit` instead.

**Comment by CyberMew** [comment]
Thank you all for the information. May I know to which version of RN is this supported back?

I am using the latest stable RN version 0.73.4 as mentioned (fresh project), do I have to switch to 0.74 RC for this to work out of the box? From the pod logs for 0.73.4 it is already pulling from main branch, so shouldn’t it already be the latest Hermes code?

**Comment by CyberMew** [comment]
I just tried the workaround to replace the 2 occurrences in node_modules/react-native/ReactCommon/hermes/inspector-modern/InspectorState.cpp, it did kinda work, but it still failed with another error:

[ 96%] Building CXX object API/hermes/CMakeFiles/libhermes.dir/cdp/DebuggerDomainAgent.cpp.o
[ 96%] Building CXX object API/hermes/CMakeFiles/libhermes.dir/inspector/chrome/MessageTypes.cpp.o
[ 98%] Building CXX object API/hermes/CMakeFiles/libhermes.dir/cdp/RuntimeDomainAgent.cpp.o
[ 98%] Building CXX object API/hermes/CMakeFiles/libhermes.dir/inspector/chrome/MessageConverters.cpp.o
/Users/user/Downloads/AwesomeProject4/ios/Pods/hermes-engine/API/hermes/hermes.cpp:623:63: error: only virtual member functions can be marked 'override'
  void setExternalMemoryPressure(const jsi::Object &, size_t) override;
                                                              ^~~~~~~~
[ 98%] Building CXX object API/hermes/CMakeFiles/libhermes.dir/inspector/chrome/MessageInterfaces.cpp.o
1 error generated.
make[3]: *** [API/hermes/CMakeFiles/libhermes.dir/hermes.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 98%] Building CXX object API/hermes/CMakeFiles/libhermes.dir/cdp/RemoteObjectsTable.cpp.o
[ 98%] Building CXX object API/hermes/CMakeFiles/libhermes.dir/inspector/chrome/JSONValueInterfaces.cpp.o
make[2]: *** [API/hermes/CMakeFiles/libhermes.dir/all] Error 2
make[1]: *** [API/hermes/CMakeFiles/libhermes.dir/rule] Error 2
make: *** [libhermes] Error 2
++ echo 'Copy Apple framework to destroot/Library/Frameworks'

Going to ios/Pods/hermes-engine/API/hermes/hermes.cpp Line 623 and deleting "override" makes it compilable now, but more errors appears when I continue to build:

```
Showing Recent Errors Only
Undefined symbol: facebook::jsi::HostObject::getPropertyNames(facebook::jsi::Runtime&)
Undefined symbol: facebook::jsi::HostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)
Undefined symbol: facebook::jsi::HostObject::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)
Undefined symbol: facebook::jsi::HostObject::~HostObject()
Undefined symbol: facebook::jsi::NativeState::~NativeState()
Undefined symbol: facebook::jsi::JSINativeException::~JSINativeException()
Undefined symbol: facebook::jsi::Array::createWithElements(facebook::jsi::Runtime&, std::initializer_list<facebook::jsi::Value>)
Undefined symbol: facebook::jsi::Value::Value(facebook::jsi::Value&&)
Undefined symbol: facebook::jsi::Value::Value(facebook::jsi::Runtime&, facebook::jsi::Value const&)
Undefined symbol: facebook::jsi::Value::~Value()
Undefined symbol: facebook::jsi::Buffer::~Buffer()
Undefined symbol: facebook::jsi::JSError::JSError(facebook::jsi::Runtime&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)
Undefined symbol: facebook::jsi::JSError::JSError(facebook::jsi::Runtime&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)
Undefined symbol: facebook::jsi::JSError::JSError(facebook::jsi::Runtime&, facebook::jsi::Value&&)
Undefined symbol: facebook::jsi::JSError::~JSError()
Undefined symbol: facebook::jsi::Pointer::operator=(facebook::jsi::Pointer&&)
Undefined symbol: facebook::jsi::Runtime::createValueFromJsonUtf8(unsigned char const*, unsigned long)
Undefined symbol: facebook::jsi::Runtime::~Runtime()
Undefined symbol: facebook::jsi::Value::asBool() const
Undefined symbol: facebook::jsi::Value::asNumber() const
Undefined symbol: facebook::jsi::Object::getPropertyAsObject(facebook::jsi::Runtime&, char const*) const
Undefined symbol: facebook::jsi::Object::getPropertyAsFunction(facebook::jsi::Runtime&, char const*) const
Undefined symbol: facebook::jsi::Value::asObject(facebook::jsi::Runtime&) const &
Undefined symbol: facebook::jsi::Value::asString(facebook::jsi::Runtime&) const &
Undefined symbol: facebook::jsi::Object::asFunction(facebook::jsi::Runtime&) const &
Undefined symbol: facebook::jsi::Value::asObject(facebook::jsi::Runtime&) &&
Undefined symbol: facebook::jsi::Value::asString(facebook::jsi::Runtime&) &&
Undefined symbol: facebook::jsi::Object::asFunction(facebook::jsi::Runtime&) &&
Undefined symbol: typeinfo for facebook::jsi::HostObject
Undefined symbol: typeinfo for facebook::jsi::NativeState
Undefined symbol: typeinfo for facebook::jsi::JSINativeException
Undefined symbol: typeinfo for facebook::jsi::Buffer
Undefined symbol: typeinfo for facebook::jsi::JSError
Undefined symbol: typeinfo for facebook::jsi::Runtime
Undefined symbol: vtable for facebook::jsi::HostObject
Undefined symbol: vtable for facebook::jsi::NativeState
Undefined symbol: vtable for facebook::jsi::JSIException
Undefined symbol: vtable for facebook::jsi::JSINativeException
Undefined symbol: vtable for facebook::jsi::Buffer
Undefined symbol: vtable for facebook::jsi::Runtime
```

Something seems seriously not right here... Just wondering if it is an issue on my personal laptop or the project or podspec.

**Comment by CyberMew** [comment]
Hi, thank you for the information. I am not actually doing it myself, but React Native is the one pulling it from repo during `pod install`.  I actually had to install cmake for the iOS script to compile (or it will fail straightaway without reason) as I thought it was a new change. Here are the logs when running pod install from a fresh copy of 0.73.4:
```
-> Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the latest commit from main.
Const Defined!

Resolving dependencies of `Podfile`
...
-> Installing hermes-engine (0.73.4)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/facebook/hermes.git
     /var/folders/k_/xy96gkc174zbxxm83lp7npgc0000gp/T/d20240226-77169-alau10
     --template=
     Cloning into '/var/folders/k_/xy96gkc174zbxxm83lp7npgc0000gp/T/d20240226-77169-alau10'...
     Updating files: 100% (10870/10870), done.
   $ /usr/bin/git -C
   /var/folders/k_/xy96gkc174zbxxm83lp7npgc0000gp/T/d20240226-77169-alau10 checkout
   --quiet db06dc2ef19f88343e2ec362d63d301be8d8e355
 > Running prepare command
   $ /bin/bash -c  set -e .
   /Users/user/Downloads/AwesomeProject4/node_modules/react-native/sdks/hermes-engine/../../sdks/hermes-engine/utils/create-dummy-hermes-xcframework.sh
   ++ rm -rf destroot
   ++ mkdir -p destroot/Library/Frameworks
   ++ pushd destroot/Library/Frameworks
   ++ echo ''
   ++ mkdir -p macosx/hermes.framework
   ++ clang dummy.c -dynamiclib -o macosx/hermes.framework/hermes
   ++ mkdir -p ios/hermes.framework
   ++ clang dummy.c -dynamiclib -o ios/hermes.framework/hermes
   ++ rm dummy.c
   ++ popd
  > Copying hermes-engine from
  `/Users/user/Library/Caches/CocoaPods/Pods/External/hermes-engine/98848d96c55ab96e916e0a7c8ab1435b-9819c`
  to `Pods/hermes-engine`
...
[!] hermes-engine has added 2 script phases. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.
```
Doing a search and it seems some others are facing issue with building on iOS as well (though they did not provide actual error but I assume is similar): https://stackoverflow.com/questions/77956730/setting-up-react-native-version-0-73-4-environment-installing-at-ios-for-macos

I do not have any issue with RN 0.71.x, since the podspec pulls the tar file from maven.

Not sure why it is pulling from source, but I also tried `BUILD_FROM_SOURCE=false bundle exec pod install` to no avail - it still pulls from main (not hitting maven).

**Comment by neildhar** [comment]
@CyberMew it certainly shouldn't be trying to build Hermes from source right out of the box. React Native distributes prebuilt binaries for Hermes that should be used instead. Could you share your exact steps for setting up the project? It may be an issue in React Native instead.

**Comment by tmikov** [comment]
Uh-oh, at the very least it looks like building Hermes from source using CocoaPods isn't well supported by RN. We need to look into that.

**Comment by Ann-MarieKemp** [comment]
My team is experiencing this issue as well. My teammates and I who are located in the US don't have an issue building our React Native project but our deployment system located in Europe and a colleague located there as well have the same `PauseReason::AsyncTrigger` issue when running our pod install command. We are all building from the same source code and would expect the pod install process to work the same way for all of us.

**Comment by tmikov** [comment]
@Ann-MarieKemp it looks like there are two problems here:
1. RN distributes binary versions of Hermes, it should not be building from source at all.
2. Additionally, looks like building from source is broken and uses an incorrect version of Hermes.

The integration of Hermes with React Native and the associated build process is owned by React Native, so I am transferring this issue to them.
