### ISSUE TITLE
fatal: unable to access 'http://github.com/facebook/hermes.git/'

### ISSUE THREAD

**Issue by MoSattler** [facebook/hermes#1323]
When trying to build my RN code for iOS in Xcode cloud, it seems like there is a persistent connection problem:

```
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the latest commit from main.
fatal: unable to access 'http://github.com/facebook/hermes.git/': Failed to connect to 172.17.121.157 port 8088 after 3 ms: Couldn't connect to server
Const Defined!
[!] Failed to load 'hermes-engine' podspec: 
[!] Invalid `hermes-engine.podspec` file: [!] Unable to locate the executable `cmake`.
 #  from /Volumes/workspace/repository/node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec:116
 #  -------------------------------------------
 #        puts "Const Defined!"
 >        CMAKE_BINARY = Pod::Executable::which!('cmake')
 #        # NOTE: Script phases are sorted alphabetically inside Xcode project
 #  -------------------------------------------
Error
Command exited with non-zero exit-code: 1
Warning
```

is this a known problem for Hermes + xcloud? Cause the IP looks like a private one.

**Comment by tmikov** [comment]
I am sorry, no idea what XCode Cloud is, unfortunately we are unable to provide support for it. We can help with issues with the CMake build itself, but beyond that, the Hermes podspec is maintained by React Native: https://github.com/facebook/react-native/tree/main/packages/react-native/sdks/hermes-engine.

Judging from the error output above, seems that CMake is missing.

**Comment by MoSattler** [comment]
Hey @tmikov - Got it, thanks for checking it out! Just as a sidenote, [Xcode Cloud](https://developer.apple.com/xcode-cloud/) is Apple's CI/CD for building, testing, deploying (etc).
