### ISSUE TITLE
I hope Static Hermes supported Windows, Linux, and MacOS.

### ISSUE THREAD

**Issue by Foxchandaisuki** [facebook/hermes#1339]
I think Static Hermes is very awesome, and could be a killer function for Flutter.

But for now, it only supports iOS and Android.  It would be better for static Hermes to support Windows, Linux, and MacOS.

**Comment by tmikov** [comment]
Hi, that is inaccurate. Similarly to Hermes, Static Hermes is mostly OS-agnostic and targets all major platforms.

**Comment by Foxchandaisuki** [comment]
Thx for answer. Could you please answer this question, too?

https://github.com/facebook/hermes/issues/1341

2024년 3월 11일 (월) 오전 11:49, Tzvetan Mikov ***@***.***>님이 작성:
