### ISSUE TITLE
A possible performance issue

### ISSUE THREAD

**Issue by YaoHouyou** [facebook/hermes#134]
### Version
[3826084](https://github.com/facebook/hermes/tree/382608426baaa059b8220d6135cebc426a21a1d5)

### Build steps
```
hermes/utils/build/build_llvm.py --distribute
hermes/utils/build/configure.py --distribute
cd build_release && ninja
```
### Testcase
```
var NISLFuzzingFunc = function(size) {
    var array = new Array(size);
    while (size--){
        array[size] = 0;
    }
    print(array.length);
};
var NISLParameter0 = 904862;
NISLFuzzingFunc(NISLParameter0);
```
### Output
```
904862
```
### Execution steps
```
./build_release/bin/hermes -w testcase.js
```
### Description
Hermes performed the above test case for 31 minutes and 30 seconds, while other engines runs took less than 1 second, such as v8, spiderMonkey, chakra, javascriptCore. So, I suspect that hermes is not optimized.
The execution time of each engine is as follows:
v8: `92 ms`
spiderMonkey: `113 ms`
chakra: `328 ms`
javascriptCore: `142 ms`
hermes: `1830309 ms`

**Comment by tmikov** [comment]
Thank you for reporting this. In this case Hermes optimizes for memory footprint - we only allocate storage for the elements that exist, so if you are initializing the array in reverse order, Hermes has to reallocate the array for every new element inserted on the left.

We realize that this is a use case that may come up, so we will investigate if we can improve it.
