### ISSUE TITLE
Hermes Date constructor problem

### ISSUE THREAD

**Issue by chufengma** [facebook/hermes#136]
in hermes(0.2.1):

``` 
// test.js
let d = new Date("2019/10/16").getTime();
print(d);
----
// run with hermes 0.2.1
>>> hermes-cli-darwin-v0.2.1/hermes test.js
>>> NAN
```

in Node:
```
let d = new Date("2019/10/16").getTime();
console.log(d);
----
// run with node
>>> node test.js
>>> 1571155200000
```

**Comment by chufengma** [comment]
And 
```
new Date("2019-10-16 00:00:00+0800").getTime()
---
NaN
```

**Comment by mhorowitz** [comment]
@ljharb is correct.  In order to keep the VM small, we have chosen to parse only the strings the spec requires.  If you require parsing other date formats, we suggest using an npm module which implements richer date parsing such as https://www.npmjs.com/package/moment, or you can write your own.

**Comment by flyskywhy** [comment]
https://www.npmjs.com/package/dayjs

    let d = new Date(dayjs("2019/10/16")).getTime();

**Comment by PrimulaX** [comment]
In RN project on Android (Hermes enabled) app keeps crashing on `Date.prototype.toDateString()`

**Comment by mhorowitz** [comment]
@PrimulaX please open a new issue using one of the forms at https://github.com/facebook/hermes/issues/new/choose.  Include as much logging or repro information as you can.
