### ISSUE TITLE
Closures caputure external variable errors

### ISSUE THREAD

**Issue by cs-robert** [facebook/hermes#1360]
## Bug Description

I packaged the js code using webpack and executed it with the hermes engine, but the results didn't work as expected

Hermes git revision (if applicable): 0.6.0

OS:Android 

my_engineGlobal should be v1
but it's value is not 

code example:
<img width="828" alt="图片" src="https://github.com/facebook/hermes/assets/6836667/31ce99a0-27a8-43bb-8d84-177b43853d6e">

demo https://github.com/cs-robert/hermesTest

run demo ,click test ,adb logcat | grep JsNativeLog
The originGlobal value is really weird

**Comment by tmikov** [comment]
I am sorry, can you please provide a minimal reproduction of the problem using the Hermes CLI?

**Comment by cs-robert** [comment]
> I am sorry, can you please provide a minimal reproduction of the problem using the Hermes CLI?
The logic of executing js is very simple, just inject a JsNativeLog method to print the log, and then execute test.js
all code is in https://github.com/cs-robert/hermesTest
Java_com_example_hermestest_MainActivity_evaluateJavaScript(JNIEnv *env, jclass clazz,
                                                            jstring script) {
    try {
        std::shared_ptr<facebook::hermes::HermesRuntime> runtime = facebook::hermes::makeHermesRuntime();
        runtime->global().setProperty(*runtime, "JsNativeLog", facebook::jsi::Function::createFromHostFunction(
                *runtime,
                facebook::jsi::PropNameID::forAscii(*runtime, "JsNativeLog"),
                0,
                [](facebook::jsi::Runtime &rt,
                   const facebook::jsi::Value &thisVal,
                   const facebook::jsi::Value *arguments,
                   size_t argumentCount) {
                    auto str = arguments[0].getString(rt).utf8(rt);
                    __android_log_print(ANDROID_LOG_INFO, "JsNativeLog", "JSLog  %s", str.c_str());
                    return facebook::jsi::Value();
                }));
        const char *scriptChar = env->GetStringUTFChars(script, nullptr);
        std::string source = std::string(scriptChar);
        std::shared_ptr<const facebook::jsi::Buffer> hbcPtr = std::make_unique<facebook::jsi::StringBuffer>(source);
        runtime->evaluateJavaScript(hbcPtr, "test.js");
    } catch (const facebook::jsi::JSError &error) {
        __android_log_print(ANDROID_LOG_ERROR, "JsNativeLog", "%s %s", error.getMessage().c_str(), error.getStack().c_str());
    } catch (const facebook::jsi::JSIException &err) {
        __android_log_print(ANDROID_LOG_ERROR, "JsNativeLog", "%s", err.what());

    } catch (const std::exception &ex) {
        __android_log_print(ANDROID_LOG_ERROR, "JsNativeLog", "%s", ex.what());

    } catch (...) {

    }

}

**Comment by cs-robert** [comment]
> I am sorry, can you please provide a minimal reproduction of the problem using the Hermes CLI?
Strangely enough, when I delete some of the WebPack-generated code in the js file, it works fine.What I'm removing is a closure that won't execute and doesn't affect the logic。
my_engineGlobal, my_engineGlobal2, my_engineGlobal3, my_engineGlobal4... These variables are simply defined and printed in a method without any logic to modify them

**Comment by cs-robert** [comment]
![image](https://github.com/facebook/hermes/assets/6836667/f9dc7a8a-2727-4211-a25c-ef8bf8b6afca)

**Comment by cs-robert** [comment]
hbc doesn't seem to have this problem, not sure if it's a coincidence or really OK

**Comment by tmikov** [comment]
@cs-robert in your first post you said Hermes version 0.6.0. That version is almost 4 years old. Can you reproduce this with the latest Hermes version?

**Comment by cs-robert** [comment]
> @cs-robert in your first post you said Hermes version 0.6.0. That version is almost 4 years old. Can you reproduce this with the latest Hermes version?

0.7.2 work fine,Why is hbc OK? And want to understand the specific logic of what caused it? How was it repaired?

**Comment by tmikov** [comment]
@cs-robert it is hard to say, many things have changed in 4 years. Still, resolution of variables is very important, so I am pretty sure that old versions didn't have major bugs related to it. You might be seeing a problem related to *lazy compilation* in an unexpected context: when running from source, Hermes lazily compiles every function when it is called the first time, which is a complicated process.
