### ISSUE TITLE
How to write C++ addons?

### ISSUE THREAD

**Issue by kneth** [facebook/hermes#137]
It appears to be a popular request that [Realm supports for Hermes](https://github.com/realm/realm-js/issues/2455), and I guess other C++ libraries are in the same situation.

Is there a small demo C++ addon to take a look at? Or any official documentation on how to develop C++ addons for Hermes?

**Comment by mhorowitz** [comment]
There are some pointers to the code documentation and a sample in [this comment](https://github.com/facebook/hermes/issues/43#issuecomment-512558215).

If you are looking to add functionality which can be used from JavaScript, you should take a look at JSI's HostFunction and HostObject APIs.
