### ISSUE TITLE
Partial async generator support persent in Hermes isn't spec compliant

### ISSUE THREAD

**Issue by leotm** [facebook/hermes#1380]
## Bug Description

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC
- [x] The issue is reproducible with the latest version of React Native.

Hermes git revision (if applicable): [hermes-2023-03-07-RNv0.71.4-ee25883ea34374f687883a641c8101ac0d292fc6](https://github.com/facebook/hermes/releases/tag/hermes-2023-03-07-RNv0.71.4-ee25883ea34374f687883a641c8101ac0d292fc6)
React Native version: 71.17
OS: Android (running on macOS)
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce

Attempt to access async iterator proto

code example:

```js
async function* AsyncGeneratorFunctionInstance() {}
const AsyncGeneratorFunction = Object.getPrototypeOf(
  AsyncGeneratorFunctionInstance,
).constructor
const AsyncGenerator = AsyncGeneratorFunction.prototype;

const asyncIterable = {
  async *[Symbol.asyncIterator]() {},
};
var results = [
  typeof asyncIterable[Symbol.asyncIterator].prototype.__proto__ === 'object', // it's an object even in Hermes, but looks a different shape
  typeof AsyncGenerator.prototype, // undefined on hermes
  asyncIterable[Symbol.asyncIterator].prototype.__proto__ === AsyncGenerator.prototype, // true in other engines
  asyncIterable[Symbol.asyncIterator].prototype.__proto__.__proto__ // null in Hermes, object with an iterator fn in other engines
];

// Node 18.18.2
// console.log(Object.getOwnPropertyDescriptors(asyncIterable[Symbol.asyncIterator].prototype.__proto__.__proto__))
// {
//   [Symbol(Symbol.asyncIterator)]: {
//     value: [Function: [Symbol.asyncIterator]],
//     writable: true,
//     enumerable: false,
//     configurable: true
//   }
// }

throw JSON.stringify(results);
```

## The Expected Behavior

Other engines: `[true,"object",true,{}]`
Hermes: `[true,"undefined",false,null]`

**Comment by tmikov** [comment]
Sorry, Hermes has no async iterator support at the moment (though we will add it to Static Hermes). I think you are essentially testing a Babel transformation.

**Comment by leotm** [comment]
thanks for clarifying ^ and great it will be in Static Hermes 🎉

my mistaken assumption was `node_modules/react-native/Libraries/Core/InitializeCore.js` is running Babel-free

to run in a React Native environment w/o Babel you could
```js
new Function('{var}', String.raw`
  // my code
`)({var: 1});
```

or the usual way

```js
// babel.config.js
module.exports = {
  ignore: [/myFile\.cjs/],
  presets: ['module:metro-react-native-babel-preset'],
};
```

or outside the React Native environment, directly via the Hermes [CLI](https://github.com/facebook/hermes/releases/tag/v0.12.0) or [building](https://github.com/facebook/hermes/blob/main/doc/BuildingAndRunning.md) the [static_h](https://github.com/facebook/hermes/tree/static_h) branch for latest
