### ISSUE TITLE
Support for Async/Await and Promise with JSI API

### ISSUE THREAD

**Issue by verenkoska** [facebook/hermes#1381]
## Description
The following code only prints the string when using the Hermes' executable, but not with the JSI API:

```
async function test() {
 await 1;
 print("Hello World!");
}
test();
```

Same happens with promises:

```
promise = new Promise(function(resolve) { resolve(); });
promise.then(function() { print("Hello World!"); });
```

Do you know how can I get the same behaviour in both situations?
I already tried multiple runtime configurations when creating the JSI runtime, but did not manage to find a solution.

Thank you for the support!

**Comment by tmikov** [comment]
Is this a custom integration of Hermes, outside of RN? 

Promises and async require an event loop and one of:
- Preferably, the [micro-task queue](https://github.com/facebook/hermes/blob/b0cae0b9c7aadd295145c295ffb87db9b401cb62/public/hermes/Public/RuntimeConfig.h#L79) has to be enabled and [drained](https://github.com/facebook/hermes/blob/b0cae0b9c7aadd295145c295ffb87db9b401cb62/API/jsi/jsi/jsi.h#L246) in every iteration of the event loop
- Or an enqueuing function has to be stored in the global property `setImmediate()`.

**Comment by trossimel-sc** [comment]
Thank you for the response!
Yes, it's custom. 
Are there plans to integrate an event loop when using the JSI Api?

**Comment by verenkoska** [comment]
Thank you for the response!
Yes, it's custom.
Are there plans to integrate such a behaviour when using the JSI Api?
