### ISSUE TITLE
Address Sanitizer tests failing with ES6 Classes

### ISSUE THREAD

**Issue by Beanyy** [facebook/hermes#1388]
## Bug Description

I'm running address sanitization tests on our code base with Hermes and I'm encountering a consistent stack-use-after-scope errors with ES6 classes. I've narrowed down the issue to the code here:

https://github.com/facebook/hermes/blob/7991309805159967d2b045fbe722f1aad2d43409/lib/AST/ES6Class.cpp#L58-L65

One of the calling functions `makeHermesES6InternalCall` calls `toNodeList` which returned an `ESTree::NodeList` that was allocated on the stack. Changing the code such that the `ESTree::NodeList` is created on the stack of `makeHermesES6InternalCall` instead fixes the ASAN error. I'm not 100% sure why this is happening and it may be due to some compiler specific optimizations. 
https://github.com/facebook/hermes/blob/7991309805159967d2b045fbe722f1aad2d43409/lib/AST/ES6Class.cpp#L400-L412

It creates a little bit a repetitiveness but removing the `toNodeList` function (and replacing the calling sites with the appropriate fix) resolved the issue entirely for me.

Let me know what you think.

---

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC
- [ ] The issue is reproducible with the latest version of React Native.

Hermes git revision (if applicable):
React Native version:
OS:
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1.
2.

code example:

**Comment by tmikov** [comment]
Thank you for catching this!

This is a compiler bug in Apple CLang. It was worked around in Static Hermes in https://github.com/facebook/hermes/commit/b6a791ce924c65d8ae16ca339c9f8e4b9416086b, but we must have forgotten to backport it to Hermes.

We will backport the fix. 

Please note that the ES6 classes AST transform is undocumented and unsupported. But it still shouldn't crash :-)

**Comment by Beanyy** [comment]
Thanks! That fixed the issue.
