### ISSUE TITLE
Importing files suppress `async generators are unsupported` errors

### ISSUE THREAD

**Issue by leotm** [facebook/hermes#1389]
## Bug Description

Hermes suppresses `async generators are unsupported` errors in imported files

https://github.com/facebook/hermes/blob/7991309805159967d2b045fbe722f1aad2d43409/lib/AST/SemanticValidator.cpp#L798-L800

OS: Android, iOS
Platform : arm64-v8a (macOS, M2)

## Steps To Reproduce

`npx react-native@latest init RN07119 --version 0.71.19`

`npx react-native@latest init RN07214 --version 0.72.14`

```cjs
// file.cjs
async function* foo() {
  yield await Promise.resolve('a');
  yield await Promise.resolve('b');
  yield await Promise.resolve('c'); // remove this yield to see error in sim/emu
};
function bar() {}; // remove this fn to see error in sim/emu

// Try this example wrapped in a new Function(String.raw``)() to see error

// Hot reload any change to see error in Metro
// [Error: Exception in HostFunction: Compiling JS failed: 2:3:async generators are unsupported Buffer size 665 starts with: 5f5f642866756e6374696f6e2028676c]
```

```js
// babel.config.js
module.exports = {
  ignore: [/file\.cjs/],
  presets: ['module:metro-react-native-babel-preset'],
};

```

```js
// e.g. index.js, App.tsx, node_modules/react-native/Libraries/Core/InitializeCore.js
require('./file.cjs');
```

## The Expected Behavior

Error `async generators are unsupported` ([Android](https://github.com/facebook/hermes/assets/1881059/6e982d0c-8b56-4424-bc70-143ebd11c286), [iOS](https://github.com/facebook/hermes/assets/1881059/19aa9431-504e-4d91-ac22-2ea1d6a9e77a))

**Comment by tmikov** [comment]
I am not sure I understand the problem. What are "imported files"? 

Hermes, in the way it is currently used by React Native, has no concept of modules or imported files. It sees a single source file that has been transformed by Babel and packaged by Metro. If that file contains async generators, Hermes will report an error.

**Comment by leotm** [comment]
i see ^ i mean files ignored by Babel, required or imported like
- index.js > require('./file.cjs')
- index.js > App.tsx > require('./file.cjs')
- node_modules/react-native/Libraries/Core/InitializeCore.js > require('./file.cjs')

simple cases (stripping part of the example) report the Hermes error correctly to sim/emu
but more complex usage (full example, or [ses.cjs](https://github.com/MetaMask/metamask-mobile/blob/main/ses.cjs)) doesn't
unless e.g. called in a `new Function(String.raw``)()` which is strange

**Comment by leotm** [comment]
good point i suppose it's not Hermes side, since Metro hot reload outputs correctly to console
`[Error: Exception in HostFunction: Compiling JS failed: 2:3:async generators are unsupported Buffer size 665 starts with: 5f5f642866756e6374696f6e2028676c]`
so Hermes reports the single source file error correctly to Metro each change
also https://github.com/facebook/hermes/commit/8239e82977410dc7dfdaa5432549e98e5e6b19f2 hasn't changed in nearly a year

i'll close here to fix either RN side or Metro side
since the bug is failing to propagate the Hermes error to sim/emu
with beyond simple usage of async generators
