### ISSUE TITLE
Throw an exception that should not be thrown

### ISSUE THREAD

**Issue by YaoHouyou** [facebook/hermes#139]
### Version
[3826084](https://github.com/facebook/hermes/tree/382608426baaa059b8220d6135cebc426a21a1d5)

### Build steps
```
hermes/utils/build/build_llvm.py --distribute
hermes/utils/build/configure.py --distribute
cd build_release && ninja
```
### Testcase
```
var NISLFuzzingFunc = function(i) {
    while (--i >= 0) {
        this[i] = null;
    }
    print("hello world");
};
var NISLParameter0 = 710403;
NISLFuzzingFunc(NISLParameter0);
```
### Execution steps
```
./build_release/bin/hermes -w testcase.js
```
### Output
```
RangeError: Property storage exceeds 196607 properties
    at NISLFuzzingFunc (testcase.js:3:17)
    at global (testcase.js:8:16)
```
### Expected output
```
hello world
```

**Comment by tmikov** [comment]
This is by design. In order to be able to work in configurations with very constrained virtual address space, Hermes allocates memory in 4MB segments (the size is configurable at build time). In addition to that, for performance we have decided to restrict the number of property descriptors to a single segment, leading to this limitation.

The spec doesn't specify a limit to the number of properties in an object, but that number obviously can't be infinity, so we can think of this as a kind of out-of-memory error.

Admittedly this is not ideal, and we bump into this limitation occasionally, but this is one of those design decisions that make Hermes uniquely suited for its purpose.

**Comment by tmikov** [comment]
Note that this restriction on the number of properties does not exist for arrays.

**Comment by vicary** [comment]
Hot module reloading sometimes hit this, requires manual reload to clean things up.

**Comment by tmikov** [comment]
There must be an object that is used as a map somewhere in the code, which isn't being cleaned up.

**Comment by vicary** [comment]
@tmikov Can't confirm this because we are exactly in the middle of developing a module that do internal cleanups, it stopped happening again somewhere in the progress. Good catch though, stopped me from worrying if it was other little things.

**Comment by KianSalehi** [comment]
Hi! I seem to be having a similar issue. I was wondering if there was a fix for this? I read the comments and saw the comment "There must be an object that is used as a map somewhere in the code, which isn't being cleaned up." The only time I use a map function in my code it seems to be 
```javascript
{Object.entries(produitFiniData).map((item) => {
        var currItem = item[1];
        const inforOperateData = {
          0: currItem.numerodelot,
          1: currItem.type,
          2: currItem.numeroarticle,
          3: currItem.ligneproduction,
          4: currItem.couleur,
          5: currItem.lotfermeops,
          6: currItem.lotfermeqa,
        };
        const dropDownInfo = {
          0: currItem.derniertestqa.lumiere,
          1: currItem.derniertestqa.ph,
          2: currItem.derniertestqa.gout,
          3: currItem.derniertestqa.brix,
          4: currItem.derniertestqa.brixeaurincage,
        };
        const length = currItem.infoqahistorique.length;
        if (length == 0) {
          var currRowColor = AppColors.green;
        } else {
          const lastTest = currItem.infoqahistorique[length - 1];
          var currRowColor = checkRowColour(
            currItem.qatimerstatus,
            currItem.couleur,
            lastTest.lumiere,
            lastTest.temperature,
            lastTest.ph,
            lastTest.pressionair,
            lastTest.limpidite,
            lastTest.corpsetranger,
            lastTest.gout,
            lastTest.sceaubouchon,
            currItem.moyennepoidsnet,
            lastTest.brixeaurincage,
          );
        }

        return currItem.statut == 'Termine' ? null : (
          <TouchableBoxColum
            key={item}
            boxStyle={{backgroundColor: currRowColor}}
            currData={inforOperateData}
            dropDownInfo={dropDownInfo}
            onPressCityIcon={() =>
              navigation.navigate('InFoOperateProductFini', {
                produitFiniData: item[1],
              })
            }
            onPressEditIcon={() =>
              navigation.navigate('inFoQualityAsurance', {
                produitFiniData: item[1],
              })
            }
            onPressDocIcon={() =>
              submitSendNotification(
                currItem.numerodelot,
                id,
                currItem.lotfermeops,
                currItem.lotfermeqa,
              )
            }
          />
        );
      })}
```

**Comment by tmikov** [comment]
@KianSalehi my comment above, which you quoted, wasn't referring to the `map()` function, I was referring to an object being used as a dictionary. You would see this error if you put more than about 190,000 properties in a single object. Typically this indicates that the object is either used as an array, or is used as a dictionary. Both of these can be corrected by using an actual [array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) or an actual [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

**Comment by KianSalehi** [comment]
Oh I see! thank you very much.

**Comment by sbjang96** [comment]
Hi! Isn't this issue related to array?
What is the difference between using [ ] literal and using [array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) when declaring an array?

**Comment by ljharb** [comment]
@sbjang96 there shouldn’t be an inherent difference, altho it’s a bad idea to ever use Array() because it creates a sparse array, which is much harder to do unintentionally with literal syntax.

**Comment by sbjang96** [comment]
@ljharb Thanks for the answer, but it's not the answer I'm looking for. I wonder why the above issue is solved when using [array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) instead of [ ] literal in Hermes.

**Comment by tmikov** [comment]
@sbjang96 a regular object in Hermes has a limited number of properties (around 200,000 in a normal configuration).

If you need to insert more than 200,000 properties, and the property names are valid array indexes (like "1", "123", or "51267"), instead of an object, you can construct an array, either by using an array literal, or by calling the array constructor. Both `[]` and `Array()` work equally well.

If the property names are not valid array indexes, or if they are very sparse, you should construct a map using `new Map()`.

**Comment by sbjang96** [comment]
Thank you for answer.

**Comment by mpaliath** [comment]
@tmikov regarding "the size is configurable at build time" can you point me to the configuration that does this? 

I understand the limitation but we are investigating options to quickly unblock customers while we find all the objects affected and change them to map/array as needed.

**Comment by neildhar** [comment]
@mpaliath https://github.com/facebook/hermes/blob/main/CMakeLists.txt#L144-L146 defines the heap segment size, the number of properties allowed in an object is roughly proportional to the segment size.

**Comment by mpaliath** [comment]
Thank you @neildhar but maybe I misunderstood. Is this only settable at hermes build time or while building our app?

**Comment by DaAitch** [comment]
@tmikov do you know whether it's possible to change the segment size in a react-native project and if there are any draw-backs, like engine stability or overall higher memory usage for an application?

I our case, we use a setup where `Map` seems to not work at all (redux state) so it seems like the only solution is either splitting, changing hermes seg-size or reduce data. None of them seem to be easy.

**Comment by tmikov** [comment]
@DaAitch it is possible, if you manually rebuild Hermes. Such a configuration is less tested, but it should work, and I don't expect significant new bugs to surface there. If they did, it would be a priority for us to fix them (provided we can reproduce).

It is hard to predict how it will affect memory usage without measuring. Typically, smaller segment sizes benefit apps with very small heaps. Larger segment sizes mean that the heap is consumed in larger increments - whether it really makes a difference depends on the total heap size relative to the segment size. My intuition is that if you stay close to the default segment size - 2MB, 4MB, 8MB - it won't make a dramatic difference.  

Out of curiosity: why do you need this?

**Comment by DaAitch** [comment]
@tmikov thanks for clarifying this.

> Out of curiosity: why do you need this?

Our react-native app is offline-first and we have a lot of data. Global state management happens with `redux` and most entities are stored in object "maps" `id => entity`. At some point the engine just throws `RangeError: Property storage exceeds..`. We should maybe think of using `Map` and use the `replacer/reviver` parameters in `JSON.stringify/.parse` for persisting it to the filesystem.

**Comment by kapil21** [comment]
> Note that this restriction on the number of properties does not exist for arrays.

it fails for Array also . try this line  let arry  = Array(196608).fill(0); and it will fail.

**Comment by tmikov** [comment]
@kapil21 No, it does not fail for array.

<img width="299" alt="Screen Shot 2023-01-06 at 10 07 02 AM" src="https://user-images.githubusercontent.com/7785196/211072297-efdd6e41-614f-497c-8c1f-02b2d5db75dd.png">

**Comment by 1stmuse** [comment]
@tmikov  i don't have any object that has up to a 100 properties but i still get this error, what is the negative of turning off hermes in my application ?

**Comment by tmikov** [comment]
@1stmuse some library in your code must have an object with more than 190,000 properties.
