### ISSUE TITLE
ReferenceError: Property 'document' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by claudioviola** [facebook/hermes#1390]
I'm using hermes from my Expo React Native app

As far as I import this lib 
https://github.com/OfficeDev/microsoft-teams-library-js/releases/tag/v2.22.0

I get this error

ReferenceError: Property 'document' doesn't exist, js engine: hermes

Do you know how I could manage it?

**Comment by tmikov** [comment]
I am sorry, we can't really help to debug problems with 3rd party JS libraries, unless there is a minimal repro that clearly shows that there is a problem with Hermes.

With that said, this error is not very surprising, Hermes is not a web browser, so it doesn't provide a DOM implementation and doesn't expose a global property called `document`.

**Comment by claudioviola** [comment]
Totally understandable.
Thanks for the clarification

Il ven 3 mag 2024, 17:59 Tzvetan Mikov ***@***.***> ha
scritto:
