### ISSUE TITLE
JSI - Create a function that is backed by a jsi::HostObject?

### ISSUE THREAD

**Issue by andyjtb** [facebook/hermes#1402]
## Problem
Hi, I'm in the process of adding Hermes as a backend to [ScriptX](https://github.com/Tencent/ScriptX), which is a script engine wrapper allowing the backing engine to be switched out with a single CMake flag

In ScriptX there is the notion of a `ClassDefine`, which allows a user to fairly easily expose a C++ class to JS with familiar semantics
An example can be see [here](https://github.com/Tencent/ScriptX/blob/main/test/src/NativeTest.cc) 
But to take the important bit:
```
const ClassDefine<TestClass> TestClassDefAll =
    defineClass<TestClass>("TestClass")
        .nameSpace("script.engine.test")
        .constructor()
        .function("add", &TestClass::add)
        .function("add1", &TestClass::add_1)
        .property("version", &TestClass::getVersion, &TestClass::setVersion)
        .instanceFunction("greet", &TestClass::greet)
        .instanceFunction("age", &TestClass::age)
        .instanceProperty("src", &TestClass::getSrc, &TestClass::setSrc)
        .build();
```

This allows the below to be valid JS

```
const a = script.engine.test.TestClass.version;
let b = new script.engine.test.TestClass();
b.age(123)
b.src = "abc";
```

As you can see from this, we are able to not only map C++ functions, but also custom C++ getters and setters for JS properties

In order to recreate this behaviour I've made a class that inherits from `jsi::HostObject`
It stores all of the getters and setters as lambdas, and also owns a jsi::Object to use as a backing data store so JS properties/functions can be added at runtime too

The above setup works great for "static" instances, where we just create an instance of the HostObject and add it to global, so `script.engine.test.TestClass.version` works
However, I'm not sure what the best method for supporting `new` is

I've read the discussion [here](https://github.com/react-native-community/discussions-and-proposals/issues/91#issuecomment-611839611) regarding creating jsi::HostObjects but I'm not entirely sure how it maps to the above usage

I've tried adding a `prototype` property to the HostObject that returns a function, but I still get "constructor is not callable"

Is there a way to make a HostObject appear to JS as a Function?

**Comment by neildhar** [comment]
Hey @AndyBrown91, have you considered using an ordinary JavaScript function instead of a `jsi::HostObject`? You can populate your accessors as getters/setters on the function. Note that these getters or setters could be `jsi::HostFunction`s that update state on the native side associated with the object.

If you need to store data on the native side, you can attach a `jsi::NativeState` to any JS object (including functions), and access it from your `HostFunction`s. In general, keeping properties you want to use from JS directly in JS, instead of accessing them through `HostObject`s is preferable, since accessing JS properties is much more efficient, and reduces the risk of creating uncollectable cycles through `jsi::Value`s.

**Comment by neildhar** [comment]
You can use `Object.defineProperty` to set an arbitrary function (including a HostFunction) as a getter. Loosely, `Object.defineProperty(whatever, "myprop", {get: myHF, ...<other flags>})`.

**Comment by AndyBrown91** [comment]
Was just in the process of editing the above, thanks for pointing that out. I'll absolutely give that a go
Really appreciate you helping me reframe the issue

**Comment by mikehuebner** [comment]
Just chiming in on this, noticed that `typeof function` is returning `object` only within production builds.

**Comment by neildhar** [comment]
@mikehuebner have you observed a bug with Hermes in `typeof`? Could you open a new issue with the details and a minimal repro?
