### ISSUE TITLE
Getting error while installing pod for React native projects

### ISSUE THREAD

**Issue by nikesh8** [facebook/hermes#1410]
```
[!] Invalid `hermes-engine.podspec` file: undefined method `visionos' for #<Pod::Specification name="hermes-engine">.

 #  from /var/folders/2j/9ky63w7d4b5ck27l861k81p40000gp/T/d20240530-17004-j2x4a9/hermes-engine.podspec:34
 #  -------------------------------------------
 #    spec.ios.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"
 >    spec.visionos.vendored_frameworks = "destroot/Library/Frameworks/universal/hermes.xcframework"
 #    spec.osx.vendored_frameworks = "destroot/Library/Frameworks/macosx/hermes.framework"
 #  -------------------------------------------
 ```
 cocoapods: 1.12.1
 ruby: 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
 
react-native: 0.72.6
npm: 10.5.0
node: 20.12.2

![image](https://github.com/facebook/hermes/assets/55312626/833223b7-055f-4234-b208-16d0206f67a2)

Please provide a solution to fix this error.

**Comment by neildhar** [comment]
Hey @nikesh8, this part of the build is maintained by React Native, so they would be best equipped to explain why it's trying to use a podspec from upstream Hermes, rather than the copy of the podspec in RN. As a start, could you share the exact repro steps?

**Comment by vksgautam1986** [comment]
the only thing which i can suggest if you can try node 16.14 or something

**Comment by nikesh8** [comment]
@neildhar @vksgautam1986 Thank you for the support and the response. I am able to install pods after upgrading the CocoaPods version to `v1.13.0`.

**Comment by kmraditya108** [comment]
For future seekers, 

try to update below in Podfile: 

```
use_react_native!( 
   :hermes_enabled => false,
```
