### ISSUE TITLE
Intentional fallthrough?

### ISSUE THREAD

**Issue by r-barnes** [facebook/hermes#1441]
## Bug Description

Is the fallthrough from the `#endif` block above [this line](https://github.com/facebook/hermes/blob/075c3ebcfedc0b7291fb05a3bc0527a78b4c31f6/lib/Parser/JSParserImpl.cpp#L3948) intentional?
```
            new (context_) ESTree::TSTypeAssertionNode(*optType, *optExpr));
      }
      // SHOULD THIS BE A FALLTHROUGH OR A BREAK?
#endif

    case TokenKind::identifier:
```

If so, can we mark it with `LLVM_FALLTHROUGH`?

**Comment by avp** [comment]
The `J_COND` in the interpreter seems to be a false positive, there's `DISPATCH` on each of the cases.

The others have been fixed, closing this issue.
