### ISSUE TITLE
RangeError: Maximum callstack size exceeded with many modules in single bundle

### ISSUE THREAD

**Issue by mikeduminy** [facebook/hermes#1448]
## Bug Description

We are unable to open our full app in development, which runs a single bundle with over 40,000 modules. In production we are using Re.Pack which enables code-splitting and does not run into this problem.

In this PR the default JS register count was doubled - https://github.com/facebook/hermes/pull/923. Sadly we are hitting the same error again.

Note that the error is not reproducible using JSC in our reproduction repo (see below).

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC
- [x] The issue is reproducible with the latest version of React Native.

### Environment
Hermes git revision (if applicable): unknown, tied to RN versions below
React Native version: 0.72.12 (our app), 0.74.2 (reproduction app)
OS: OSX
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): unknown, this occurs in the iOS simulator and android emulator

## Steps To Reproduce

I've been able to mostly* reproduce it in this repo - https://github.com/mikeduminy/rn-reproducer.
> `*` The error we're experiencing in our app is `"RangeError: Maximum callstack size exceeded - no stack"` whereas the error in this reproduction repo is simply `"RangeError: Maximum callstack size exceeded"` so I'm not 100% certain it has the same cause.

Steps to reproduce:
1. Clone above repo and install dependencies
2. Generate 50,000 modules to simulate a large app (note: no lazy imports)
3. Run the app on iOS simulator and Android emulator
4. Observe the red screen (note, you may need to close and re-open the app to see this)

![342809230-3e23f51c-936e-459b-abec-3207ec2737f4](https://github.com/facebook/hermes/assets/4092035/d03c9bfa-43b6-4246-b0e7-558c315a0997)
![Screenshot_1719331985](https://github.com/facebook/hermes/assets/4092035/260700c9-05ee-423e-a683-25d4ff759207)

## The Expected Behavior

A unhandled JS Exception **should** be thrown but it would not be a call stack size exceeded error. 

In order to test if the callstack resulted from executing the entrypoint module of the bundle (the last few lines of the bundle) I [added a forced error](https://github.com/mikeduminy/rn-reproducer/blob/main/ReproducerApp/metro.config.js#L18-L23) just before that.

```js
serializer: {
    getRunModuleStatement: moduleId =>
      // If we see this error, it means the module was fully parsed
      // If we see another error, it means the problem occurred during the bundle parsing
      `throw new Error("before module execution: ${JSON.stringify(
        moduleId,
      )}"); __r(${JSON.stringify(moduleId)});`,
  },
```

If you see this error then hermes has successfully executed the bundle. If you see the max call stack error then this error was never even reached and that is the problem we are facing in our app - the bundle is not fully executed / loaded.

**Comment by neildhar** [comment]
Hey @mikeduminy, could you share more about why you suspect a bug in Hermes? It is likely that loading the bundle just requires a lot of deep recursion, which exhausts Hermes' register stack. Release mode builds also enable optimisations, which means that you may not observe the bug in release mode because individual stack frames are smaller.

Some other things you could try:
1. Increasing the register stack size further by configuring it in the Hermes `RuntimeConfig`.
2. Creating and running a bundle locally with the `hermes` CLI tool, which should give you better visibility into what is happening.

**Comment by mikeduminy** [comment]
@neildhar I thought about recursion being the problem which is why I investigated the resulting bundle and found that metro is basically just declaring a bundle of modules (not executing them), then executing the entrypoint. For example:

```js
(function(){ /* load metro runtime */ })()
(function(){ /* load react-native stuff */ })()
__d(function() { /* module code */ }, 0, [], "./index.js")
__d(function() { /* module code */ }, 1, [0], "./anotherModule.js")
/* ... more declaration calls */
throw new Error("before module execution: 0")
__r(0) // begin evaluating the modules (entrypoint)
```

> The `__d` function is [fairly simple](https://github.com/facebook/metro/blob/main/packages/metro-runtime/src/polyfills/require.js#L123-L171), just adding the unevaluated modules into a map. The code has not changed in over a year.

Since the execution of the bundle fails **before** the entrypoint is run it leads me to believe that the number of available registers is the problem. Since it works on JSC I would advocate for an increase in default allocated registers. We cannot easily increase this number as consumers of React Native.

In our app we can actually fix this problem by _randomly commenting out imports_ until it works. It doesn't matter what we comment out, just that the resulting modules falls below some unknown count.

**Comment by mikeduminy** [comment]
That's interesting, maybe the [modules[moduleId] = mod;](https://github.com/facebook/metro/blob/main/packages/metro-runtime/src/polyfills/require.js#L156) is overflowing the number of properties on a single object 🤔

I've been able to replicate the overflow in my [repro app](https://github.com/mikeduminy/rn-reproducer/tree/main) so using that to generate a bundle that fails is totally possible. Let me know if you want me to make it super easy to generate the bundle and I'll prep a script.

The other thing to note is the loaded bundle is not run through the hermes transform as it is failing in dev mode. I have not tested it in production but can do so and see if the problem persists.

Can you help me with the correct commands to run to execute the bundle in the hermes CLI?

**Comment by neildhar** [comment]
We have instructions for building and running Hermes [here](https://github.com/facebook/hermes/blob/main/doc/BuildingAndRunning.md).

Alternatively, you could try running against a precompiled copy of Hermes downloaded from the releases page (although they haven't been updated for some time).

Make sure that you run with `-O0` (to disable optimisations) and potentially specify `-max-num-registers` to ensure that you're getting a representative run.

**Comment by tmikov** [comment]
@mikeduminy it might also be very useful if you could upload somewhere the final JS bundle of the repro app (before it is compiled by Hermes). Then we can compile it and examine the generated bytecode.

**Comment by mikeduminy** [comment]
I have added both working and broken bundles for Android and iOS [here](https://github.com/mikeduminy/rn-reproducer/tree/64804232b791885c713fc697576435a8e6e7dcc7/ReproducerApp/artifacts). The difference between the working and broken bundles is a single additional module. 

I also conducted some analysis of each bundle only to discover that the breaking point for both platforms is when the number of modules exceeds 50357. 

Here is count and list of modules in each platform:
- Android
  - ✅  [working](https://github.com/mikeduminy/rn-reproducer/blob/64804232b791885c713fc697576435a8e6e7dcc7/ReproducerApp/artifacts/android-working-meta.txt) - 50357 modules
  - ❌ [broken](https://github.com/mikeduminy/rn-reproducer/blob/64804232b791885c713fc697576435a8e6e7dcc7/ReproducerApp/artifacts/android-broken-meta.txt) - 50358 modules
- iOS
  - ✅ [working](https://github.com/mikeduminy/rn-reproducer/blob/64804232b791885c713fc697576435a8e6e7dcc7/ReproducerApp/artifacts/ios-working-meta.txt) - 50357 modules
  - ❌ [broken](https://github.com/mikeduminy/rn-reproducer/blob/64804232b791885c713fc697576435a8e6e7dcc7/ReproducerApp/artifacts/ios-broken-meta.txt) - 50358 modules

**Comment by mikeduminy** [comment]
> We have instructions for building and running Hermes [here](https://github.com/facebook/hermes/blob/main/doc/BuildingAndRunning.md).
> 
> Alternatively, you could try running against a precompiled copy of Hermes downloaded from the releases page (although they haven't been updated for some time).
> 
> Make sure that you run with `-O0` (to disable optimisations) and potentially specify `-max-num-registers` to ensure that you're getting a representative run.

Assuming you don't need me to do this anymore?

**Comment by neildhar** [comment]
@mikeduminy Not yet at least, hopefully the bytecode output of the bundle is enough to pinpoint what is going on.

**Comment by neildhar** [comment]
I found the problem, the size of the global function is causing the register allocator to hit a memory limit and fall back to fast but very inefficient allocation. As a result the global function ends up singlehandedly overflowing the stack. We'll work on a fix.

**Comment by mikeduminy** [comment]
Hey @neildhar, awesome news that you found the problem!

I've explored the world of register allocators a little bit which has been interesting. It looks like Hermes is assuming that the "fast pass" allocator will be able to handle anything under the fass pass thresdhold and anything above a memory limit - https://github.com/facebook/hermes/blob/cf111e67f958e5734fc2546e428e9c6238b73364/lib/BCGen/RegAlloc.cpp#L611-L612.

The first condition looks sound and I assume that our bundle is above the threshold, but what is the purpose of the second condition? It seems like that might be what we are hitting in this case.

**Comment by tmikov** [comment]
The idea is that the threshold is configurable, so it can be adjusted to different levels in different cases. Unfortunately, it looks like we never actually did the adjustment.

**Comment by neildhar** [comment]
> what is the purpose of the second condition? It seems like that might be what we are hitting in this case.

@mikeduminy Yep, exactly, your bundle is hitting this case. In dev-mode, the compiler is usually running on a phone, where memory is relatively limited. The full register allocator can be quite memory intensive (more than linear in the size of the function), so we have this limit to avoid OOMing when we allocate (we have seen OOMs because of this in practice). The current limit is fairly conservative though, and as @tmikov said, it should be configurable depending on the use case.

That said, we have a fix in 6b69a06fc4a498ac467b590985515100c63313c3 that improves the code quality of the fast pass significantly. In the case of your bundle, it reduces the register usage for the global function from 402916 to 39.  That fix has currently landed in the `static_h` branch, and we'll port it to `main` shortly.

**Comment by mikeduminy** [comment]
@neildhar fantastic news! Once that lands in `main` can we get it backported to RN 72 or 73?

**Comment by neildhar** [comment]
It has already landed in main in 20b13b96f49c6819f6090f17a5ec29d3faec45c6 and you can request a pick in the RN release discussions. The changes are relatively isolated so they should be safe to pick.

**Comment by tmikov** [comment]
It is a bug fix, so RN should be willing to pick it.

**Comment by tmikov** [comment]
@cortinico interesting. It appears that `test/Parser/flow/declare-module-import-allowed.js` was incorrectly included in the diff. @neildhar any idea why?

Seems like ignoring changes to that file should work?

**Comment by mikeduminy** [comment]
The only change to that file is this added line: `// Auto-generated content below. Please do not modify manually.`
https://github.com/facebook/hermes/commit/20b13b96f49c6819f6090f17a5ec29d3faec45c6#diff-97c6e0145c7c283475c236bc7a3f9987026beff83bed44f8b4be9e5a7cf6c6b6R14

**Comment by neildhar** [comment]
@tmikov it looks like that file was initially added with FileCheckOrRegen, but this is the first time we actually ran `update-lit` to regenerate tests, so it ended up getting swept up in this diff.
