### ISSUE TITLE
"HBC version" should be reflected in the documentation or the file name

### ISSUE THREAD

**Issue by qq741079111** [facebook/hermes#1449]
I need a "hbcdump" tool with "HBC version==94", but I cannot find it. I can only download the source code one version at a time and open "include \ themes \ BCGen \ HBC \ BytecodeVersion. h" to view it.

**Comment by tmikov** [comment]
Hi, as far as I understand, you are asking whether we are planning to develop a tool that can disassemble multiple bytecode versions, or alternatively a collection of binaries for different versions.

Unfortunately, this is out of scope for Hermes - at any time we only support the current version of the bytecode. We do not provide backward compatibility with different bytecode versions, so there is no value for us in maintaining a tool to disassemble multiple versions. Additionally, as of the next major version of Hermes (Static Hermes), bytecode versions will change at most at major releases, so for practical purposes the Hermes version will identify the bytecode version.

Anyway, if the ability to disassemble multiple versions at a time is needed, a separate open source project could compile different versions of `hbcdump` and package them with a front-end tool that invokes the correct one.

Snapshots of the source tree for each version can be obtained from here: https://github.com/facebook/hermes/commits/main/include/hermes/BCGen/HBC/BytecodeVersion.h.
