### ISSUE TITLE
Wrong bytecode version with hbcdump

### ISSUE THREAD

**Issue by weilanxiao** [facebook/hermes#1451]
## Bug Description

I am receiving the following error when using hbcdump version 0.12.0. 

### input 
`./hbcdump -objdump-disassemble ./assets/index.android.bundle` 

### output
`Error: fail to deserializing bytecode: Wrong bytecode version. Expected 89 but got 96%   `

**Comment by neildhar** [comment]
Hey @weilanxiao, it looks like you're trying to use hbcdump from 0.12.0 to dump bytecode from a newer version of Hermes. You'll need a newer version of hbcdump, corresponding to the version of Hermes that you are trying to dump bytecode for. Please take a look at this related discussion: https://github.com/facebook/hermes/issues/1449
