### ISSUE TITLE
How to get libjsi.so and header files from hermes aar

### ISSUE THREAD

**Issue by LiShiqii** [facebook/hermes#1477]
## Problem
We have a project to build hermes engine into Android app, and our Android app is not react, we want to use Hermes as a JS engine and using a wrapper to connect with our custom components. And After pull the hermes android from maven repo https://mvnrepository.com/artifact/com.facebook.react/hermes-android. We build the app, and only saw the header files for Hermes and didn't see where is the libjsi.so and its header files. And I did see the jsi file exists in https://mvnrepository.com/artifact/com.facebook.react/react-android, but we don't want to build that into our app since react-android contains lots of other unneeded dependencies for our app. 

## Solution

Is there a way to pull the libjsi.so and its header file from Hermes maven aar? Or what is the best practice to pull that into our non react Android app.

**Comment by tmikov** [comment]
Hi, if you are using Hermes outside of RN, you need to compile Hermes from source. You can see the steps for Android compilation here: https://github.com/facebook/hermes/blob/751d19feb44f6fba04707ffff9111af37dbde220/.circleci/config.yml#L54

**Comment by leon60740** [comment]
> Hi, if you are using Hermes outside of RN, you need to compile Hermes from source. You can see the steps for Android compilation here:
> 
> https://github.com/facebook/hermes/blob/751d19feb44f6fba04707ffff9111af37dbde220/.circleci/config.yml#L54

I'm building Hermes from source by following the CI configuration, but the output doesn't include libjsi.so. How can I build it for arm64-v8a? (Sorry I'm new to C++).

**Comment by ammarahm-ed** [comment]
Facing the same issue @tmikov any guidence? the built aar does not include libjsi.so

**Comment by ammarahm-ed** [comment]
![Screenshot 2024-11-16 at 11 30 49 PM](https://github.com/user-attachments/assets/7ca98113-f47f-4c9b-9bf2-b6df37e93d6b)
I think commenting this out will include libjsi.so
