### ISSUE TITLE
async example yield different result than v8

### ISSUE THREAD

**Issue by wcandillon** [facebook/hermes#1480]
## Bug Description

The following code returns 10 on v8 but doesn't return anything using the hermes binary:

```
function resolveAfter2Seconds(x) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}

async function f1() {
  const x = await resolveAfter2Seconds(10);
  console.log(x); // 10
}

f1();
```

## The Expected Behavior

To return 10;

**Comment by tmikov** [comment]
I am afraid, I can't reproduce this. I just tried it and it works as expected. See the attached screenshot:

<img width="314" alt="Screenshot 2024-08-16 at 1 51 27 PM" src="https://github.com/user-attachments/assets/95f6bb30-5ca9-4c16-ae04-9ac956762b8e">

**Comment by tmikov** [comment]
Your example uses `console.log()`, which isn't provided by the Hermes CLI. An exception is thrown in the primise.

**Comment by wcandillon** [comment]
```
$ cat oo.js
function resolveAfter2Seconds(x) {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(x);
    }, 2000);
  });
}

async function f1() {
  const x = await resolveAfter2Seconds(10);
  console.log(x); // 10
}

f1();
$ ./bin/hermes foo.js
$  echo $?
0
```
no output nor exception. How do I reconcile the difference of behaviour? 
Using print() does yield the "expected" result.

**Comment by tmikov** [comment]
@wcandillon there is no real difference in behavior. The spec does not specify how unhandled Promise rejection should be handled by the host environment. It is up to the integrator of the JS engine. Browsers and NodeJS provide their own mechanisms. I suspect React Native does too, or it should.

The Hermes CLI tool is a very minimalistic integration of the engine, it only provides `print()` and a couple of more things. It doesn't configure a rejection hook.

If you need this behavior, you can configure the rejection hook yourself from JS like this:
```
HermesInternal.enablePromiseRejectionTracker({
  allRejections: true,
  onUnhandled: function(id, error) {
    print("Unhandled Promise rejection:", error.stack);
  },
});
```

I think there is a good point to be made that the Hermes CLI tool should set this by default and it should also probably provide a very simple polyfill for `console.log()`. We will look into it.

**Comment by flawrist** [comment]
I don't understand why console.log() is not implemented yet. It's so crucial.

**Comment by tmikov** [comment]
> I don't understand why console.log() is not implemented yet. It's so crucial.

@sergeevabc it was added more than a year ago in 00f94f4ceecf6c0aa9ee613cbfab6b447155ae7f. Not sure why it is crucial though, since the Hermes CLI is just a simple tool for testing.

**Comment by flawrist** [comment]
@tmikov 

https://github.com/facebook/hermes/releases/tag/v0.13.0

``` console
$ hermes --version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  DEBUG build

Hermes JavaScript compiler and Virtual Machine.
  Hermes release version: 0.12.0
  HBC bytecode version: 96

$ echo var x=`SGVsbG8gCg==`; console.log(atob(x)); | hermes
>> Uncaught ReferenceError: Property 'console' doesn't exist
    at global (JavaScript:1:23)
    at eval (native)
    at evaluateLine (JavaScript:1:6459)
>>
```

Here's what other runtimes offer:

``` console
$ echo var x=`SGVsbG8gCg==`; console.log(atob(x)); | node
Hello

$ deno eval "var x=`SGVsbG8gCg==`; console.log(atob(x));"
Hello

$ llrt -e "var x=`SGVsbG8gCg==`; console.log(atob(x));"
Hello
```

**Comment by tmikov** [comment]
> @tmikov 
> 
> https://github.com/facebook/hermes/releases/tag/v0.13.0
> 
> ``` console
> $ hermes --version
> LLVM (http://llvm.org/):
>   LLVH version 8.0.0svn
>   DEBUG build
> 
> Hermes JavaScript compiler and Virtual Machine.
>   Hermes release version: 0.12.0
>   HBC bytecode version: 96
> 
> $ echo var x=`SGVsbG8gCg==`; console.log(atob(x)); | hermes
> >> Uncaught ReferenceError: Property 'console' doesn't exist
>     at global (JavaScript:1:23)
>     at eval (native)
>     at evaluateLine (JavaScript:1:6459)
> >>
> ```
> 
> Here's what other runtimes offer:
> 
> ``` console
> $ echo var x=`SGVsbG8gCg==`; console.log(atob(x)); | node
> Hello
> 
> $ deno eval "var x=`SGVsbG8gCg==`; console.log(atob(x));"
> Hello
> 
> $ llrt -e "var x=`SGVsbG8gCg==`; console.log(atob(x));"
> Hello
> ```

@sergeevabc Hopefully you understand that Hermes is not a runtime like NodeJS, Deno, etc. Hermes is only the JS engine, similar to v8, JavaScriptCore, etc. console.log() is not a part of ECMAScript. It is the responsibility of the integrator to implement that functionality. The Hermes CLI is just a minimal tool for testing, it is not a complete runtime like NodeJS and it isn't intended to be. It is only 3.5MB after all. 

I could swear I already said that. 

However, as I said, for convenience we already added console.log() one year ago. I literally showed you the commit.

**Comment by flawrist** [comment]
@tmikov If commit was uploaded a year ago or so (Oct 2024), then why Hermes displays an error? Because the latest release of Hermes (0.13, Aug 2024) knows nothing about it. There is no Hermes binary that contains that commit. Being an end user, not a developer with skills to compile such binaries, I do not know what to do with this commit, except to print it, hang it on the wall and throw darts, lol.

**Comment by tmikov** [comment]
> @tmikov If commit was uploaded a year ago or so (Oct 2024), then why Hermes displays an error? Because the latest release of Hermes (0.13, Aug 2024) knows nothing about it. There is no Hermes binary that contains that commit. Being an end user, not a developer with skills to compile such binaries, I do not know what to do with this commit, except to print it, hang it on the wall and throw darts, lol. 

@sergeevabc I appreciate your pain. However, this is an open source project. We provide the source for programmers. That is all. The expectation is that they will contribute back in exchange for having free access. Being able to build it is really the minimal requirement.

This is not a free support forum for end users. I am sorry. Perhaps such a user support forum is needed, but GitHub is not it.

You are correct that we don't provide binary releases. Such releases would be nice, but also mostly pointless, for obvious reasons. Any actual usage of the engine requires a deeply technical integration.

**Comment by tmikov** [comment]
Wanted to add: that's not to say that we never want to provide binary releases. Sure we do. But binary releases are just a minor convenience. Our primary use is as a library on Android and iOS, so the logistics of actually useful binary releases are staggering.

**Comment by tmikov** [comment]
Wanted to add: that's not to say that we never want to provide binary releases. Sure we do. But binary releases are just a minor convenience. Our primary use is as a library on Android and iOS, so the logistics of an actually useful binary releases are staggering.

**Comment by tmikov** [comment]
Also, very fair point: we urgently need to update our README.
