### ISSUE TITLE
ReferenceError: Property 'Proxy' doesn't exist

### ISSUE THREAD

**Issue by daheeahn** [facebook/hermes#149]
RN version: 0.61.0
I followed [https://facebook.github.io/react-native/docs/hermes](url)

but I encountered this error
`ReferenceError: Property 'Proxy' doesn't exist`

I'm using redux (not mobx)

How can I do?

**Comment by daheeahn** [comment]
Related closed issue [https://github.com/facebook/react-native/issues/25740](#25740)

**Comment by avp** [comment]
Something in your project must need `Proxy`. We're looking into supporting `Proxy` in #33, so you can follow the discussion there.
