### ISSUE TITLE
Asset validation failed, hermes contains bitcode. XCode 16

### ISSUE THREAD

**Issue by Drzaln** [facebook/hermes#1525]
## Bug Description

When trying to upload my app to AppStore using XCode 16, I get this error
```
Asset validation failed (90482)
Invalid Executable. The executable '***.app/Frameworks/hermes.framework/hermes' contains bitcode. (ID: 37fb02b5-0173-4c01-8d79-88a9cf6a33d8)
```
I'm already disable bitcode in the Build Settings

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC
- [ ] The issue is reproducible with the latest version of React Native.

Hermes git revision (if applicable):
React Native version: 0.72.4
OS: iOS
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. Enable hermes with react native 0.72.4
2. Upload the app to AppStore using XCode 16

code example:

**Comment by tmikov** [comment]
Hi, IIRC, Apple changed their mind on bitcode and and went back and forth about it.  

Unfortunately RN 0.72 is no longer supported, but if you upgrade to 0.73 or even better to 0.75, this should address your problem.

**Comment by Shivangigupta01** [comment]
I was facing this same issue in RN version: "0.72.6", and was able to resolve it by following [this](https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e/79022687#:~:text=In%20case%20you%20have%20already%20post_install%20has%20been%20used%20then%20copy%20and%20past%20the%20below%20script%20inside%20that.) link.

After making the required changes, make sure to clean the project, derived data, install pods again and it should work.

**Comment by avnshproinfo** [comment]
Yeah same link worked for me, you can fix it by following these steps: [fix](https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e/79022687#:~:text=In%20case%20you%20have%20already%20post_install%20has%20been%20used%20then%20copy%20and%20past%20the%20below%20script%20inside%20that.)

**Comment by anilokcuoglu** [comment]
> I was facing this same issue in RN version: "0.72.6", and was able to resolve it by following [this](https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e/79022687#:~:text=In%20case%20you%20have%20already%20post_install%20has%20been%20used%20then%20copy%20and%20past%20the%20below%20script%20inside%20that.) link.
> 
> After making the required changes, make sure to clean the project, derived data, install pods again and it should work.

This is the solution that worked for me.

**Comment by abid-mahmood-TS** [comment]
> Yeah same link worked for me, you can fix it by following these steps: [fix](https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e/79022687#:~:text=In%20case%20you%20have%20already%20post_install%20has%20been%20used%20then%20copy%20and%20past%20the%20below%20script%20inside%20that.)

This was the life saviour, thanks @avnshproinfo

**Comment by ahmedfaraz587** [comment]
I am getting this issue in XCode 16 but none of the answers help me to resolve that issue 

Upload failed
	error: Asset validation failed
Invalid Executable. The executable '' contains bitcode. (ID: 2aa62af7-6fed-46e2-8405-4946368da620)
	error: Asset validation failed
Invalid Executable. The executable 'mc.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' contains bitcode. (ID: 1581a6ec-f5d5-4946-908d-18d778fee573)
	error: Asset validation failed
Invalid Executable. The executable 'mc.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics' contains bitcode. (ID: e6505282-d042-44f2-9285-995859f32aea)
	error: Asset validation failed
Invalid Executable. The executable 'mc.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit' contains bitcode. (ID: cb690141-2be7-422c-a6c5-2374a91bc335)
	error: Asset validation failed
Invalid Executable. The executable 'mc.app/Frameworks/FBSDKShareKit.framework/FBSDKShareKit' contains bitcode. (ID: 727dc5e1-7bae-40dd-a17a-5f4d0eb4fa18)

**Comment by fonderkin** [comment]
[This](https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e/79022687#:~:text=In%20case%20you%20have%20already%20post_install%20has%20been%20used%20then%20copy%20and%20past%20the%20below%20script%20inside%20that.) solution helped me


this
   ```
 react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
```
replace with

```
bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
   def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
     framework_path = File.join(Dir.pwd, framework_relative_path)
     command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
     puts "Stripping bitcode: #{command}"
     system(command)
   end

   framework_paths = [
     "Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
     "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
     "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
     "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
     "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes"
   ]

   framework_paths.each do |framework_relative_path|
     strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
   end
```

**Comment by anilokcuoglu** [comment]
Open the ios/pods/whichframework/frameworks/ios_arm64_v7(this is my
chip)/framework.xcframework/framework you must ensure that exact path must
be entered otherwise it wont work if you need more assistance please add me
on discord im glad to help you

2 Eki 2024 Çar 09:31 tarihinde 이시현 ***@***.***> şunu yazdı:

**Comment by musti-91** [comment]
It will depends on the framework you're having.
I added for Shakebugs SDK also below in the pods
`"Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
      "Pods/Shake/Sources/Shake.xcframework/ios-arm64/Shake.framework/Shake", # <----- this line
      "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
      "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
      "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
      "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes"`

**Comment by Linuhusainnk** [comment]
How could i get the path to be added inside framework paths

**Comment by junocean** [comment]
> I am getting this issue in XCode 16 but none of the answers help me to resolve that issue
> 
> Upload failed error: Asset validation failed Invalid Executable. The executable '' contains bitcode. (ID: 2aa62af7-6fed-46e2-8405-4946368da620) error: Asset validation failed Invalid Executable. The executable 'mc.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' contains bitcode. (ID: 1581a6ec-f5d5-4946-908d-18d778fee573) error: Asset validation failed Invalid Executable. The executable 'mc.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics' contains bitcode. (ID: e6505282-d042-44f2-9285-995859f32aea) error: Asset validation failed Invalid Executable. The executable 'mc.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit' contains bitcode. (ID: cb690141-2be7-422c-a6c5-2374a91bc335) error: Asset validation failed Invalid Executable. The executable 'mc.app/Frameworks/FBSDKShareKit.framework/FBSDKShareKit' contains bitcode. (ID: 727dc5e1-7bae-40dd-a17a-5f4d0eb4fa18)

you can insert these into Podfile which mentioned, but change to

```
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end

    framework_paths = [
      "Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/ios-arm64/FBSDKCoreKit.framework/FBSDKCoreKit",
      "Pods/FBSDKShareKit/XCFrameworks/FBSDKShareKit.xcframework/ios-arm64/FBSDKShareKit.framework/FBSDKShareKit",
      "Pods/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64/FBAEMKit.framework/FBAEMKit",
      "Pods/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics",
      "Pods/FBSDKGamingServicesKit/XCFrameworks/FBSDKGamingServicesKit.xcframework/ios-arm64/FBSDKGamingServicesKit.framework/FBSDKGamingServicesKit",
      "Pods/FBSDKLoginKit/XCFrameworks/FBSDKLoginKit.xcframework/ios-arm64/FBSDKLoginKit.framework/FBSDKLoginKit",
    ]

    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end
```

**Comment by Parth8733** [comment]
**I had the same issue, and here's how I resolved it step by step:**

1. **Check Hermes Paths**  
   The paths in the original code might not be correct for your setup. First, you need to find all the Hermes frameworks and their paths within your `Pods` directory. Run the following command to find all instances of Hermes:

   ```bash
   find Pods/hermes-engine -name hermes
   ```

2. **Update Podfile**  
   Once you have the correct paths, update the `framework_paths` array in your `Podfile` to include them. Here's an example of how to do it:

   ```ruby
   framework_paths = [
     # Replace these paths with the correct ones you found
     "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
     "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-simulator/hermes.framework/hermes"
   ]
   ```

3. **Strip Bitcode**  
   Ensure that your Podfile includes the bitcode stripping logic:

   ```ruby
   def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
     framework_path = File.join(Dir.pwd, framework_relative_path)
     command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
     puts "Stripping bitcode: #{command}"
     system(command)
   end
   ```

4. **Clean and Build**  
   After updating the paths, clean your project folder,
   Then build your project again.

5. **Create the Build**  
   Finally, try creating the build again (e.g., using `eas build` or Xcode) and check the result.

**Comment by junocean** [comment]
@Linuhusainnk You can open any code editor and navigate to your project’s root directory. From there, go to ios > Pods, where you'll find relevant folders. The folder names may differ slightly from the examples I provided. Once located, replace them as needed. Remember run pod install to take effect.

**Comment by LukePJN** [comment]
I found specifying xCode 15.2 in my build scripts solved the issue for me

**Comment by xi-co** [comment]
> Yeah same link worked for me, you can fix it by following these steps: [fix](https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e/79022687#:~:text=In%20case%20you%20have%20already%20post_install%20has%20been%20used%20then%20copy%20and%20past%20the%20below%20script%20inside%20that.)

Saved my week.

solved my updated Xcode Issue.

**Comment by josephattechjays** [comment]
Build uploaded successfully but received this warning how to get rid of this
![image](https://github.com/user-attachments/assets/999d98da-791f-4160-a262-0cbecd4b2b8b)

**Comment by agametis** [comment]
The shell script `handle_bitcode.sh` from the [link](https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e/79022687#:~:text=In%20case%20you%20have%20already%20post_install%20has%20been%20used%20then%20copy%20and%20past%20the%20below%20script%20inside%20that.) did the work in my RN 0.72.5 project and Xcode 16.2.

**Comment by UnderTheMoonspell** [comment]
For us it was happening in four libs:

"appname".app/Frameworks/LogRocket.framework/LogRocket'
"appname".app/Frameworks/OpenSSL.framework/OpenSSL'
"appname".app/Frameworks/double-conversion.framework/double-conversion'
"appname".app/Frameworks/glog.framework/glog'

LogRocket and OpenSSL have a framework folder but not the other two. So after we added the solution in here, LogRocket and OpenSSL are now working, but we dont have a solution for the other two

**Comment by gabeh91** [comment]
There were the libs which were causing the issues for us:

```
framework_paths = [
      "Pods/FBSDKCoreKit/XCFrameworks/FBSDKCoreKit.xcframework/ios-arm64/FBSDKCoreKit.framework/FBSDKCoreKit",
      "Pods/FBSDKShareKit/XCFrameworks/FBSDKShareKit.xcframework/ios-arm64/FBSDKShareKit.framework/FBSDKShareKit",
      "Pods/FBAEMKit/XCFrameworks/FBAEMKit.xcframework/ios-arm64/FBAEMKit.framework/FBAEMKit",
      "Pods/FBSDKCoreKit_Basics/XCFrameworks/FBSDKCoreKit_Basics.xcframework/ios-arm64/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics",
      "Pods/FBSDKGamingServicesKit/XCFrameworks/FBSDKGamingServicesKit.xcframework/ios-arm64/FBSDKGamingServicesKit.framework/FBSDKGamingServicesKit",
      "Pods/FBSDKLoginKit/XCFrameworks/FBSDKLoginKit.xcframework/ios-arm64/FBSDKLoginKit.framework/FBSDKLoginKit",
      "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes",
      "Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
    ]
```

**Comment by bonnmh** [comment]
> Build uploaded successfully but received this warning how to get rid of this ![image](https://private-user-images.githubusercontent.com/185165376/384241011-999d98da-791f-4160-a262-0cbecd4b2b8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjkxMzgsIm5iZiI6MTczNDkyODgzOCwicGF0aCI6Ii8xODUxNjUzNzYvMzg0MjQxMDExLTk5OWQ5OGRhLTc5MWYtNDE2MC1hMjYyLTBjYmVjZDRiMmI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwNDQwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDA3NGEwM2U1NjFkMjc4YTA3YTRmNzVhNGFkMTk4Njg5YTlkMDgwODM1MzAwMzIxMjY0N2I2NjE1YjMxMTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.m4678SUeeP3xCp-Vyaa_bubkDdItmg3EPQBDB1Xkn-o)

Any solutions?

**Comment by abdullahSolace** [comment]
In my case "AmazonChimeSDK" was causing the issue and I've placed the below code before the last "end" in Podfile and then `pod install --repo-update` and it worked.

` # Paths to AmazonChimeSDK and AmazonChimeSDKMedia frameworks causing issues
    framework_paths = [
      "Pods/AmazonChimeSDK-Bitcode/AmazonChimeSDK.xcframework/ios-arm64_armv7/AmazonChimeSDK.framework/AmazonChimeSDK",
      "Pods/AmazonChimeSDKMedia-Bitcode/AmazonChimeSDKMedia.xcframework/ios-arm64_armv7/AmazonChimeSDKMedia.framework/AmazonChimeSDKMedia"
    ]
  
    # Find bitcode_strip tool
    bitcode_strip_path = `xcrun --find bitcode_strip`.strip
  
    # Strip bitcode from each framework
    framework_paths.each do |framework_relative_path|
      system("#{bitcode_strip_path} -r #{framework_relative_path} -o #{framework_relative_path}")
    end
  end`

**Comment by Karthik-V26** [comment]
Which solution worked? please tell some work around.

**Comment by Drzaln** [comment]
@Karthik-V26 
I'm using this because I use Xcode Cloud
```
project_root = File.expand_path('..', Dir.pwd)

  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
  def strip_bitcode_from_framework(bitcode_strip_path, framework_path)
    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end
  
  framework_paths = [
    "#{project_root}/Pods/hermes-engine/destroot/bin/hermes",
    "#{project_root}/Pods/hermes-engine/destroot/include/hermes",
    "#{project_root}/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-simulator/hermes.framework/hermes",
    "#{project_root}/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/Versions/0/hermes",
    "#{project_root}/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes",
    "#{project_root}/Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
    "#{project_root}/Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/0/hermes",
    "#{project_root}/Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
    "#{project_root}/Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
    "#{project_root}/Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
  ]
  
  framework_paths.each do |framework_path|
    if File.exist?(framework_path)
      puts "Found file: #{framework_path}"
      strip_bitcode_from_framework(bitcode_strip_path, framework_path)
    else
      puts "Warning: File not found: #{framework_path}"
    end
  end
```

**Comment by rahul-sysquare** [comment]
> Build uploaded successfully but received this warning how to get rid of this ![image](https://github.com/user-attachments/assets/999d98da-791f-4160-a262-0cbecd4b2b8b)

Any solution for this? Still happening with xCode 16.2

**Comment by radekzz** [comment]
Solution from @Drzaln helped me on RN 0.72.4.
I slightly modified it to find hermes files in whatever file structure is (in case using Bitrise and can have different paths)

```
post_install do |installer|
    # Strip bitcode from any hermes binaries found
    bitcode_strip_path = `xcrun --find bitcode_strip`.chomp
    def strip_bitcode_from_framework(bitcode_strip_path, framework_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "🔧 Stripping bitcode: #{command}"
      system(command)
    end

    Dir.glob("Pods/hermes-engine/**/*.framework/hermes").each do |hermes_bin|
      puts "🔍 Found Hermes binary: #{hermes_bin}"
      strip_bitcode_from_framework(bitcode_strip_path, hermes_bin)
    end
  end
```

**Comment by hoangnguyen8895** [comment]
> Solution from [@Drzaln](https://github.com/Drzaln) helped me on RN 0.72.4. I slightly modified it to find hermes files in whatever file structure is (in case using Bitrise and can have different paths)
> 
> ```
> post_install do |installer|
>     # Strip bitcode from any hermes binaries found
>     bitcode_strip_path = `xcrun --find bitcode_strip`.chomp
>     def strip_bitcode_from_framework(bitcode_strip_path, framework_path)
>       command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
>       puts "🔧 Stripping bitcode: #{command}"
>       system(command)
>     end
> 
>     Dir.glob("Pods/hermes-engine/**/*.framework/hermes").each do |hermes_bin|
>       puts "🔍 Found Hermes binary: #{hermes_bin}"
>       strip_bitcode_from_framework(bitcode_strip_path, hermes_bin)
>     end
>   end
> ```

Thanks, it's worked for me, this way completely solves the bitcode problem of hermes engine
