### ISSUE TITLE
A qusetion about Array.prototype.sort 

### ISSUE THREAD

**Issue by YuanWangC** [facebook/hermes#153]
When running the testcase below, if the length of the `numbers` is greater than or equal to 7, the engine is running weird. It takes 24+ hours to calculate but no final result. 

#### Testcase:
```
var NISLFuzzingFunc = {
     var numbers = [7, 6, 5, 4, 3, 2, 1];
     numbers.sort(function(a, b){
             return -1;
         });
    print(numbers);
}
NISLFuzzingFunc();
```
#### Command:
`build_release/bin/hermes testcase.js`

**Comment by avp** [comment]
#95 has discussion about this.

This is an issue because the comparator function returns inconsistent values.
