### ISSUE TITLE
how to build for custom linux 

### ISSUE THREAD

**Issue by georged-youi** [facebook/hermes#155]
Hi, is there a doc describing how to build hermes for a custom linux?
All I have found so far is how to build for android from source.

**Comment by tmikov** [comment]
https://github.com/facebook/hermes/blob/master/doc/BuildingAndRunning.md

**Comment by georged-youi** [comment]
Hi @tmikov,
I looked at the link you posted, but for linux and mac it only describes how to create the hermes build system.
I'm interested on how to create libhermes.so for mac and linux, as I have a native app written in c++ and react-native. I'm trying to replace javascriptcore with hermes and run it on mac and linux.

**Comment by tmikov** [comment]
As the link says: 

> The build system has now been generated in the build directory. To perform the build:
> 
> cd build && ninja

That will generate all binaries. libhermesapi.so will be under `build/API/hermes/`.

**Comment by georged-youi** [comment]
Nice, I found them.
Thanks @tmikov
