### ISSUE TITLE
React native 0.68.2 iOS with Hermes enabled not able to load the application, metro error 

### ISSUE THREAD

**Issue by chirag-blueed** [facebook/hermes#1568]
Can you suggest a solution, or is this issue specific to iOS when Hermes is enabled?
Note: This happens only with hermes enabled in my project, with default JavaScript Core it is working fine
Can some one suggest a fix of it

ERROR ReferenceError: Property 'module' doesn't exist, js engine: hermes Error: ENOENT: no such file or directory, open '/Users//Workspace//webpack:/multi_./src/index.js?' at Object.openSync (node:fs:596:3) at Object.readFileSync (node:fs:464:35) at getCodeFrame (/Users//Workspace//node_modules/metro/src/Server.js:949:18) at Server._symbolicate (/Users//Workspace//node_modules/metro/src/Server.js:1022:22) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Server.processRequest (/Users//Workspace//node_modules/metro/src/Server.js:429:7) { errno: -2, syscall: 'open', code: 'ENOENT', path: '/Users//Workspace//webpack:/multi./src/index.js?'

<img width="359" alt="image" src="https://github.com/user-attachments/assets/4ff3ace7-a02a-4860-b89b-97c7568c9ce6">

`Error: ENOENT: no such file or directory, open '/Users/*/Workspace/*/*/webpack:/multi_./src/index.js?'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at getCodeFrame (/Users/*/Workspace/*/*/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/*/Workspace/*/*/node_modules/metro/src/Server.js:1022:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (/Users/*/Workspace/*/*/node_modules/metro/src/Server.js:429:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/upforcetech/Workspace/*/*/webpack:/multi_./src/index.js?'
}`

**Comment by tmikov** [comment]
From your screenshot, your code is relying on "local eval", that is compilation of JavaScript source at runtime in the context of a function, accessing symbols declared in that function.

```
(function(module) {
   eval("module.exports = ...."); 
   ...
})
```   

Local eval is not supported by Hermes (in general Hermes is optimized for running from bytecode - compilation from source on device is very slow).

**Comment by chirag-blueed** [comment]
But @tmikov  how can I fix this? Could you please help me?

**Comment by chirag-blueed** [comment]
The release build works fine, but the debug build has issues when connected to the Metro server bundler.

**Comment by tmikov** [comment]
Sorry, @chirag-blueed, I wish I could help you, but I don't have a good practical understanding of how JS apps are packaged and built in practice. The Hermes team deals primarily with C++ and narrow JS language features. You might have better luck asking in React Native.

Take the following with a grain of salt: From what I can tell, there is Webpack usage in your code, and for some reason it is wrapped in an `eval()`. No idea why, but that's where I would start. AFAIK, RN apps are usually packaged with Metro, not Webpack.
