### ISSUE TITLE
A possible bug about eval

### ISSUE THREAD

**Issue by YiWen-y** [facebook/hermes#159]
When running tset case 1 and test case 2, they should have the same output . 

###### revision
[3826084](https://github.com/facebook/hermes/tree/382608426baaa059b8220d6135cebc426a21a1d5)

###### Command
    ./build/bin/hermes -w testcase.js

###### Test case 1
```
var NISLFuzzingFunc = function() {
    eval("with ({}) {}");
};
NISLFuzzingFunc();
```

###### Output 1
```
```       

###### Test case 2
```
var NISLFuzzingFunc = function() {
    with ({}) {}
};
NISLFuzzingFunc();
```

###### Output 2
    error: invalid statement encountered.

**Comment by tmikov** [comment]
Thank you for testing Hermes! I can't reproduce this the current top of tree version. Can you confirm whether it works for you?

**Comment by mhorowitz** [comment]
I was also unable to repro.  I had to modify both test cases, as the function definitions are missing a closing `}` on the function body.  Once I fix that, I get this output from test case 1:
```
SyntaxError: 1:1:invalid statement encountered.
    at NISLFuzzingFunc (/tmp/testcase.js:2:9)
    at global (/tmp/testcase.js:4:16)
```
And this output from test case 2:
```
/tmp/testcase-2.js:2:5: error: invalid statement encountered.
    with ({}) {}
    ^~~~~~~~~~~~
Emitted 1 errors. exiting.
```

**Comment by YiWen-y** [comment]
I'm so sorry that I deleted a line of code by mistake,  can you try it again?

**Comment by tmikov** [comment]
@YiWen-y you are testing with a version of Hermes that is more than two months old. It appears that the bug has already been fixed.

**Comment by mhorowitz** [comment]
Still looks like the same error for both runs:

```
$ cat /tmp/testcase-1.js
var NISLFuzzingFunc = function() {
  eval("with ({}) {}");
};
NISLFuzzingFunc();
$ .../hermes -w /tmp/testcase-1.js
SyntaxError: 1:1:invalid statement encountered.
    at NISLFuzzingFunc (/tmp/testcase-1.js:2:7)
    at global (/tmp/testcase-1.js:4:16)
mhorowitz-mac:~/fbsource$ cat /tmp/testcase-2.js
var NISLFuzzingFunc = function() {
  with ({}) {}
};
NISLFuzzingFunc();
$ .../hermes -w /tmp/testcase-2.js
/tmp/testcase-2.js:2:3: error: invalid statement encountered.
  with ({}) {}
  ^~~~~~~~~~~~
Emitted 1 errors. exiting.
```

**Comment by YiWen-y** [comment]
@tmikov I got it.Thanks！
