### ISSUE TITLE
Runtime.callFunctionOn returns an empty value on debugging

### ISSUE THREAD

**Issue by RedMickey** [facebook/hermes#166]
Hello, we are the development team of **VS Code** extension for debugging **React Native** apps ([vscode-react-native](https://github.com/microsoft/vscode-react-native)). Now we are working on **React Native Hermes** debugger and we've faced the problem related to usage of **Chrome DevTools Protocol** method [`callFunctionOn`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-callFunctionOn). We use [vscode-chrome-debug-core](https://github.com/microsoft/vscode-chrome-debug-core) library to communicate with **Hermes** debugger. Some functions of the library (e.g. [getNumPropsByEval](https://github.com/microsoft/vscode-chrome-debug-core/blob/893ec53d4640c275575da78d984a403f6489d9ab/src/chrome/variablesManager.ts#L300)) use **Chrome DevTools Protocol** method `Runtime.callFunctionOn`. But each call of this method returns the following response `"{"result":{},"id":someId}"` - an empty result object. We tried to call `Runtime.callFunctionOn` function with different parameters, but the result remained the same.
Below is the list of the function calls with different arguments that we tried:
1) For example in case of usage of `getNumPropsByEval` method, the `Runtime.callFunctionOn` function is used to evaluate the length of the watched array. Below there is an example of the function call:
```
        this.chrome.Runtime.callFunctionOn({
            objectId,    // 121 
            functionDeclaration: " function() { return [this.length, Object.keys(this).length - this.length + 2]; }",
            silent: true,
            returnByValue: true
        })
```
2) The function should only return a static array. Without `silent` mode.
```
        this.chrome.Runtime.callFunctionOn({
            objectId,    // 121 
            functionDeclaration: "function() { return [0, 2]; }",
            silent: false,
            returnByValue: true
        })
```
3) The function should return `process` variable. Doesn't provide `objectId` prop and without `silent` mode.
```
        this.chrome.Runtime.callFunctionOn({
            functionDeclaration: "function() { return process; }",
            silent: false,
            returnByValue: true
        })
```
For all cases that are described above the `callFunctionOn` method returns empty result object.
`Runtime.callFunctionOn` method also doesn't return any error messages.

Could you please tell us if `Runtime.callFunctionOn` method is implemented in Hermes debugger and if it is, how can we use it?

For reference: the list of [known issues with Hermes debugging](https://github.com/microsoft/vscode-react-native/issues/1099) for React Native Tools extension.

#### `react-native info` command output:
```
System:
    OS: macOS 10.15.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 33.88 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.1
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by tmikov** [comment]
Thanks for bringing this up! We will look into it.

**Comment by willholen** [comment]
You can find a list of implemented messages here: https://github.com/facebook/react-native/blob/master/ReactCommon/hermes/inspector/tools/message_types.txt

`Runtime.callFunctionOn` is not currently one of them, and the empty response you're getting is a default response for unsupported messages.

**Comment by willholen** [comment]
@RedMickey Can you help us prioritize this issue relative to the messages in #209?

**Comment by RedMickey** [comment]
@willholen, During [the migration of React Native Tools extension on `js-debug`](https://github.com/microsoft/vscode-react-native/issues/1209), we faced the similar problem as described in this issue. After the refactoring the requests that the debugger sends to the target have changed a bit. The debugger uses `Runtime.callFunctionOn` method, when it's trying to retrieve arrays content. Now it sends the following messages to the target:
```json
{
  "id": 66,
  "method": "Runtime.callFunctionOn",
  "params": {
    "functionDeclaration": "function(){const e={__proto__:this.__proto__},t=Object.getOwnPropertyNames(this);for(let r=0;r<t.length;++r){const n=t[r],i=n>>>0;if(String(i>>>0)===n&&i>>>0!=4294967295)continue;const a=Object.getOwnPropertyDescriptor(this,n);a&&Object.defineProperty(e,n,a)}return e}",
    "arguments": [],
    "objectId": "389",
    "generatePreview": true
  }
}
```
```json
{
  "id": 68,
  "method": "Runtime.callFunctionOn",
  "params": {
    "functionDeclaration": "function(e,t){const r={},n=-1===e?0:e,i=-1===t?this.length:e+t;for(let e=n;e<i&&e<this.length;++e){const t=Object.getOwnPropertyDescriptor(this,e);t&&Object.defineProperty(r,e,t)}return r}",
    "arguments": [
      {
        "value": -1
      },
      {
        "value": -1
      }
    ],
    "generatePreview": false,
    "objectId": "389"
  }
}
```

The target sends such a response:
```
[Reply From Target To Debugger] {
  "result": {},
  "id": 66
}
```

We currently process these requests in a special way, since Hermes engine returns an empty result object, and we cannot get specific remote objects, containing an array's ObjectId. We tried to add `returnByValue: true` field, but this didn't help. I think this method is important for debugging Hermes apps. It will be awesome if we can retrieve arrays data without special handlers.

**Comment by mattbfb** [comment]
Hello @RedMickey,

We are revisiting and address outstanding CDP issues in Hermes, and I believe this one has been fixed in the current version of Hermes. Do you still experience this issue?

Trying the call that was previously shown to be empty:
```
{
   "id": 1236,
   "method": "Runtime.callFunctionOn",
   "params": {
     "functionDeclaration": "function(){const e={__proto__:this.__proto__},t=Object.getOwnPropertyNames(this);for(let r=0;r<t.length;++r){const n=t[r],i=n>>>0;if(String(i>>>0)===n&&i>>>0!=4294967295)continue;const a=Object.getOwnPropertyDescriptor(this,n);a&&Object.defineProperty(e,n,a)}return e}",
     "arguments": [],
     "objectId": "12",
     "generatePreview": true
   }
 }
```

```
{"result":{"result":{"type":"object","description":"Object","className":"Object","objectId":"13"}},"id":1236}
```
