### ISSUE TITLE
Application crashes when trying to get info about some objects and functions during debugging

### ISSUE THREAD

**Issue by RedMickey** [facebook/hermes#167]
Hello, we are the development team of **VS Code** extension for debugging **React Native** apps ([vscode-react-native](https://github.com/microsoft/vscode-react-native)). On debugging a **Hermes** application (**React Native** v0.61.5) in **Google Chrome** we tried to watch the contents of `Map` and `Set` Javascript objects and faced the problem of crashing of the debugged application. The error occurs when we are trying to extend `__proto__` object content. This behavior is the same for `Map` and `Set` objects.
- Trying to extend `__proto__` object content of `Map`
![Screen Shot 2019-12-24 at 13 00 46](https://user-images.githubusercontent.com/33267199/71408994-184b0e80-2651-11ea-891e-7377b120b4d7.png)
- Trying to extend `__proto__` object content of `Set`
![Screen Shot 2019-12-24 at 13 01 57](https://user-images.githubusercontent.com/33267199/71409014-26009400-2651-11ea-8b7f-3870513a3fb4.png)

Is this an expected behavior?

For reference: the list of [known issues with Hermes debugging](https://github.com/microsoft/vscode-react-native/issues/1099) for React Native Tools extension.

**Comment by tmikov** [comment]
Thank you for reporting this! We are excited to to help in any way possible, although, as I mentioned in the other report, there may be some delay during the holidays. 

This error happens when the size getter is called before the constructor has initialized the object, which are first sight seems impossible. However construction is in fact a two-stage process - first we allocate the object and then we call the constructor. I guess it is theoretically possible that the debugger could be invoked between them. That would explain why the getter would observe an uninitialized state.

You said that you "are trying to extend __proto__ object content". What do you mean by that specifically?

**Comment by RedMickey** [comment]
@tmikov, I meant clicking on the dropdown icon on `__proto__` view in Google Chrome `Scope` tab to watch detailed info about `__proto__` object. This action triggers Google Chrome to send Chrome DevTools Protocol message to Hermes debugger to retrieve data about `__proto__` object.

![Screen Shot 2019-12-24 at 13 01 57](https://user-images.githubusercontent.com/33267199/71436487-b943d300-26fe-11ea-9cd0-19e40e1fcdbc.png)

**Comment by RedMickey** [comment]
@tmikov, we've faced a new one problem similar to described earlier one. When we try to watch function info clicking the dropdown icon on its view in **Google Chrome**, the application crashes throwing the following error:
- For example `setTimeout` function in `Global` object
![Screen Shot 2019-12-25 at 16 21 42](https://user-images.githubusercontent.com/33267199/71446496-0b075000-2735-11ea-8bfb-85197d0aea5e.png)
- Promise's `resolve` function
![Screen Shot 2019-12-25 at 16 29 13](https://user-images.githubusercontent.com/33267199/71446498-15294e80-2735-11ea-9891-9d79ab8360cd.png)

But not all functions cause such error, we are still able to watch info of some functions.
For example we can watch the following functions' info:
![Screen Shot 2019-12-25 at 16 44 44](https://user-images.githubusercontent.com/33267199/71446593-15761980-2736-11ea-90c1-1835e3b6fc99.png)

Is this an expected behavior?

**Comment by tmikov** [comment]
One guess I have is the debugger is calling the size getter as part of inspecting the `__proto__` object, which causes it to be invoked with an incorrect this. I think the problem here is not so much the behavior of the getter, but the exception propagating out of the debugger and into the app.

IIRC, we may have already fixed this. We will look into it and post an update.

**Comment by willholen** [comment]
I believe this was due to exceptions thrown while inspecting properties, which were not well handled in native. This has since been fixed and I'm unable to reproduce it as described.

**Comment by RedMickey** [comment]
Hello, we tested debugging of a React Native Hermes application (React Native v0.64.0 and Hermes engine v0.7.2) and could reproduce the problem with crashing of the debugged application. On debugging a Hermes application in Google Chrome we tried to inspect the contents of `Map` and `Set` Javascript objects as before. Currently the application being debugged doesn't show an error message, it shuts down without an error.

- Trying to inspect the contents of the `__proto__` object of a Map
  ![Screen Shot 2021-04-29 at 17 40 42](https://user-images.githubusercontent.com/33267199/116693023-fb9db400-a9c5-11eb-8e33-4ee11fb0391d.png)

- Trying to inspect `setTimeout` function in the `Global` object
  ![Screen Shot 2021-04-30 at 14 03 05](https://user-images.githubusercontent.com/33267199/116693074-12440b00-a9c6-11eb-82df-72549b8a8d55.png)

**Comment by EzioLi01** [comment]
Hey, I still can repro this issue on iOS app using Flipper, could you please have look on this?

**Comment by mattbfb** [comment]
Hello @EzioLi01, could you share some details on the specific steps (and builds) you're using? I can't seem to reproduce this locally using the descriptions above (e.g. inspecting `__proto__` of a map on iOS 
<img width="161" alt="Screen Shot 2022-08-12 at 10 13 41 AM" src="https://user-images.githubusercontent.com/111091151/184372061-16141e54-6df1-4540-afba-4e749a478e7f.png">
). Thanks!

**Comment by mattbfb** [comment]
I cannot seem to reproduce this on current versions.

Starting with a new RN application created with `npx react-native init`, then adding the code in the examples above:
```
let timerId = setInterval(() => {
    let map = new Map();
    map.set(1, 'testValue');
    map.set('keyValue', 'test');

    let set = new Set([1, 2, 3, 4, 5]);
    console.log(map);
    console.log(set);
    console.log('hi');
}, 7000);
```

I can inspect both the `__proto__` of maps, and `setTimeout` on `Global`:

![inspect](https://user-images.githubusercontent.com/111091151/229196624-ca4333e5-874e-472c-9275-979fe2f6d614.gif)

Are there still steps that can reproduce the error?
