### ISSUE TITLE
Disassembling index.android.bundle documentation needed

### ISSUE THREAD

**Issue by kseniamukhortova** [facebook/hermes#169]
I created a release build of my app with react-native 0.61.2 and enabled Hermes. In my Crashlytics I receive information about crashes along with stacktraces. Perviously I used to apply apktool to extract index.android.bundle from my apk, and it contained js code where I was able to find the issue by stacktrace.

But now using Hermes index.android.bundle seems to contain bytecode rather than js and I wasted a day trying to disassemble it. The last thing I tried was hbcdump tool mentioned in https://github.com/facebook/hermes/blob/master/doc/BuildingAndRunning.md, but all I get is "Error: fail to deserializing bytecode: Wrong bytecode version. Expected 73 but got 62"

There should be some clear documentation on how one can disassemble index.android.bundle created with hermes

**Comment by tmikov** [comment]
You can disassemble bytecode using `hermes -b --dump-bytecode file`. You can also build the correct version of `hbcdump` if you check out the Hermes version corresponding to the release you are using.

However ordinarily you shouldn't have to do that. What is preventing you from correlating the error location to  the actual source?
