### ISSUE TITLE
hi, how can I build a hermes engine for android?

### ISSUE THREAD

**Issue by HiVie** [facebook/hermes#170]
hi, how can I build a hermes engine for android? i want to run some benchmark on android with hermes engine, but i don't know how to build an arm version hermes engine.

**Comment by tmikov** [comment]
Precompiled versions of Hermes for Arm are available here: https://github.com/facebook/hermes/releases

You can find information about cross-compiling Hermes here: https://github.com/facebook/hermes/blob/master/doc/ReactNativeIntegration.md

**Comment by HiVie** [comment]
> Precompiled versions of Hermes for Arm are available here: https://github.com/facebook/hermes/releases
> 
> You can find information about cross-compiling Hermes here: https://github.com/facebook/hermes/blob/master/doc/ReactNativeIntegration.md



> Precompiled versions of Hermes for Arm are available here: https://github.com/facebook/hermes/releases
> 
> You can find information about cross-compiling Hermes here: https://github.com/facebook/hermes/blob/master/doc/ReactNativeIntegration.md

well，our team are now developing a framwork like react-native in android platform, and we want to try hermes engin to deal with the JavaScript, is that possible?

**Comment by tmikov** [comment]
Yes, it is possible. The link I provided above explains how to cross-compile Hermes for Android, you can ignore the React Native parts.
