### ISSUE TITLE
Consider implementing Error.line, Error.column, Error.fileName/sourceURL

### ISSUE THREAD

**Issue by 404-html** [facebook/hermes#171]
If some code wrapped in `try/catch` block fails the exception is not detailed.
My code looks like this:
```js
try {
	...
} catch (ex) {
	Log(ex);
}
```

I log error object into database. Here's what I can see:
`{ "error": { "jsEngine": "hermes" } }`
`{ "jsEngine": "hermes" }`

This happens on production, React Native build.

Before turning on Hermes I was getting exact failure position in bundle file:
```json
{
	"line": 595,
	"column": 4814,
	"sourceURL": "index.android.bundle"
}
```

Is there any way to get more detailed exceptions?

**Comment by tmikov** [comment]
The "line", "column", "fileName"/"sourceURL", fields of the Error object are non-standard (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) and Hermes doesn't implement them. They are supported by some engines (JavaScriptCore, SpiderMonkey) but not by others (v8, Chakra). Ideally you shouldn't have to depend on them.

The `Error.stack` property is also non-standard, but it is implemented by all engines, including Hermes. It includes the same information. so, in Hermes you can get failure position using something like this:

```
try {
    ...
} catch (e) {
      location = e.stack.split("\n")[1];
}
```

I believe there are npm packages that abstract the differences between engines and allow you to get that information in a fairly portable way.
