### ISSUE TITLE
Date.parse() difference between JSC and Hermes

### ISSUE THREAD

**Issue by adamczyk777** [facebook/hermes#175]
Hello dear contributors and maintainers 👋 

While switching to Hermes from JSC in a React Native app, I stumbled upon a weird issue with Date parsing. I've seen that according to standard when `Date.parse` fails should return a `NaN` and that a correct date string looks like `YYY-MM-DD`. Anyway before I was using below construct:
```javascript
new Date(moment(date).format('YYYY/MM/DD'));
```

And while using JSC it parsed without issues. After switching to hermes calling this caused an error and `new Date` call resolved to `null` value. I was able to mitigate consequences of that by changing separators from `/` to `-`. I am not sure whether it is a bug or a feature. If it is as it should be feel free to close the issue. 

On a side note according to `yarn.lock` I am using Hermes in version `0.2.2`, which came bundled together with RN 0.61.5

Thanks for your hard work!

**Comment by ljharb** [comment]
Try that code in Chrome - i believe jsc may be one of the only browsers that supports `/`.

**Comment by avp** [comment]
Discussed in #136

**Comment by adamczyk777** [comment]
Thanks, for a brief reply, haven't tried that in Chrome, but format was odd to me anyway. Thanks for a swift response!
