### ISSUE TITLE
 An unexpected error occurred: "https://registry.yarnpkg.com/hermes-engine/-/hermes-engine-0.2.1.tgz: unexpected end of file".

### ISSUE THREAD

**Issue by Nykollas** [facebook/hermes#181]
React native new project initialization won't work due this error:
```
 An unexpected error occurred: "https://registry.yarnpkg.com/hermes-engine/-/hermes-engine-0.2.1.tgz: unexpected end of file".

```

**Comment by willholen** [comment]
I tried reproducing this with `react-native init AwesomeProject` but did not get this error. It sounds like either a transient network failure or a full disk. Can you make sure you have available disk space and try it again today?

**Comment by Nykollas** [comment]
That was a transient network failure thank you !
