### ISSUE TITLE
App not starting when compiled to bundle (aab) format 

### ISSUE THREAD

**Issue by 404-html** [facebook/hermes#191]
Dear Hermes Army,

I'm having problem when publishing my app in [Android bundle format](https://developer.android.com/platform/technology/app-bundle) with Hermes enabled - it shows white screen and that's it. Problem doesn't occur in case of APK format.
After some time Android throws "app not responding" type of popup.

Image below shows pre-launch report from Google Play
![image](https://user-images.githubusercontent.com/45104241/75602896-cb107080-5ac9-11ea-9da6-fbd556016f7f.png)

My internal logs showed there might be a problem with App Purchases (I can see a lot of entries saying "Error: Billing is unavailable. This may be a problem with your device, or the Play Store may be down."). I'm using [react-native-iap](https://github.com/dooboolab/react-native-iap) for that.

I'll try to trace it down so I'm open for any tips for doing that.

**Comment by avp** [comment]
https://github.com/facebook/react-native/issues/26400 has a discussion about this.
