### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by steskalja** [facebook/hermes#192]
When will Windows 10 be supported as a targeted platform for hermes? There are more Windows 10 devices out there compared to iOS and they will continue to grow to be the size of Android OS.

**Comment by haozhun** [comment]
Hermes supports Windows 10 from the beginning. [README](https://github.com/facebook/hermes/blob/master/README.md) contains instructions to building on Windows.

**Comment by steskalja** [comment]
What I am looking for is to use Hermes in a React Native app on Windows 10, and not build it on Windows 10 to use on Android

**Comment by avp** [comment]
Is this issue relevant? https://github.com/microsoft/react-native-windows/issues/2799

It seems that the folks at Microsoft working on react-native-windows are also working on the Unicode implementation in Hermes for Windows (see https://github.com/facebook/hermes/issues/58)

**Comment by haozhun** [comment]
It looks like you are not trying to building Hermes. What you're interested in is running Hermes within RN. For your need, it's supported, and @avp has provided pointer to how to do it.

The rest of this comment is likely orthogonal to your question. However, I'd like to clarify things a bit for potential future readers of this issue. When building Hermes on Windows, Windows is the only currently supported target. In other words, the built binary/library can run on Windows. It is not supported to cross compile Hermes targeting Android. Of course, this does not preclude copying the Android library/binary onto a Windows host for RN application development.
