### ISSUE TITLE
v0.5.0 and  rn062

### ISSUE THREAD

**Issue by philipheinser** [facebook/hermes#213]
Can v0.5.0 be used with react-native 0.62?

**Comment by punisher97** [comment]
I testing with RN0.62.2 but no working, the app crash with this error: 
`couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found
   `

**Comment by willholen** [comment]
Unfortunately v0.5.0 is intended exclusively for the upcoming react-native 0.63 RC, and is not compatible with 0.62.x. I have updated the release description to clarify, thanks!
