### ISSUE TITLE
The website playground is broken

### ISSUE THREAD

**Issue by tmikov** [facebook/hermes#217]
It hangs when the button is clicked a second time.

**Comment by rickhanlonii** [comment]
Looks like this was fixed but not deployed

**Comment by rickhanlonii** [comment]
Deployed and verified that it's fixed!

**Comment by avp** [comment]
Loading https://hermesengine.dev/playground/ directly results in a blank screen with messages in the console that look like this:
```
Loading failed for the <script> with source “https://hermesengine.dev/playground/styles.6461568a.js”.
```

Also, the playground itself when navigating from the landing page doesn't load any text on the right side in Firefox 76, but it does appear to work correctly in Chrome.

**Comment by rickhanlonii** [comment]
Strange, do you know what we're doing wrong @yangshun?

**Comment by yangshun** [comment]
Seems like the assets paths on https://hermesengine.dev/playground/ are incorrect. They should have a leading slash in front. It should be a Docusaurus bug. It's weird because https://v2.docusaurus.io/showcase/ doesn't have that problem. Will investigate.

**Comment by yangshun** [comment]
Did investigation and realized it's not a bug with the set up and not Docusaurus. There's a file called `website/utils.js` which rewrites paths found in the files to be relative, but it isn't doing it right. I think those files were added during the initial setup of the website on Docusaurus 1 but is not needed for Docusaurus 2 (I don't think they were even needed for Docusaurus 1 too). I'm making a PR to clean those up.

**Comment by yangshun** [comment]
@rickhanlonii can you deploy the latest website so that the fix will be live?

**Comment by rickhanlonii** [comment]
Yeah will do now
