### ISSUE TITLE
x2 memory usage + potentially memory leak.

### ISSUE THREAD

**Issue by punksta** [facebook/hermes#221]
I was debugging out-of-memory errors of production app and found that
1. Hermes used about twice more RAM memory comparing to JSC.
2. it didn't free unused memory.

### tested on:
- react-native 61.5
- debug build type
- production, minified, JS
- android emulator x86, api 29

### hermes 0.2.1
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/13404754/79740998-cf564e80-8300-11ea-84b7-9d653e841400.png">

### JSC r241213
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/13404754/79740940-bf3e6f00-8300-11ea-97f0-7486eb24ad0f.png">

You can clearly see how memory was growing and wasn't getting free

## note
I think it's something either related to json parsing or `fetch` api because the app loads large json objects (10*5mb)

**Comment by avp** [comment]
This seems related to #164, which discusses a memory leak in `WeakMap` that was fixed in 0.4.1.

It seems likely that the fix is related to your issue - can you try upgrading Hermes and seeing if that works? Note that Hermes 0.4.1 works with RN 0.62.0.

**Comment by punksta** [comment]
@avp yep. But I can try upgrading no earlier than next week. JSC solves my current problem

**Comment by sinxwal** [comment]
@punksta Have you checked Hermes 0.4.1? 
In my case the memory usage is still huge.

**Comment by punksta** [comment]
@sinxwal unfortunately I just switched to JSC and I don't have time for experiments. I will update this issue if I try it.

**Comment by sinxwal** [comment]
@punksta Thanks, mate. Switching to JSC is so expensive(

**Comment by punksta** [comment]
@sinxwal you mean things like https://github.com/facebook/react-native/issues/25494 ? 
It is painful, but for my current project it isn't as bad as memory leaks. Basically I am just hoping that it will be fixed one day.

**Comment by punksta** [comment]
I tested the app again.

* React-native 63.2
* production, minified js, release build type, with android studio profiler on
* android v21 emulator

### Hermes
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/13404754/97701004-04f8a300-1aad-11eb-9302-3a998eaa11e0.png">

### JSC
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/13404754/97701877-5fdeca00-1aae-11eb-85ca-0c911cd21045.png">


Memory leak seams resolved. Memory usage is also much better.

**Comment by tmikov** [comment]
@punksta do you have an idea why the Java memory and the stack are so drastically different? Shouldn't they be the same?

**Comment by punksta** [comment]
@tmikov Indeed stack usage is very different: 20mb (hermes) vs 1.2mb (jsx). But I don't know why, unfortunately

**Comment by tmikov** [comment]
@punksta AFAICT, it is the opposite 1.2mb Hermes vs 20mb jsc. That actually makes sense - Hermes doesn't use the native stack, while JSC does. So the Hermes "stack" would count as "native memory". If we add them together we get about 75MB total native memory, approximately the same between both engines. Which is disappointing for us, of course, but not awful.

There are two remaining mysteries:
- Why is the Java memory so different?
- Is your application deeply recursive? 20MB is a lot of stack.

**Comment by punksta** [comment]
@tmikov you are right. I can't recall any deep recursions in the app.

Let me describe what the app does. It loads about 80mb by chunks and writes it into sqlite.

So data flow is the following:

`okhttp -> react-native-fetch-blob -> javascript engine -> react-native-sqlite-2 -> sqlite`

I assume that gc could not release memory allocated for java objects in one of these components.
Stack memory was already taken the loading started. So it's something else.

I will try to explore memory dump.
