### ISSUE TITLE
Regex fails on RN 

### ISSUE THREAD

**Issue by sourabhv** [facebook/hermes#231]
The RegEx `/^{+\/?|\/?}+$/` fails on RN 0.61.5 with error

> Invalid regular expression: Quantifier has nothing to repeat, js engine: hermes

But the regex works fine on hermes build from master.

Changing the regex to `/^\{+\/?|\/?\}+$/` also works.

**Comment by avp** [comment]
RN 0.61.5 is a release from November 2019. The Hermes regex parser bug was likely fixed in the series of commits near edeef8a28a1cb873eec3fcfaefed6f769ba4ffc2, which is why updating Hermes and RN should fix your issue.

Closing because the fix is already in master.
