### ISSUE TITLE
What should be included in v0.5.1

### ISSUE THREAD

**Issue by tmikov** [facebook/hermes#243]
This issue is to discuss which fixes should be backported to the next patch release 0.5.1.

**Comment by tmikov** [comment]
The fix for https://github.com/facebook/hermes/issues/235 was already added .

**Comment by willholen** [comment]
7bee987bf5e3e09f8d131d023abb9d276e41a069 adds `vcruntime140_1.dll` to the NPMs

**Comment by mhorowitz** [comment]
b96f6e339f3f7527464db77628278f11d9fcb036 saves unstripped libraries for symbolication.

**Comment by avp** [comment]
dd8111291b7d47388be203856bace770664b8de8 fixes a parser bug

**Comment by tmikov** [comment]
So we need PRs for all of these against the branch.

**Comment by Huxpro** [comment]
For the record.

#293 also included https://github.com/facebook/hermes/commit/013566a05d8dc7a38e7628a6923173896e7edeb8 which fixes #219 

Besides, we will also include https://github.com/facebook/hermes/commit/01906adfb4bacf6e46a274c2e4e400501237815f , https://github.com/facebook/hermes/commit/557e181be519ddf06dbf0684b1413a8dd498f85c and backport changes that enable `hermes-engine-darwin` npm package before actually releasing `v0.5.1`.

**Comment by Huxpro** [comment]
It's now released and published to npm. Closed.
