### ISSUE TITLE
[Playground] Hermes worker aborts on slow network

### ISSUE THREAD

**Issue by Huxpro** [facebook/hermes#247]
I haven't figured out what exactly happened but the reproducibles are:

1. Hermes worker thread would abort when it's processing the 1st message but received a 2nd. (However, the Playground tried to not `postMessage` in a loading state, which at least tried to eliminate this case).

2. Loading the website under "fast 3G" simulation and doing monkey testing on the run button and help button several times could make Hermes thread aborted.

My best guess would be some race condition are happening. 
I observed each running request would need to load another `hermes.mem` (and the fact I'm testing with cache disabled) could be part of the reason?

![Screen Shot 2020-05-19 at 12 55 21 PM](https://user-images.githubusercontent.com/5563315/82372107-3a627600-99d0-11ea-824f-cba0627ae142.png)

**Comment by dulinriley** [comment]
Hi @Huxpro I've been trying to get this issue to reproduce with a debug + assertions Hermes build, and I'm not hitting this issue. I do seem to be hitting other issues though, when I try with the slow network settings you use, it's taking a very long time to load all of the JS files.

Can you tell me more about how you tested this? Was this with the site that's deployed, or was this from a master build? If the latter, did this use `yarn start` (debugging way) or `yarn build` (production way) to build the website?
