### ISSUE TITLE
Build error when building with ASan (with solution)

### ISSUE THREAD

**Issue by farazsth98** [facebook/hermes#251]
# Error
I tried to build hermes on Ubuntu 18.04 LTS with ASan. I followed the instructions laid out in [this file](https://github.com/facebook/hermes/blob/master/doc/BuildingAndRunning.md) to install all dependencies. I also installed did a `sudo apt install clang llvm`.

I configured it as follows:
```
$ hermes/utils/build/configure.py --enable-asan
$ cd build_asan
```
Attempting to build with ninja then resulted in the following error:
```
$ ninja
[64/503] Linking CXX executable bin/FileCheck
FAILED: bin/FileCheck 
: && /usr/bin/c++  -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -fsanitize=address -fvisibility=hidden -g  -fsanitize=address -fno-pie external/llvh/utils/FileCheck/CMakeFiles/FileCheck.dir/FileCheck.cpp.o  -o bin/FileCheck  external/llvh/lib/Support/libLLVHSupport.a external/llvh/lib/Demangle/libLLVHDemangle.a && :
/usr/bin/ld: external/llvh/lib/Support/libLLVHSupport.a(Process.cpp.o): undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[66/503] Building CXX object external/llvh/utils/unittest/CMakeFiles/gtest.dir/googletest/src/gtest-all.cc.o
ninja: build stopped: subcommand failed.
```
# Solution
The solution in the end was to do a `sed -i 's/FLAGS = /FLAGS = -pthread /g' build.ninja` to add the `-pthread` flag to all the `FLAGS`, `LINK_FLAGS`, and `LANGUAGE_COMPILE_FLAGS` variables within `build.ninja`. After doing that, the build worked successfully.

Note that `-lpthread` resulted in the same error if that matters, because I noticed in `build_asan/external/llvh/include/llvm/Config/config.h` there's two lines of code that state:
```
/* Define to 1 if you have the `pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1
```

I'm not sure if this error occurred due to my build environment specifically, or if `hermes/utils/build/configure.py` needs to be modified to include `-pthread` in all the flags (I wasn't sure how to do that). If anyone knows the root cause of this error and can provide a more elegant solution, that would be great!

**Comment by dulinriley** [comment]
Hi @farazsth98, sorry for getting back to you so late.

I believe this commit from @neildhar: 45c2d63edb7598ad5dff367153ea6b70bcb3d221 fixes the issue you're seeing.
