### ISSUE TITLE
A bug about constructor Error

### ISSUE THREAD

**Issue by NWU-NISL** [facebook/hermes#252]
### Testcase:
``` javaScript:
var NISLFuzzingFunc = function (nislMutationParameter0) {
    var i = new Error(nislMutationParameter0);
    var tmp = i["message"];
    print(tmp);
    print(tmp.length);
    print(typeof tmp);
};
var nislMutationArgument0 = undefined;
var NISLCallingResult = NISLFuzzingFunc(nislMutationArgument0);
```
### Command:
``` shell
hermes testcase.js
```

### Output:
```
undefined
9
string
```

### Expected output:
```

0
string
```

According to ES6, when the value of `message`  is `undefined` in [19.5.1.1](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-error-message), The "message" property of Error instance should not be "undefined". 
In addition,  output of other engines such as v8, javascriptCore and spiderMonkey is showing in Expected output.

**Comment by tmikov** [comment]
Thank you, this indeed looks like a bug. It also seems like it might be a good starting task for a community contribution.

**Comment by ahmedkrmn** [comment]
Hi Tzvetan, how do you suggest I approach this bug fix?

**Comment by ahmedkrmn** [comment]
@tmikov I've submitted a PR #254 
The usage of `StringPrimitive::equals()` or `StringPrimitive::compare` results in the hex dump below with no other output when running the above test case:
```
0x00007FF6AA54D198 (0x000001DE344201B8 0x00007FF6AA7341F0 0x000000A03C78D878 0x000000A03C78D7E8)
0x00007FF6AA593EB9 (0x000000A03C78E3B0 0x000001DE309C6750 0x000001DE309C6750 0x000000A03C78E3A8)
0x00007FF6AA5C5986 (0x000000A03C78D9A0 0x000000A03C78DA10 0x000001DE34017A18 0x000000A03C78E2D0)
0x00007FF6AA5C53F5 (0x000001DE34FFFED8 0x000001DE309C89F0 0x000000A03C78E3A0 0x0000000000000000)
0x00007FF6AA583DB5 (0x000000A03C78E2D0 0x000000A03C78DB40 0x000001DE309C6750 0x00007FF6AA558E92)
0x00007FF6AA584F48 (0x0000000000000000 0x000001DE3402C670 0x00000000008174E8 0x000001DE309C6750)
0x00007FF6AA57DFC4 (0x000001DE3402C4A8 0x00007FF6AA55A6CC 0x000000000042C4A8 0x0000000000000000)
0x00007FF6AA585227 (0x0000000000000000 0x000000A03C78E690 0x000001DE309CE240 0x000000A03C78EA20)
0x00007FF6AA549427 (0x000001DE00000000 0x000000A03C78E960 0x00007FF6AA61D4A0 0x000001DE309C6750)
0x00007FF6AA61D064 (0x000001DE30916100 0x0000000000000000 0x000001DE30916100 0x000001DE3091AD40)
0x00007FF6AA50807E (0x000001DE309161C0 0x000001DE309161C0 0x000001DE309161C0 0x000001DE30934CA0)
0x00007FF6AA5087BE (0x0000000000000000 0x0000000000000000 0x000001DE309161C0 0x0000000000000000)
0x00007FF6AA6ECEC8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF89CE27BD4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF89EDCCE51 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
```

**Comment by tmikov** [comment]
The JS spec [says](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-error-message) that if the constructor is called with "undefined", we shouldn't set the message property at all.

What needs to be done is to change this line:
https://github.com/facebook/hermes/blob/9a27ca50107d3609a0bcd8d39ced5ab1538e91ff/lib/VM/JSLib/Error.cpp#L110

Instead of checking for non-zero number of arguments, we should just check whether the argument is undefined.
