### ISSUE TITLE
A question about fault tolerance

### ISSUE THREAD

**Issue by NWU-NISL** [facebook/hermes#258]
when executing statement `function f(){"run_here_1"}`which  is followed by `print("run_here_2");` without semicolon in the middle as testcase1, Hermes has the same result as other engines like V8, ChakraCore, SpiderMonkey .  It seems that all engines have fault-tolerant consensus on this. But when executing testcase2 which adds `if(true)`at the beginning, only Hermes throw an exception. Is it an issue about Hermes's fault tolerance mechanism?

#### version

[044cf4b](https://github.com/facebook/hermes/tree/044cf4b7dd1adfb56969886c09dbe522ccaae06c)

#### command
`build/bin/hermes -w testcase.js`

#### testcase1

```
var NISLFuzzingFunc = function(){
	function f(){print("run_here_1");}print("run_here_2");
	f();
};
NISLFuzzingFunc();
```

#### output1

```
run_here_2
run_here
```

#### testcase2

```
var NISLFuzzingFunc = function(){
	if(true)function f(){print("run_here_1");}print("run_here_2");
	f();
};
NISLFuzzingFunc();
```

#### output2

```
error:';' expected
```

Contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by avp** [comment]
Thanks for this report. This doesn't appear to be a bug in Hermes, as the `declaration not allowed as expression statement` is the error we intend to output. Here's the reasoning behind the parsing logic:

Per the [IfStatement](https://tc39.es/ecma262/#sec-if-statement) grammar, the first consequent after the `if` is a Statement. That statement must be parsed as an [ExpressionStatement](https://tc39.es/ecma262/#prod-ExpressionStatement). It's explicitly noted in the spec that the ExpressionStatement cannot start with `function`, among others.

The code doesn't SyntaxError when you use `if (true) { function f() ... }`.

**Comment by tmikov** [comment]
This seems related to Annex B. We are adding support for it.
