### ISSUE TITLE
ReferenceError: Property 'Reflect' doesn't exists, js engine: hermes

### ISSUE THREAD

**Issue by Kailash23** [facebook/hermes#259]
I am using[ p-memoize](https://github.com/sindresorhus/p-memoize) for caching promise response. 
I am getting this error when Hermes enabled, It goes away when I turn off Hermes.

After a little searching, I found that maybe it's because of Hermes engine doesn't support Reflect. I tried using this library too [reflect.ownkeys](https://www.npmjs.com/package/reflect.ownkeys) since p-memoize uses this method. It didn't work. 

Any way to circumvent this problem without going off Hermes?

**Comment by ljharb** [comment]
Can you elaborate about how `reflect.ownkeys` didn't work? It does not require the presence of `Reflect`.

It does, however, use `typeof` to check if the global variable exists: https://github.com/es-shims/Reflect.ownKeys/blob/master/polyfill.js#L6 but that should never, in any version of any engine, throw an error.

**Comment by ljharb** [comment]
@Kailash23 if you `require('reflect.ownkeys/auto')` before requiring p-memoize it absolutely will work.

**Comment by Kailash23** [comment]
@ljharb  I am facing the same problem.

```
import {readFile, DocumentDirectoryPath} from 'react-native-fs';
require('reflect.ownkeys/auto');
import pMemoize from 'p-memoize';

const basePath = DocumentDirectoryPath + '/WordPowerDB/WordMap';

const generatePath = partialWord => {
  return `${basePath}/${partialWord[0]}/${partialWord}-map.json`;
};

export const memGetSuggestions = pMemoize(getSuggestions, {maxAge: 20000});

async function getSuggestions(partialWord) {
  return new Promise(async resolve => {
    let path = generatePath(partialWord);
    try {
      console.log('heavy work!');
      let output = await readFile(path);
      resolve(JSON.parse(output));
    } catch (e) {
      console.log('Fetching suggestions : ', e);
      resolve([]);
    }
  });
}
```
[Error here](https://word-power-f39ad.web.app/Error.png)

**Comment by mhorowitz** [comment]
I can't comment on what's happening with p-memoize, or why it's failing.  @ljharb thanks for the help there.  If you figure out Hermes is doing something wrong, please open a new task so we can work on it.  But I agree, the polyfill seems like it should work.

That said, you could also [enable the experimental Proxy/Reflect support](https://github.com/facebook/hermes/issues/33#issuecomment-606963341).  Note that this will only work with the exact versions in that comment.  There seems to be at least one unidentified bug in Proxy which I haven't been able to track down yet, so we haven't yet enabled it by default, but that shouldn't affect `Reflect.ownKeys`, which is very simple.

**Comment by ljharb** [comment]
@Kailash23 if you're using `import`, you have to `import 'reflect.ownkeys/auto'` FIRST, before any other imports or code.

That polyfill/shim will continue to do the right thing with Hermes' experimental support added, and when it ships stable.

**Comment by Kailash23** [comment]
@ljharb Still getting the same reference error.
```
import 'reflect.ownkeys';
import {readFile, DocumentDirectoryPath} from 'react-native-fs';
import pMemoize from 'p-memoize';

const generatePath = partialWord => {
  const basePath = DocumentDirectoryPath + '/WordPowerDB/WordMap';
  return `${basePath}/${partialWord[0]}/${partialWord}-map.json`;
};

export const memGetSuggestions = pMemoize(getSuggestions, {maxAge: 20000});

function getSuggestions(partialWord) {
  return new Promise(async resolve => {
    let path = generatePath(partialWord);
    try {
      let output = await readFile(path);
      console.log('<Heavy call>');
      resolve(JSON.parse(output));
    } catch (e) {
      console.log('Fetching suggestions : ', e);
      resolve([]);
    }
  });
}
```
I also tried importing at `index.js` top.

**Comment by ljharb** [comment]
@Kailash23 feel free to find me on freenode, or some popular slacks, under this username, and i'll be happy to help you further. Failing that, please file an issue on `reflect.ownkeys` and we can discuss it there :-)

**Comment by Kailash23** [comment]
I had filed this issue at `reflect.ownkeys`. Thanks a lot : ) @ljharb @mhorowitz

**Comment by rjuevesano** [comment]
can someone help me? I got this issue too...
```
com.facebook.react.common.JavascriptException: ReferenceError: Property 'Reflect' doesn't exist, js engine: hermes
```

RN: 0.63.4

**Comment by mhorowitz** [comment]
@rjuevesano Reflect was enabled at the same time as Proxy, which was RN 0.64/Hermes 0.7.x.  Ideally, you should update to the latest version of React Native and Hermes.

If you cannot, you can manually enable a version of Hermes for RN 0.63 which will enable Proxy and Reflect: See the release notes here https://github.com/facebook/hermes/releases/tag/v0.5.2-rc1.  `npm install hermes-engine@0.5.2-rc1` should be enough to use it, and there are posts about this in earlier comments on this issue.

**Comment by rjuevesano** [comment]
> npm install hermes-engine@0.5.2-rc1

Yup... doing that works for me. Thanks :)
