### ISSUE TITLE
ReactNativeIntegration.md is not up to date

### ISSUE THREAD

**Issue by marecar3** [facebook/hermes#262]
Hi there,

It seems that instructions in the file`ReactNativeIntegration.md`  aren't precise anymore as we are mentioning `crosscompile_llvm.sh` in **Package build** section and that file doesn't exist in source code.

Could we make sure that this document is up to date? Thanks. cc @tmikov

**Comment by mhorowitz** [comment]
Thanks for the report.

The `crosscompile_llvm.sh` section was removed in https://github.com/facebook/hermes/commit/9c952b81a81727b26950fbe6045f7a0d5f5485b6 on June 8.

Sorry for taking so long to respond and get this closed.
