### ISSUE TITLE
Building hermes on MacOS not working on tag/0.4.1 with latest XCode

### ISSUE THREAD

**Issue by marecar3** [facebook/hermes#263]
Hi there,

I am following the steps from the tutorial: https://github.com/facebook/hermes/blob/master/doc/BuildingAndRunning.md#building-on-linux-and-macos in order to build hermes. 

**Steps:**
checkout: https://github.com/facebook/hermes/tree/release-v0.4
execute command: `hermes/utils/build/configure.py`

**Setup:**
`cmake 3.17.3`
`git 2.27.0`
`ninja 1.10.0`

`XCode Version 11.5 (11E608c)`
`java version "1.8.0_181"`
`Android NDK: android-ndk-r21c`
`gradle 6.0.1`

`gcc version: Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**CMakeError:**

> Run Build Command(s):/usr/local/bin/ninja cmTC_24a1d && [1/2] Building CXX object CMakeFiles/cmTC_24a1d.dir/src.cxx.o
> [2/2] Linking CXX executable cmTC_24a1d
> FAILED: cmTC_24a1d 
> : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DHAVE_GC_SECTIONS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names --gc-sections CMakeFiles/cmTC_24a1d.dir/src.cxx.o  -o cmTC_24a1d   && :
> clang: error: unsupported option '--gc-sections'
> ninja: build stopped: subcommand failed.
> 
> Source file was:
> int main() { return 0; }

**Error from console**

> CMake Deprecation Warning at CMakeLists.txt:299 (cmake_policy):
>   The OLD behavior for policy CMP0023 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> CMake Error at CMakeLists.txt:349 (include):
>   include could not find load file:
> 
>     LLVMConfig
> 
> 
> CMake Error at CMakeLists.txt:350 (include):
>   include could not find load file:
> 
>     AddLLVM
> 
> 
> CMake Error at CMakeLists.txt:351 (include):
>   include could not find load file:
> 
>     HandleLLVMOptions
> 
> 
> CMake Error at tools/hermes/CMakeLists.txt:12 (add_llvm_tool):
>   Unknown CMake command "add_llvm_tool".

**Comment by willholen** [comment]
You are applying the Master build instructions to the `release-v0.4` branch. Try following the [`release-v0.4` build instructions instead](https://github.com/facebook/hermes/blob/release-v0.4/doc/BuildingAndRunning.md).

Older versions of Hermes required building LLVM separately first, which is why you're seeing CMake complain about `add_llvm_tool` not being recognized. 

I tested it and was able to build the branch using Xcode 11.5 with these instructions. Please reopen if you're still having problems!

**Comment by marecar3** [comment]
Thanks, @willholen, it's working!

**Comment by nthtrung09it** [comment]
@willholen @marecar3  I can build using the instructions, but how can I import this project into VSCode or CLion so I can debug it? Thanks in advance. I am trying to build Hermes v0.2.1.
