### ISSUE TITLE
Where is unsupported feature list?

### ISSUE THREAD

**Issue by mehulmpt** [facebook/hermes#27]
The Chain React 2019 launch video mentions there's a complete list of unsupported ES6 features including Proxies and local evals. Can somebody point me to the complete unsupported list?

This is what I'm talking about: https://youtu.be/zEjqDWqeDdg?t=795

Thank you and congrats on the awesome engine!

**Comment by jemmyphan** [comment]
https://github.com/facebook/hermes/blob/master/doc/Features.md

**Comment by mehulmpt** [comment]
Got it! Thanks!
