### ISSUE TITLE
Introduce explicit "commit" in OSCompat abstraction of virtual memory

### ISSUE THREAD

**Issue by haozhun** [facebook/hermes#3]
To start, read the attached picture to understand how the basics of memory allocation works in POSIX and Windows.

The cause of the problem is the transition from Reserved to Committed. On POSIX, it is implied. As a result, in Hermes code, there isn't a call that explicitly does that.

A shortcut was taken in my initial Windows port:
* `oscompat::vm_allocate` on Windows returns memory that has been Committed.
* `oscompat::vm_unused` does nothing.

For context, the point of `vm_unused` is to free the physical memory (but not virtual address space), and so that it doesn't count against our RSS. (Please correct me if this understanding is incorrect.)

The goal of this issue is:

* Add `vm_commit` (MEM_COMMIT on Windows, no-op on posix)
* Change `vm_allocate` to reserve the memory without committing it (MEM_RESERVE on Windows, no change needed on posix)
* Implement `vm_unused` with `MEM_DECOMMIT` on Windows. 
* Change relevant code that interacts with `vm_*` so that they invoke `vm_commit` before accessing the memory if `vm_commit` has not been invoked since the latest `vm_allocate` and `vm_unused`.

![50932988_366403384141481_1486283032032706560_o](https://user-images.githubusercontent.com/2020503/54563211-e00df580-4985-11e9-976e-d2dfb2081224.jpg)

Tracked as T40416012 at Facebook.

**Comment by chumzee** [comment]
my phone is low 4mb...

**Comment by tmikov** [comment]
Implemented in 043f073eefccc13f79bdc749a288d08151527ada
