### ISSUE TITLE
 RN 0.63.1 + enableHermes -> very slow launch performances

### ISSUE THREAD

**Issue by imranMnts** [facebook/hermes#318]
## Bug Description

I recently updated RN version of my project from 0.59.10 to 0.63.1. It works properly, I didn't detect any issue but when I turn on Hermes to benefice its advantages, my app takes 2 times longer to be launched in release mode.

Versions:
Hermes version: 0.5.0
React Native version: 0.63.1
Android version: Android 8.0
Device: Samsung J3

Launch times (to see the first screen of the app):
 - without hermes: ~7s
 - with hermes: ~20s

If anyone has had to face this problem, your help is welcome 🙂
Thank you.

**Comment by avp** [comment]
Thanks for the report. It's easier to debug these sorts of issues with some code to look at - without it, we're in the dark regarding the actual problem.

A few things to try:
- Make sure you're in release mode
- Try putting some logging statements to try and narrow down precisely where the error is. It could be some code for which Hermes is not optimized
- https://github.com/facebook/hermes/issues/295 has some discussion on how to track these sorts of things down.

**Comment by Huxpro** [comment]
@imranMnts any updates? Have you tried what @avp suggested (especially making sure you were in the release mode)?

**Comment by peterkuiper** [comment]
I have seen this as well. We use react-native-sodium and the decrypt function itself takes about 7s. Due to this (and maybe other packages hit by this issue), the startup time is about 15-20s (we have to load encrypted data into redux). After disabling Hermes, the startup time is about 4-7s. We are using RN 0.63.4 and testing on low end Android devices (these seem to be affected the most).

**Comment by Huxpro** [comment]
Besides of what @avp had mentioned, there is also possibility that you are not using pre-compiled bytecode. You can check if the `main.jsbundle` looks like JS source or bytecode. The bytecode is compiled in `react-native-xcode.sh` and we've seen people/codebase (e.g. Mattermost) has their own copy of `react-native-xcode.sh` hence the app doesn't use bytecode and fallback to Hermes's on-device lazy compilation.

**Comment by tmikov** [comment]
FWIW, startup time of 4-7s doesn't sound that great either. Perhaps the lesson here is that JavaScript, even with a JIT, is just not that suitable for high intensity computation like decryption. It would work much better if the decryption was implemented in C++.

**Comment by imranMnts** [comment]
@Huxpro 
Sorry for the late response, we had some other urgent topics

I double-checked and I'm sure I'm in release mode.
I updated RN's version to 0.64.1, Hermes working fine on iOS but we have still the speed issue during the startup on android.

Hermes version: 0.7.2
RN version: 0.64.1

**Comment by imranMnts** [comment]
I fixed the issue on my side.

It was due to the bundle generated in the APK, it was in JS and to beneficiate from Hermes' improvements it should be bytecode.

**Comment by Huxpro** [comment]
@imgraham thanks for reporting back!

As I mentioned before, this is often the cause:

> You can check if the main.jsbundle looks like JS source or bytecode. 

Would you mind sharing with us how did you find it and what was the improvements?

**Comment by devjaw** [comment]
@imranMnts how did you fix it ?

**Comment by imranMnts** [comment]
we generated the bundle manually via
`react-native bundle --platform android \ ...`

I removed it and added

```
project.ext.react = [
    enableHermes: true,
]
apply from: "../../node_modules/react-native/react.gradle"
```
in my `app/build.gradle` 
which generate the bundle during the compilation automatically and fix the bundle which was in js

**Comment by aemre** [comment]
> we generated the bundle manually via `react-native bundle --platform android \ ...`
> 
> I removed it and added
> 
> ```
> project.ext.react = [
>     enableHermes: true,
> ]
> apply from: "../../node_modules/react-native/react.gradle"
> ```
> 
> in my `app/build.gradle` which generate the bundle during the compilation automatically and fix the bundle which was in js

so manually creating bundle solve the issue?

**Comment by CloudCityxx** [comment]
I also encountered this problem。 very very slow.

**Comment by CloudCityxx** [comment]
> 

I tried this solution, but it didn't solve, it was still very slow

**Comment by CloudCityxx** [comment]
> > we generated the bundle manually via `react-native bundle --platform android \ ...`
> > I removed it and added
> > ```
> > project.ext.react = [
> >     enableHermes: true,
> > ]
> > apply from: "../../node_modules/react-native/react.gradle"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in my `app/build.gradle` which generate the bundle during the compilation automatically and fix the bundle which was in js
> 
> so manually creating bundle solve the issue?

I tried this solution, but it didn't solve, it was still very slow

**Comment by imranMnts** [comment]
@CloudCityxx Did you unzip your apk to check if your bundle contains bytecode or js? (in assets folder)

**Comment by upngo** [comment]
For anyone who stumbles upon this with RN 0.71.0
 Upgrade to 0.71.1 as there was an issue with hermes and debug (didn't affect release builds)
