### ISSUE TITLE
JS Intl support in Hermes (2/4) - Collator

### ISSUE THREAD

**Issue by Khalef1** [facebook/hermes#320]
Hermes doesn't currently support the JS Intl namespace. Opening this issue to track the implementation of Collator.

**Comment by Khalef1** [comment]
@mganandraj is planning to work on this in late August

**Comment by mganandraj** [comment]
A PR is out : https://github.com/facebook/hermes/pull/317

**Comment by chrisbobbe** [comment]
#317 (mentioned [above](https://github.com/facebook/hermes/issues/320#issuecomment-670205871)) was [reportedly](https://github.com/facebook/hermes/pull/317#issuecomment-701092510) closed in favor of #338.

#338 has [reportedly](https://github.com/facebook/hermes/pull/338#issuecomment-707998772) been merged, in https://github.com/facebook/hermes/commit/44bd2ef186febf5b5e18b03e8e7edc6daf32c127. Does that mean this issue should be closed? 🙂

**Comment by Khalef1** [comment]
Yup, this should be closed
