### ISSUE TITLE
JS Intl support in Hermes (3/4) - NumberFormat

### ISSUE THREAD

**Issue by Khalef1** [facebook/hermes#321]
Hermes doesn't currently support the JS Intl namespace. Opening this issue to track the implementation of NumberFormat.

**Comment by Khalef1** [comment]
@mganandraj is planning to work on this in late August

**Comment by mganandraj** [comment]
On track to send out a PR by Sept 2nd. Thanks!

**Comment by Khalef1** [comment]
PR: #338

**Comment by chrisbobbe** [comment]
#338 (linked to [above](https://github.com/facebook/hermes/issues/321#issuecomment-688914037)) has [reportedly](https://github.com/facebook/hermes/pull/338#issuecomment-707998772) been merged, in https://github.com/facebook/hermes/commit/44bd2ef186febf5b5e18b03e8e7edc6daf32c127. Does that mean this issue should be closed? 🙂

**Comment by Khalef1** [comment]
Yup, this should be closed
