### ISSUE TITLE
Standalone hermes artifact

### ISSUE THREAD

**Issue by nlgtuankiet** [facebook/hermes#326]
### Context
As a developer, I want to update small parts of my native app (Android + iOS) logic without update the app. The idea is to write these logics/functions in JS then use a runtime to evaluate the result
```java
SomeRuntime.evaluate("1 + 1"); // return "2"
```

### Exiting solution problem
on the Android side, there are some libraries/runtimes that support the use case, but they all have some limitations.
Duktape: lightweight (size), functional but performance is not that great
https://github.com/square/duktape-android
J2V8: offer the best performance, but heavy in size (8mb in split APK)
https://github.com/eclipsesource/J2V8
and some others but not worth to mention

Performace matter because this "function" is invoked for about 100 times per second in a single background thread.
Note: my app is 80% native and 20% react, so reuse the Hermes engine is a good option

### Solution
Make Hermes become a standalone library, support both apps that use React and app that doesn't.

**Comment by tmikov** [comment]
Hi, Hermes already is a standalone library - although its primary use is in ReactNative apps, it has no dependencies on React Native itself.  `libhermes.so` simply exports a JSI interface, which is loaded and used by React Native, and can similarly be loaded and used by any app. 

With that said, our focus currently is React Native, so we don't have a lot of documentation for non-RN use cases. 

For some mode details, please see this comment: https://github.com/facebook/hermes/issues/43#issuecomment-512558215

**Comment by nlgtuankiet** [comment]
for some reason I couldn't find any reference to `libhermes.so` in the react native sdk. The only reference I found is 
```groovy
task packageReactNdkLibs(dependsOn: buildReactNdkLib, type: Copy) {
    from("$buildDir/react-ndk/all")
    into("$buildDir/react-ndk/exported")
    exclude("**/libjsc.so")
    exclude("**/libhermes.so")
}
```

Could you please show me how to load the `libhermes.so` or obtain an instance of the JSI interface?

**Comment by tmikov** [comment]
Take a look here: https://github.com/facebook/react-native/tree/b8621f5d303442ab78dc5d745cfc86a941d4737c/ReactAndroid/src/main/java/com/facebook/hermes/reactexecutor

Let me know if that helps.

**Comment by nlgtuankiet** [comment]
Unfortunately, it didn't help much, I haven't figured out how to do it, could you please be more specific. I'm seeing that we have a JavaScriptExecutor interface, I guess that where we can evaluate the result of a javascript expression, but all of JavaScriptExecutor's method name didn't suggest that : (

**Comment by mhorowitz** [comment]
Are you writing your app code in C++ or Java?

**Comment by mhorowitz** [comment]
Once you get further along, you should be able to use `evaluateJavaScript` to run your code, but that won't give you the best performance.  Instead, you should use `evaluateJavaScript` to define a function (either return it, or give it a global name), then use `jsi::Function::call` to invoke the function.

**Comment by nlgtuankiet** [comment]
I'm writing in code in Java :(
My js code is only performing calculations on the primitive type.
Could you guys please make a java binding for Hermes?

**Comment by mhorowitz** [comment]
Unfortunately, we don't have plans to write a standalone Java API for JSI/Hermes ourselves.

If someone in the community is interested in writing one, I think that would be a great contribution and we would be happy to give feedback.

**Comment by JoshMarler** [comment]
Wondered if I could piggy back on this thread to ask if there is a CMake target or similar I can use for a libHermes.so or even better a static lib?

I'm investigating integrating Hermes into the Blueprint React framework as a JS backend: https://github.com/nick-thompson/blueprint

We're currently using Duktape but it's GC phase is too slow and on the face of things Hermes design goals look like exactly what I need. 

Specifically I'd like to include hermes in an existing CMake project and link a binary to a libHermes.so or libHermes.a. Is this possible? If anyone is able to point me in the right direction I would be MORE than happy to contribute some documentation should I succeed. 

Cheers

**Comment by JoshMarler** [comment]
Small update, building with `--static-link` option currently failing on ubuntu x64:

```
[406/525] Linking CXX shared library API/hermes/libhermes.so                                                                                                                                                       
FAILED: API/hermes/libhermes.so                                                                                                                                                                                    
: && /usr/bin/c++ -fPIC -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor 
-fvisibility=hidden -g  -O3 -shared -Wl,-soname,libhermes.so -o API/hermes/libhermes.so API/hermes/CMakeFiles/libhermes.dir/hermes.cpp.o API/hermes/CMakeFiles/libhermes.dir/DebuggerAPI.cpp.o API/hermes/CMakeFile
s/libhermes.dir/hermes_tracing_compat.cpp.o  -Wl,-rpath,/usr/lib/x86_64-linux-gnu  jsi/libjsi.a  lib/VM/libhermesVMRuntime.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  /usr/lib/x86_64-linux-gnu/libicui18n.a  /usr/li
b/x86_64-linux-gnu/libicudata.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  lib/ADT/libhermesADT.a  lib/Platform/libhermesPlatform.a  lib/Platform/Intl/libhermesPlatformIntl.a  lib/BCGen/HBC/libhermesHBCBackend.a  li
b/Inst/libhermesInst.a  lib/BCGen/libhermesBackend.a  lib/libhermesFrontend.a  lib/FrontEndDefs/libhermesFrontEndDefs.a  lib/libhermesOptimizer.a  lib/SourceMap/libhermesSourceMap.a  lib/Parser/libhermesParser.a
  lib/AST/libhermesAST.a  lib/Support/libhermesSupport.a  lib/Regex/libhermesRegex.a  lib/Platform/Unicode/libhermesPlatformUnicode.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  /usr/lib/x86_64-linux-gnu/libicui18n.a
  /usr/lib/x86_64-linux-gnu/libicudata.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  /usr/lib/x86_64-linux-gnu/libicui18n.a  /usr/lib/x86_64-linux-gnu/libicudata.a  lib/InternalBytecode/libhermesInternalBytecode.a  e
xternal/dtoa/libdtoa.a  external/llvh/lib/Support/libLLVHSupport.a  external/llvh/lib/Demangle/libLLVHDemangle.a  -lpthread  -ldl  -lpthread && :                                                                  
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libicui18n.a(smpdtfmt.ao): relocation R_X86_64_PC32 against symbol `_ZTIN6icu_6013DecimalFormatE' can not be used when making a shared object; recompile with -fPIC         
/usr/bin/ld: final link failed: Bad value                                                                                                                                                                          
collect2: error: ld returned 1 exit status   
```

**Comment by tmikov** [comment]
## Using Outside of RN

@JoshMarler yes, using Hermes independently of RN will continue to work and be supported. As you can see, Hermes itself has no source dependencies on React Native, its build process, tests, etc, are completely independent. Frankly, entangling the two would be bad design. (The one exception to this is the [Hermes Inspector](https://github.com/facebook/react-native/tree/master/ReactCommon/hermes/inspector), which we hope to address eventually)

With that said, ReactNative is our primary user and our ability to help with different integrations may be more limited or may take us longer. 

I am pretty sure you won't hit a fundamental integration issues, and if you did, we would consider it a bug ad address it.

## Static Linking
While it is theoretically possible, we decided to stop actively supporting static linking, because it turned out to be too much hassle. I am sure it can be made to work with some tweaking of the build scripts. If it was done cleanly, we would accept a PR. 

## ICU
ICU is not fun, but it is needed for compatibility with the JavaScript spec, but not all applications actually use all its functionality. If your app doesn't need it, it is possible to stub it out with some fairly small source modifications to Hermes. You can look at the different implementations under https://github.com/facebook/hermes/tree/master/lib/Platform/Unicode .

**Comment by JoshMarler** [comment]
@tmikov , Thanks for the excellent feedback. This is really encouraging. 

Static linking isn't essential for us. Working in Buildroot and it has an ICU package etc. `ldd` shows libhermes.so has a pretty lean shared of shard lib dependencies all of which we have on our target system I think. Super glade this is CMake and I can just pass it a toolchain file!

Awesome, thanks for the ICU hint. I'll build as is initially and reconsider if major issues. 

I'll carry on down this route given your advice then. If I hit a workable solution I'll gladly contribute some form of documentation or WIKI detailing the process. Can point to our frameworks usage of `jsi.h` as example that may be beneficial for people attempting similar things. 

Thanks, 

Josh

**Comment by JoshMarler** [comment]
@tmikov , Just trawled through some source. 

Can I just check expected usage of an API. I notice `jsi.h` includes `jsi-inl`. If I want to register a C++ function I assume I'm expected to go through `facebook::jsi::detail::createFromHostFunction` ?

Wasn't totally obvious from any docs etc so just hunting through some headers at the moment. Looks like this is the entry point to all the things?

**Comment by tmikov** [comment]
### Re: how to create functions
You should never call anything in the `detail` namespace. In order to create a host function (a native function callable from JS) use `facebook::jsi::Function::createFromHostFunction()`. Once you have the result, you can either install it in the global object, or pass it as a parameter to a JS function which can do with it as it pleases.

### Build problems
I thought you were already able to build libhermes.so, which includes jsi.cpp? That specific build error does not make sense to me. PropNameID is declared in `jsi.h`, which is included at the top of `jsi.cpp`. That source line is already in the facebook::jsi namespace. Have you modified the source in any way?

**Comment by JoshMarler** [comment]
@tmikov , Please ignore all the above! Have now implemented the basics of API as suggested:

https://github.com/JoshMarler/blueprint/commit/60f2e54628058c904a06aff462523f64e38bd3f6

All makes sense now. Thanks for the heads up. 

Re build problems. Discovered the culprit. Silly mistake on my end. All looking good now. Thanks for the assistance.

**Comment by JoshMarler** [comment]
@tmikov , 

Please let me know if better to open another issue for this. 

I'm wondering if I could quickly check in on your comments regarding removing the ICU dependency. I've now got Hermes working with our custom React renderer and have compiled successfully for 32bit ARM under Buildroot. I want to evaluate this as we're using Duktape and right now the mark-and-sweep GC phase is too slow and causing our UI to stutter. 

I'm hitting an issue where adding the ICU Buildroot package appears to push us over our hardware's max root fs size. Ideally I'd like to remove ICU.

Was you previous suggesting basically that I could remove https://github.com/facebook/hermes/blob/master/lib/Platform/Unicode/PlatformUnicodeICU.cpp and/or basically implement the PlatformUnicode interface with some empty stubs? Are things likely to collapse if I do this? At present we don't have a requirement for unicode strings in our UI as it's all just ASCII. 

Any assistance much appreciated.

**Comment by tmikov** [comment]
@JoshMarler the best approach would be to define a new "Unicode Platform". It sounds complicated but is actually easy:
1. Add a new define in [PlatformUnicode.h](https://github.com/facebook/hermes/blob/ea2b5aa5a7a792cf599f5b06b5503c280d364d85/include/hermes/Platform/Unicode/PlatformUnicode.h#L18). 
2. Define `HERMES_PLATFORM_UNICODE` to it in [CMakeLists.txt](https://github.com/facebook/hermes/blob/master/CMakeLists.txt#L392) using `add_definitions()`. If you want to be fancy, you can add a new CMake option and set that flag depending on its value (that would be needed if you wanted to publish this in a PR).
3. Create a new file under [Platform/Unicode](https://github.com/facebook/hermes/tree/master/lib/Platform/Unicode), for example `PlatformUnicodeASCII.cpp`. You can copy `PlatformUnicodeEmscripten.cpp` as a starting point.
4. `localeCompare()` can be implemented as simple numerical comparisons of its arguments, the rest of the functions are not really important.

**Comment by JoshMarler** [comment]
This is great, thanks @tmikov. Really appreciating the level of support and responsiveness on this project. Hopefully shouldn't need to bother you all again for a while!

**Comment by tmikov** [comment]
@JoshMarler no worries, all of us here really enjoy working on open source! 

If GC pauses are an issue for you, you may also want to try our new Hades garbage collector (though keep in mind it is still considered experimental). On 32-bit devices it runs in incremental mode, but still provides a noticeable improvement in pause times. You can enable it by passing `-DHERMESVM_GCKIND=HADES` when configuring CMake (or by editing HERMESVM_GCKIND in CMakeCache.txt).

**Comment by JoshMarler** [comment]
Awesome thanks @tmikov ! I spotted the Hades option and wondered what it involved. Incremental GC is exactly what we need and not currently provided by Duktape. Also evaluating QuickJS and potentially V8 but the design goals of Hermes sound like the exact right thing for our project.

**Comment by tmikov** [comment]
@JoshMarler FWIW, we are significantly faster than both Duktape and QuickJS (the latter has a performance comparison on their website, but the numbers are incorrect).

**Comment by JoshMarler** [comment]
Awesome. Really looking forward to doing an A/B profile on our hardware tomorrow once this ICU issue removed.

**Comment by JoshMarler** [comment]
@tmikov , if there are any other pearls of wisdom in regards to config/cmake options for a 32bit ARM target I'd be super grateful to hear. Duktape shortcomings have been initial bundle eval and GC stalls. We'd still like to keep overall mem usage/fluctuation as low as possible whilst achieving a 25-30hz or so frame rate. 

Please let me know if there are useful things I can contribute back to documentation off of the back of this. I.e. how to integrate Hermes into a C++ project etc.etc. I'd be happy to give something back.

**Comment by tmikov** [comment]
@JoshMarler there are basically two things to ensure you will get good performance:
- Make sure you compile the JS to bytecode in advance, with optimizations (`hermesc -O ...`), as part of your build process, and execute only the compiled bytecode on the device. That is perhaps the most common mistake.
- Make sure Hermes is compiled without assert and with optimizations (`Release`, `MinSizeRel`).

There are further ways to significantly decrease the size of the compiled bytecode, like stripping backtrace information and erasing function names. Let me know if those are important for you.

**Comment by tmikov** [comment]
@JoshMarler yes, I think it would be awesome if you could contribute some documentation of what you did, or a PR of the changes you did to Hermes, etc. But I don't want to jinx it yet - let's see if Hermes meets your requirements.

**Comment by JoshMarler** [comment]
Great information. Thanks. I've got very high hopes for this.

**Comment by JoshMarler** [comment]
@tmikov just to check what is the correct set of API calls to run a precompiled .hbc file?

Still `prepareJavascript` and `evaluatePreparedJavascript` ? The tests seem to suggest this is the case but I'm only getting succesfull render loading .js file at the moment.

**Comment by JoshMarler** [comment]
@tmikov , Still tinkering. Hitting this at the moment:

```
Compiling JS failed: 1:1:unrecognized Unicode character \u0000 Buffer size 902282 starts with: 00000000000000000000000000000000
Hermes evaluate exception: Compiling JS failed: 1:1:unrecognized Unicode character \u0000 Buffer size 902282 starts with: 00000000000000000000000000000000
ReactJUCEGainPlugin: /home/josh/development/blueprint/react_juce/hermes/API/jsi/jsi/../jsi/jsi.h:1094: facebook::jsi::Object facebook::jsi::Value::getObject(facebook::jsi::Runtime&) const &: Assertion `isObject()' failed.
Aborted (core dumped)

```

I've not messed with any ICU or unicode platform stuff yet. Just trying to switch to loading a precompiled .hbc rather than JS source.

**Comment by JoshMarler** [comment]
@tmikov, OK so I have a render now loading precompiled bytecode. A bunch of stuff in the app appears not to be working vs loading as plain JS. Not total sure what the reason for this is right now.

**Comment by JoshMarler** [comment]
@tmikov , I've got all the cmake and PlatformUnicode stuff setup to allow me to pass `HERMES_PLATFORM_UNICODE_ASCII_ONLY`. This instantiates my `PlatformUnicodeASCII.cpp` file as the unicode provider. 

I'm not total sure what `localCompare` needs to do but are you basically suggesting straight equality comparison for the two char arrays? i.e. compare two local strings?

**Comment by mhorowitz** [comment]
> Please let me know if there are useful things I can contribute back to documentation off of the back of this. I.e. how to integrate Hermes into a C++ project etc.etc. I'd be happy to give something back.

I agree with Tzvetan on sequencing.  But once you've got Hermes working well for you, Improvements to OSS documentation would be most welcome.  As you have seen, JSI in particular is just documented in the header files, with the tests serving as mediocre examples.  There is much room for improvement here.

**Comment by JoshMarler** [comment]
Yep no problem. I'd be more than happy to contribute some things back once I've finished up. FYI I've got a CMake option working which allows me to pass `HERMES_UNICODE_ASCII_ONLY` and implements a simple PlatformUnicode implementation which has allowed me to remove ICU for now. If this sounds like a useful thing to have I'd be happy to drop over a PR. The implementation of my `PlatformUnicodeASCII.cpp` can probably use some improvements from those better initiated, character code conversion foo isn't really one of my strong points!

I'll drop over some PR's once I'm done. Few small things that might be of to people with similar use cases.

**Comment by tmikov** [comment]
@JoshMarler glad to see you worked through the issues. By the time I woke up, it was too late to help you :-)

**Comment by JoshMarler** [comment]
Heh yeah cheers. Hopefully I can stop spamming this thread. I'll fire a PR over in the next few days. Not expecting it to be merged at all it just might server as useful info/inspiration for you.

I will link to the implementation over at the blueprint/react-juce framework once complete. It might serve as a nice example for other users.

**Comment by JoshMarler** [comment]
For reference, current light hack: https://github.com/JoshMarler/hermes/commit/0721169705400b08e319a3be86d23a0f3f726e3e

**Comment by JoshMarler** [comment]
I lied. 

So I've added the `hermesc` target as a dependency because I want to ensure I'm compiling from source with same settings when doing cross-compile for ARM under Buildroot. 

Since adding this I'm hitting a `IMPORTFILE-NOTFOUND` error at `hermes/lib/InternalBytecode/CMakeLists.txt:23`. Looks like I've got some issue cross compiling the hermes compiler tool. I didn't hit this when just compiling the `libhermes` target under Buildroot. 

For reference the following vars are reported prior to this error:

```
-- CMAKE_HOST_SYSTEM_NAME = Linux
-- CMAKE_SYSTEM_NAME = Linux
-- HERMES_APPLE_TARGET_PLATFORM =
-- CMAKE_CROSSCOMPILING = TRUE
```

Looks as expected to me. Any ideas?

**Comment by JoshMarler** [comment]
Noted the following in `hermesc` CMakeLists.txt:

```
# The Hermes compiler is used as part of the build of the VM.
# During cross-compilation, the compiler needs to be built for the host system,
# then used to build the VM for the target system.
if(NOT CMAKE_CROSSCOMPILING)
  # Namespace added to avoid clashing the host binary with the target binary.
  export(TARGETS hermesc FILE ${CMAKE_BINARY_DIR}/ImportHermesc.cmake NAMESPACE native-)
endif()
```

Is this correct or should the condition be flipped and should my `add_dependency(hermesc)` invocation be changed?

**Comment by JoshMarler** [comment]
@tmikov , just trawling through commit log to  try and work this out. Found commit https://github.com/facebook/hermes/commit/4fe84e2cbd0cbac40a571a7836709ad4346909e5. Would you be able to elaborate a little on how the native-hermesc target is supposed to be used? I can see this runs as a custom commands to convert some internal bytecode into and linkable C++ format but I'm not totally clear on what I need to do to set this up.

**Comment by JoshMarler** [comment]
This guide gives me a bit more context: https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/Exporting-and-Importing-Targets

Still not too clear on how to setup the host vs target compiles of the `hermesc` tool.

**Comment by JoshMarler** [comment]
Looks like following advice in #421 might be working. Makes sense. Need to workout how to create a host package for Buildroot to automate build of the host `hermesc` instance but hopefully this should all work...

**Comment by tmikov** [comment]
@JoshMarler cross compilation came up recently. I admit it is a kind of a pain. See if my comments here can be of any help: https://github.com/facebook/hermes/issues/421#issuecomment-733864973

**Comment by tmikov** [comment]
I wonder whether using CMake export is an overkill here. It is just a single executable, we might just as well pass its path directly to CMake.

**Comment by JoshMarler** [comment]
@tmikov, I think the export itself is fine and indeed it seems to be the expected approach for this problem. My cmake foo wasn't quite strong enough to workout the expected usage until I did a bit of reading.

Very nearly there now with Buildroot. Everything compiles, links and installs to the target rootfs as expected. 

At the moment I'm getting a crash on load I need to investigate after linking to libhermes. 

One quick question, if I'm precompiling my JS to bytecode as part of the buildroot step is it ok to use the host compiled hermesc binary? Or do I need to use the cross compiled target to compile the JS for loading ?

**Comment by JoshMarler** [comment]
This stuff should all.make a good contribution for the docs as wasn't immediately obvious. If I can come up with anything neater for a cross compiled project I'll let you know.

**Comment by tmikov** [comment]
> One quick question, if I'm precompiling my JS to bytecode as part of the buildroot step is it ok to use the host compiled hermesc binary? Or do I need to use the cross compiled target to compile the JS for loading ?

You can use either, but the expectation is that you would use the host one because it is more convenient. They are guaranteed to produce the same bytecode.

**Comment by JoshMarler** [comment]
Excellent, thanks @tmikov.

**Comment by JoshMarler** [comment]
Heh. Almost there. 

Hit this at runtime after linking to `libhermes`: 

```
libjsi.so: cannot open shared object file: No such file or directory
```

Somewhat suprised as I only have a static jsi lib in my build output. I see there is `HERMES_STATIC_LINK` as an option which I guess links in all dependent libs statically. 

I'll run through the cmake sources again and workout dependencies etc. Spamming this thread to death right now but it might be useful for others to follow the process as I go until I can document things properly.

**Comment by JoshMarler** [comment]
@tmikov, FYI adding a STATIC type to the jsi library declaration fixed the above for me.

**Comment by tmikov** [comment]
@JoshMarler I am trying to figure out why it doesn't have the STATIC in the first place. Weird. All Hermes libraries are automatically made static by `add_hermes_library()`, but JSI isn't using it.

**Comment by JoshMarler** [comment]
@tmikov , Yeah it appeared one of the odd ones out which doesn't the `add_hermes_library` helper. Wondered if it had just been missed?

**Comment by tmikov** [comment]
@JoshMarler Apparently the default is controlled by the CMake variable BUILD_SHARED_LIBS, which isn't normally set. Is it by any chance set in your build? 
In any case I believe we should add the STATIC to jsi.

**Comment by JoshMarler** [comment]
@tmikov , I suspect our buildroot configuration ends up passing that through. I think you're probably right about the jsi lib having the STATIC specifier though yeah.

**Comment by JoshMarler** [comment]
@tmikov, Thought I'd just check in on contributions back. Will you be adding the `STATIC` specifier discussed? Also, is an "ASCII only" platform Unicode implementation of any use to you guys? It's a hack on my end really to remove ICU dependency for embedded hardware but let me know if it sounds like something of use.

**Comment by tmikov** [comment]
Re the STATIC specifier. It should be added, together with POSITION_INDEPENDENT_CODE ON, similar to https://github.com/facebook/hermes/blob/master/cmake/modules/Hermes.cmake#L125. If you are interested in submitting a PR, please do.

Re ASCII only platform. Yes, I think it will be useful. For others doing a similar integration, but also since Hermes size is being unfairly compared to other VMs due to our dependency on ICU.

**Comment by JoshMarler** [comment]
@tmikov, Great thanks I can fire PRs over for both later today. Thanks for the assistance.

**Comment by JoshMarler** [comment]
@tmikov , Just tinkering now but is there a specific reason for jsi to not be using `add_hermes_library` ?

**Comment by tmikov** [comment]
@JoshMarler even though JSI originated in Hermes, it is used with other engines, so JSI library itself can't depend on Hermes. Yes, this change LGTM.

**Comment by JoshMarler** [comment]
@tmikov, cool thanks for the response. I'll fire over some PR's with the various little fixes. 

Out of interest I found this helpful to cleanup cmake client usage:

```
diff --git a/API/hermes/CMakeLists.txt b/API/hermes/CMakeLists.txt
index 18a0fca6..a670ed04 100644
--- a/API/hermes/CMakeLists.txt
+++ b/API/hermes/CMakeLists.txt
@@ -82,6 +82,7 @@ hermes_link_icu(libhermes)
 
 # Export the required header directory
 target_include_directories(libhermes PUBLIC ..)
+target_include_directories(libhermes PUBLIC ../../public/)
 
 if("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang" OR
     "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
```

Should this be added or is the expectation for the user the setup the `public` include? Without this preprocess of hermes.cpp fails. Alternative is for user to add the include path to their target explicitly but if this doesn't cause some unforeseen issue it means users can just `target_link_libraries(libhermes)` and they're good to go. Should be documented either way.

**Comment by JoshMarler** [comment]
@tmikov, I think I'm just about at the last hurdle which appears to be cmake on Windows. I think I'm hitting the following issue: https://stackoverflow.com/questions/33062728/cmake-link-shared-library-on-windows

VS/Windows dll's isn't one of my strong points. Is VS cmake regularly tested? At the moment my target is looking for `hermes.lib` but I only have a `hermes.dll` in my build output.

**Comment by JoshMarler** [comment]
@tmikov , Opened up speculative PR based on all the above findings. Will fire over ASCII ICU replacement in separate PR. 

https://github.com/facebook/hermes/pull/454

It would be cool to check in on whether a static libhermes target is a possibility.

**Comment by JoshMarler** [comment]
Haaaaaang on. Is this all because I should be linking against `hermesapi` if I want a static equivalent?

**Comment by JoshMarler** [comment]
@tmikov, just a shout out to say thanks a bunch for your assistance through this. We've just successfully merged Hermes support:

https://github.com/nick-thompson/blueprint/commit/ae472e33e842bc6ffcebe3e245269769f4d868c8

I will be contributing some more thinks back up to the project soon. Really appreciate the support.

**Comment by dulinriley** [comment]
Hi @JoshMarler, I'm Riley and I work primarily on Hades, the new concurrent garbage collector. Our goal with the collector is to deliver consistently low pause times (the 99.9'th percentile is <= 50 milliseconds). Have you tried it out with your app? I'd be curious to know your experience with it, and to know if you had any issues.

cc @neildhar who works on Hades with me

**Comment by JoshMarler** [comment]
Hey Riley!

I've not enabled Hades yet no but I'll definitely give it a test and fire you over some notes etc. Will probably be next week as I'm currently on leave

**Comment by dulinriley** [comment]
@JoshMarler in terms of memory usage, it might be slightly higher than the current default (called "GenGC" or "NCGen" in the code), but likely less than 10% worse. In some cases it can even be slightly lower than GenGC because Hades can collect more often.

For growth over time, it shouldn't have any noticeable impact. Hades will compact memory to reduce fragmentation, so over a period of many collections it'll be as compact as GenGC.

**Comment by JoshMarler** [comment]
@dulinriley,

Ah OK interesting. I'll definitely give this a try. I'm running in the context of a UI for a real-time audio app so I'll let you know if I hit any implications using Hades in this context. 

I'd simply not switched it on previously as GC spikes disappeared but I shall A/B profile and see how things look.

**Comment by tmikov** [comment]
Just a quick node with respect to Hades. @JoshMarler, I suspect you are targeting a 32-bit device. On 32-bit devices Hades can't do full concurrent collection and falls back to incremental instead. The benefit is still significant compared to GenGC, but somewhat less pronounced.

**Comment by franz-fletcher** [comment]
Sumn sumn Rust bindings? I know rust support is something that will be considered post native architecture rollout and library refactoring innitiatives. Just like the progress I'm seeing reported on the viability of embedding the hermes runtime in non React Native projects.

Any chance someone with some domain experience in embedded hermes can spare some time to give me a basic overview of the undocumented API and what I would need to consider before I start hacking and lead myself astray?

Btw, @tmikov your contributions to the react ecosystem and willingness to invest in low level DX and supporting developers like us is really inspiring. I can't hate on Meta in good faith, knowing just how much folks like you have done to shape the app development landscape and all our carrers!

**Comment by ludescher** [comment]
hi everyone,
im curious if its possible to use/link the bundled hermes binary in a c++ turbo module like `Champignon` described [here](https://stackoverflow.com/questions/75987913/how-to-configure-cmake-to-include-a-local-build-binary)?
This would open up a few interesting possibilities.

**Comment by tmikov** [comment]
@ludescher I don't see why not. Hermes is a just a normal library.

**Comment by ludescher** [comment]
@tmikov thank you for your reply.
this sounds promising, maybe i will give it a shot.

**Comment by anmonteiro** [comment]
> ## Static Linking
> While it is theoretically possible, we decided to stop actively supporting static linking, because it turned out to be too much hassle. I am sure it can be made to work with some tweaking of the build scripts. If it was done cleanly, we would accept a PR.

I managed to statically link `libhermes` into a musl + `-static` binary with the patch included in the following PR: https://github.com/nix-ocaml/nix-overlays/pull/1083.

My executable is then linked with:

```
  -lhermesbundled # this is the name I chose for the bundle, could easily be changed
  -lstdc++
  -licuio
  -licutu
  -licui18n
  -licuuc
  -licudata
```

`file` command output:

```bash
$ file result/bin/hermes_test
result/bin/hermes_test: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

I find the patch isn't too intrusive, with one exception: the CMake function based on https://cristianadam.eu/20190501/bundling-together-static-libraries-with-cmake/

I'm unsure if the patch is clean enough to be incorporated in the repo, but I wanted to share my progress anyway.

**Comment by tmikov** [comment]
@anmonteiro we actually fully support compiling Hermes into a single static library in the next major release (called Static Hermes) due some time in 2024. See here for example: https://github.com/facebook/hermes/blob/c4499d0b2b1a05f0aa149630e0f4485a369cc54b/lib/CMakeLists.txt#L109

**Comment by anmonteiro** [comment]
aha, that's good news. I suppose that's still being developed in a separate branch, and will eventually be merged back into main?

**Comment by tmikov** [comment]
@anmonteiro more or less. More accurately, it will become the new main branch.

**Comment by Wolfleader101** [comment]
> @anmonteiro we actually fully support compiling Hermes into a single static library in the next major release (called Static Hermes) due some time in 2024. See here for example:
> 
> https://github.com/facebook/hermes/blob/c4499d0b2b1a05f0aa149630e0f4485a369cc54b/lib/CMakeLists.txt#L109


Im curious as to how easy it will be to integrate this into a C++ application for windows...
Could then be used as the backend scripting engine for a game engine and could be very powerful...
