### ISSUE TITLE
Hermes: BCProviderFromSrc closure memory leak

### ISSUE THREAD

**Issue by ChasonTang** [facebook/hermes#327]
## Bug Description
In C++ project
```
runtime->run("somecode below", "test.js", hermes::hbc::CompileFlags());
runtime->collect();
runtime->getHeap().createSnapshot(llvm::outs());
```
The test.js
```
globalThis.TestA = function TestA() {};
globalThis.testA = new globalThis.TestA();
globalThis.typeof1 = function typeof1(obj, world) {
    globalThis.typeof2 = function typeof2(obj2) {
        return typeof obj2;
    };
    
    return globalThis.typeof2(obj);
};
globalThis.typeof1(globalThis.testA, 'world');
globalThis.testA = undefined;

// In hermes-repl, could uncomment below two line to make garbage collect and create heap snapshot
// gc();
// createHeapSnapshot();
```
<img width="622" alt="截屏2020-08-11 下午4 00 32" src="https://user-images.githubusercontent.com/7238515/89872657-daa0f300-dbeb-11ea-8762-e0d4d2a7d0e7.png">
<img width="277" alt="截屏2020-08-11 下午4 00 22" src="https://user-images.githubusercontent.com/7238515/89872655-daa0f300-dbeb-11ea-8eaa-36f65d88e933.png">

Chrome show that the typeof2 capture the obj and world parameter, but normally the testA is assigned undefined that will be garbage collection from heap, So the memory leak happen.
However, compile to bytecode and run bytecode is correct and no memory leak.

Hermes version: 5.0
React Native version (if any):
Android version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

**Comment by tmikov** [comment]
This is expected behavior. With optimizations turned off, Hermes does not perform capture analysis, so it has to assume that all variable and parameters that are in scope are captured. So, `obj` and `world` are stored in a heap environment.

You can see what is happening by examining the unoptimized bytecode:
```
Function<typeof1>(3 params, 20 registers, 3 symbols):
Offset in debug table: source 0x003a, lexical 0x0000
    CreateEnvironment r0
    LoadParam         r1, 1
    LoadParam         r2, 2
    GetGlobalObject   r3
    LoadConstUndefined r4
    StoreToEnvironment r0, 0, r1     // obj is stored in the heap environment
    StoreToEnvironment r0, 1, r2     // world is stored in the heap environment
    TryGetById        r5, r3, 1, "globalThis"
    CreateClosure     r6, r0, 3      // typeof2 closure is created with the same environment
    StoreToEnvironment r0, 2, r6
    PutById           r5, r6, 1, "typeof2"
    TryGetById        r7, r3, 1, "globalThis"
    GetByIdShort      r8, r7, 2, "typeof2"
    LoadFromEnvironment r9, r0, 0
    Mov               r13, r7
    Mov               r12, r9
    Call              r10, r8, 2
    Ret               r10
```

**Comment by ChasonTang** [comment]
I see. Thank you for your answer
