### ISSUE TITLE
DebugPrint Equivalent

### ISSUE THREAD

**Issue by WilliamParks** [facebook/hermes#336]
## Problem

Hello! Does Hermes have a DebugPrint funciton or equivalent? I did a quick search through the code base, but couldn't find anything.

I'm looking to see how objects are laid out in memory, to help debug something. Thanks!

**Comment by Huxpro** [comment]
Hi @WilliamParks,

Did you refer to v8/d8's `%DebugPrint` function which outputs memory addresses, element kinds and so on? If that's the case, we don't have something equivalent yet, but community contributions are welcome. I would imagine adding a `HermesInternal.DebugPrint()`, which is only present in debug builds and calling a native function behind the scene.

> I'm looking to see how objects are laid out in memory, to help debug something. 

I would be interested in understanding your use cases better to see if there are other alternatives: what information do you need and what bug are you trying to look at in specific?

**Comment by WilliamParks** [comment]
Hey @Huxpro, I appreciate the quick response.

I was looking for an equivalent to v8/d8's `DebugPrint`, mainly to help me figure out how things are laid out in memory.
