### ISSUE TITLE
Test fails: AlignedStorageTest.cpp:124: Failure Expected: (initial) != (FAILED), actual: 18446744073709551615 vs 18446744073709551615

### ISSUE THREAD

**Issue by yurivict** [facebook/hermes#347]
```
Note: Google Test filter = AlignedStorageTest.AdviseUnused
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from AlignedStorageTest
[ RUN      ] AlignedStorageTest.AdviseUnused
/usr/ports/lang/hermes/work/hermes-0.5.2-rc1/unittests/VMRuntime/AlignedStorageTest.cpp:124: Failure
Expected: (initial) != (FAILED), actual: 18446744073709551615 vs 18446744073709551615
[  FAILED  ] AlignedStorageTest.AdviseUnused (0 ms)
[----------] 1 test from AlignedStorageTest (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AlignedStorageTest.AdviseUnused

 1 FAILED TEST
```

Version 0.5.2-rc1
clang-10
FreeBSD 12.2

**Comment by tmikov** [comment]
Looks like regionFootprint() is failing, which isn't very surprising: it is trying to use the Linux implementation, which attempts to read `/proc/self/smaps`, which I suspect is Linux-specific. I think a FreeBSD implementation has to be added.

**Comment by yurivict** [comment]
Please note that you open the file ```std::ifstream smaps("/proc/self/smaps");``` and don't check for failure.

**Comment by tmikov** [comment]
We don't really need to check for failure - it just naturally falls through to the error exit at the bottom.

**Comment by tmikov** [comment]
Closing this, since we can't provide first party support for FreeBSD. Happy to incorporate community PRs for it though.
