### ISSUE TITLE
cmake configure continies after it doesn't find pthread_getname_np that is required for build

### ISSUE THREAD

**Issue by yurivict** [facebook/hermes#348]
```
-- Looking for pthread_getname_np
-- Looking for pthread_getname_np - not found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - not found
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
...
/wrkdirs/usr/ports/lang/hermes/work/hermes-0.5.2-rc1/lib/Support/OSCompatPosix.cpp:516:9: error: use of undeclared identifier 'pthread_getname_np'
  ret = pthread_getname_np(pthread_self(), threadName, sizeof(threadName));
        ^
1 error generated.
```

```pthread_getname_np``` should be made required.

**Comment by tmikov** [comment]
Detection for `pthread_getname_np()` is part of LLVM's build scripts, but LLVM itself doesn't require it, so it wouldn't make sense to set it to required there. In any case, the end result is the same - the build fails eventually.

However I think the proper solution here would be do conditionalize the code inside `OSCompatPosix.cpp` depending on `HAVE_PTHREAD_GETNAME_NP`. Technically Hermes doesn't really the thread name in Hermes - is just used for diagnostics.

PRs are welcome.

**Comment by yurivict** [comment]
I've created the FreeBSD port for ```Hermes```. ```pthread_getname_np()``` was only fairly recently added to FreeBSD, so the port availability is limited to system versions where ```pthread_getname_np()``` is available.

At this point this isn't a significant problem from the port's standpoint.

**Comment by tmikov** [comment]
Patches for FreeBSD are very welcome! It will have to be community supported - there is no practical way for us to test on FreeBSD at Facebook. However we can look into whether we can run FreeBSD tests on CircleCI so that we can at least know when it breaks.
