### ISSUE TITLE
An issue about the Array.prototype.pop().

### ISSUE THREAD

**Issue by NWU-NISL** [facebook/hermes#349]
The pop() method removes the last element of the array and returns it，and the maximum length of the array is 2^32−1.But after I put an element in the last position of the array, an RangeError occurred while executing the pop function.When executing this test case on other engines, (like chakraCore, v8 and spiderMonkey)，no error occurred.

**version**

[b6530ae](https://github.com/facebook/hermes/tree/b6530ae)

**Test case**

```javascript
var NISLFuzzingFunc = function(){
    var a = [];
    a[Math.pow(2,32)-2] = 1;
    a.pop();
}
NISLFuzzingFunc();
```

**Command**

```javascript
./build/bin/hermes -w testcase.js
```

**Output**

```javascript
RangeError: Out of memory for array elements.
```

**Expected behavior**

```javascript
Pop successfully.
```

**Comment by tmikov** [comment]
Thank you for reporting this. I investigated and found the bug, working on a fix.
