### ISSUE TITLE
Assertion Failure at JSLexer.h:154

### ISSUE THREAD

**Issue by HongxuChen** [facebook/hermes#357]
## Bug Description

When running `hermes $JSFILE` with some crafted JSFILEs, `hermes` may trigger the assertion failure.

- [x] I have confirmed this bug does not occur with JSC

Hermes version: 0.7.0 (git ab7c2cfa)
React Native version (if any):
Android version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):  x86_64

## Steps To Reproduce

1. Craft a javascript file `test.js` with the following content:
```javascript
export { a as+ }
```

2. run `./hermes test.js` and it reports:

```
assert_JSLexer.h:154.js:1:14: error: 'identifier' expected in export clause
export { a as+ }
       ~~~~~~^
hermes: /home/hongxu/work/hermes/hermes-asan/include/hermes/Parser/JSLexer.h:154: hermes::UniqueString* hermes::parser::Token::getResWordOrIdentifier() const: Assertion `getKind() == TokenKind::identifier || isResWord()' failed.
```

## The Expected Behavior
No assertion triggered.

**Comment by tmikov** [comment]
Thanks for reporting yet another bug! It appears that there is a missing "else" or some other error recovery mitigation:
https://github.com/facebook/hermes/blob/20a33312e42709b9b8d4860ad2c3aa65d7315930/lib/Parser/JSParserImpl.cpp#L5734
