### ISSUE TITLE
Assertion failure at JSParserImpl-flow.cpp:1716

### ISSUE THREAD

**Issue by HongxuChen** [facebook/hermes#362]
## Bug Description

When running `hermes $JSFILE` with some crafted JSFILEs, `hermes` may trigger the assertion failure.

- [x] I have confirmed this bug does not occur with JSC

Hermes version: 0.7.0 (git ab7c2cfa)
React Native version (if any):
Android version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):  x86_64

## Steps To Reproduce

1. Craft a javascript file `test.js` with the following content:
```javascript
({
   f() :<A = { () }
})
```

2. run `./hermes test.js` and it reports:

```
./assert_JSParserImpl-flow.cpp:1716.js:2:24: error: ':' expected in function type annotation
        f() :<A = { () }
                    ~~~^
hermes: /home/hongxu/work/hermes/hermes-orig/external/llvh/include/llvh/ADT/Optional.h:176: T* llvh::Optional<T>::getPointer() [with T = hermes::ESTree::FunctionTypeAnnotationNode*]: Assertion `Storage.hasVal' failed.
```

## The Expected Behavior
No assertion triggered.

**Comment by tmikov** [comment]
Thank you for reporting this. It appears that we are incorrectly trying to parse this using Flow syntax, even though it should be disabled.
