### ISSUE TITLE
Optimise the size of iOS artifacts

### ISSUE THREAD

**Issue by grabbou** [facebook/hermes#368]
## Problem

Right now, the artifact itself is rather large after all architectures, dSYMs, and bitcode were included - **2GB**. We need to find a way to reduce this to a reasonably small size, so that it doesn't affect React Native users.

The goal is to reduce the size so that it comes w/o penalty for new React Native applications.

## Solution

- Optimise size of `hermes-engine-darwin` npm package
  - Turn off bitcode (**2GB** with bitcode enabled for three architectures, **12MB** without bitcode). While it saves the size, it makes it impossible to build React Native with `bitcode`, which comes "on" by default. Potential change in the default template possible as long as it makes sense to do so. We can also disable `bitcode` for `iphonesimulator` architectures as I think it makes no sense to ship that for non-release architectures (won't be able to build for simulator in the release tho)
  - Decide what to do with symbols - `dSYM` weights **200mb**
- Make it optional package, so that users will have to install `hermes-engine-darwin` npm package on demand (unlike for Android) - size constraint doesn't affect the initial setup time. Potential degraded DX as it requires many actions to be done to enable Hermes
- Do not use `npm` for `hermes-engine-darwin`, but use `CocoaPods` dependency management mechanism. We can publish full Hermes to CocoaPods repository and it will be automatically installed as soon as React Native users change the flag in a Podfile to `enable_hermes`. This is done by removing `path` to a `Hermes` podspec that points to `node_modules`.
- Build Hermes in the user land (don't ship artifacts)

Opening this issue to discuss potential ways going forward and options that we have.

**Comment by alloy** [comment]
We definitely do not need bitcode for the simulator. IIRC, Xcode doesn’t even actually build bitcode until an archive release is built.

Symbols should be made available, at the very least for release builds in order to symbolicate crash reports. These could potentially be made available separately for when needed, but we have to take into account the possibility that RN users will not know/remember to do so and in turn struggle with unhelpful crash reports.

I am in favour of not using npm. At first it seemed like it might be good to stay consistent for now, but it’s becoming clear that it’s only adding friction, with eg mow needing to decide when to install it.

(FWIW I believe we also shouldn’t install the Android runtime by default.)

Building hermes in user-land would solve the artefact size issue, but isn’t trivial to convert (although everything is doable) and would increase the build time of RN projects.

**Comment by grabbou** [comment]
> Are you saying Xcode won’t allow a simulator release build without the slice present?

I believe when bitcode is turned on and simulator slices don't contain bitcode, the build will fail, unless you turn that off for that particular build. I am fine with that, but I am trying to think for the users as well.

My current preferred solution is to release Hermes to the CocoaPods repository with artifacts and have `pod install` automatically download required artifacts (no matter their size) as soon as users flip the `hermes_enabled` flag and re-run installation.

I think this is totally fine, given it's what `Flipper` does already [here](https://github.com/facebook/react-native/blob/master/scripts/react_native_pods.rb#L72-L100). I think the approach of using `npm` makes sense for smaller packages, such as community native modules. For a package like this one, where 100% is native code, I don't see any benefits of going that path.

**Comment by mhorowitz** [comment]
2gb!  This sounds painful for everyone without the biggest network connections.

How does the CocoaPods repository release process work?

**Comment by alloy** [comment]
@mhorowitz CocoaPods isn’t a package manager, so it doesn’t host packages; this means we just need to serve the artefacts from _somewhere_, e.g. a GitHub release, and then point the CocoaPods podspec to that location.

CocoaPods also supports tarballs compressed with xz, so I’m interested in seeing how large the archive will be when compressed with that algorithm.

**Comment by grabbou** [comment]
I will experiment with that and post results at the beginning of next week.

**Comment by grabbou** [comment]
I am back after holidays, resuming my work on this one. Will keep you posted.

**Comment by alloy** [comment]
To publish a podspec to the centralised spec repo, you need to follow the steps outlined here: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

An important thing to note here is that, as we’re planning to distribute prebuilt binaries, the `source` attribute of the spec needs to be updated for each release and we can leave out the `prepare_command` entirely. It’s probably easiest to look for an env variable from within the podspec, e.g.:

```ruby
spec.source = ENV['hermes-artefact-url'] ? ENV['hermes-artefact-url'] : { git: "https://github.com/facebook/hermes.git", tag: "v#{spec.version}" }

unless ENV['hermes-artefact-url']
  spec.prepare_command = '…'
end
```

And then do:

```bash
env hermes-artefact-url='…' pod trunk push hermes.podspec
```

**Comment by mhorowitz** [comment]
Thanks, @alloy, a couple more questions.

1. If we push a podspec with ENV checks for the binary artifact, won't the user of the pod need to set the env var in order to download the prebuilt version?  Is this something the RN podspec would do?

2. How does versioning work?  In the future when we create v0.8.0 for use by rn 0.65, how do we have rn 0.64 continue to use hermes v0.7.x?  Is there any mechanism for automatic updates to new patch releases?

**Comment by alloy** [comment]
1. When you push a podspec it will be serialized to JSON, so the evaluation results are then recorded and won’t require the user to do anything.

2. Setting version requirements on “pods” works similarly as with eg npm. That is, the `React-Core/Hermes` module in RN will have a requirement such as `~> 0.7`, which indicates any `0.7.x` (preferably the latest possible) will be used.

**Comment by Huxpro** [comment]
@alloy it seems like `pod` dislike `spec.source` being a String and asked for a Hash?

```
$ env hermes-artifact-url='https://github.com/facebook/hermes/releases/download/v0.7.1/hermes-engine-darwin-v0.7.1.tgz' pod trunk push hermes-engine.podspec
Updating spec repo `trunk`

Validating podspec
 -> hermes-engine (0.7.1)
    - ERROR | source: Unsupported type `String`, expected `Hash`
    - ERROR | unknown: Encountered an unknown error (no implicit conversion of Symbol into Integer) during validation.

[!] The spec did not pass validation, due to 2 errors.
```

**Comment by alloy** [comment]
Ah yes indeed, my bad. See the doc on it here https://guides.cocoapods.org/syntax/podspec.html#source. The hash can also include a checksum for the artefact.

**Comment by alloy** [comment]
As for the name, I think `hermes-engine` would probably be better to entirely disambiguate from the existing Hermes pod.

**Comment by Huxpro** [comment]
@alloy the current document seem to use a different syntax, but from what I understood I changed the podspec to:

```
spec.source = ENV['hermes-artifact-url'] ? { http: ENV['hermes-artifact-url'] } : { git: "https://github.com/facebook/hermes.git", tag: "v#{spec.version}" }
```

then redo the push. This is what I got:

```
λ env hermes-artifact-url='https://github.com/facebook/hermes/releases/download/v0.7.1/hermes-engine-darwin-v0.7.1.tgz' pod trunk push hermes-engine.podspec

Updating spec repo `trunk`

CocoaPods 1.10.0.rc.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.rc.1

Validating podspec
/Users/jsx/github/hermes/hermes-engine.podspec:8: warning: already initialized constant Pod::HermesHelper::BUILD_TYPE
/Users/jsx/github/hermes/hermes-engine.podspec:8: warning: previous definition of BUILD_TYPE was here
/Users/jsx/github/hermes/hermes-engine.podspec:10: warning: already initialized constant Pod::HermesHelper::OSX_DEPLOYMENT_TARGET
/Users/jsx/github/hermes/hermes-engine.podspec:10: warning: previous definition of OSX_DEPLOYMENT_TARGET was here
/Users/jsx/github/hermes/hermes-engine.podspec:11: warning: already initialized constant Pod::HermesHelper::IOS_DEPLOYMENT_TARGET
/Users/jsx/github/hermes/hermes-engine.podspec:11: warning: previous definition of IOS_DEPLOYMENT_TARGET was here
/Users/jsx/github/hermes/hermes-engine.podspec:8: warning: already initialized constant Pod::HermesHelper::BUILD_TYPE
/Users/jsx/github/hermes/hermes-engine.podspec:8: warning: previous definition of BUILD_TYPE was here
/Users/jsx/github/hermes/hermes-engine.podspec:10: warning: already initialized constant Pod::HermesHelper::OSX_DEPLOYMENT_TARGET
/Users/jsx/github/hermes/hermes-engine.podspec:10: warning: previous definition of OSX_DEPLOYMENT_TARGET was here
/Users/jsx/github/hermes/hermes-engine.podspec:11: warning: already initialized constant Pod::HermesHelper::IOS_DEPLOYMENT_TARGET
/Users/jsx/github/hermes/hermes-engine.podspec:11: warning: previous definition of IOS_DEPLOYMENT_TARGET was here
 -> hermes-engine (0.7.1)
    - ERROR | file patterns: The `source_files` pattern did not match any file.
    - ERROR | file patterns: The `preserve_paths` pattern did not match any file.
    - ERROR | file patterns: The `vendored_frameworks` pattern did not match any file.
    - ERROR | header_mappings_dir: The header_mappings_dir (`destroot/include`) is not a directory.
    - WARN  | license: Unable to find a license file
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the App editor. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

[!] The spec did not pass validation, due to 4 errors and 1 warning.

[!] Unable to read the license file `LICENSE` for the spec `hermes-engine (0.7.1)`

[!] Unable to read the license file `LICENSE` for the spec `hermes-engine (0.7.1)`

[!] Unable to read the license file `LICENSE` for the spec `hermes-engine (0.7.1)`

[!] Unable to read the license file `LICENSE` for the spec `hermes-engine (0.7.1)`

```

Could you able to provide fixes through either comments or PRs (if it's non-trivial)?

**Comment by grabbou** [comment]
Does `destroot` exist on your machine? It looks like it is missing and that's why CocoaPods is complaining. You would have to build iOS/Mac frameworks first (one hour job), by:
```bash
cd test/ApplePlatformsIntegrationTestApp
pod install
```
This would execute the https://github.com/facebook/hermes/blob/master/hermes-engine.podspec#L37 script.

**Comment by grabbou** [comment]
As discussed on Discord, you may wanna use `hermes-runtime-darwin` instead to test it. The current package you're using was meant to be consumed by `npm`.

**Comment by Huxpro** [comment]
```
env hermes-artifact-url='https://github.com/facebook/hermes/releases/download/v0.7.1/hermes-runtime-darwin-v0.7.1.tar.gz' pod trunk push hermes-engine.podspec

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  hermes-engine (0.7.1) successfully published
 📅  October 13th, 00:57
 🌎  https://cocoapods.org/pods/hermes-engine
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

**Comment by Huxpro** [comment]
@grabbou @alloy Should this be closed? Or do we have some other ideas to further optimize the size?

**Comment by alloy** [comment]
I think this is good for now. Specifically we no longer install this dependency by default with new apps, people have to opt-in and _then_ install it.
