### ISSUE TITLE
An issue about the arguments object

### ISSUE THREAD

**Issue by NWU-NISL** [facebook/hermes#374]
## Description

According to Ecma262 specification, When changing the `arguments` exotic object's property, it will change the corresponding value of the argument binding at the same time. But when I executed the following test case, Hermes doesn't use the `arguments` object to change the argument correctly. I think it may be a bug of the Hermes engine.

## Version

[b6530ae(release)](https://github.com/facebook/hermes/tree/b6530ae)

## Testcase

~~~javascript
function f0(args){
    var v0 = 0;
    for (var v1 = 0; v1 < args.length; ++v1){
        v0 += args[v1];
        args[v1] += v1;
    }
    return v0;
}

function f1(a, b, c, d){
    return [
        f0(arguments),
        a,
        b,
        c,
        d
    ];
}

print(f1(0,1,2,3));
~~~

## Command

~~~javascript
./build/bin/hermes -w testcase.js
~~~

## Output

~~~javascript
6,0,1,2,3
~~~

## Expected Output

~~~javascript
6,0,2,4,6
~~~

## Ecma262 Specification

[9.4.4 Arguments Exotic Objects](https://tc39.es/ecma262/#sec-arguments-exotic-objects)

**NOTE 2** ……This means that changing the property changes the corresponding value of the argument binding and vice-versa. ……

**Comment by ljharb** [comment]
I believe this only applies in sloppy mode.

**Comment by tmikov** [comment]
Thank you for your report - you are correct that it doesn't work in Hermes, though that is by design. This is functionality we deliberately chose not to support: it is documented here: https://github.com/facebook/hermes/blob/master/doc/Features.md#miscellaneous-incompatibilities
