### ISSUE TITLE
An issue about the template string

### ISSUE THREAD

**Issue by NWU-NISL** [facebook/hermes#378]
#### Description

In the following test case, I defined an object `v0` and rewrote its `toString` and `valueOf` function. Then I used a template string to call the variable. According to ECAM262, it will evaluate the expression `v0`. In my opinion, the `toString` method should be called firstly because `v0` is an object instead of a number. Is this a normal behavior of the Hermes engine?

#### Testcase

~~~javascript
function f0() {
    var v0 = {
        toString: function() {
            return 'foo';
        },
        valueOf: function(){
            return 'bar';
        }
    };
    print(`${v0}`);
}
f0();
~~~

#### Version

[9caeabc](https://github.com/facebook/hermes/commit/9caeabcda3876828e25c2aa816356a70224c0813)

#### Command

~~~javascript
./build/bin/hermes -w testcase.js
~~~

#### Output

~~~javascript
bar
~~~

#### Expected Output

~~~javascript
foo
~~~

#### Ecma262  Specification

[12.2.9.6 Runtime Semantics: Evaluation](http://www.ecma-international.org/ecma-262/11.0/index.html#sec-template-literals-runtime-semantics-evaluation)

> 2. Let subRef be the result of evaluating Expression.

[7.1.17 ToString ( argument )](http://www.ecma-international.org/ecma-262/11.0/index.html#sec-tostring)

**Comment by ljharb** [comment]
Template literals should indeed only ever call `toString` when it's present - ie, https://tc39.es/ecma262/#sec-template-literals-runtime-semantics-evaluation calls https://tc39.es/ecma262/#sec-tostring which calls https://tc39.es/ecma262/#sec-toprimitive with hint String.

**Comment by tmikov** [comment]
A case of incorrect optimization.
