### ISSUE TITLE
not standard date.toString() format

### ISSUE THREAD

**Issue by nes123** [facebook/hermes#38]
(new Date).toString()

results in  "2019-07-15T20:29:57.312+03:00" 

instead of the familiar javascript format:

Mon Jul 15 2019 20:29:57 GMT+0300 (IDT)

any ideas how I can enforce the familiar javascript format instead of this new one as it is not compatible with my code?

**Comment by mhorowitz** [comment]
Our current implementation matches the ES6 spec, which allows the implementation a lot of flexibility.    But, ES9 is more strict, and requires output like the familiar form you show.

We'll work on updating our implementation, but until then, `(new Date).toLocaleString()` may give you something more friendly to your purpose.

**Comment by danilobuerger** [comment]
@mhorowitz The ES6 spec states:
> Return an implementation-dependent String value that represents tv as a date and time in the current time zone using a convenient, human-readable form.

A string in ISO 8601 isn't really a "convenient, human-readable form". So, arguably, this is not spec compliant.

**Comment by avp** [comment]
The ES9.0 compliant version of `Date.prototype.toString` was added in a38ec5fda7c0216576621ac7e2a8de23f56661ed.

**Comment by ljharb** [comment]
(ES2018; the edition number isn't used after ES6 / ES2015)
