### ISSUE TITLE
bug(chore): String.prototype.matchAll is undefined

### ISSUE THREAD

**Issue by Gregoirevda** [facebook/hermes#381]
## String.prototype.matchAll is undefined

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: hermes-engine@0.5.1
React Native version (if any): 0.63.2
Android version (if any): 10.0+ (API 30)
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86

## Steps To Reproduce
1. console.log(String.prototype.matchAll) // undefined

```js
const result = [..."aaa".matchAll(/A/g)];
```
Throws:
`Undefined is not a function`

## The Expected Behavior
I would expect `String.prototype.matchAll` to exist

**Comment by ljharb** [comment]
In the meantime, you can use https://npmjs.com/string.prototype.matchall.

**Comment by tmikov** [comment]
@Gregoirevda `String.prototype.matchAll()` was added in ES2020. We are gradually implementing features of newer spec, but we haven't fully caught up to ES2020 yet :-) So, we will get to it, but not sure when, especially if quality polyfills already exist.

**Comment by tmikov** [comment]
With that said, community contributions are welcome! :-)

**Comment by Huxpro** [comment]
@tmikov @Gregoirevda 

Actually, Hermes had implemented ES2020 `String.prototype.matchAll` and ES2021 `String.prototype.replaceAll` and released under [v0.6.0](https://github.com/facebook/hermes/releases/tag/v0.6.0). 

Once the RN0.64 is out, you can upgrade to Hermes v0.6 or v0.7 to use them natively ;)
