### ISSUE TITLE
A question about uninitialized variables

### ISSUE THREAD

**Issue by NWU-NISL** [facebook/hermes#387]
###### Description

When executing this test case, `a2` is not initialized before the call, other engines (such as v8, spiderMonkey, JavaScriptCore, etc.) threw a `ReferenceError`, but hermes did not do so. Is this a different implementation of hermes?

###### Version

[9caeabc](https://github.com/facebook/hermes/tree/9caeabc)

###### Test case

```js
var h = function f(a0 = function () {
  a2;
}(), a2) {
};
h();
```

###### Execution steps

```js
./build/bin/hermes -w testcase.js
```

###### Output

```

```

###### Expected behavior

```js
ReferenceError: can't access lexical declaration `a2' before initialization
```

**Comment by Huxpro** [comment]
@NWU-NISL Heeey thanks for reporting this!
It's a known issue and we are working on it ;)

**Comment by tmikov** [comment]
Already fixed in the next major release of Hermes.
