### ISSUE TITLE
Adding globalThis

### ISSUE THREAD

**Issue by benjamingr** [facebook/hermes#39]
Hey,

I want to try contributing some code to Hermes because it looks like a fun project and a lot more manageable to push code to than V8 (or other big engines).

globalThis is a new canonical way to access the global variable.

Do you have plans to support this (standard) feature and if so - would you be interested in a PR for this?

(I totally get if the answer is "no" because of scoping and I didn't see any other exposed glboal - even though it's standard JS)

**Comment by ljharb** [comment]
globalThis is the only standard JS global :-) the others are part of node or browsers.

**Comment by avp** [comment]
While `globalThis` isn't part of the standard yet (still in [Stage 3](https://tc39.es/proposal-global/#sec-other-properties-of-the-global-object-global) of the TC39 proposal process), it's already gained some amount of adoption and it seems reasonable to plan to add it to Hermes. We'll work on adding the property to the global object soon.

If you need access to the global object before `globalThis` is added to Hermes, you can use the Function constructor (which will be a little slower but should produce the correct output):
```js
let global = (new Function('return this'))();
```

**Comment by ljharb** [comment]
@avp it's shipping in every browser https://twitter.com/mathias/status/1151140681374547969 so the stage isn't really relevant; it'll be stage 4 relatively soon. Glad to hear you're adding it :-)

**Comment by dulinriley** [comment]
It’s a shame that `globalThis` is a property that is writable, if it was a keyword we could compile it to `GetGlobalObject` in HBC.

**Comment by ljharb** [comment]
@dulinriley see item 2: https://github.com/tc39/proposal-global/blob/master/NAMING.md#constraints

**Comment by avp** [comment]
d088f6f5fdfd56e0dd946dc53533462fd3505102 adds this.
