### ISSUE TITLE
How to increase call stack size

### ISSUE THREAD

**Issue by freddie-freeloader** [facebook/hermes#391]
## Problem

We switched from JSC to Hermes for our React Native app on Android.

Since publishing that change, we got a number of `RangeError: Call stack size exceeded` crash reports.

In the long run, we should fix these recursive calls but for now:

1. Is there a difference in default call stack size between JSC and Hermes?

2. I know that the call stack size of V8 can be adjusted with `--stack_size`. Is there a similar option for Hermes?

**Comment by tmikov** [comment]
What is the exact error message? Hermes doesn't contain an error message "Maximum call stack size exceeded".

**Comment by freddie-freeloader** [comment]
Hi!

Thank you for answer. :slightly_smiling_face: 

I am not quite sure how to clarify my issue. So, I am going to reiterate my main questions:

> - Is there a difference in default call stack size between JSC and Hermes?
> - I know that the call stack size of V8 can be adjusted with --stack_size. Is there a similar option for Hermes?

**Comment by tmikov** [comment]
Before we can try helping you, we need to at least know what error you are getting. As I already said, Hermes does *not* have an error message "Call stack size exceeded". Can you please provide the error message?

**Comment by freddie-freeloader** [comment]
Thank you for your patience!
I just realized that this error might be thrown by the React Call stack. AFAIK React does maintain its own call stack these days. :wink: 

I'll close this issue than. Thanks for the support!
