### ISSUE TITLE
Autorization header sent with a lower case name

### ISSUE THREAD

**Issue by zabojad** [facebook/hermes#397]
## Bug Description

My app sends  an Authorization header along with a POST XmlHttpRequest:

```js
var req = new XMLHttpRequest();

// ...

req.open('POST', 'https://...', true);

req.setRequestHeader('Authorization', 'Basic ...');

req.send(payload);
// ... 
```

On the server side, we receive the header with a lowercased name, ie: 'authorization: Basic ...'

- [-] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.5.1
React Native version (if any): 0.63.2
Android version (if any): 10
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86

## Steps To Reproduce

1. create a XMLHttpRequest
2. Set the Authorization header
3. Send it and check the case of the header name on the server side

code example:

```js
var req = new XMLHttpRequest();

req.open('POST', 'https://...', true);

req.setRequestHeader('Authorization', 'Basic ...');

req.send(null);
```

## The Expected Behavior

The case of the header names should not be changed.

**Comment by Huxpro** [comment]
Hi @zabojad, `XMLHttpRequest` is not part of JavaScript and it's something implemented by a *host environment* instead of a JS engine like Hermes. In this case, you might want to [ask for help from React Native](https://github.com/facebook/react-native/issues).
