### ISSUE TITLE
async await keywords silently fails

### ISSUE THREAD

**Issue by reimertz** [facebook/hermes#398]
We are using Storboard, we had a generic error "Uknown" but managed to pinpoint it to a [very specific use of `async` as key in an object](https://github.com/storybookjs/storybook/blob/next/lib/channel-websocket/src/index.ts#L78).

Once playing arounf with it; we managed to see that it had to do with a missing `,` 

**Working Example**

```
const hermesCriesWhenAsync = ({ async }) => ({
  async: async,
});

console.log(hermesCriesWhenAsync({async: true}))
```

**Breaking example**
```
const hermesCriesWhenAsync = ({ async }) => ({
  async: async // <= missing comma
});

console.log(hermesCriesWhenAsync({async: true}))
```

No idea how to move further here. Any ideas?

**Comment by avp** [comment]
Thanks for the report. Can you please explain what you mean by "silent fails" in this context? Do you mean that the `async` property is not being stored on the object?

I tried to reproduce any issues using the command line `hermes` tool on a recent build of Hermes, and I wasn't able to see anything wrong. Here's the code I ran:
```
const hermesCriesWhenAsync = ({ async }) => ({
  async: async
});

print(hermesCriesWhenAsync({async: true}).async) // print instead of console.log
```
The output was `true`, which is correct.

Are you sure this is the exact code being passed to Hermes? If Babel is being run on it, the code being sent to Hermes depends on the output of your configuration of Babel, which is important in the case of parser bugs. If you can find some code that doesn't work when fed directly to `hermes` on the CLI, that would be helpful.

Also, Which version of Hermes are you using?

**Comment by reimertz** [comment]
Oh, I am so sorry @avp - I did not mean _silent_ but a _generic_ error: "Unknown".. 

We are on Hermes 0.50.0.

Here is a screengrab how to reproduce it;

<img width="637" alt="bild" src="https://user-images.githubusercontent.com/625287/97210907-8c4cca80-17be-11eb-8d25-7b7e2e03b87a.png">

**Comment by reimertz** [comment]
By using yarn resolutions and setting the version to `0.5.1`, we seem to get it working! 
Is there another way to specify this version except from using resolutions?

**Comment by reimertz** [comment]
It seems this was discussed in https://github.com/facebook/hermes/issues/241 so feel free to close this if this is considered the same bug. :)

**Comment by Huxpro** [comment]
> Is there another way to specify this version except from using resolutions?

@reimertz I'm not sure why you want to override in the `"resolutions"` field if that's what you mean. 

As long as there isn't an explicit lock file, either `yarn` or `npm` would pick `hermes-engine@0.5.1` over `hermes-engine@0.5.0` since RN 0.63 is specified to allow patch update. 

If you do have a lock file, you can just `yarn upgrade hermes-engine` (or the `npm` equivalent) to update your lock file.

- <https://github.com/facebook/react-native/blame/6fa9dbabfc0fd502381161e5854318a8e8ff54a4/package.json#L100>
- <https://classic.yarnpkg.com/en/docs/dependency-versions/>
