### ISSUE TITLE
Optional chaining does not work on function calls

### ISSUE THREAD

**Issue by janicduplessis** [facebook/hermes#403]
## Bug Description

Optional chains on the return value of a function do not work properly.

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

I haven't tested with JSC since I'm not sure if it supports optional chaining, however the code does work with the babel transform enabled.

Hermes version: 0.7.1
React Native version (if any):
Android version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

Using this code:

```js
const returnsNull = () => null;
console.log(returnsNull()?.a.b.c);
```

It crashes with `Cannot read property 'b' of undefined`

## The Expected Behavior

Logs `undefined`

**Comment by ljharb** [comment]
This is expected; optional chaining only applies to that one property access. In other words, the `a` access is optional, but the b and c accesses aren’t, so they throw.

**Comment by janicduplessis** [comment]
@ljharb Shouldn't it bail out since the first access is null?

For example this works:

```js
const nullValue = null;
console.log(nullValue?.a.b.c);
```

**Comment by ljharb** [comment]
Ah, i see what you mean. Yes, it should :-)

**Comment by janicduplessis** [comment]
Yea my example was a bit confusing, I just tried to have the smallest code that repros. I more realistic case similar to what I had in my app is:

```js
const data = [{node: {a: 'a'}}];
const res = data.find(d => d.node.a === 'b')?.node.a;
```

Also just ran the code in chrome to confirm it works there.

**Comment by tmikov** [comment]
Just tried it. Works fine with trunk.

**Comment by tmikov** [comment]
Fixed here: https://github.com/facebook/hermes/commit/b61f164ceb8f5669c9800b281cbd6e11fd267b07
