### ISSUE TITLE
Running quit() on hermes repl does not quit repl

### ISSUE THREAD

**Issue by Naturalclar** [facebook/hermes#405]
## Bug Description

Calling `quit()` on hermes repl results in a following error:

```
Uncaught QuitError: Quit
    at quit (native)
    at global (JavaScript:1:5)
    at eval (native)
    at evaluateLine (JavaScript:1:6328)
```

Is this behavior expected?

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.7.1
React Native version (if any): n/a
Android version (if any): n/a
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

1. Perform a release build 

```sh
utils/build/configure.py --distribute
cd build_release && ninja
```

2. Run hermes repl

```sh
cd bin
hermes
```

3. Run `quit()` in repl

code example:

## The Expected Behavior
quit() runs successfully, existing out of hermes repl

**Comment by tmikov** [comment]
quit() throws an "uncatchable" exception. Arguably, there is utility in seeing the exception in the REPL. What is the use case for this?

**Comment by Naturalclar** [comment]
@tmikov Thanks for the information! It just seemed natural to me for `quit()` to terminate the repl, but there are other ways to exit out of the repl, and I agree that verifying `quit()` throwing an uncatchable exception is useful for testing purposes.
I'll close the issue.

**Comment by tmikov** [comment]
We have discussed it internally and we are ok with either behavior. If you submit a PR for it, we are happy to review it.
