### ISSUE TITLE
macOS CI tests are failing due to Xcode version

### ISSUE THREAD

**Issue by mhorowitz** [facebook/hermes#411]
## Bug Description

Two macOS-related CI failures:
https://app.circleci.com/pipelines/github/facebook/hermes/1655/workflows/9ea6c655-b00c-467f-91f2-13007d482b33/jobs/12356
https://app.circleci.com/pipelines/github/facebook/hermes/1655/workflows/9ea6c655-b00c-467f-91f2-13007d482b33/jobs/12355

The error is
> failed to create host: Image xcode:12.0.0-beta is not supported

This appears related to the fix for #355 .

**Comment by neildhar** [comment]
Fixed in a5cecca83f074dd78ed13e3eb90e6c200b4277e3
