### ISSUE TITLE
configure.py fails for Emscripten

### ISSUE THREAD

**Issue by gfx** [facebook/hermes#421]
## Bug Description

I am trying to build Hermes with Emscripten, but I cannot finish even the configure.py.

https://github.com/facebook/hermes/blob/master/doc/Emscripten.md suggests I can use `configure.py`, but what I seen is something like this:

```
$ python3 $PWD/utils/build/configure.py \
    --distribute \
    --wasm \
    --emscripten-platform=upstream \
    --emscripten-root="$EMSDK/upstream/emscripten" \
    $PWD/tmp/embuild
...
CMake Error at lib/InternalBytecode/CMakeLists.txt:11 (include):
  include could not find load file:

    IMPORTFILE-NOTFOUND
...
```

It seems `IMPORT_HERMESC` is missing in including `lib/InternalBytecode/CMakeLists.txt`.

Hermes version: 92b4013ec5a6623430a2c43a14b197b428060636 (latest as of Nov 21, 2020)
React Native version (if any): N/A
Android version (if any): N/A
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): wasm (build platform: macOS 10.15.7)

## Steps To Reproduce

Described in the description section.

## The Expected Behavior

Configure.py and build success.

**Comment by tmikov** [comment]
Hermes now requires a two stage build because it contains bytecode which needs to be compiled by Hermes... I guess we haven't updated configure.py and instructions for cross compilation instructions yet. 

You need to have a native host build of Hermes first, and it will create a file called `ImportHermesc.cmake` in its build directory.

Then follow the steps here https://github.com/facebook/hermes/blob/master/doc/Emscripten.md#build-with-cmake-directly and additionally pass `-DIMPORT_HERMESC=` initializing it with the absolute path to `ImportHermesc.cmake` above. That should hopefully work.

**Comment by gfx** [comment]
@tmikov 

Thank you! `cmake` passes!

However, `make` failed because some symbols seem missing:

```
cmake .. \
    -DCMAKE_BUILD_TYPE=Release  \
    -DEMSCRIPTEN_FASTCOMP=0 \
    -DCMAKE_EXE_LINKER_FLAGS="-s NODERAWFS=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s LLD_REPORT_UNDEFINED=1" \
    -DCMAKE_TOOLCHAIN_FILE="$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
    -DIMPORT_HERMESC=../build/ImportHermesc.cmake
...
wasm-ld: error: symbol exported via --export not found: __cxa_is_pointer_type
wasm-ld: error: symbol exported via --export not found: __cxa_can_catch
```

emcc is:

```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement) 2.0.9 (59aedd441c317b7064146d4d888eab272e92dd03)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tmikov** [comment]
I think you are trying to build everything and it is failing (many of the the tools like hdb are not expected to work with Emscripten). What happens if you only do `make hermesc`, `make hermes`, or `make emhermesc`.

**Comment by gfx** [comment]
Thanks!

* [x] `make hermesc`
* [x] `make hermes`
* [x] `make emhermesc`

The three are okay. So `hdb` is unnecessary?

**Comment by tmikov** [comment]
Right. Hdb is the Hermes Debugger command line frontend and it can't be compiled to Wasm. The only targets that are supposed to work are the ones I mentioned above.

**Comment by gfx** [comment]
Nice. Thank you! BTW what do you think to add a CI environment for Emscripten (only builds, not tests)?  I'm willing to add it.

**Comment by tmikov** [comment]
@gfx I think that would be great! Frankly, I am not very familiar with our CI on Github, will you be able to test it, see the errors, etc, while working on it?

**Comment by gfx** [comment]
@tmikov Not sure, but anyone can run a circleci job locally with `circleci` CLI.

**Comment by Huxpro** [comment]
Closed by https://github.com/facebook/hermes/pull/423 and b0e544ed665a03098f3633de1499762302d10b7a
