### ISSUE TITLE
Sort large array will cause app freeze and throw a crash libc.so

### ISSUE THREAD

**Issue by kyunkakata** [facebook/hermes#424]
## Bug Description

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any): v0.63.2
Android version (if any): all version
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): all platform.

## Steps To Reproduce
```js
let arr = [];
for(let i = 0; i < 3000; ++i){
  arr.push({x: Math.floor(Math.random() * 10000)});
}
arr.sort((a,b)=> a.x > b.x ? 1 : -1);
```

1. Production build with hermes cause app to freeze call invoke Array.sort and throw libc.so to Crashlytics

## The Expected Behavior
-- Normal sort behavior
Using js-lodash sort resolve problem. But native C (through Hermes) makes the app Unable to respond.
```js
let arr = [];
for(let i = 0; i < 3000; ++i){
  arr.push({x: Math.floor(Math.random() * 10000)});
}
arr = lodash.orderBy(arr, 'x', 'asc');
```

**Comment by tmikov** [comment]
I could not reproduce this with the current Hermes master. It seems related to a bug we fixed some time ago.

I must however point out that your comparison function is incorrect - it never returns "0". I bet that fixing the comparison function would resolve the problem in older versions of Hermes.
