### ISSUE TITLE
[Website] missing normalize.css

### ISSUE THREAD

**Issue by Huxpro** [facebook/hermes#432]
## Description

The website is requesting `normalize.css` from `https://hermesengine.dev/Users/jsx/github/hermes/website/node_modules/normalize.css/normalize.css`, which seems to be based on whoever built and deployed the website to production. 

This same issue repros if you build the site locally.

This path seems to come from

```
stylesheets: [
  require.resolve('./node_modules/normalize.css/normalize.css'),
],
```

in `hermes/website/docusaurus.config.js`

**Comment by Huxpro** [comment]
The `stylesheets` option in `docusaurus.config.js` is only for external stylesheets. To include stylesheets installed via npm, one would have to create a plugin and use the `getClientModules()` lifecycle method which is too much hassle and I'd rather just copy the css under `/static`.

But I worried that css from /static is not hashed (though it might not be changed often).

**Comment by Huxpro** [comment]
Alternatively, find a CDN version of the CSS

**Comment by slorber** [comment]
Hi,

We have a "clientModules" available in config now:
https://v2.docusaurus.io/docs/docusaurus.config.js/#clientmodules

Also, you can create a local plugin quite easily:
https://v2.docusaurus.io/docs/using-plugins#creating-plugins

**Comment by Huxpro** [comment]
@slorber thanks for jumping in to help! 
The `clientModules` looks exactly like what we want. I will try it late today 🤩
