### ISSUE TITLE
error: no member named 'makeHandleInParentScope' in 'hermes::vm::Runtime'

### ISSUE THREAD

**Issue by yurivict** [facebook/hermes#436]
```
usr/ports/lang/hermes/work/hermes-0.7.2/lib/VM/JSProxy.cpp:69:19: error: no member named 'makeHandleInParentScope' in 'hermes::vm::Runtime'
  return runtime->makeHandleInParentScope<Callable>(std::move(trapVal->get()));
         ~~~~~~~  ^
/usr/ports/lang/hermes/work/hermes-0.7.2/lib/VM/JSProxy.cpp:69:43: error: 'Callable' does not refer to a value
  return runtime->makeHandleInParentScope<Callable>(std::move(trapVal->get()));
                                          ^
/usr/ports/lang/hermes/work/hermes-0.7.2/include/hermes/VM/Callable.h:136:7: note: declared here
class Callable : public JSObject {
      ^
2 errors generated.
```

Version: 0.7.2
clang-10

**Comment by mhorowitz** [comment]
It looks like the release tag wasn't updated to include a final cherry pick.  If you build ae3597e33633bbe13298db308c6062c94a9236a9 it should work.  I'll see about getting the tag fixed.

**Comment by yurivict** [comment]
The latest commit also fails: https://github.com/facebook/hermes/issues/388

This patch makes it build:
```
--- external/llvh/CMakeLists.txt.orig   2020-12-17 03:26:48 UTC
+++ external/llvh/CMakeLists.txt
@@ -27,4 +27,4 @@ add_subdirectory(lib)
 add_subdirectory(utils/FileCheck)
 add_subdirectory(utils/not)
 add_subdirectory(utils/count)
-add_subdirectory(utils/unittest)
+#add_subdirectory(utils/unittest)
```

But tests still fail:
```
ld: error: unable to find library -lgtest_main
ld: error: unable to find library -lgtest
```

It would be best to use external gtest.

**Comment by mhorowitz** [comment]
As discussed in https://github.com/facebook/hermes/issues/347#issuecomment-692854270, the Hermes team doesn't have the resources to support FreeBSD.  However, we would welcome PRs with fixes for any issues found there.

**Comment by yurivict** [comment]
@mhorowitz What led you to think that this has something to do with FreeBSD?

**Comment by mhorowitz** [comment]
The previous five PRs you've submitted were all FreeBSD.  I don't believe this is an all-platforms bug, as our CI tests are passing (except for one which is not related to this).

If the problem is not on FreeBSD, can you post what OS and CPU you are building for, and how to repro the failure. Thanks!

**Comment by yurivict** [comment]
There are 2 problems:
* utils/unittest is unconditionally built when tests aren't enabled
* It fails to find the installed gtest library during cmake, despite ```pkg-config``` finding ```gtest_main``` fine.

Both problems seem to have nothing to do with FreeBSD. They are rather general coding defects.

**Comment by mhorowitz** [comment]
Can you please give instructions to reproduce?  The tests pass on Linux, MacOS, and Windows, so reproduction instructions would help.

**Comment by yurivict** [comment]
From my description, cmake scripts don't use pkg-config to find ```gtest_main```. Despite that failure, it still works on some platforms, but this doesn't mean that there is no problem. ```gtest_main``` should be found and discovered paths used.

**Comment by tmikov** [comment]
@yurivict gtest is [included with Hermes](https://github.com/facebook/hermes/tree/master/external/llvh/utils/unittest/googletest), so cmake should not be using pkg-config to find it.

**Comment by Huxpro** [comment]
As for the tagging issue. I've updated the tag v0.7.2 to include the final cherry-pick ;)
