### ISSUE TITLE
jsi CMakeLists.txt should set compile flags with PRIVATE scope 

### ISSUE THREAD

**Issue by JoshMarler** [facebook/hermes#448]
https://github.com/facebook/hermes/blob/e9ed52ceb7077b53f8b5cb95ae148f126a81bae1/API/jsi/jsi/CMakeLists.txt#L27

I'm working on a project which includes the libhermes target via cmake using `add_subdirectory` and links to `libhermes`. We have `.c` files in our project and the build errors out due to `-wno-non-virtual-dtor` being absorbed from the jsi lib target. I think these flag should be specified as `PRIVATE` ideally?

**Comment by dulinriley** [comment]
Thanks for pointing this out, we should probably separate warning flags as private.
I'll check which of our flags should be public/private/interface, and put up a commit fixing it

**Comment by JoshMarler** [comment]
Awesome thanks @dulinriley. That was the only flag which causes issues when linking against libhermes. No further issues after that.
