### ISSUE TITLE
Failed to transform hermes-release.aar to match attributes {artifactType=android-manifest}

### ISSUE THREAD

**Issue by deepakverma4** [facebook/hermes#449]
## Bug Description

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:0.4.1
React Native version (if any):0.62.2
OS version (if any):macos 11.2
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): (8) arm64 Apple M1

## Steps To Reproduce

1. run ```./gradlew app:assembleRelease```
 ``` What went wrong:
Execution failed for task ':app:preReleaseBuild'.
> Could not resolve all files for configuration ':app:releaseCompileClasspath'.
   > Failed to transform hermes-release.aar to match attributes {artifactType=android-manifest}.
      > Execution failed for JetifyTransform: /Users/igesia/work/mobile/igesia-mobile-app/node_modules/hermes-engine/android/hermes-release.aar.
         > Failed to transform '/Users/igesia/work/mobile/igesia-mobile-app/node_modules/hermes-engine/android/hermes-release.aar' using Jetifier. Reason: Unexpected end of ZLIB input stream. (Run with --stacktrace for more details.)```

code example:

## The Expected Behavior

it should generate apk

**Comment by Huxpro** [comment]
@deepakverma4 thanks for reporting this. 

It's not clear to me where the issue could be. The error says "(Run with --stacktrace for more details.)". Could you try to run that to help us investigate?

**Comment by CHANDRAMOHANnegi** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform hermes-debug.aar to match attributes {artifactType=android-databinding}.
      > Execution failed for JetifyTransform: /Users/a/b/abc/node_modules/hermes-engine/android/hermes-debug.aar.
         > Transform's input file does not exist: /Users/a/b/abc/node_modules/hermes-engine/android/hermes-debug.aar. (See https://issuetracker.google.com/issues/158753935)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
**After upgrading to react-native:0.68.5 , i enabled hermes, using PNPM**

**Comment by neildhar** [comment]
@CHANDRAMOHANnegi  This seems to be a build issue with React Native where it is unable to find Hermes, could you open an issue on the RN repo? You may also want to try upgrading to RN 0.69 which bundles Hermes differently.

Closing this issue since it isn't a problem in Hermes.
