### ISSUE TITLE
Hermes crashes on attempt to emit binary to the same destination

### ISSUE THREAD

**Issue by noomorph** [facebook/hermes#45]
**UPD:** The bug looks Linux-specific.

### Steps to reproduce

1. Download latest release: https://github.com/facebook/hermes/releases/download/v0.1.0/hermes-cli-linux-v0.1.0.tar.gz
2. Change directory to the one with the unpacked `hermes` binary.
3. Download the attached bundle: https://gist.githubusercontent.com/noomorph/db28b07f10d822e58af10f0276eac5b7/raw/2ec64da516295db823fa0aee327f7fa3221e51bf/index.android.bundle
4. Run:
```bash
hermes -emit-binary -out index.android.bundle index.android.bundle -O -w
```

### Expected result

The original bundle file should be replaced with the emitted binary.

### Actual result

Crash:

```
Stack dump:
0.      Program arguments: /home/x/Projects/hermesvm/10/hermes --emit-binary -out index.android.bundle index.android.bundle -O -w
1.      Program arguments: /home/x/Projects/hermesvm/10/hermes --emit-binary -out index.android.bundle index.android.bundle -O -w
[0x41ba83]
[0x41abc9]
[0x41ac6c]
[0x4265e0]
[0x499f43]
[0x49a163]
[0x43d7ff]
[0x43d967]
[0x44003a]
[0x4399b2]
[0x439b32]
[0x42b8b9]
[0x4308d6]
[0x40487b]
[0x712f34]
[0x7131b1]
[0x408116]
[0x41ba83]
[0x41abc9]
[0x41ac6c]
[0x4265e0]
[0x499f43]
[0x49a163]
[0x43d7ff]
[0x43d967]
[0x44003a]
[0x4399b2]
[0x439b32]
[0x42b8b9]
[0x4308d6]
[0x40487b]
[0x712f34]
[0x7131b1]
[0x408116]
Bus error (core dumped)
```

### Environment

* Ubuntu 18.04.2 LTS (4.15.0-54-generic)

**Comment by willholen** [comment]
hermes-engine 0.1.1 is out with mhorowitz's fix
