### ISSUE TITLE
A possible performance problem related to frequent memory allocation

### ISSUE THREAD

**Issue by YaoHouyou** [facebook/hermes#463]
#### Description 

Repeatedly assigning a value to an index with a large value in the array will cause the execution time of Hermes engine to be much longer than the execution time of other engines.

#### Version

b6530ae

#### Testcase

```javascript
var NISLFuzzingFunc = function () {
    var arr2 = [1];
    arr2[500000] = 'X';
};
for (var INDEX = 0; INDEX < 1000; INDEX++) {
    NISLFuzzingFunc();
}
```
#### Command:
```
build_release/bin/hermes -w testcase.js
```

#### Execution time

```
hermes:  1109ms
JerryScript: 12ms 
duktape: 16ms 
quickJS:  12ms
MuJS:  13ms
```

#### Build step

```
hermes/utils/build/configure.py --distribute
cd build_release && ninja
```

#### CPU

```
Intel(R) Core(TM) i9-9940X CPU @ 3.30GHzz
```

**Comment by dulinriley** [comment]
This is an optimization that we are aware of and we've already implemented called a "sparse" array, one that acts more like a dictionary than a dense linear array.
The way we detect this is with a "shift limit" constant when you do `arr[x] = y` and `x` is very far outside of the
current range. See this line in JSArray.cpp:
https://github.com/facebook/hermes/blob/7a02fc67b33182b0b3c490f440ccaa1bb0215f12/lib/VM/JSArray.cpp#L251

So currently that limit is `1048576`. If you change your example to be:
```
var NISLFuzzingFunc = function () {
    var arr2 = [1];
    arr2[1048576 + 2] = 'X';
};
for (var INDEX = 0; INDEX < 1000; INDEX++) {
    NISLFuzzingFunc();
}
```
You'll notice it should speed up quite a bit.

It's hard to always pick a perfect limit here, as if we pick 500,000 as the limit, then you could
open up an issue saying `arr[499999]` is too slow.

I confirmed that lowering the shiftLimit constant in the code speeds the example up significantly.

**Comment by dulinriley** [comment]
@tmikov what number do you think is right for the shift limit?
My intuition on this feels like we should find the point at which filling out the array to X slots becomes
noticeably slower (let's say 1.5x slower) than filling in the slot sparsely.

For example, if the code was:
```
var arr = [1];
arr[10000 + 1] = 'X';
```
vs `arr[10000 + 2]` and the shift limit is 10,000, running that 1000 times shows a difference of 8 seconds
to 0.07 seconds (in debug mode). So it seems like 10,000 has some definite cost that is worth mitigating.

**Comment by tmikov** [comment]
@dulinriley We can't just look at the cost of initializing the array, we also have to consider the cost of accessing it.

**Comment by tmikov** [comment]
My position is that while it can be interesting to look at such things in isolation, any decisions should be made in the context of actual working code that is exhibiting a performance problem. If the array is that spare, does the code really need an array?

**Comment by dulinriley** [comment]
@YaoHouyou we're going to close this issue because it's a synthetic example. If you (or anyone else) is seeing this issue having a large impact on their usage of Hermes, we can take another look at changing the behavior.
