### ISSUE TITLE
Invalid Statement encountered. js enginer: hermes

### ISSUE THREAD

**Issue by simistern** [facebook/hermes#474]
## Bug Description

```
ERROR    SyntaxError: 4:1:invalid statement encountered., js engine: hermes
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
```

- [X] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: `0.5.2-rc1`
React Native version (if any):  `0.63.4`
OS version (if any): * but currently testing on Catalina 10.15.7 
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

1. This code resides in a monorepo orchestrated with Lerna so it could be part of the issue
2. Mobile codebase resides at `./consumer-mobile/mobile/`
3. change build.gradle file as follows:
```
    if (enableHermes) {
        def hermesPath = "../../../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
```
and 
```
project.ext.react = [
    entryFile: "mobile/consumer-mobile/index.js",
    root: "../../../../",
    enableHermes: true,  // clean and rebuild if changing,
    hermesCommand: "../../../../node_modules/hermes-engine/%OS-BIN%/hermesc",
]
```
and 
```
def enableHermes = project.ext.react.get("enableHermes", true);
```

## The Expected Behavior
App compiles and builds with Hermes engine

**Comment by Huxpro** [comment]
@simistern Emm, I'm not sure I understand.

Since it complained 

```
SyntaxError: 4:1:invalid statement encountered., js engine: hermes
```

Could you at least tell us what is there?

**Comment by simistern** [comment]
Sorry, I will do my best to clarify the issue. 
Do you mean the javascript source code being compiled from the react native side? There was no mention of hermes in the source code. The only changes were to our build.gradle file to enable hermes. 

Is it possible that this line ```hermesCommand: "../../../../node_modules/hermes-engine/%OS-BIN%/hermesc"``` could perhaps fail with that error, based on an incorrect hermes binary being referenced? Do you know of any way I can test these gradle paths? I am newish at android development so this is a bit of a black box for me at the moment :)

**Comment by Huxpro** [comment]
@simistern 

> Do you mean the javascript source code being compiled from the react native side? 

yeah, I meant the JavaScript source code in the line 4 where the SyntaxError complained. 

> The only changes were to our build.gradle file to enable hermes.

Note that Hermes has different [language feature supports](https://hermesengine.dev/docs/language-features) with JSC.

**Comment by Huxpro** [comment]
@simistern Our guess is that either `eval()` or `new Function()` is being invoked at runtime and there is a syntax error in the string that being passed in, and Hermes throws an exception as it should. JSC might be working because it support more syntactical feature than Hermes.

**Comment by simistern** [comment]
I am trying to find a way to locate the stack trace through metro bundler but haven't been able to isolate it. 
Running the app in debug mode allows it to properly function, but global.HermesInternal is `undefined` .  

Do you have any recommendations for how I would find that stack trace, or isolate the `eval()` or `new Function()`? We have neither of those in our codebase but they could be in node_modules. 

Is there android tooling which can perhaps tell me if gradle is able to locate the package correctly?

**Comment by Huxpro** [comment]
>  global.HermesInternal is undefined .

If `global.HermesInternal` is undefined then you were **NOT** actually on Hermes. However, it might be a false negative if you were using the old remote debugging instead of the proper debugging setup as documented [here](https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools).

It might be better to ask the metro stack trace and gradle questions to RN.

**Comment by NicholasIoanJones** [comment]
same issue encountered here. Just trying to turn on Hermes to speed up slow Android start up in RN.

**Comment by marf** [comment]
We have the exact same problem here: 

`SyntaxError: 4:1:invalid statement encountered., js engine: hermes`

Any luck in finding the issue?

Thank you

**Comment by TacticCoder** [comment]
Upgraded from 0.64.2 to 0.65.2 with enabling Hermes. same for me.

**Comment by mhurali-folio** [comment]
I am facing a similar issue with hermes enabled. Have a look at following:

console.log(eval(`(1+1)`)) --> This Works
console.log(eval('(class abc{})')) --> This throws error invalid expression at 1:2

**Comment by tmikov** [comment]
@mhurali-folio You are using an unsupported language feature inside the eval(). See https://github.com/facebook/hermes/blob/main/doc/Features.md#in-progress .

**Comment by guptaprnv** [comment]
I am also facing the same issue when using template function of lodash which is calling new Function() method in hermes, is there any other method which we can use instead of template function.

**Comment by IlliaPruskyi** [comment]
@guptaprnv, Did you find any solution?

**Comment by exzos28** [comment]
any updates?

**Comment by tmikov** [comment]
Closing, since no actionable information has been provided. Hermes does not yet support "local eval", though support has been planned for a future version.
