### ISSUE TITLE
2 tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [facebook/hermes#477]
## Bug Description

Log: https://people.freebsd.org/~yuri/hermes-test-failure-0.7.2.20210322.log

```
  Expected Passes    : 1422
  Unsupported Tests  : 56
  Unresolved Tests   : 12
  Unexpected Failures: 2
```

Also, what does "Unresolved Tests" mean?

**Comment by avp** [comment]
Unresolved tests are explained in the LIT docs: https://llvm.org/docs/CommandGuide/lit.html#test-status-results

Closing this for now because we can't provide direct support for FreeBSD, but PRs from the community are welcome.
