### ISSUE TITLE
How to open a debug session/connection with Hermes API ?

### ISSUE THREAD

**Issue by JoshMarler** [facebook/hermes#486]
## Problem

We've recently integrated the hermes library over at `react-juce`: https://github.com/nick-thompson/react-juce/blob/master/react_juce/core/EcmascriptEngine_Hermes.cpp

`react-juce` provides an abstract `EcmascriptEngine` type with a few different impls for Duktape and Hermes etc. 

We provide a `EcmascriptEngine::debuggerAttach` call for users which launches a debug session and awaits attach from some debug client, i.e. vscode, chrome debugger etc. 

Duktape provides a fairly simple route in for this which opens up a tcp connection ready for any client implementing the Duktape debug protocool:

https://github.com/nick-thompson/react-juce/blob/master/react_juce/core/EcmascriptEngine_Duktape.cpp#L373

Would anyone be able to point me in the right direction for implementing such functionality with the hermes api/Debugger? 

I'm currently searching through sources trying to find some insight into how I might use the Hermes Debugger object to open up a debug session on some port for the chrome debugger similar to the experience provided by React Native. The solution isn't jumping out at me!

Is this essentially a case of needing to implement the debug APIs in a similar fashion to the `hdb` tool so that our `EcmascriptEngine` class may act as a debug host/proxy ?

Thanks

**Comment by neildhar** [comment]
Hi @JoshMarler, for your reference, RN's Hermes chrome debugger integration is implemented [here](https://github.com/facebook/react-native/tree/master/ReactCommon/hermes/inspector/chrome). As you suggest, you'll need to parse the requests coming in over the network and plumb them through to the lower level `DebuggerAPI` we expose, like the `hdb` tool.

**Comment by JoshMarler** [comment]
Excellent, thanks for the info @neildhar
