### ISSUE TITLE
iOS hermes_enable = true, ipa size increases a lot 

### ISSUE THREAD

**Issue by CoderYLZhang** [facebook/hermes#499]
## Bug Description

- [ ] iOS hermes_enable = true, ipa size increases a lot 
![image](https://user-images.githubusercontent.com/13221319/115347126-9b4b8d00-a1e3-11eb-8adf-6275d3a7b828.png)

Check out the IPA content to see that the increase in size comes mainly from hermes
![image](https://user-images.githubusercontent.com/13221319/115347706-5116db80-a1e4-11eb-8465-36f4f9337b5a.png)

hermes macho:
![image](https://user-images.githubusercontent.com/13221319/115347479-05fcc880-a1e4-11eb-9c87-8f032d7aa88c.png)

Hermes version: 0.72
React Native version (if any): 0.64.0
OS version (if any): OS: macOS 11.2.3
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): iOS 14

## Steps To Reproduce

1.
2.

code example:

## The Expected Behavior

Will it be optimized in the future 
Or what I can do for it

**Comment by tmikov** [comment]
Is that an uncompressed size of 400MB?? Wow.

**Comment by drash-course** [comment]
I have the same issue, my app went from 76.4 MB (Hermes disabled) to 942.1 MB (Hermes enabled). A few megabytes of size increase is OK but it looks like something is wrong here. How can Hermes + bytecode weight almost 900 MB?

**Comment by alloy** [comment]
The LLVM segment of a Mach-O binary contains LLVM bitcode (for details, see e.g. [this article](https://jonasdevlieghere.com/embedded-bitcode/)). Bitcode is big on disk but is not sent to the end-user’s device. In fact it was introduced partially to allow an end-user to _only_ install the architecture their device needs and thus reduce IPA size, this is what Apple refers to as ‘slicing’. You can find details on the process in [this article](https://ankur-s20.medium.com/implementing-app-thinning-in-your-project-step-by-step-tutorial-ios-app-b3cfd139896d), which also explains how to verify the IPAs that the end-user will get.

The important question here is thus not if the IPA you submit to the App Store has increased size, but if the resulting IPAs that the end-user will get have only increased in the few MB size that would be expected by enabling Hermes. Can you check that?

**Comment by CoderYLZhang** [comment]
@alloy Thank you, I'll test what you said 
Besides, I have one more question
After upgrading to 0.64 Xcode build once again does not work. Here are all "Not found" and "Could not build" errors:
```
'exception' file not found
'memory' file not found
'functional' file not found
Could not build module 'React'

#include <memory>
#import <React/RCTEventDispatcher.h>
#import <React/RCTEventEmitter.h>
etc.
```
https://github.com/facebook/react-native/issues/31303

**Comment by f4z3k4s** [comment]
Hi!

Just ran into this:

App size with `hermes_enabled => false`: 113.4mb
App size with `hermes_enabled => true`:  540.19mb

These sizes are measured by iOS on the device itself, when going to `Settings > General > iPhone storage` and checking my app's size.

I do not think that this is intentional. Or is it?

Please let me know if I can provide any necessary information.

**Comment by jmeistrich** [comment]
I am seeing my built ipa at 423 MB. Uncompressing the ipa, the app inside the Payload folder is 1.11 GB with 112 MB being libSwift* things and Framework/hermes.framework/hermes is 844 MB by itself. And the executable in the cocoapod at Pods/hermes-engine/destroot/Library/Frameworks/iphoneos/hermes.framework/hermes is 1.26 GB.

That seems like it's probably much bigger than it needs to be?

But App Store Connect shows the Universal app size as 22.6MB with iPhone 12 only 6MB. So the install size is great. It's just troublesome to have to upload 423 MB for every app update.

This is on RN 0.64.1 with Hermes 0.7.2.

**Comment by nadimahamad** [comment]
Following solution for hermes enabled and RN 0.64.2.
1.Need to do bitcode enabled - Yes at Build setting tab in xcode.
2.Need to choose deployment target version above ios 13.1
Then once do clean & build and then archive. your .ipa file size will be reduce.

**Comment by johnpanos** [comment]
> Following solution for hermes enabled and RN 0.64.2. 1.Need to do bitcode enabled - Yes at Build setting tab in xcode. 2.Need to choose deployment target version above ios 13.1 Then once do clean & build and then archive. your .ipa file size will be reduce.

This still doesn't work for me. App is still around ~500mb on device built using the release scheme.

**Comment by chrisnojima** [comment]
note xcode 14 deprecates bitcode: https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

**Comment by anhnch** [comment]
I was shocked at first
**587MB** On the phone with debug/release build

But the archive size is much better
**20.7MB** archived without hermes
**23.6MB** archived with hermes and "rebuild from bitcode" unchecked
**16.1MB** archived with hermes and "rebuild from bitcode" checked 

Performance is great!

**Comment by arcln** [comment]
I used the following "run script phase" to strip the bitcode from hermes framework (to be put after all others).

```bash
BITCODE_STRIP="$(xcrun -sdk iphoneos --find bitcode_strip)"

function strip_framework_bitcode {
    FRAMEWORK="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Frameworks/$1.framework/$1"
    "${BITCODE_STRIP}" -r "${FRAMEWORK}" -o "${FRAMEWORK}" 
}

strip_framework_bitcode "hermes"
```

This reduces the .framework size to a few megabytes and can be useful for reducing artifact storage costs.

**Comment by wilsonWangYJ** [comment]
> I was shocked at first **587MB** On the phone with debug/release build
> 
> But the archive size is much better **20.7MB** archived without hermes **23.6MB** archived with hermes and "rebuild from bitcode" unchecked **16.1MB** archived with hermes and "rebuild from bitcode" checked
> 
> Performance is great!



> I was shocked at first **587MB** On the phone with debug/release build
> 
> But the archive size is much better **20.7MB** archived without hermes **23.6MB** archived with hermes and "rebuild from bitcode" unchecked **16.1MB** archived with hermes and "rebuild from bitcode" checked
> 
> Performance is great!

Is this data you uploaded to the appstore and saw? It is still very large when it is directly archive .app

**Comment by tmikov** [comment]
This has been resolved in latest version that build without bitcode.
