### ISSUE TITLE
Bundle Format Spec

### ISSUE THREAD

**Issue by HazAT** [facebook/hermes#51]
Hello :)

I work for Sentry, we do crash reporting and therefore we are very interested in the bundle format / source maps.
We recently added support for ram bundles which had its own binary format and it seems that hermes has yet another format.

Can you point us towards some docs/specs/source so we can start implementing support for hermes bundles?

**Comment by mhorowitz** [comment]
Hi!  There aren't docs, but I can point you to some source code to get you started.  First, I should point out that the bytecode file format is not intended to be fixed long-term.  We update it pretty often, so you should expect to need regular incremental changes.

The overall format of the bytecode file is defined in the serializer/deserializer code.  It's driven by a [visitor here](https://github.com/facebook/hermes/blob/d088f6f5fdfd56e0dd946dc53533462fd3505102/include/hermes/BCGen/HBC/BytecodeFileFormat.h#L373-L389).  This header defines a magic number and the bytecode version, which your tool can use to recognize Hermes bytecode files, and the specific format of each file.  The implementations are in [BytecodeStream.cpp](https://github.com/facebook/hermes/blob/a311b71ce1333c1c7ee1454b0639ab7289a07514/lib/BCGen/HBC/BytecodeStream.cpp).  The bytecodes themselves are defined in [BytecodeList.def](https://github.com/facebook/hermes/blob/d088f6f5fdfd56e0dd946dc53533462fd3505102/include/hermes/BCGen/HBC/BytecodeList.def).

We also have some tooling to dump bytecode files which might help.  If you have a bytecode file, you can run
```
bin/hermes -dump-bytecode myfile.hbc
```
to see various data about the file.  This was intended for humans, not automated systems, so I wouldn't depend on parsing the output, but it might help you writing your own tool.

The source maps are in the conventional format; we're not doing anything special there.
