### ISSUE TITLE
Cannot take heap snapshot in DevTools memory profiler: stuck at "Snapshotting..." after recording (RN 0.64)

### ISSUE THREAD

**Issue by jaydgoss** [facebook/hermes#512]
## Bug Description
Reopening https://github.com/facebook/hermes/issues/301 for RN 0.64

![image](https://user-images.githubusercontent.com/6308575/118265160-c5146e80-b486-11eb-9835-0b6d553b5767.png)
There are no errors in the console and the app is fully responsive. The console is working too.

Chrome version: 89.0.4389.114
Hermes version: 0.7.2
React Native version (if any): 0.64
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

**Comment by neildhar** [comment]
Just to confirm, you're seeing this issue for the allocation timeline profiler and not the heap snapshot right?

I'm able to repro the issue with the allocation timeline profiler, and can verify that it is fixed with 38576cb971859a532241d13573c4a0675c9bc471 (which will be in RN 0.8).

**Comment by jaydgoss** [comment]
@neildhar That's true, the issue was occurring for allocation timeline & allocation sampling, heap snapshot looks like it's working as expected.

Thanks for the info, I'll try with 0.8.

**Comment by Venryx** [comment]
Oddly, I'm having a similar issue with just using Chrome's memory snapshot tools (any of the three) to do profiling of a remote NodeJS instance running in my Kubernetes cluster.

(This is unrelated to the hermes library; I'm only mentioning it here so my name shows up in search results for this issue, months later when I try googling for it again. ^_^)
