### ISSUE TITLE
Generators support

### ISSUE THREAD

**Issue by noomorph** [facebook/hermes#52]
The documentation claims that generators are supported in Hermes, as well as for-of loops:
 
https://github.com/facebook/hermes/blob/9cf7a40f33b3c56e7cba1afd4890437a86e5343d/doc/Features.md#L5-L12

Consider this gist: https://gist.github.com/noomorph/f9272f1a3f4a9d1f419c2e8dadfb5fe2

As for [for-of.js](https://gist.github.com/noomorph/f9272f1a3f4a9d1f419c2e8dadfb5fe2#file-for-of-js), the command below runs successfully, thereby confirming built-in support for that construct:

```bash
> ./hermes for-of.js
0
1
2
```

As for [generator.js](https://gist.github.com/noomorph/f9272f1a3f4a9d1f419c2e8dadfb5fe2#file-generator-js), a similar command would fail, like shown below:

```
> ./hermes generator.js
generator.js:1:9: error: 'identifier' expected after 'function'
function* seq(n) {
~~~~~~~~^

shell returned 2
```

## Steps to reproduce

1. Download Hermes binary shipped with the latest release: https://github.com/facebook/hermes/releases/tag/v0.1.0
2. Download the gist above [as ZIP](https://gist.github.com/noomorph/f9272f1a3f4a9d1f419c2e8dadfb5fe2/archive/f2c9567db10ae7cd32d5b1ae3894049ace64e25f.zip).
3. Unpack Hermes and gist to the same directory, and `cd` into it.
4. Run the commands suggested above.

## Expected result

I see a few options - either:

1. It is a documentation issue. Then docs should explicitly state that support for generators is not built-in, instead, Hermes relies on a transpiler.
2. It is a bug, and generators were meant to work without prior transpilation in Hermes.
3. It is an incorrect issue - and I just need to add extra command-line flags to run code with generators via Hermes.

## Actual result

While `for-of` and `generators` stand in the very same `Supported features` list side by side, I see major differences in how they are supported in Hermes. More clarity won't hurt if we bring it in.

**Comment by mhorowitz** [comment]
This is a version skew issue.  Generators are supported in master and in the initial github commit, but due to some manual steps to make the initial binary release before OSS launch, didn't make it into the v0.1.0 build.  If you build from master, then generator.js should work.  When we make the next binary release, for-of and generators should be equally supported.  We're working on better release automation so it's less error-prone in the future.  Sorry for the confusion!
