### ISSUE TITLE
Support getting and setting Symbol-keyed properties on jsi Object

### ISSUE THREAD

**Issue by RedBeard0531** [facebook/hermes#521]
## Problem

It looks like the C++ API for Object only supports getting and setting String-keyed properties. It would also be useful to be able to get/set Symbol-keyed properties. In other js engines, we use a unique Symbol property to store the internal pointer to the C++ backing object on an ordinary JS object. It doesn't seem like that is possible with the JSI API today.

Also, I assume that this will be important for implementing and consuming some of the new JS protocols that involve methods with Symbol names, but I haven't hit that yet in the early stages of my Hermes port.

## Solution

Either add `Object::getProperty`/`setProperty` overloads that take a `Symbol` (or perhaps a `Value` and have the same semantics as `obj[val]` in JS), or add a factory to create a `PropNameId` from a `Symbol`, similar to `PropNameId::fromString`.

## Additional Context

https://github.com/facebook/hermes/blob/3415dd0cb56d732ebc9373f97194e6c27fb9d0fe/API/jsi/jsi/jsi.h#L451-L454 says that support for creating a symbol is incomplete. But I assume it is still possible to create them via `rt.global().getPropertyAsFunction(rt, "Symbol").call(rt, "mySymName")`. This ticket is about using the symbol once it is created via some means. If internal support for Symbols isn't fully baked, then that comment should at least be updated to not just have "creation" as the TODO.

**Comment by neildhar** [comment]
This is supported in Hermes starting with 2b6d408980d7f23f50602fd88169c8a9881592a6.

**Comment by wcandillon** [comment]
this is very cool :)
