### ISSUE TITLE
Hermes incorrectly handles some class definitions

### ISSUE THREAD

**Issue by noomorph** [facebook/hermes#53]
### Description

Normally, since the support for classes has not landed in Hermes, when you run code with classes, e.g.:

```js
class A {
  foo() {}
}
```

You would expect the following error:

```
> ./hermes class.js
class.js:1:1: error: invalid statement encountered.
class A {
^~~~~~~~~
Emitted 1 errors. exiting.
```

This is fine, and the behavior is consistent. But - see below:

### Steps to reproduce

However, if you add a semicolon after `foo` method definition:

```diff
-  foo() {}
+  foo() {};
```

and run it again:

```
> ./hermes class.js
```

### Actual result

Hermes  **freezes** (hangs up).

![Screenshot from 2019-07-18 13-16-19](https://user-images.githubusercontent.com/1962469/61449748-4455bb80-a95e-11e9-8b86-f28156f5b058.png)

### Expected result

Hermes should print an error:

```
> ./hermes class.js
class.js:1:1: error: invalid statement encountered.
class A {
^~~~~~~~~
Emitted 1 errors. exiting.
```

Addendum: [Source code for the problematic class.js](https://github.com/facebook/hermes/files/3406025/class.txt)

### Environment

* at the very least, can be reproduced both on Mac and Linux
* using the latest Hermes release: https://github.com/facebook/hermes/releases/tag/v0.1.0

**Comment by avp** [comment]
Already fixed in f4733a630df4e339fffcc9e2857768c6be870b78 so the fix will be in the next release.
