### ISSUE TITLE
Build fails with Android Studio 4.3 Arctic Fox / AGP 7.0

### ISSUE THREAD

**Issue by pvegh** [facebook/hermes#532]
Execution failed for task ':bundleReleaseLocalLintAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-content project caused this error: .../node_modules/hermes-engine/android/hermes-release.aar

**Comment by pvegh** [comment]
AS 4.3 and AGP 7.0.0 is now stable and it's actually a showstopper now

**Comment by neildhar** [comment]
The build is now maintained by RN. If you're still having problems building Hermes, please open an issue in the RN repo.
