### ISSUE TITLE
Subproject commit 5e1139cc5e0eab70e75ad6720df0e686585f3604-dirty

### ISSUE THREAD

**Issue by Mahern-13** [facebook/hermes#534]
## Bug Description

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: latest
React Native version (if any): 0.64
OS version (if any): 11.4
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## The Expected Behavior

Hermes should not register dirty flag on end of subcommit./

**Comment by avp** [comment]
Can you please explain what the problem is in more detail? What is this a subcommit of and what's causing a problem?
