### ISSUE TITLE
[question] How to run test?

### ISSUE THREAD

**Issue by zzz6519003** [facebook/hermes#536]
Still trying to get a build, should I ask in other places? Thanks!

**Comment by zzz6519003** [comment]
still trying to setup the dev environment

**Comment by avp** [comment]
See https://github.com/facebook/hermes/blob/master/doc/BuildingAndRunning.md

`ninja check-hermes` will run the tests.

**Comment by zzz6519003** [comment]
@avp thx! is there a way to run single test? running whole cost too much time XD

**Comment by avp** [comment]
Unittests can be run by simply executing the binaries in `unittests/` in your build dir.

LIT tests can be filtered by using the `LIT_FILTER` env variable, which takes a regexp for which tests to run.

e.g. `LIT_FILTER=foo ninja check-hermes` runs all tests that have `foo` in the name.

**Comment by zzz6519003** [comment]
THX! LIT - LLVM Integrated Tester?
