### ISSUE TITLE
Error messages via JSIException and source maps

### ISSUE THREAD

**Issue by JoshMarler** [facebook/hermes#544]
We're currently using an integration of Hermes over at react-juce:

https://github.com/nick-thompson/react-juce/blob/master/react_juce/core/EcmascriptEngine_Hermes.cpp

At present our developer workflow involves displaying an error screen with output returned via `JSIException`. See the below code fragment:

```
        juce::var evaluate(const juce::File &code)
        {
            try
            {
                auto jsiBuffer = std::make_shared<jsi::StringBuffer>(code.loadFileAsString().toStdString());
                auto js        = runtime->prepareJavaScript(jsiBuffer, code.getFullPathName().toStdString());
                auto result    = runtime->evaluatePreparedJavaScript(js);

                return jsiValueToVar(result, *runtime);
            }
            catch (const jsi::JSIException &e)
            {
                throw Error(e.what());
            }
        }
```

We're missing a lot of source information in stack traces (nonsense filenames):

```
TypeError: Cannot read property 'filterTerms' of undefined
    at anonymous (/usr/share/js/somefile.js:6617:113)
    at anonymous (/usr/share/js/somefile.js:17001:76)
    at anonymous (/usr/share/js/somefil.js:17187:27)
    at call (native)
```

Our JS file is a webpack bundle with an associated source map file. Is there a programmatic way to `evaluate` a JS file and use it's source map to provide better error output via `JSIException`. I'm sure I'm missing many important details here!

Wondering whether we should try `runtime->debugJavaScript()` or similar? The lines reported as `annonymous` are named in webpack bundle so perhaps this is a result of optimisations applied by `evaluatePreparedJavascript` ?

Thanks

**Comment by JoshMarler** [comment]
NOTE. Tried using `runtime->debugJavaScript()` and this appears to make no difference to vars in stack traces being reported as `anonymous` using a webpack development mode bundle. No vars minified out in the bundle or anything.

**Comment by JoshMarler** [comment]
Edit. Please ignore. I've worked out why the functions the error occured in are reported as annonymous. Fundamental misunderstanding of mobx observer components.

**Comment by tmikov** [comment]
Somehow this issue fell through the cracks. The good news is that this has always been possible: Hermes can consume a source map and can report errors based on it.
