### ISSUE TITLE
[Feature request] snapshot support

### ISSUE THREAD

**Issue by gengjiawen** [facebook/hermes#554]
## Problem

Directly load bytecode from file to save the lex and parse time. This will improve much time
on low-end devices.

This is supported by quickjs (qjsc), jerryscript(jerry-snapshot) and V8 Engine.

## Solution

Provide a tool to generate bytecode from js file and provide api to load snapshot.

**Comment by Huxpro** [comment]
@gengjiawen I'm confused. 

> Directly load bytecode from file to save the lex and parse time.

Isn't it what Hermes is about? 

> Provide a tool to generate bytecode from js file and provide api to load snapshot.

`hermesc` compile your JS file to Hermes bytecode file and both JSI and Hermes already provide APIs to load the bytecode file.

> Snapshot

I guess what you were trying to request is the support of "heap snapshot", e.g. https://github.com/facebook/hermes/issues/35 or [V8 custom startup snapshots](https://v8.dev/blog/custom-startup-snapshots), which is something we've been experimenting but not stabilized.

**Comment by gengjiawen** [comment]
> hermesc compile your JS file to Hermes bytecode file and both JSI and Hermes already provide APIs to load the bytecode file.

I missed this part somehow. Thanks for the explanation.
