### ISSUE TITLE
Date initialization is inconsistent with JSC 

### ISSUE THREAD

**Issue by stulip** [facebook/hermes#556]
Date initialization is inconsistent with JSC 

Hermes version: 0.8.1
React Native version (if any): 0.65.0-rc.2
OS version (if any): MacOS 11.4  And Android 10(29)

code example:
JSC or Chrome
`const date = new Date("2020-12-11 12:11:11").toJSON()`
`console.log(date) = "2020-12-11T04:11:11.000Z"`
![image](https://user-images.githubusercontent.com/5770971/126767263-c9138708-8e2b-418c-85b0-045cd38774ff.png)

Hermes

`const date = new Date("2020-12-11 12:11:11").toJSON()`
`console.log(date) = "2020-12-11T12:11:11.000Z"`

![image](https://user-images.githubusercontent.com/5770971/126767448-fd4ca28b-dec0-4d17-823a-2ef80294bce0.png)

**Comment by neildhar** [comment]
Thanks for reporting this!

This should be fixed in 62cdd1956a3451877ce2dd42fa0f5b6bce035141. Please feel free to reopen this issue if you see this problem in the next release.
