### ISSUE TITLE
Application becomes unresponsive when using Hermes

### ISSUE THREAD

**Issue by justblender** [facebook/hermes#557]
## Bug Description
I have started working on a new project and wanted to continue the development using the Hermes engine, after doing initial set up one thing that stood out to me immediately is that the app becomes completely unresponsive when using [VideoPlayerOverlay component](https://github.com/justblender/epic-growth/blob/main/app/components/VideoPlayer/VideoPlayer.tsx#L113). The JS perf monitor shows -2.1 FPS at peak. I have tried getting rid of Animated, 3rd-party packages and so on to nitpick the issue myself, yet the app always stays unresponsive unless you `return null` when rendering the component (i.e. render nothing).

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any): 0.64.2
OS version (if any): Windows 10 Build 20H2, Android 11
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce
It's unclear what causes the issue and how to reproduce it exactly, but after removing [VideoPlayerOverlay component](https://github.com/justblender/epic-growth/blob/main/app/components/VideoPlayer/VideoPlayer.tsx#L113) the app becomes responsive again. 

## The Expected Behavior
The application should stay responsive just like it does when running with JSC.

**Comment by neildhar** [comment]
Hi @justblender, unfortunately, I wasn't able to repro this using the test app you linked. The app seems responsive both when using Hermes and JSC, and the JS perf monitor shows reasonably good performance.

Could you elaborate on what you were doing when the app became unresponsive? It would be helpful if you could share a screen capture and relevant logcat output.

**Comment by tmikov** [comment]
Closing, since no actionable information provided.
