### ISSUE TITLE
Memory leaks detected in Xcode Profiling

### ISSUE THREAD

**Issue by adriaandebolle** [facebook/hermes#558]
## Bug Description

Our app gets slower when using. Therefore, we are looking into memory leaks and app performance.
Enabling hermes-engine seemed to always be helpful.
Within our project and a new react native project there are memory leaks with "responsible library hermes".

_Is this something to worry about? What is normal and is it better for some projects to disable hermes?
Is under the hood perhaps something else responsible than hermes?_ 

Sorry for the rookie questions.

Hermes version: 0.7.2 (hermes-engine)
React Native version (if any): 0.64.2
OS version (if any): macOS 11.4
Xcode version: 12.5.1

## Steps To Reproduce

1. `npx react-native init AwesomeProject`
2. `:hermes_enabled => true` (Podfile)
3. Run in xcode with debug executable
4. Profile in instruments to monitor leaks

code example:

Our app (unblnd.com/app)
<img width="1440" alt="Screenshot 2021-07-25 at 13 22 59" src="https://user-images.githubusercontent.com/14223265/126903462-3e250ff8-8a32-4622-8098-d9f9565c9d50.png">

New AwesomeProject
<img width="1440" alt="Screenshot 2021-07-25 at 16 43 40" src="https://user-images.githubusercontent.com/14223265/126903465-bd878e88-ac54-46aa-a080-e3c743f7a1c3.png">

## The Expected Behavior

Performance improvement without memory leaks.

**Comment by neildhar** [comment]
Hi @adriaandebolle, thanks for reporting this. I'm not familiar with how the Instruments tool presents leaks, but trying it locally, I see that it does report leaks in Hermes even on smaller scripts.

However, clicking on the arrow next to these leaks then shows that the associated memory was in fact freed later during execution. I'm wondering whether you're seeing the same thing, or if these leaks are persisting for the lifetime of the program.

![Screenshot 2021-07-26 at 11 36 50 PM](https://user-images.githubusercontent.com/4301777/127107363-e8e21767-8453-4a0b-8763-93b418ab24c6.png)
![Screenshot 2021-07-26 at 11 37 05 PM](https://user-images.githubusercontent.com/4301777/127107368-80775bff-e751-4e7d-a32f-eb4401053d44.png)
