### ISSUE TITLE
Is hermes JS engine specific to ReactNative app or can we use hermes JS engine in non reactNative apps ?

### ISSUE THREAD

**Issue by Raju-567** [facebook/hermes#56]
Can we use hermes Javascript engine in non-reactnative mobile apps ? . Our current Mobile android app  uses Google's V8 javascript engine for compiling and running the Javascript code and creating custom javascript objects using JNI-V8 APIs , can we replace V8 with hermes in this project ?.
When will be documentation for hermes will be made public ?

**Comment by mhorowitz** [comment]
Thanks for asking about Hermes!  #43 addresses using Hermes for non-React Native use cases.
