### ISSUE TITLE
Slow performance on crypto hashing functions

### ISSUE THREAD

**Issue by desfero** [facebook/hermes#569]
## Bug Description

Cryptography operations are significantly slower on Hermes than on JSC/V8.
A simple call to get Ethereum private key from mnemonics can take a significant amount of time (around ~15s).
In the end that would affect user expirience

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.7.2
React Native version (if any): 0.64.2
OS version (if any): MacOs
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

1. Have an empty react-native project with hermes enabled
2. Try to import mnemonic
```
 import { Wallet } from 'ethers';

 const mnemonic = "uphold eagle true another decide enlist average party relief seven arrange giant"
 const { address, privateKey } = Wallet.fromMnemonic(mnemonic)
```
3. Call to `Wallet.fromMnemonic` will take a significant amount of time

From quick profiling, it seems like Hermes spends a lot of time processing bitwise operations during hashing. 
For e.g. call to `rotr64_lo` from [hash.js](https://github.com/indutny/hash.js/blob/fcd35edcc4e30145be4b7a737477ad54e83afc25/lib/hash/utils.js#L263) takes on my machine ~15ms were at the same time JSC can process that in less than 1ms.

## The Expected Behavior
Should process all cryptography operations faster (as close as possible to JSC/V8 performance).

**Comment by neildhar** [comment]
Hi @desfero, unfortunately, Hermes is not going to be as well suited to computationally heavy workloads like cryptography, since it does not have a JIT. For that kind of workload, you can implement the computation in C++ and invoke it through JSI.

Two questions:
1. I noticed your OS is listed as macOS, are you working on an RN desktop app?
2. Would it be possible for you to share a self contained snippet of JS that exhibits the 15x slowdown you observed? It would be useful for us to profile and check whether you're hitting some especially bad case in Hermes.

In addition, we're also currently working on some asm.js support that would speed up these computations significantly.

**Comment by desfero** [comment]
Hi @neildhar. 

1. My mistake, I'm working on an IOS/Android app.
2. I did a basic react-native init with some small changes: https://github.com/desfero/rnHermesBitwisePerfShowcase/blob/master/App.js#L12.

Let me know if that's enough.

**Comment by neildhar** [comment]
Thank you for preparing that benchmark! I was able to repro a ~2x perf gap on Android between Hermes and JSC. Unfortunately, from profiling, I don't see anything that suggests this is hitting a particularly bad case in Hermes, so there isn't anything we can immediately do to improve performance.

That said, now that we have this benchmark, I'd like to take a closer look in the coming weeks to figure out where exactly we differ from JSC here.

**Comment by tmikov** [comment]
@neildhar to clarify, is this a 2x gap between Hermes in interpreted mode and JSC with 1st level JIT?

**Comment by neildhar** [comment]
@tmikov Yes, I believe this is with JSC's 1st level JIT enabled, so the gap makes sense. I'd like to also try this on iOS and see what we find.

**Comment by neildhar** [comment]
I ran this benchmark on iOS as well. In the emulator, I do see that JSC is ~10x faster than Hermes in a release build of the app. However, this performance difference does not appear on a physical device. On device, both Hermes and JSC seem comparable. This seems to suggest that JSC in the emulator is able to fully JIT code, whereas JSC on the actual device is not.

@desfero was the gap you measured in an emulator or on a device?

**Comment by AndreyBubnov** [comment]
> I ran this benchmark on iOS as well. In the emulator, I do see that JSC is ~10x faster than Hermes in a release build of the app. However, this performance difference does not appear on a physical device. On device, both Hermes and JSC seem comparable. This seems to suggest that JSC in the emulator is able to fully JIT code, whereas JSC on the actual device is not.
> 
> @desfero was the gap you measured in an emulator or on a device?

Hi. Check gap difference on android device/simulator (whatever). Most of crypto hash functions kill js thread. On iOS we dont face any perf issues.

**Comment by tmikov** [comment]
To be fair, JavaScript will always have a handicap for crypto (without Wasm). My recommendation would be to implement the crypto functions in C++.

**Comment by tmikov** [comment]
Update: there will be a dramatic speed up of numeric computations in one of the next major Hermes version. Closing this issue.
