### ISSUE TITLE
lazy breakpoint(setBreakpointByUrl)

### ISSUE THREAD

**Issue by yFeii** [facebook/hermes#573]
## Problem

[CDP](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#method-setBreakpointByUrl)  uses setBreakpointByUrl to set breakpoints before executing js(or CodeBlock). I noticed that there is a similar API for hermes [debugger](https://github.com/facebook/hermes/blob/0b02a101f5d824becb73dcff2750e9384dcbc2ae/include/hermes/VM/Debugger/Debugger.h#L387): resolveBreakpoints, but I found that there is no place to call this method, so I have the following questions:
1. Is resolveBreakpoints used to implement setBreakpointByUrl？
2. Does hermes now support the setBreakpointByUrl?

**Comment by mattbfb** [comment]
Hermes itself doesn't currently contain a CDP implementation. React Native does contain a CDP implementation for use with Hermes. That implementation does support `setBreakpointByUrl`, but does not directly make use of `resolveBreakpoints`.

**Comment by mattbfb** [comment]
I believe the questions have been answered. Feel free to reopen if more information is needed.
