### ISSUE TITLE
store as global object is not working on debugger

### ISSUE THREAD

**Issue by nomi9995** [facebook/hermes#583]
## Bug Description

![image](https://user-images.githubusercontent.com/36044436/131081158-5af426fe-78ea-4a37-9641-6f058783cd48.png)

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.7.2
React Native version (if any): 0.64.2
OS version (if any): Big Sur
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): all

## Steps To Reproduce

1. open hermes degger from fliiper
2. then right mouse click on any object of `console.log` and click on `store as global object` it will not store as global object

code example:

## The Expected Behavior
when i click on `store as global object` it should store that object in temp variable and should be copy by `copy()`

**Comment by nomi9995** [comment]
@avp is there any chance to add this enhancement?

**Comment by jpporto** [comment]
Hi. This has been merged back in the [react native](https://github.com/facebook/react-native/commit/eb08af57a95e99d45d72e7c097c41b181c3130cd) repository (which is Hermes' CDP implementation's home).
