### ISSUE TITLE
Hermes enabled debug build is too slow. 

### ISSUE THREAD

**Issue by pkpardeep482** [facebook/hermes#589]
Hi, I am using react-native 0.60.4. in which which i recently enabled hermes. Now the problem is , its working fine in release mode, but we have dependencies which we need to test in debug mode too. but due to hermes debug builds are too slow. 
Please help

**Comment by oleksandr-dziuban** [comment]
Same for our project.
RN v0.69.6
iOS and Android debug builds are very slow on Hermes. Animations seems to be postponed, API calls with fetch are freezing in debug mode.

Release apps work perfectly

**Comment by tmikov** [comment]
Closing, since Hermes is never supposed to be used in debug mode outside of Hermes development.
