### ISSUE TITLE
FinalizationRegistry Support

### ISSUE THREAD

**Issue by rockwotj** [facebook/hermes#604]
## Problem

I'm using [react native `Blob` objects](https://github.com/facebook/react-native/blob/main/Libraries/Blob/Blob.js#L111-L122) and having a hard time creating a framework within our app that doesn't result in leaks.

## Solution

I was wondering if support for FinalizationRegistry has been considered for Hermes. Adding that would allow any blob created in RN be able to notify the native layer when the object is GC'd so the memory could be released automatically. Without the application in javascript has to do a bunch of reference counting logic to ensure that blobs are closed properly.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry

## Additional Context

I believe on recent enough builds Javascript Core supports FinalizationRegistry now. And it seems that WeakRef is supported on Hermes already.

**Comment by ABespolov** [comment]
WeakRef doesn't work. So I need to replace hermes to v8 on android. It would be great to see WeakRef support, because JSCore and v8 already have it.

**Comment by neildhar** [comment]
Hi @rockwotj, the use case you describe is already possible in Hermes. A `jsi::HostObject` can be used to to retain and free resources when a JS object is garbage collected.

This is what the `BlobCollector` in RN does, and you can take a look at it as a reference: https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/modules/blob/jni/BlobCollector.h.

**Comment by rockwotj** [comment]
Thanks @neildhar for the code pointers! I was unaware of that code's existence.

**Comment by rockwotj** [comment]
Also does that mean that the comment I linked to is outdated?
