### ISSUE TITLE
"too many nested expressions" on export statement

### ISSUE THREAD

**Issue by dlebedynskyi** [facebook/hermes#628]
## Bug Description

During build for Hermes optimized bundle  on CI
```
executing "node_modules/hermes-engine/linux64-bin/hermesc -O -emit-binary -output-source-map -out=.tmp/android/debug/index.bundle.hbc .tmp/android/debug/index.bundle"
```

we have encountered following error
```
tmp/android/debug/index.bundle:888741:33797: error: Too many nested expressions/statements/declarations
exports.A = exports.B = exports.C .... = exports.ZZZZZ= void 0;

```
Error happened after update to Babel 7.16. Error does not happen with Babel 7.14 

Versions used 
```
"@babel/core@^7.0.0", "@babel/core@^7.1.0", "@babel/core@^7.1.6", "@babel/core@^7.16.0", "@babel/core@^7.7.5":
  version "7.16.0"
  
metro@0.64.0, metro@^0.64.0:
  version "0.64.0"
 
"@react-native-community/cli-hermes@^5.0.1":
  version "5.0.1"
 
hermes-engine@~0.7.0:
  version "0.7.2"
```  

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any): 0.64.2
OS version (if any): Android 
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):arm64-v8a 

## Steps To Reproduce
* Our export list has over 1100 `export.*` 
* issue started to  happen after babel [7.16 update](https://babeljs.io/blog/2021/10/29/7.16.0)

code example:

## The Expected Behavior

No error, bundle is created

**Comment by tmikov** [comment]
Thank you for reporting this. We will address it.

It occurs when there are more than 1021 assignments in a row. This code generates a reproduction case:
```
print("var exports={};");
for(var i = 0; i < 1022; ++i) {
    print("exports.x"+i+" =");
}
print("  void 0;");
```

If the resulting output is executed, it aborts with the following error:
```
t.js:1024:8: error: Too many nested expressions/statements/declarations
  void 0;
```

**Comment by tmikov** [comment]
@dlebedynskyi I wonder whether you can check how many of these assignments are there in a row in the problem case? Judging from the error line:
```
exports.A = exports.B = exports.C .... = exports.ZZZZZ= void 0;
```
it seems there may be 26**5 of them? That can't be right, right? 11,881,376 exports seems like too many?

**Comment by dlebedynskyi** [comment]
File that is a problem has 1804 exports for constants, all are like `export let A = 'A'`. 

Failure on CI reported 1100 exports to be exactly, not sure why not 1804. I'm testing possible workaround.
