### ISSUE TITLE
[Juno] gen_js broken for Flow type casts 

### ISSUE THREAD

**Issue by tmikov** [facebook/hermes#632]
The code generator is currently broken for type casts (so this only occurs without stripping the types):
```
async function test(){
  return await (x: any);
}
```
becomes this (unbalanced parenthesis around the return value):
```
async function test(){
  return await ((x: (any));
}
```

Reported in https://github.com/facebook/hermes/pull/595#issuecomment-961859809 .

**Comment by mischnic** [comment]
Can this be closed now with https://github.com/facebook/hermes/commit/b4e21ff879e094b72177a65caa043a83d19a6977?

**Comment by tmikov** [comment]
Yes!
