### ISSUE TITLE
Hermes 0.9.0 crash on android when build release RN 0.66.3

### ISSUE THREAD

**Issue by minhchienwikipedia** [facebook/hermes#638]
## Bug Description

- [ x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.9.0
React Native version (if any): 0.66.3
OS version (if any): Android 10
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): armeabi-v7a

## Steps To Reproduce
I'm trying to build a release version and the app getting crashes when I'm open the app! If I disable Hermes the app will open without crashing!

I found the log error in Android studio
`com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly`

I hope you can check it ASAP!

**Comment by neildhar** [comment]
Hi @minhchienwikipedia, this seems like it is likely a react native issue, and it is difficult to say what the source is without more information about your build setup. You can take a look at https://github.com/facebook/react-native/issues/9336, or open an issue in the React Native repo if you believe something is broken.

**Comment by minhchienwikipedia** [comment]
@neildhar I had checked that issue before, but seems that issue is showing up on the simulator & debug. My issue is showing up on the release build, and my solution to fix it is disable Hermes to make it works. But I'm still want to use Hermes!

**Comment by minhchienwikipedia** [comment]
I think this issue is related to this  [facebook/react-native#26252](https://github.com/facebook/react-native/issues/26252) But it's auto closed by the bot, and the solution for this is we should disable Hermes until we have a new version to fix it!
I'm trying to find another way but no help!

**Comment by neildhar** [comment]
@minhchienwikipedia This is unfortunately outside our area of expertise, since the bundling is done by RN. Are you able to provide a minimal repro for this bug? If so, we can surface it with the RN team as an issue.

**Comment by minhchienwikipedia** [comment]
@neildhar Yup, I'll do it, I hope we can fix this issue

**Comment by minhchienwikipedia** [comment]
I found it, my fault, I forget to remove this when upgrading React Native version!
```
if (useIntlJsc) {
        implementation 'org.webkit:android-jsc-intl:+'
} else {
        implementation 'org.webkit:android-jsc:+'
}
```
