### ISSUE TITLE
new Date() is in UTC instead of device time.

### ISSUE THREAD

**Issue by acollazomayer** [facebook/hermes#640]
## Bug Description
My device time is 23:55 but when I run Date.now() or new Date() the created date is at 22:55. I just enable Hermes on iOS and this broke my whole app.

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any): 0.65.1
OS version (if any): iOS 15
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. run console.log(new Date()) and you will see the time difference.
2.

code example:

## The Expected Behavior
Date should match with device date.
This does not occur on the playground.

**Comment by mhorowitz** [comment]
Thanks for your bug report.  I think we need a bit more information to proceed.

Date.now() is defined to return a UTC date/time as a number.  Is this returning the wrong value relative to the epoch? How are you determining the correct value?

The difference you give is one hour.  Is it possible this is a DST issue, and not a TZ issue?

Can you explain exactly how you are reproducing this?  Are you calling console.log in a React Native app? What is the entire output?

**Comment by acollazomayer** [comment]
@mhorowitz Thanks a lot for answering. What I don't understand about Date.now() or new Date() Is that in the playground it shows the correct value not UTC (I say correct value is the current value of my device) However in the simulator it shows UTC.

This was not happening before without hermes. To solve the issue I've created a Wrapper that returns the corrected value of now depending on the timezone. Which in my opinion I don't think is ideal. At least this change forced me to change the way my code works.
