### ISSUE TITLE
Profiler stuck on recording long after stopping

### ISSUE THREAD

**Issue by Sandy-Garrido** [facebook/hermes#642]
## Bug Description
After having updated from RN 0.64.2 to RN 0.66.0 and with that, enabled the hermes engine, I have not since been able to do any profiling using chrome devtools. I have followed the steps from RN docs on getting to hermes inspect area, however whilst I can see comments and errors appear in the inspect window, the profiler does not want to work and I don't get any specific errors except that the inspect window is inoperable unless I clear the  CPU profiles list of any currently in recording...

I have installed react-devtools and run that profiler, that seems to work but it seems that some details are missing in the information it provides over the chrome devtools inspect window which is why react-devtools isn't my preferred method

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: ~0.9.0 (Prepacked with RN 0.66.0)
React Native version (if any): 0.66.0
OS version (if any): MacOS 12.0.1 (Monterery)
Platform: x86_64

## Steps To Reproduce
I click record
make some actions in the app
click stop but the recording is just stuck on recording

![Screenshot 2021-11-22 at 18 07 43](https://user-images.githubusercontent.com/33653854/142914321-03750a1a-96f3-4b51-b164-1c4d5fa7cb1f.png)

## The Expected Behavior
- I expect the recording to stop and be presented with the profiled components

side note: As, at this point, unsure if it's a bug or setup so pointing me in the right direction is greatly appreciated.

**Comment by neildhar** [comment]
Hi @Sandy-Garrido, the Hermes sampling profiler has not been wired up to be used through DevTools. Improving the developer experience of our sampling profiler is certainly on our radar though.

For now, you can profile your application with these instructions: https://reactnative.dev/docs/profile-hermes

**Comment by Sandy-Garrido** [comment]
> Hi @Sandy-Garrido, the Hermes sampling profiler has not been wired up to be used through DevTools. Improving the developer experience of our sampling profiler is certainly on our radar though.
> 
> For now, you can profile your application with these instructions: https://reactnative.dev/docs/profile-hermes

Thanks! I must have something misconfigured somewhere as when I use that method, the app just crashes the second I click start sampling :( Have you experienced or heard of this before?

**Comment by TomasSestak** [comment]
Still stuck but I tried to use it because of the mention here: https://reactnative.dev/docs/hermes/#debugging-js-on-hermes-using-google-chromes-devtools

**Comment by jpporto** [comment]
Hi @TomasSestak,

The page you linked doesn't mention the sampling profiler -- it is only for debugging JavaScript using Chrome DevTools. The team is still working on wiring up sampling profiler support, so I am afraid you can't use it at the momment.

You can still use the directions in https://reactnative.dev/docs/profile-hermes for profiling android applications.

**Comment by heyalexchoi** [comment]
I tried using the hermes profiler through both `chrome://inspect` and flipper. The profiler gets stuck on 'recording' on both. Are there any options for profiling a react native ios app running hermes?

@jpporto @neildhar
