### ISSUE TITLE
App crashing when enabling Hermes  and using react-native-firebase

### ISSUE THREAD

**Issue by Dassine** [facebook/hermes#648]
Hi guys!

Last week, I had to enable the hermes-engine in my podfile since the TF build was crashing at launch. Once done, the build worked fine. This week, Im trying to react-native-firebase/app and /messaging to add Push Notification and the app is again crashing at launch. I read somewhere that react-native-firebase is not compatible with hermes but React-Native mentioned that they added Proxy support to hermes jn RN 0.64

Im using RN 0.66 since last week and the added react-native-firebase packages are 13.0.1. I believe since 2020 both were upgraded to support PN, isn’t it?

**Comment by neildhar** [comment]
Hi @Dassine, we're not familiar with firebase, so we can't really provide advice on troubleshooting this issue. Do you have any logging or stack traces you could share corresponding to the crash? I recommend bringing this up with the firebase team, unless you believe there is a bug in Hermes itself.

**Comment by Dassine** [comment]
@neildhar  Thank you for your feedback.  I end up finding a small issue in the setup of react-native-firebase.
