### ISSUE TITLE
toLocaleString() for currency is missing with symbol and decimal places

### ISSUE THREAD

**Issue by markglibres** [facebook/hermes#655]
## Bug Description

We have this script in jest test and it returns `$100.00` which was the expected output.

```TypeScript
(100).toLocaleString('en-AU',{
    style: 'currency',
    currency:'Australia/Sydney',
    minimumFractionDigits: 2,
  })
```

But when hermes is enabled in iOS, the script will render in the app as `100` without the currency symbol and decimal places. 

Hermes version: 0.66.3
React Native version (if any): 0.66.3
OS version (if any): iOS 14.4

**Comment by neildhar** [comment]
Hi @markglibres, this functionality is provided by Intl, which is currently unsupported by Hermes on iOS.

We have an existing issue tracking this (https://github.com/facebook/hermes/issues/23), so I'm going to close this one.
