### ISSUE TITLE
WeakRef support

### ISSUE THREAD

**Issue by ABespolov** [facebook/hermes#658]
Hi, it would be nice to see [WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef) in hermes. Are there some plans to support it?

**Comment by neildhar** [comment]
Hi @ABespolov, we don't currently have plans to build `WeakRef` support. If you share a little more about your use case, I might be able to suggest some existing feature in Hermes that fills that need though.

Out of curiosity, do you expect to rely on the behaviour of `WeakRef`s where they cannot be reclaimed until the end of a job? Supporting that behaviour would be a more invasive change, but I've been wondering whether it would be a good idea to implement a simpler, non-compliant version of `WeakRef` where the referent may be reclaimed at any time.

**Comment by ABespolov** [comment]
@neildhar thanks for answer! I use WeakRef array to store some class instances with similar type. It allows me to sync data across application on different tabs and screens. For example if I want to change some filed in one instance I also want to sync this changes with all instances with the same type. I store all class instances in one array to be able to access this instances anytime. But it's hard to remove this instances from the array if I don't use them anymore to avoid memory leak. I would need to use componentWillUnmount in each component that uses class instance. Instead of this I prefer to relay on garbage collector to remove unused instances. The main purpose is to have "heap" of objects and don't worry about removal this objects if we don't have links on this objects anymore. So I don't need to worry about exact moment of reclaim. I successfully use WeakRef with JSC on IOS and with V8 on Android. It would be great to switch to hermes on each platform.

**Comment by neildhar** [comment]
If this manipulation is being done from native code, you could use a `jsi::WeakObject`. Otherwise, there probably isn't a way to do this purely in JavaScript without manually unregistering the component in some way. Hermes does support `WeakMap` and `WeakSet`, but those are not enumerable.

**Comment by ABespolov** [comment]
I think WeakMap is useless in the most cases. WeakRef is very suitable for garbage collected cache. I hope for future support of WeakRef and ES21, ES22 features, thanks!

**Comment by fbmal7** [comment]
Hi @ABespolov, happy to give an update: WeakRef has been shipped with Hermes since [096e777a](https://github.com/facebook/hermes/commit/096e777a8a358200fd8fc92e85175dbad5b6904d) 😃 

You can pass `-Xmicrotask-queue` on the command line to active WeakRef. You may want to read more on the [spec](https://tc39.es/ecma262/multipage/managing-memory.html#sec-weak-ref.prototype.deref) to understand why you need to enable Microtasks for WeakRefs. TLDR; WeakRefs are kept alive until the end of the microtask they were created or dereferenced in.

**Comment by kennetpostigo** [comment]
@fbmal7 any chance this will eventually be available without a flag?

**Comment by tmikov** [comment]
@kennetpostigo Hermes cannot control whether the micro-task queue is enabled or not. This is up to the integrator (i.e. React Native). It might make sense to open an issue with React Native.
