### ISSUE TITLE
Moving functions between Hermes runtimes.

### ISSUE THREAD

**Issue by Szymon20000** [facebook/hermes#671]
## Problem

Do you think it would be possible to take function from one context and move it to the other with all of the dependencies that are needed? 
I remember I tried to run function from a first context on a second one but strings from that function where not available one the second context. Does Hermes provide a way to iterate over strings used in function to copy them?  Is it possible to iterate over function closure and copy deps as well?

**Comment by mhorowitz** [comment]
It sounds like you are asking if you can take a jsi::Function output by HermesRuntime, and use it in another.  If that is correct, I think the practical answer is no.  (Nothing is _impossible_, but this was never intended, and nothing about the implementation makes this particularly easy.  This limitation is not unique to Hermes.  Neither JSC nor v8 supports this in their C/C++ APIs, either.

If you could explain why you want to do this, there may be another approach which is more practical.  In particular, you could always load the same bytecode into two runtimes.

**Comment by mhorowitz** [comment]
I think you will need to implement tooling to add those NPM modules to the bytecode loaded in the runtime in the other thread.  I think we have a lot of standard features we need to implement first before we could prioritize investing in something like this.

**Comment by Szymon20000** [comment]
I wanted to investigate that myself. Obviously I understand you have tons of more important stuff. 
Thx for your answers.
