### ISSUE TITLE
Property 'console' doesn't exist

### ISSUE THREAD

**Issue by aianshume** [facebook/hermes#675]
## Bug Description

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.11.0
React Native version (if any):
OS version (if any): zorin os 16 lite (based on ubuntu 20.04)
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

1. just build hermes from the repo
2. test hermes command with some javascript code

code example:
`console.log("Hemes works!");`

## The Expected Behavior
Hermes Works

## Screenshot
 
![Screenshot_2022-02-16_05-45-18](https://user-images.githubusercontent.com/68537640/154172582-7e6b9190-82d8-4f65-9ac8-e07f98b1a8a6.png)

**Comment by neildhar** [comment]
Hi @aianshume, `console` is not a built-in in JavaScript. Hermes does not provide a `console.log` function, it is provided by React Native or any other Hermes integrator.

If you'd like to run the Hermes executable directly, you should be able to use the `print` function to print things to the console.

**Comment by aianshume** [comment]
> Hi @aianshume, `console` is not a built-in in JavaScript. Hermes does not provide a `console.log` function, it is provided by React Native or any other Hermes integrator.
> 
> If you'd like to run the Hermes executable directly, you should be able to use the `print` function to print things to the console.

nice one thank you

**Comment by 89z** [comment]
> Hi @aianshume, `console` is not a built-in in JavaScript.

Neither is `print`. Since neither one is built-in, wouldn't it make sense to just use the one support by every single browser since 2011?

**Comment by melroy89** [comment]
That is funny, since JS/TS runtimes like Node.js or Bun do know about console.

I believe Herman should create a simple wrapper, so all console.* calls will become `print()`

**Comment by tmikov** [comment]
@melroy89 absolutely, runtimes should provide an implementation of `console`. However Hermes is not a runtime like NodeJS or a Bun, it is a JS engine like v8 or JSC.

It would be convenient to add an implementation of console to the *hermes tool*.
