### ISSUE TITLE
Support for destructuring assignments in catch parameter

### ISSUE THREAD

**Issue by YiWen-y** [facebook/hermes#680]
###### Version

V0.10.0

###### Test case

```js
var foo = function() {
    var y = 200;
    try {
        throw {}
    } catch ({
        x = function(){print(y);}
    }) {
        let y = 300;
        x();
    }
};
foo();
```

###### Command 

    /.jsvu/hermes Testcase.js

###### Output

```
/Testcase.js:5:14: error: Destructuring in catch parameters is currently unsupported } catch ({ ^ Emitted 1 errors. exiting.	
```

###### Expected result

```
200
```

###### Description

When executing this test case, other engines can execute normally and output the expected result `200`, but hermes throws a syntax error in line 5. I don't know why hermes throw the destructing exception because there is no any destructing assignment statement in catch block.

**Comment by YiWen-y** [comment]
Thanks for your reply @neildhar . Do you mean the code `catch ({
        x = function(){print(y);}
    })` contains syntax errors? If so, why do other engines not report errors but only hermes? Is hermes stricter in this regard?

**Comment by neildhar** [comment]
It doesn't contain a syntax error, but it does contain a destructuring assignment (the `{ x = function(){print(y);}` is in fact a destructuring assignment). Hermes doesn't support destructuring assignments in catch blocks, so it reports an error.

**Comment by YiWen-y** [comment]
I see, thanks. @neildhar

**Comment by tmikov** [comment]
This is supported correctly in the branch for the next major version of Hermes.
