### ISSUE TITLE
ES Classes support

### ISSUE THREAD

**Issue by oblador** [facebook/hermes#685]
## Problem

I'm working on a project making esbuild the bundler for `react-native` to drastically reduce the compile time of the JS bundle, but esbuild will not transpile classes to ES5 compatible code. Since `react-native` uses classes in several places it means that the resulting bundle runs fine on JSC but crashes on Hermes. Since hermes is [intended to become the standard engine](https://reactnative.dev/blog/2021/10/26/toward-hermes-being-the-default) for `react-native` this becomes a major blocker. 

## Solution

Classes is listed under [In Progress](https://hermesengine.dev/docs/language-features#in-progress), but my interpretation is that it's more of a _things we want to do at some point_ as it hasn't changed since the initial commit 3 years ago. Since default RN setup transpile classes with babel there hasn't been much of a use case, so I understand it hasn't been prioritized. I ask you to consider this use case that I think would be a great boost for the RN ecosystem.

**Comment by ljharb** [comment]
It seems like the proper solution is for esbuild to support outputting ES5 code, like the defacto standard (babel) does?

**Comment by oblador** [comment]
Esbuild will simply error out when using classes with ES5 target, which AFAIU is an intentional limitation, whereas Hermes intends to support classes per the link posted above.

**Comment by ljharb** [comment]
Sure. But why does Hermes need to do extra work to bypass esbuild’s intentional choice? If esbuild wants to be useful for RN, then it may need to change its decision.

**Comment by oblador** [comment]
Hermes doesn't _need_ to do anything, I'm simply posting a use case/feature request for something already listed as on the roadmap on the website. I'm not representing esbuild nor do I know the author, and from what I can tell you do not represent hermes so lets hear what the maintainers think.

**Comment by ljharb** [comment]
Sure, I'd love hermes to support classes natively regardless :-) but i hope you're also filing an issue on esbuild with this use case for having them do the standard thing and output ES5.

**Comment by ljharb** [comment]
I think the main benefit would be the capabilities that are otherwise impossible, like extending builtins.

**Comment by mikeduminy** [comment]
Classes have been widely supported by all major browsers since early 2016, so it makes sense for modern transpilation and bundling tools like ESBuild to not prioritize transpilation of such features. I can't speak for the complexity vs perf/size considerations if hermes added support for classes, but from a developer experience perspective I, too, would like to request that the case for classes is re-evaluated.

**Comment by tmikov** [comment]
Classes will be fully supported in one of the next major versions of Hermes. Closing this issue, since EcmaScript compatibility is tracked separately.

**Comment by kungfooman** [comment]
> It seems like the proper solution is for esbuild to support outputting ES5 code, like the defacto standard (babel) does?

I think you are looking for https://github.com/swc-project/swc, which is more something like a "faster Babel", while esbuild just... bundles.

esbuild's own description is: `An extremely fast bundler for the web`

**Comment by tmikov** [comment]
FYI, we will be releasing a beta version of Hermes with full support of classes in Q1 2024.

**Comment by natew** [comment]
@tmikov since we're at the end of 2024 just curious how this is coming, I was debugging why One's SWC pipeline can be slow and a big part of it is our need to transpile down to ES5. Without that need, we could use oxc-transform and get 5x faster!
