### ISSUE TITLE
AST2JS missing visit for some elements

### ISSUE THREAD

**Issue by ScalletaZ** [facebook/hermes#695]
Unsupported AST node kind: RestElement
Unsupported AST node kind: SpreadElement

generate js from ast with js code parsed like:
```
function I(t, n, i, e, r, l){
      return (0, c.wg)(), (0, c.iD)("div", s, [(0, c._)("h1", null, (0, u.zw)(i.msg), 1), (0, c._)("button", {onClick: n[0] || (n[0] = (() => {
        return l.greet && l.greet(());
      }))}, "Greet")]);
    }
```

**Comment by ScalletaZ** [comment]
maybe:
`
  void visit(SpreadElementNode *node) {
    visitESTreeNode(*this, node->_argument, node);
  }
  void visit(RestElementNode *node) {
    visitESTreeNode(*this, node->_argument, node);
  }
`

**Comment by tmikov** [comment]
AST2JS was an experiment and isn't finished, it should probably be removed. However equivalent functionality exists in Juno, where it is intended to be complete and tested: https://github.com/facebook/hermes/blob/main/unsupported/juno/crates/juno/src/gen_js.rs
