### ISSUE TITLE
Build and publish across architectures using VcPkg on Windows

### ISSUE THREAD

**Issue by mganandraj** [facebook/hermes#70]
This will enable seamless consumption of Hermes on Windows. Post this change, a developer should be able to "vcpk install Hermes:arm-windows" for e.g. and refer to Hermes headers and libraries from visual studio.

The sub tasks of this work item are,
1. Enable building all platforms on Windows host machine. We target the following platforms at least,
   a. x86/x86_64
   b. cross compile to ARM/ARM64.
2. VcPkg port file.

**Comment by mganandraj** [comment]
Please note that I've done the majority of the work and expecting to send PRs in a couple of days after thorough verification ..

**Comment by tmikov** [comment]
Can you describe what it entails? Also, AFAIK, VcPkg is supposed to be cross-platform. Are you aiming only for Windows support or other platforms as well?
