### ISSUE TITLE
AppleTV support

### ISSUE THREAD

**Issue by frankenthumbs** [facebook/hermes#704]
## Problem

We are currently using a monorepo to host iOS, tvOS, android, androidTV and react-native-web apps. We would love to run hermes on the native apps but the lack of tvOS support is stopping us.

## Solution

create AppleTV binaries

## Additional Context

Not sure if this would be non-trivial. Just starting to dig into the compilation process to see how hard this would be.

**Comment by neildhar** [comment]
For RN development, the host-specific builds of Hermes are maintained by the RN team, and they would be better placed to give you pointers on RN development on other platforms.

Unless it is being used by RN, tvOS is not a platform that we specifically support builds for, so I'm closing this issue for now.

**Comment by tmikov** [comment]
Though this is interesting and highly coincidental: https://github.com/facebook/hermes/pull/1000
