### ISSUE TITLE
Closure scope leak in for loops

### ISSUE THREAD

**Issue by oblador** [facebook/hermes#707]
## Bug Description

Hermes uses `var` semantics for `let/const` variables, leading to scope leaking in for loops. 

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.11.0
React Native version (if any): N/A
OS version (if any): macOS
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce

```js
const keys = ['a', 'b', 'c'];
const obj = {};
for (let i = 0; i < keys.length; i++) {
  const key = keys[i];
  obj[key] = () => key;
}
console.log([obj.a(), obj.b(), obj.c()]);
```

Hermes output: `['c', 'c', 'c']` 🛑 

## The Expected Behavior
JSC output: `['a', 'b', 'c']` ✅ 
Node output: `['a', 'b', 'c']` ✅

**Comment by neildhar** [comment]
Hi @oblador, Hermes does not support block scoping, and we instead rely on babel transforms to lower code like this into something that Hermes can correctly run. Please see #575 for more details.

**Comment by oblador** [comment]
Wouldn't it be better to not support the let/const syntax alltogether?
