### ISSUE TITLE
Android crash on  __mutex_base:365

### ISSUE THREAD

**Issue by armadilio3** [facebook/hermes#725]
## Bug Description

After upgrading to React Native 0.67.3 and Hermes 0.9.0 we have started seeing crashes reported in Firebase with the following stack trace:
```
#00 pc 0x4b38c libc.so 
#01 pc 0x4ef74 libc.so 
#02 pc 0xaf0d0 libc.so 
#03 pc 0x52258 libc++_shared.so 
#04 pc 0xee9cc libhermes.so (hermes::vm::HadesGC::Executor::worker() [__mutex_base:365])
#05 pc 0xee918 libhermes.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, hermes::vm::HadesGC::Executor::Executor()::{lambda()#1}> >(std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, hermes::vm::HadesGC::Executor::Executor()::{lambda()#1}>) [HadesGC.cpp:1050])
#06 pc 0xafce8 libc.so 
#07 pc 0x502c8 libc.so 
```
- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version:
React Native version (if any): 0.67.3
OS version (if any): 0.9.0
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce

Steps to reproduce are unknown, there appear to be a lot of paths users take to reach this error, but it appears to happen on low end devices with limited memory (devices like moto g(8), Galaxy S6, Galaxy S8 running Android 7, 8 & 11 but likely more OS versions we just didn't have this version of RN + Hermes running for too long since the crashes were too frequent)

## The Expected Behavior
The app doesn't crash with around 30-50mb free memory.

**Comment by neildhar** [comment]
Hi @armadilio3, thanks for reporting this. What version of RN and Hermes were you previously on?

From the trace, it looks like Hermes is failing to allocate a thread for its background GC. Is there a crash message or reason given in the trace?

I also noticed that you mentioned the issue appears on armv7 as well. Could you share a stack trace from that platform?

**Comment by armadilio3** [comment]
@neildhar My bad, I wen trhough Firebase again and I couldn't find armv7 reports, I've updated the description to not include that arch.

> What version of RN and Hermes were you previously on?

I think it was RN 0.63.x and Hermes 0.5.1

> Is there a crash message or reason given in the trace? The crash seems to be happening in libc.

This is the only message we see. Everything else on all other threads has no information on what was going or what happened.

**Comment by neildhar** [comment]
Unfortunately, it's hard to say why this would be happening. Are you seeing crashes on these devices at a higher rate overall? Hermes 0.9 uses significantly less memory than Hermes 0.5 so we would expect it to do better on resource constrained devices.

**Comment by armadilio3** [comment]
We have seen OOM crashes in third party modules that we have addressed, it's possible that our fixes to our previous OOM crashes have let the users progress further which now crashes in Hermes itself. 
We still have some memory improvements that we are going to try with the next release, could this just be a low memory issue and not a bug in hermes?

**Comment by neildhar** [comment]
Unfortunately, there isn't enough information to say anything for certain. But it is certainly possible that the app is just running out of memory.

Closing this for now, but feel free to reopen it if you find strong evidence of a Hermes bug here.
