### ISSUE TITLE
couldn't find DSO to load: libhermes.so caused by: dlopen failed: library "libjsi.so" not found result: 0

### ISSUE THREAD

**Issue by cs-robert** [facebook/hermes#726]
## Bug Description

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.11.0
React Native version (if any):
OS version (if any): android  8.0
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

## Steps To Reproduce

I upgrade  hermes version to 0.11.0,it crash when execute         System.loadLibrary("hermes");

code example:

**Comment by neildhar** [comment]
Hi @cs-robert, can you share a little more about your setup? Is this happening in RN?

It seems like libjsi.so is not being included in your app, if so, this is likely an issue with the RN build.

**Comment by cs-robert** [comment]
it is not a RN project,I Just use hermes as a js engine

**Comment by neildhar** [comment]
Got it, recent versions of Hermes split out libjsi.so into a separate file, so you'll need to make sure your build is set up to include libjsi.so in the app.

If you'd prefer not to ship libjsi.so, you could consider building Hermes from source and statically linking in JSI. This flag controls the behaviour: [link](https://github.com/facebook/hermes/blob/2a46912e2647208143ad4c0429e6b0676f94d8e8/android/hermes/build.gradle).

You can see how to build and package Hermes as an Android library [here](https://github.com/facebook/hermes/blob/main/doc/ReactNativeIntegration.md#package-build).
