### ISSUE TITLE
Array concatenation exception

### ISSUE THREAD

**Issue by YiWen-y** [facebook/hermes#729]
###### Version

0.10.0

###### Execution steps 

    .jsvu/hermes Testcase.js

###### Test case 1

```js
var foo = function(it) {
    var a = [...it, , ];
    print(a);
    print(a.length);
};
var Parameter0 = [1, 2];
foo(Parameter0);
```

###### Output 1

```
1,2
2
```

###### Expected behavior

```
1,2,
3
```

###### Test case 2

```js
var foo = function(it) {
    var arr = [ , ];
    var a = it.concat(arr);
    print(a);
    print(a.length);
};
var Parameter0 = [1, 2];
foo(Parameter0);
```

###### Output 2

```
1,2,
3
```

###### Description

I tested on multiple JS engines, test case 1 and test case 2 have the same semantics, they should have the same output. But Hermes outputs abnormal results when executing test case 1.

**Comment by neildhar** [comment]
Thanks for reporting this, it is indeed a bug in our array literal handling. We'll fix it shortly.
