### ISSUE TITLE
Interpret Javascript on a native app

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [facebook/hermes#734]
## Problem

I was looking around for Android's version of iOS's JavaScriptCore, but there isn't a package available that is maintained. Is Hermes able to run as a JS interpreter in a native app? Current alternatives are LiquidCore and AndroidJSCore, but they're unmaintained or archived.

I'm wondering if anyone's tried to use Hermes as an interpreter for their native Kotlin app, and, if so, could anyone help point me in the right direction. The use is to take advantage or the event driven nature of JS. Please let me know if this is out of scope. Thank you.

**Comment by neildhar** [comment]
@Andrew-Chen-Wang It's certainly possible to use Hermes in a native app on any platform. Hermes is available as a JS interpreter in React Native for instance. I recommend taking a look at React Native's Hermes integration if you're looking for an example of how to consume Hermes.

**Comment by Andrew-Chen-Wang** [comment]
Gotcha, thank you. I'll write some tutorial up if I get this working on a base app (though it's not necessary for us yet).
