### ISSUE TITLE
Wrong source map with hermes

### ISSUE THREAD

**Issue by kopax-polyconseil** [facebook/hermes#744]
## Bug Description

We are having wrong sourcemaps with hermes and I have created 3 reproduction to the sentry team, but it might be related to this package `hermesc` program.

It seems it is not possible to get the proper source map yet, even with a basic reproduction: 

See here for all details : https://github.com/getsentry/sentry-react-native/issues/2087

It would be nice to have one author thought.

Thanks!

**Comment by tmikov** [comment]
I am sorry, we are not really familiar with Sentry. Can you please explain what the problem is in the context of Hermes? What parameters are you passing to the compiler, what is the desired output, etc?

**Comment by kopax-polyconseil** [comment]
Hello, we have raised the issue to sentry team and help them trouble shoot, they fixed their doc and scripts, now it work as described in the documentation. Thanks for replying a year later ^^

**Comment by tmikov** [comment]
@kopax-polyconseil sorry, some issues fell through the gaps. We are improving our processes so this shouldn't happen again.
