### ISSUE TITLE
No longer include FindPythonInterp (deprecated since CMake 3.12), use FindPython instead

### ISSUE THREAD

**Issue by leotm** [facebook/hermes#748]
## Bug Description

- https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2720711

- [ ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: `hermes-2022-04-28-RNv0.69.0-15d07c2`
React Native version (if any): `0.69-rc.0`
OS version (if any): `macOS 12.3.1`
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

- https://github.com/reactwg/react-native-releases/discussions/21#discussioncomment-2720711

## The Expected Behavior

Python3 found, Hermes installed successfully

**Comment by leotm** [comment]
cc @neildhar @tmikov 

any pointers on going about the fix replacing `FindPythonInterp` with `FindPython2` (possibly `FindPython`) and `FindPython3` appreciated!

**Comment by mikehardy** [comment]
possibly useful note: reporter on road to 0.69 issue indicated FindPython worked when they tried it - no indication (yet) if FindPython3 would work. I guess it would be preferred but there is an implication there that some python-2-isms may not work without forward port to pyrhon3

**Comment by neildhar** [comment]
Thanks for reporting this, I saw this mentioned on the RN 0.69 release discussion. We actually only recently bumped our minimum CMake version past 3.12, so this hadn't been updated yet. https://github.com/facebook/hermes/pull/749 will make the proposed change.
