### ISSUE TITLE
Performance issues with Hermes in iOS

### ISSUE THREAD

**Issue by amanBhawsar** [facebook/hermes#751]
## Bug Description

After enabling Hermes the performance of our app has deteriorated. On some screens the performance of the app has become worse, the number of re-renders have increased 10X time. The RAM consumption is also very high for us in Hermes.

### Context

Our app has many updates via sockets. With JSC, there are no issues with re-render of components but as soon as we switch to hermes. The number of re-renders has increased significantly because of which our JS thread gets choked and app becomes unresponsive. We also tried disabling sockets but still Flatlist performance is compromised when scrolling fast and doing any action on UI like a button press or opening a modal the JS thread goes complete down but with JSC there are no such issues.

We tried for creating a repro, but couldn’t do it. We know how hard it is for you all to help us without it but can you please point to the direction where we can look at...

#### Videos:
[JSC - JavaScript Thread not getting blocked, it drops on fast scroll but recovers.
](https://drive.google.com/file/d/1aCMFAn7mYatx7dty1Ri973rexxS4KRSG/view?usp=sharing)[Hermes - High RAM consumption + JS thread FPS 0](https://drive.google.com/file/d/1unKBVI2_OEAP6_nte3jvP8F_XEdgX0E5/view?usp=sharing)

**RN Version**: "0.66.4"

**Comment by neildhar** [comment]
Hi @amanBhawsar, to start, could you try comparing the performance on a real device? I believe JSC is able to JIT in an emulator, but not on physical devices, so comparing on device will be more realistic.

**Comment by amanBhawsar** [comment]
Hi @neildhar , 

Thanks for your reply.
Tried running on real devices. We are getting the same issue on affected screens.

**Comment by neildhar** [comment]
Hi @amanBhawsar, a repro would really help here, ideally a standalone JS file that we can examine outside the context of an app. Is there any chance you're able to isolate the behaviour you're running into?

It would also be helpful if you're able to run the allocation profiler in XCode's Instruments. That can give us a sense for which types and sizes of allocations are contributing to high memory consumption.

**Comment by neildhar** [comment]
Actually, I noticed in your videos that you are using the RN performance monitor. I just discovered that the monitor is most easily available through the dev menu, which means the app may have been built in a debug configuration. Can you confirm whether the app is being built in release mode or debug mode?

RN apps built in release mode use optimised precompiled bytecode with Hermes, which make execution much faster. In debug mode, Hermes consumes JS from source and does not perform any optimisations, so performance can be much worse.

**Comment by amanBhawsar** [comment]
Hi @neildhar, we have got the issue. Earlier, we were using js bundle instead of bytecode. 
Thanks for your help.

**Comment by nitish24p** [comment]
@amanBhawsar Did you have to run any other command for converting to hbc file.. Doesnt the bundle release command for react native already do this.. i.e convert to byte code
