### ISSUE TITLE
[Crash] can't find libhermes.so in certain cases (64bit?)

### ISSUE THREAD

**Issue by MayrPatrick** [facebook/hermes#76]
### **Context:** 
we're having a **hybrid app** (native + RN), that is using **React Native 0.60.4** and **Hermes** for the RN part. 

### **Current behavior/problem:**
the release build (universal APK) that incorporates the Hermes "adaptions" (= switch) is working fine for a big chunk of our userbase but crashes for the others. 

**crashMessage:** 
mostly: `couldn't find DSO to load: libhermes.so`, 
whereas other users have a slightly different message: 
```
couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed:"/data/data/.../lib-3/libc++_shared.so" is 32-bit instead of 64-bit
```
(could also be lib-1, lib-2, ...).

**Additional info:** 
- crashLocation: `SourceFile line 738 in com.facebook.soloader.SoLoader.ॱ`
- crashException: `java.lang.UnsatisfiedLinkError`

### **What we did:**
**a.)** switching the "enableHermes" flag from _false_ to _true_

**b.)** add a couple of _pickFirst_ entries to the _build.gradle_ file 
```
packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    }
```
(similar to what https://github.com/facebook/react-native/issues/25601#issuecomment-516317789 suggested/did)

**c.)** we had to order the dependencies within the _dependencies.gradle_ file as follows (excerpt)
```
dependencies {
	api 'com.facebook.react:react-native:0.59.10'
	// Workaround for using Hermes as JS engine
	api fileTree(dir: 'libs', include: '*.aar')
	api 'com.facebook.react:react-native:0.60.4'
```

**Comment by kele86838437** [comment]
Maybe your project has different so files between 32 bit and 64 bit.

**Comment by PatrickBic** [comment]
they seem to be correct :-/ 

I pulled the (installed) apk from a phone via `adb pull ... ` and after unpacking it, compared the libs with the ones from the hermes-release.aar package. They are identical and therefore I'm thinking that those are fine.

**Comment by gbalduzzi** [comment]
I'm facing a similar situation. I'm using react native `0.62.0` and in my `app/build.gradle` I had to set those pickFirst to solve some linking problems:

```
packagingOptions {
        pickFirst 'lib/x86_64/libjsc.so'
        pickFirst 'lib/x86/libjsc.so'
        pickFirst 'lib/arm64-v8a/libjsc.so'
        pickFirst 'lib/armeabi-v7a/libjsc.so'
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }
```

I correctly published my app on the store and now I'm getting crash on some devices with android 5 and android 6. 

Interestingly enough, **all the devices I got the error with were running an Intel Atom chipset** (not sure if relevant).

The error:
```
java.lang.UnsatisfiedLinkErrorSoLoader.java:789
couldn't find DSO to load: libhermes.so caused by: APK was built for a different platform
```

**Comment by roots-ai** [comment]
Any updates herE?
