### ISSUE TITLE
Promise.allSettled and Promise.any is undefined

### ISSUE THREAD

**Issue by retyui** [facebook/hermes#766]
That super weird that a fresh method from **ES2022** `Object.hasOwn` was implemented, but methods of perv. ecmascript spec not implemented yet:
- `Promise.allSettled(...) // ES2020`
- `Promise.any(...) // ES2021`

## Bug Description

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.11.0
React Native version (if any): 0.69.0
OS version (if any): Android 11
Platform: arm64-v8a, armeabi-v7a, x86, x86_64

## Steps To Reproduce

```tsx
const object1 = {prop: 'exists'};

console.log(Object.hasOwn(object1, 'prop')); // true
console.log(Object.hasOwn(object1, 'toString')); // false

Promise.allSettled([]); // TypeError: undefined is not a function, js engine: hermes
Promise.any([]);        // TypeError: undefined is not a function, js engine: hermes
```

## The Expected Behavior

```
// `Promise.allSettled, Promise.any` works without any exceptions
```

**Comment by SMKH-PRO** [comment]
Promise.allSettled is undefined in React-Native 0.68.2 with hermes enabled.

Any solution to this?

**Comment by retyui** [comment]
you need to install and apply custom polyfill for that methods

**Comment by ljharb** [comment]
eg https://npmjs.com/promise.any and https://npmjs.com/promise.allsettled

**Comment by retyui** [comment]
@ljharb also be careful with these polyfills

- [promise.allsettled - 41.5kB](https://bundlephobia.com/package/promise.allsettled@1.0.5) 
- [promise.any - 48.9kB](https://bundlephobia.com/package/promise.any@2.0.4) 

As their size too big(  `48.9kB` is 7 React's (`6.4kB`)!!!

**Comment by ljharb** [comment]
@retyui and those 25 lines are incorrect, per spec. They also break if `delete Promise.all` has been ran, which is also incorrect.

This thread isn't the place to debate it, though.

**Comment by retyui** [comment]
- `Promise.allSettled` - added  ([0.68.4](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0684),  [v0.69.6](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0696), 0.70.x+)https://github.com/facebook/react-native/pull/34544
- `Promise.any` -  I hope will be added soon https://github.com/facebook/react-native/pull/35080

**Comment by retyui** [comment]
Re open issue:

reason: https://github.com/facebook/hermes/issues/766

**Comment by fbmal7** [comment]
So, a bit of context for how we handle Promise. We actually do use a modified version of a polyfill, based on [this implementation](https://github.com/then/promise/blob/8.2.0/src/es6-extensions.js). So, Hermes actually has had support for `allSettled` and `any`.

- `allSettled` was introduced [here](https://github.com/facebook/hermes/commit/e8fa81328dd630e39975e6d16ac3e6f47f4cba06), Sep 7th.
- `any` was introduced [here](https://github.com/facebook/hermes/commit/e97db61b49bd0c065a3ce7da46f074bc39b80c6a), Oct 27th.

So, this does make sense that they have not made their way into the most recent versions of RN, at least specifically for `any`. However, `allSettled` may have had a chance to make it in.. Let me see if I can find the cut dates for the recent releases.

**Comment by fbmal7** [comment]
@retyui  So to follow up, this behavior you are experiencing is expected for the version you are using. RN 0.70 was first cut on [Jul 15th](https://github.com/facebook/react-native/compare/main...0.70-stable). RN 0.71 is not fully released yet, but the first release candidate was cut on [Nov 3rd](https://github.com/facebook/react-native/compare/main...0.71-stable).

Therefore, you can expect `Promise.allSettled` and `Promise.any` for RN 0.71+, and not in any version below. At least, this is purely from the Hermes' side of things. I'm not sure if there are any additional polyfills that RN includes when Hermes is present that could add support for these methods in other versions, but that would be question for RN.

**Comment by retyui** [comment]
got it, should be fixed in react-native@0.71.x

**Comment by n-kulic** [comment]
> got it, should be fixed in [react-native@0.71.x](mailto:react-native@0.71.x)

I have tested with `"react-native": "0.70.6"` on Android (Samsung Galaxy s9) physical device and it appears that `allSettled` is still undefined as I'm getting that error
```ts
Promise.allSettled([])
```

```diff
-[TypeError: undefined is not a function]
```

**Comment by neildhar** [comment]
@n-kulic as mentioned above, this feature is available in RN versions 0.71 and newer. Version 0.70.6 is older than the minimum version that supports this feature.

**Comment by leeyyl** [comment]
@neildhar No it's wrong because I use RN 0.71.7 and I got the same issue as @n-kulic said.

**Comment by tmikov** [comment]
@leeyyl as you can see here https://github.com/facebook/hermes/blob/eaf662b316f2f6333ecb8fb6e17e6f3779367372/lib/InternalBytecode/01-Promise.js#L331 , it is present in Hermes. According to the Git blame it was added here https://github.com/facebook/hermes/commit/e8fa81328dd630e39975e6d16ac3e6f47f4cba06 on Sep 7th 2022.

**Comment by leeyyl** [comment]
> @leeyyl as you can see here
> 
> https://github.com/facebook/hermes/blob/eaf662b316f2f6333ecb8fb6e17e6f3779367372/lib/InternalBytecode/01-Promise.js#L331
> 
> it is present in Hermes. According to the Git blame it was added here [e8fa813](https://github.com/facebook/hermes/commit/e8fa81328dd630e39975e6d16ac3e6f47f4cba06) on Sep 7th 2022.

@tmikov So how to use the `core.allSettled` in Hermes?

**Comment by tmikov** [comment]
@leeyyl As I explained, Promise.allSettled has been available in Hermes since September 2022. Download any version of Hermes, compile and run the CLI and see for yourself.

Which version of Hermes is packaged with each RN release is an orthogonal question. You might be using a version of RN without it, or there might be a polyfill that is overwriting Promise, or something else could be wrong in your setup. 

We are unable to investigate problems that are outside of Hermes, so consider filing an issue with React Native. They might know what is going on, might be able to pick this change in one of their point releases, etc.
