### ISSUE TITLE
'short' formatting  for Intl.NumberFormat not working (number, currency)

### ISSUE THREAD

**Issue by Kisilov-Vadim** [facebook/hermes#768]
## Bug Description

  Intl.NumberFormat working not correct with short formatting style for numbers and currencies, next options:
```
{
  notation: 'compact',
  compactDisplay: 'short',
  currency?: 'USD',
  style?: 'currency',
}
```

Hermes version: 0.9.0
React Native version (if any): 0.66.4
OS version (if any): iOS 15.5 (Simulator)

## Steps To Reproduce
code example:

```
Intl.NumberFormat('en', {
  currency: 'USD',
  style: 'currency',
  notation: 'compact',
  compactDisplay: 'short',
}).format(val)
```

Return the next formated values:
1000 -> $1,000.00
235789 -> $235,789.00
1000000 -> $1,000,000.00
1000000000 -> $1,000,000,000.00

Expected return values:
1000 -> $1K
235789 -> $235.8K
1000000 -> $1M
1000000000 -> $1B

**Comment by neildhar** [comment]
Hi @Kisilov-Vadim, Hermes 0.9.0 does not support Intl on iOS, are you using an Intl polyfill?

The next release of RN will contain Hermes with Intl support on iOS, but unfortunately, the functionality you mention here is still unsupported, because there is no way to get it from the system APIs on iOS.

**Comment by vijayradke** [comment]
@Kisilov-Vadim  Please check - [](https://github.com/kerrmarin/nmbr-icu) this might be helpful.

**Comment by Ishchenko-Vladislav** [comment]
Android exemple:
Intl.NumberFormat('en', {
  currency: 'USD',
  //style: 'currency', //< delete style
  notation: 'compact',
  compactDisplay: 'short',
}).format(val)

**Comment by jgo80** [comment]
Why was this one closed? is this a "won't fix"? I tried a JS polyfill, but it's insanely slow.
