### ISSUE TITLE
Chrome profiling doesn't work

### ISSUE THREAD

**Issue by janicduplessis** [facebook/hermes#769]
## Bug Description

When using the chrome profiler (or Flipper) stopping the profiler hangs forever. After having a look it seems like `serializeInDevToolsFormat` never returns.

Hermes version: main branch
React Native version (if any): main branch
OS version (if any): any
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): any

## Steps To Reproduce

Not sure if possible to repro here directly, but I can repro in the RNTester app in the react-native repo.

Here's the repro steps for iOS, I can also repro on Android:

1. Follow the instructions in https://github.com/facebook/react-native/tree/main/packages/rn-tester#running-on-ios to run RNTester. Make sure to run `yarn setup-ios-hermes` so it uses hermes.
2. Using the latest Flipper version, go to Hermes Debugger -> Profiler tab -> Start -> Stop

## The Expected Behavior

The profiler stops and show the profile data.

**Comment by rjdestigter** [comment]
@janicduplessis Did you manage to resolve this for yourself?

**Comment by janicduplessis** [comment]
It should work in latest version of react native
