### ISSUE TITLE
will hermes support JSContextGroup?

### ISSUE THREAD

**Issue by cs-robert** [facebook/hermes#771]
## Problem

  I have a jscontext ,i want to create a new context ,and  share all values with the old one.

## Solution

 V8 and jsc can support this 

## Additional Context

JSContextGroupRef

**Comment by jpporto** [comment]
Hi @cs-robert,

Hermes doesn't support sharing JavaScript objects between runtimes, and there are no plans to do so.

John Paul

**Comment by cs-robert** [comment]
hi,  @jpporto how about  clone a jscontext?
