### ISSUE TITLE
Need support '.mjs'

### ISSUE THREAD

**Issue by jp928** [facebook/hermes#780]
## Problem

I am using repack which is a webpack based js bundle tool. When I integrate with GraphQL library and add '.mjs' in the extension. The js doesn't work.

## Solution

I disabled hermes for time being because I can't find a solution.

## Additional Context

The GraphQL throws error GraphqlError doesn't exist.

**Comment by SimpleCreations** [comment]
I might be wrong but I don't think this issue belongs in the Hermes repository. Hermes is a JS runtime/compiler and is agnostic of file extensions; it does not resolve JS modules in React Native applications and only processes the bundle that is put together by the Metro bundler (or repack in your case).

I believe the next step for you is to check your repack configuration to make sure the _.mjs_ files are resolved properly and/or raise this issue in the repack's repository.

**Comment by jpporto** [comment]
Closing this issue as it is not a hermes issue.
