### ISSUE TITLE
eval() function is not compatible with hermes in iOS

### ISSUE THREAD

**Issue by Yandamuri** [facebook/hermes#785]
### Description

I have `hermes` enabled in my `iOS` project and trying to execute following code snippet,

     let testCall = () => this.testCall();
     let funct = '{() => testCall()}';   // function in string format
     let finalFunc = eval(funct);

Now, If I execute the `finalFunc()` then am getting following error,

   
![Simulator Screen Shot - iPhone Xs Max - 2022-07-22 at 12 52 47](https://user-images.githubusercontent.com/31983789/180386153-e5eee6ed-3b2d-4565-890a-7c0ed694f6b7.png)

But if I  I execute the `finalFunc()` when `hermes` is disabled then `testCall()` function is called successfully.

Note: In `Android` there is no issue no matter `hermes` is enabled or disabled.

### Version

0.67

### Output of `npx react-native info`

    System:
         OS: macOS 11.6
         CPU: (8) x64 Apple M1
         Memory: 40.87 MB / 8.00 GB
         Shell: 5.8 - /bin/zsh
    Binaries:
        Node: 12.22.1 - /usr/local/bin/node
        Yarn: Not Found
        npm: 6.14.12 - /usr/local/bin/npm
       Watchman: Not Found
    Managers:
           CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
     SDKs:
          iOS SDK:
          Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
          Android SDK: Not Found
    IDEs:
          Android Studio: 4.2 AI-202.7660.26.42.7351085
          Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    Languages:
          Java: 11.0.10 - /usr/bin/javac
    npmPackages:
          @react-native-community/cli: Not Found
          react: 17.0.2 => 17.0.2 
          react-native: 0.67.0 => 0.67.0 
          react-native-macos: Not Found
          npmGlobalPackages:
          *react-native*: Not Found

### Steps to reproduce

1. Kindly clone the reproducible demo

2.Once the project is ran you will be able to see a text called 'Button'

3.Just tap on the button then you will face the error which is in above screen shot

### Snack, code example, screenshot, or link to a repository

Please find the reproducible demo here - -https://github.com/Yandamuri/Test-Hermes-In-IOS

**Comment by cortinico** [comment]
Moving this over to facebook/hermes for further support. @neildhar could you answer this?

**Comment by jpporto** [comment]
Hi @Yandamuri,

Hermes [doesn't support](https://github.com/facebook/hermes/blob/main/doc/Features.md#excluded-from-support) local eval -- so eval can't use locals, nor define new ones.

John Paul

**Comment by Yandamuri** [comment]
@jpporto Thank you for your response.

I didn't understand that what is `local eval`. Do you meant to say that there is a way(alternative) to use `eval()` with `hermes`?

**Comment by jpporto** [comment]
Hi,

Hermes' eval doesn't let you use local variables defined outside of the eval string, and it won't introduce variables in the outside scope. In other words: eval in hermes is non-confirming (w.r.t. the JS spec). There are no alternatives to eval.

John Paul

**Comment by EduFrazao** [comment]
Hi @Yandamuri .
I do some dynamic evaluation here, but not with eval, only with ```new Function()```
But off course, I select the "variables" that I want to provide acess on dynamic scripts, and inject those on my constructor.
Works fine with Hermes.

**Comment by Yandamuri** [comment]
@EduFrazao Thank you for your response

Can you please provide a small snippet of code how you do dynamic evolution without hermes?

**Comment by tmikov** [comment]
Local eval support is planned in future versions of Hermes, but at this time unfortunately we cannot commit to a timeframe. Closing this task, as spec compliance is tracked separately.

**Comment by PauloBarroso85** [comment]
Any update on making eval supported in Hermes?

**Comment by tmikov** [comment]
Global eval (`eval()` at the global scope or `new Function()`) has always been supported. We are slowly making progress towards enabling local eval, but frankly view it as fairly low priority. 

Local `eval()` compromises the performance of all surrounding functions, because variables can no longer be optimzed.

**Comment by fesaza** [comment]
any update on this? :) to support eval

**Comment by tmikov** [comment]
We don't have concrete plans to support local eval(), since frankly it contradicts the goals of the project - Hermes is primarily an ahead of time compiler. The changes and additional complexity necessary for local eval() are staggering.

For some context, we technically already support local eval() in some sense, since that is what is used by the debugger to evaluate variables, etc. However this relies on running from source. Once the source is compiled to bytecode, all the necessary metadata is gone and we would need a completely new mechanism to serialize and deserialize it.
