### ISSUE TITLE
Why isn't there a latest release package for all three platforms (Linux/Windows/MacOS)?

### ISSUE THREAD

**Issue by whatleo** [facebook/hermes#787]
As mentioned above！

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/4222370/181226637-8660cec7-927c-4fb0-9fb0-22358deab4da.png">

**Comment by micahlt** [comment]
This is a valid question!  0.69.x has been out for a while - it'd be great to have Hermes support for it!

**Comment by neildhar** [comment]
@micahlt Since RN 0.69, RN builds and bundles Hermes separately, so the Hermes release process is decoupled from the RN releases. That is, RN 0.69 and RN 0.70 already support Hermes, with Hermes being the default for new app templates in RN 0.70. 

That said, we're planning to cut a new release for the CLI in the next few days.

**Comment by micahlt** [comment]
Gotcha - so just to clarify, Hermes can be set up as described in the documentation on the RN site even though it hasn't individually been released?

**Comment by neildhar** [comment]
@micahlt Yes, that is unchanged.

**Comment by monomichael** [comment]
> @micahlt Since RN 0.69, Hermes is distributed as part of RN and does not need to be installed separately. So we no longer need to distribute a separate Hermes release corresponding to each RN version.
> 
> That is, RN 0.69 and RN 0.70 already support Hermes, with Hermes being the default for new app templates in RN 0.70.
> 
> That said, we're planning to cut a new release for the CLI in the next few days.

@neildhar Is there any updates on the release for the CLI? Though building from source is always an option, it would be helpful to have a prebuilt version.

**Comment by fbmal7** [comment]
@monomichael We just published a new release containing all the CLI files 😀
