### ISSUE TITLE
How do I debug the bytecode built by Hermes in the Chrome Debugging tool?

### ISSUE THREAD

**Issue by Ossianaa** [facebook/hermes#797]
I have a index.android.bundle file ,but i don't have source file,

How do I debug the bytecode built by Hermes?

**Comment by mattbfb** [comment]
We don't currently offer an interactive bytecode debugger; the Chrome Dev Tools are used for debugging at the JavaScript level. You can disassemble the bytecode with `hbcdump` to follow the path of execution.
