### ISSUE TITLE
Is there any rust bindens for hermes??

### ISSUE THREAD

**Issue by David00154** [facebook/hermes#798]

**Comment by mattbfb** [comment]
Hi @David00154, 

We don't currently publish any official bindings or wrappers for Rust. There is some use of the Hermes parser that may be of interest (https://github.com/facebook/hermes/tree/6c530474a450a12dbf1b58b8c5a41cf9ad64ec8a/unsupported/juno/crates/hermes), but not a full binding for all of Hermes.
