### ISSUE TITLE
Preseed the compiler about possible runtime data structures

### ISSUE THREAD

**Issue by blainekasten** [facebook/hermes#816]
## Problem

We've found that our current implementation of graphql queries through apollo incur a huge execution time with hermes. There are surely performance improvements to be done within apollo, but i'm suspecting that the performance degradation within hermes _might be_ from not being able to optimize these data structures at build time.

## Solution

_if_ i'm correct in that assumption, would it make sense to be able to feed the hermes compiler information about the data structures that may appear from things like network requests?

## Additional Context

I have sampling_profiles that can show the work apollo is doing if that helps. Ultimately it's looping over all of the data and "normalizing" it into a cache. 

related: https://github.com/apollographql/apollo-client/issues/7951

**Comment by jpporto** [comment]
Hi,

What do you mean by "optimize these data structures at build time"? I am not aware of any current optimizations in the hermes compiler that would benefit from it knowing about object shapes, but maybe I am misunderstanding your suggestion.

Hermes' sampling profiles can be used for optimizing your JS source code, and native profilers (e.g., gprof, vtune) are useful for identifying how the native application (including the hermes VM) can be improved.

John Paul
