### ISSUE TITLE
console.log of objects/arrays not working on iOS targets and Flipper

### ISSUE THREAD

**Issue by elrony** [facebook/hermes#817]
Hello,

I have recently upgraded my react native app to 0.70.1 and noticed that console.logs of objects and arrays do not work properly with Flipper on an iOS Simulator/Device - Android works as expected.

The log for objects and array shows in the console but when the expand icon is pressed nothing happens.

Hermes version: 0.70.1
React Native version (if any): 0.70.1
OS version (if any): macOS 12.6 (intel)
XCode: 14
Flipper: 0.166.0
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): x86_64

## Steps To Reproduce

create a new RN 0.70.1 app and console.log objects or arrays, run on an iOS Simulator.

example
```
useEffect(() => {
  console.clear();
  console.log('object', { a: 1 });
  console.log('array', [1, 2, 3]);
}, []);
```
## The Problem
iOS
https://user-images.githubusercontent.com/5883791/191434982-77a941eb-e1f5-4bc0-8852-d0112a7bcedb.mp4

## The Expected Behavior
Android
https://user-images.githubusercontent.com/5883791/191435337-48c0b72a-81a3-4769-b252-304c26223c54.mp4

**Comment by mattbfb** [comment]
We can reproduce this locally and have a fix in progress. Thanks for reporting this!

**Comment by mgvictor7** [comment]
Hi!

I have the same error on IOS.
On Android work well.

Hermes version: 0.70.1
React Native version: 0.70.1
OS version: macOS 12.6 (Mac mini (M1, 2020))
XCode: 14
Flipper: 0.166.0

thank you

**Comment by mgvictor7** [comment]
> We can reproduce this locally and have a fix in progress. Thanks for reporting this!

Any news about this bug??

**Comment by mattbfb** [comment]
@mgvictor7 We have a fix in the works that should address the issue. I'll follow up here when it merges.

**Comment by traxx10** [comment]
Same issue

**Comment by Mladen1kus** [comment]
Hi @mattbfb, any updates on this? Do you know in which version this fix will come out or if we can do anything about this until the fix comes online?

**Comment by mattbfb** [comment]
@Mladen1kus The fix is still in the works. I can't yet say for sure which future version will include it, but I can post the changes here when they are merged, as you may be able to apply them locally before they are included in an official release.

**Comment by kirx76** [comment]
> @Mladen1kus The fix is still in the works. I can't yet say for sure which future version will include it, but I can post the changes here when they are merged, as you may be able to apply them locally before they are included in an official release.

Yep, we need that fix locally, post it.

**Comment by invyctus92** [comment]
With flipper 0.173.0, Xcode 14.1, and react native 0.70.4 it now works correctly. Thanks

**Comment by Mladen1kus** [comment]
> With flipper 0.173.0, Xcode 14.1, and react native 0.70.4 it now works correctly. Thanks

Hi @invyctus92 , did you make any local changed? I'm on flipper 0.173.0, Xcode 14.0.1 and RN 0.70.5 but still no luck.

**Comment by invyctus92** [comment]
> > With flipper 0.173.0, Xcode 14.1, and react native 0.70.4 it now works correctly. Thanks
> 
> Hi @invyctus92 , did you make any local changed? I'm on flipper 0.173.0, Xcode 14.0.1 and RN 0.70.5 but still no luck.
> 
> Edit: only difference i see is Xcode version (will try to update) and RN 0.70.5 which is a hotfix.

With Xcode updated to 14.1 , it should solve

**Comment by numandev1** [comment]
> @mgvictor7 We have a fix in the works that should address the issue. I'll follow up here when it merges.

we need that fix locally, post it.

**Comment by StephenTANM** [comment]
Still having this issue

**Comment by tusharmutreja200** [comment]
Guys, do we have any update on this issue ?

**Comment by mattbfb** [comment]
The issue did not end up being isolated to a specific message (although the most common place it appears is in console log messages), so we are building a fix that will correctly fix it for all instances. We don't have a concrete ship that for that change right now.

**Comment by Darren120** [comment]
bruh +1
;plz

**Comment by quoctruongkt** [comment]
Is there any latest fix for this issue. I'm using Flipper 0.177.0, xcode: 14.2, RN: 0.73 and this issue is unresolved

**Comment by StephenTANM** [comment]
I don't know if this works for anyone else but I switched from using my wifi extender to connecting to the modem and rebuilt my project and it seems to have fixed the problem for some odd reason.

**Comment by numandev1** [comment]
@mgvictor7 is there any chance?

**Comment by WooMinGy** [comment]
I have same issue both of Android and iOS

**Comment by mattbfb** [comment]
An improved version of CDP handling has has now landed and current versions of Hermes and React Native should no longer exhibit this behavior. Please comment if this issue reappears.

**Comment by dannyhw** [comment]
still getting this on 0.73.4, is the fix out in a react native version?
