### ISSUE TITLE
Crashed: Thread :  SIGABRT  0x0000000000000000 from Crashlytics

### ISSUE THREAD

**Issue by Vietvantue** [facebook/hermes#818]
## Bug Description
We observe crashes on Firebase Crashlytics have relevant log to Hermes.

Hermes version: 0.11
React Native version (if any): 0.68.2
OS version (if any): Android 12
Device: Galaxy Tab S7 FE
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): 

## Steps To Reproduce

Crashlytics log:

> Crashed: Thread :  SIGABRT  0x0000000000000000
#00 pc 0x519e0 libc.so 
#01 pc 0x519b0 libc.so 
#02 pc 0x6d29ec libart.so 
#03 pc 0x16ea8 libbase.so 
#04 pc 0x6f14 liblog.so 
#05 pc 0x1fefc libhermes-executor-release.so 
#06 pc 0x1ab9d8 libhermes.so 
#07 pc 0x1aba18 libhermes.so 
#08 pc 0x18e144 libhermes.so 
#09 pc 0x3b8a8 libhermes.so 
#10 pc 0xecb7c libhermes.so 
#11 pc 0xf2d64 libhermes.so 
#12 pc 0xf2b7c libhermes.so 
#13 pc 0xf3558 libhermes.so 
#14 pc 0xed52c libhermes.so 
#15 pc 0xe9cd0 libhermes.so 
#16 pc 0xec980 libhermes.so 
#17 pc 0x95368 libhermes.so 
#18 pc 0x93e0c libhermes.so 
#19 pc 0x5a930 libhermes.so 
#20 pc 0x5fe00 libhermes.so 
#21 pc 0xc7f5c libhermes.so 
#22 pc 0xc834c libhermes.so 
#23 pc 0xc8100 libhermes.so 
#24 pc 0xc834c libhermes.so 
#25 pc 0xc8100 libhermes.so 
#26 pc 0xc834c libhermes.so 
#27 pc 0xc8100 libhermes.so 
#28 pc 0xc6c58 libhermes.so 
#29 pc 0x35600 libhermes.so 
#30 pc 0x4f04c libhermes.so 
#31 pc 0x50988 libhermes.so 
#32 pc 0x5017c libhermes.so 
#33 pc 0x35864 libhermes.so 
#34 pc 0x34424 libhermes.so 
#35 pc 0xd5f18 libhermes.so 
#36 pc 0x35600 libhermes.so 
#37 pc 0x4f04c libhermes.so 
#38 pc 0x50988 libhermes.so 
#39 pc 0x5017c libhermes.so 
#40 pc 0x35864 libhermes.so 
#41 pc 0x34424 libhermes.so 
#42 pc 0xd5f18 libhermes.so 
#43 pc 0x35600 libhermes.so 
#44 pc 0x4f04c libhermes.so 
#45 pc 0x50988 libhermes.so 
#46 pc 0x5017c libhermes.so 
#47 pc 0x35864 libhermes.so 
#48 pc 0x350d8 libhermes.so 
#49 pc 0x26918 libhermes.so 
#50 pc 0x29c48 libhermes-executor-release.so 
#51 pc 0x29aa4 libhermes-executor-release.so 
#52 pc 0x20ca4 libhermes-executor-release.so 
#53 pc 0x25d50 libhermes-executor-release.so 
#54 pc 0x957ac libreactnativejni.so 
#55 pc 0x96998 libreactnativejni.so 
#56 pc 0x76be4 libreactnativejni.so 
#57 pc 0x5e7a8 libreactnativejni.so 
#58 pc 0x5e720 libreactnativejni.so

**Comment by jpporto** [comment]
Hi. Would you be able to provide a repro for this?

**Comment by Vietvantue** [comment]
@jpporto Right now I am unable to provide a repo to reproduce it because of the issue we face on the commercial app. We catch the issue from the Crashlytics log.

Just information, by the time the issue happens, our end-user turns off the internet connection, and the app saved every failed network request to redux-persists using AsyncStorage (@react-native-async-storage/async-storage). Do you think any relevance to saving a lot of text to AsyncStorage causes a problem with Hermes?

**Comment by jpporto** [comment]
There is nothing we can do without a proper repro I am afraid.

**Comment by shayananwar** [comment]
also facing the same issue


```
Crashed: Thread :  SIGSEGV  0x0000000000002ec6
#00 pc 0x62758 libhermes.so 
#01 pc 0x54cc0 libhermes.so 
#02 pc 0x54cc0 libhermes.so 
#03 pc 0x5017c libhermes.so 
#04 pc 0x35864 libhermes.so 
#05 pc 0x350d8 libhermes.so 
#06 pc 0x4f070 libhermes.so 
#07 pc 0x50988 libhermes.so 
#08 pc 0x5017c libhermes.so 
#09 pc 0x35864 libhermes.so 
#10 pc 0x350d8 libhermes.so 
#11 pc 0x4f070 libhermes.so 
#12 pc 0x50988 libhermes.so 
#13 pc 0x5017c libhermes.so 
#14 pc 0x35864 libhermes.so 
#15 pc 0x34424 libhermes.so 
#16 pc 0xd5f18 libhermes.so 
#17 pc 0x35600 libhermes.so 
#18 pc 0x4f04c libhermes.so 
#19 pc 0x50988 libhermes.so 
#20 pc 0x5017c libhermes.so 
#21 pc 0x35864 libhermes.so 
#22 pc 0x34424 libhermes.so 
#23 pc 0xd5f18 libhermes.so 
#24 pc 0x35600 libhermes.so 
#25 pc 0x4f04c libhermes.so 
#26 pc 0x50988 libhermes.so 
#27 pc 0x5017c libhermes.so 
#28 pc 0x35864 libhermes.so 
#29 pc 0x350d8 libhermes.so 
#30 pc 0x26918 libhermes.so 
#31 pc 0x29c48 libhermes-executor-release.so 
#32 pc 0x29aa4 libhermes-executor-release.so 
#33 pc 0x20ca4 libhermes-executor-release.so 
#34 pc 0x25d50 libhermes-executor-release.so 
#35 pc 0x957ac libreactnativejni.so 
#36 pc 0x96998 libreactnativejni.so 
#37 pc 0x76be4 libreactnativejni.so 
#38 pc 0x5e7a8 libreactnativejni.so 
#39 pc 0x5e720 libreactnativejni.so 
```

**Comment by RamProg** [comment]
having the same issue

```
Crashed: Thread: SIGSEGV  0x00000000cde3b514
#00 pc 0x7650c libhermes.so 
#01 pc 0x764e4 libhermes.so 
#02 pc 0x2fbb8 libhermes.so 
#03 pc 0x267b0 libhermes.so 
#04 pc 0x19388 libhermes-executor-common-release.so 
#05 pc 0x187f0 libhermes-executor-common-release.so 
#06 pc 0x19a34 librnmmkv.so 
#07 pc 0x1cdb4 librnmmkv.so 
#08 pc 0x440554 libart.so 
#09 pc 0x6ef37a1938  
#10 pc 0x6ef3b8792d  
#11 pc 0x20087c libart.so 
#12 pc 0x20a910 libart.so 
#13 pc 0x6ef37a1938  
#14 pc 0x6ef37a181a  
#15 pc 0x20087c libart.so 
#16 pc 0x20a254 libart.so 
#17 pc 0x6ef37a181a  
#18 pc 0x6ef38894a0  
#19 pc 0x20087c libart.so 
#20 pc 0x20b074 libart.so 
#21 pc 0x80329c libart.so 
#22 pc 0x6ef38894a0  
#23 pc 0x6ef3889330  
#24 pc 0x20087c libart.so 
#25 pc 0x20a254 libart.so 
#26 pc 0x6ef3889330  
#27 pc 0x6ef38889c0  
#28 pc 0x20087c libart.so 
#29 pc 0x209334 libart.so 
#30 pc 0x41e0c libc.so 
#31 pc 0x6ef38889c0  
#32 pc 0x70bcda70  
#33 pc 0x436b6c libart.so 
#34 pc 0x468938 libart.so 
#35 pc 0x540068 libart.so 
#36 pc 0x468620 libart.so 
#37 pc 0x618040 libart.so 
#38 pc 0xa15ffc libart.so 
#39 pc 0xa14ffc libart.so 
#40 pc 0x8cd24 libc.so 
#41 pc 0xb1810 libc.so 
#42 pc 0xc2ffc libc.so 
#43 pc 0x512f0 libc.so 
#44 pc 0xb1704 libc.so 
#45 pc 0x1284f4 ld-android.so 
#46 pc 0x1287f4 ld-android.so 
#47 pc 0x6179b8 libart.so 
```

**Comment by Ramanpreet6262** [comment]
Did you find any fix for them?
