### ISSUE TITLE
`AsyncGenerator`: does not implement `[Symbol.asyncIterator]`

### ISSUE THREAD

**Issue by mfulton26** [facebook/hermes#820]
## Bug Description

`AsyncGenerator` instances in Hermes do not conform to the [async iterable protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols) as they do not implement [[Symbol.asyncIterator]](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator)

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: (How do I look this up? I'm using whatever version I would have after follow [these](https://react-native-community.github.io/upgrade-helper/?from=0.69.5&to=0.70.1) instructions. 0.70.1?)
React Native version (if any): 0.70.1
OS version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

```js
console.log(Symbol.asyncIterator in (async function* () {})());
console.log(Symbol.iterator in (function* () {})());
```

## The Expected Behavior

```console
 LOG  true
 LOG  true
```

## The Actual Behavior

```console
 LOG  false
 LOG  true
```

**Comment by tmikov** [comment]
Hi,
Thank you for reporting this. Hermes doesn't support async generators, which were introduced in ES2018. If I try to compile your example, I get:

```
bug.js:1:38: error: async generators are unsupported
console.log(Symbol.asyncIterator in (async function* () {})());
                                     ^~~~~~~~~~~~~~~~~~~~~
```

We will add them to Hermes, but at this time we don't have a concrete timeline.

**Comment by mfulton26** [comment]
I did not realize that async generators were introduced after generators; thank you for providing that clarity

I didn't see any compilation errors in my React Native project (at build time nor at run time); that might be a separate issue in and of itself

thank you

**Comment by tmikov** [comment]
There is probably a Babel pass for async generators that runs first, so Hermes doesn't see them at all. It is possible that the Babel transform is not fully spec compliant, but still usable?

**Comment by tmikov** [comment]
This will be implemented when we transition to support the corresponding version of EcmaScript.
