### ISSUE TITLE
Enable hermes engine for ios: React native on Mac M1

### ISSUE THREAD

**Issue by MohitGoel9456** [facebook/hermes#824]
After enabling hermes engine in podfile throws error while building app

`"Undefined symbols for architecture x86_64: "vtable for facebook::react::HermesExecutorFactory"`

Hermes version: 0.9.0
React Native version (if any): 0.66.1

**podfile** 
```
platform :ios, '11.0'
    target 'OneSignalNotificationServiceExtension' do
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  end

  target '****' do
  # Pods for ****
  config = use_native_modules!
  use_react_native!(path: config['reactNativePath'])

  use_react_native!(
  :path => config[:reactNativePath],
  # to enable hermes on iOS, change `false` to `true` and then install pods
  :hermes_enabled => true
```
Steps to reproduce:

1. enable hermes : true
2. pod install
3. npx react-native run-ios

I also tried following steps but still getting same error

- sudo arch -x86_64 gem install ffi
- arch -x86_64 pod install

**Comment by mattbfb** [comment]
@MohitGoel9456 this appears to be on a version of React Native from some time ago; are you able to try this on the current version of React Native?

**Comment by MohitGoel9456** [comment]
@mattbfb We don't have any plans to update to the latest version of react native. if we don't have any solution then  we will see.

**Comment by neildhar** [comment]
`HermesExecutorFactory` is implemented by React Native, it would be more appropriate to post in https://github.com/microsoft/react-native-macos
