### ISSUE TITLE
JS thread stalls while using Hermes with iOS on RN 0.68.3

### ISSUE THREAD

**Issue by jkepps** [facebook/hermes#837]
## Bug Description

Similarly to [this issue](https://github.com/facebook/hermes/issues/295), I'm attempting to enable hermes on my react native app, but when I do so, the iOS (iPhone 14 Pro simulator) app freezes for minutes (10-20+ min) with no errors, crashes, or logs of any kind. I've done some profiling as suggested in the issue reference above, and here is the output.

<img width="1136" alt="Screen Shot 2022-10-12 at 1 49 55 PM" src="https://user-images.githubusercontent.com/11086016/195445096-8204980d-5208-4bd9-b541-d59519ce6d98.png">

The nested objects with the highest % of Retained size all cause the `Allocation stack` section to display "Stack was not recorded for this object because it had been allocated before this profiling recording started."

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: unsure
React Native version (if any): 0.68.3
OS version (if any): iOS 16
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): unsure

**Comment by jpporto** [comment]
Hi,

Thank you for reporting this. Can you provide a repro? Otherwise it won't be possible to debug what's going on.

John Paulo

**Comment by jkepps** [comment]
@jpporto  thanks for the quick reply. turns out i wasn't polyfilling the Intl module correctly so the js thread was grinding to a halt while trying to parse some dates shortly after rendering the home screen. I was also on a really old version of Luxon (v1), so I wasn't getting the typical error that most others get when they forget to polyfill 🫠. [This is ultimately what helped me](https://github.com/facebook/hermes/issues/23#issuecomment-1164591009), in case anyone else stumbles upon this same problem.
