### ISSUE TITLE
Some flags are missing documentation

### ISSUE THREAD

**Issue by gibson042** [facebook/hermes#839]
## Bug Description

f811a0e75f19ab0da7dcf969a61db894fbb3cc35 renamed `-fenable-tdz` to `-Xenable-tdz`, but `--help` does not appear to document the flag, resulting in https://github.com/bterlson/eshost/issues/125 .

Hermes version: 0.11.0
React Native version (if any): n/a
OS version (if any): n/a
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): n/a

## Steps To Reproduce
```sh
$ hermes --help | grep tdz
```

## The Expected Behavior
At least one line including "Xenable-tdz".

**Comment by tmikov** [comment]
Hi,
-Xenable-tdz is unsupported and should not be used, it can be seen with "-help-hidden".
