### ISSUE TITLE
Unicode property escapes

### ISSUE THREAD

**Issue by Bardiamist** [facebook/hermes#850]
Unicode property escapes is supports now or no?

I have Ract native 0.70.5 and want to know can I use Unicode property escapes or no.

Looks its works but the [documentation](https://github.com/facebook/hermes/blob/main/doc/RegExp.md#supported-syntax) still say that not supported

**Comment by Bardiamist** [comment]
Looks
```
'a🙂dsf🙂26754 ds+.'.replace(/[^\p{L}\p{Z}\d.+]/gu, '')
```
wokrs as expecting

Result: `adsf26754 ds+.`

Any underwater rocks?

**Comment by jpporto** [comment]
Hi,

Features are added to Hermes independently from RN releases. That means there's always going to be a "gap" between the most recent Hermes and the latest RN release (potentially including point releases, e.g. 0.70.5, as the RN controls what is ported over).

Thus I wouldn't be surprised if Hermes supported the feature but it isn't available in RN yet. Have you tried asking the [RN team](https://github.com/facebook/react-native/) if that's supported in that version?

John Paul

**Comment by Bardiamist** [comment]
@jpporto you can see that I also asked [in rn repository](https://github.com/facebook/react-native/issues/29807#issuecomment-1310145762)

But here would be good if somebody answer: Is Hermes supports `Unicode property escapes` now? If yes then from what version? Then we can see the React native uses this Hermes version or no.

**Comment by fbmal7** [comment]
@Bardiamist  Hermes does not support Unicode property escapes currently. Given that you are experiencing support in some version of RN, that means you are either using JSC or there is some polyfill providing support.
