### ISSUE TITLE
Promise.allSettled is still undefined in 0.70.6 on iOS and Android with Hermes

### ISSUE THREAD

**Issue by Elolawyn** [facebook/hermes#860]
I already opened issue in `react-native` repo and they redirected me to this place.

[Original Issue](https://github.com/facebook/react-native/issues/35363)

Summary: `Promise.allSettled` is undefined in 0.70.6 on iOS and Android with Hermes but works fine when executing tests with jest.

**Comment by fbmal7** [comment]
I'm going to close this issue so we can consolidate the discussion in [766](https://github.com/facebook/hermes/issues/766)
