### ISSUE TITLE
super is invalid expression

### ISSUE THREAD

**Issue by wesleyzeng** [facebook/hermes#87]
class ThrowCompletion extends AbruptCompletion {
    constructor(value, location, nativeStack) {
        _**super(value, location);**_                                                                                                                                                                          
        this.nativeStack = nativeStack || new Error().stack;
    }
}

Evaluate above script. Hermes report "invalid expression".

**Comment by avp** [comment]
`class` is not supported functionality in Hermes yet. We're actively working on adding support for it. 

Please check [Features.md](https://github.com/facebook/hermes/blob/master/doc/Features.md) to see what features are supported in Hermes. 

For more clarification on "in progress" features, see [this comment](https://github.com/facebook/hermes/issues/57).
