### ISSUE TITLE
Deployed doc not up to date with main branch

### ISSUE THREAD

**Issue by ScreamZ** [facebook/hermes#872]
https://hermesengine.dev/docs/language-features/

BIG int are currently supported (https://github.com/facebook/hermes/issues/510#issuecomment-1190033652) and doc is up to date in https://github.com/facebook/hermes/blob/main/doc/Features.md alias for https://github.com/facebook/hermes/blob/HEAD/doc/Features.md which seems to be the HEAD and also the link given in  https://hermesengine.dev/docs/language-features/ to edit the doc

Maybe the CI is failing and not deploying the site for some time?

**Comment by neildhar** [comment]
Redeployed the site in 73e0531f7b617996dd21e1bb775ce77bd796cec4
