### ISSUE TITLE
Garbage collector strategy: Why not consider reference counting?

### ISSUE THREAD

**Issue by wesleyzeng** [facebook/hermes#88]
For mobile device or Lower-end  device, Concurrent Cycle Collection in reference counting maybe has good memory usage.

**Comment by dulinriley** [comment]
When we started the project, we knew an important issue for us to solve was ensuring that
our memory footprint was low.

Using a tracing garbage collector like our current `GenGCNC` allowed us to be able to do a compaction pass over the heap, which moves live data into a compact form that eliminates the effect of fragmentation. After finishing compaction, there is usually some leftover space at the end that we can return to the operating system.
