### ISSUE TITLE
Resolving error: property 'require' doesnt exist

### ISSUE THREAD

**Issue by matthewmturner** [facebook/hermes#884]
## Bug Description

I am working on benchmarking some javascript across different js engines.  I have a single js file and I am running on node and hermes.  The benchmark script reads in some data and runs a loop.  I read in json data (its just an array of data) to an Object with `require` but hermes is saying that `require` does not exist.  Am I missing something here about how hermes works?

Hermes version: output from `hermes --version`
```
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Hermes JavaScript compiler and Virtual Machine.
  Hermes release version: 0.12.0
  HBC bytecode version: 91

  Features:
    Debugger
    Zip file input
```

React Native version (if any): N/A
OS version (if any): macOS 13.0
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): m1 Macbook

## Steps To Reproduce

1. Following the release installation instructions [here](https://hermesengine.dev/docs/building-and-running#executing-javascript-with-hermes)
2. Create the following script:
```
// forLoop.js

const data = require(process.env.DATA);

for (let i = 0; i < data.length; i++) {
    continue;
}
```
3. Run `hermes benchmark.js`
4. See the following output:
```
hermes forLoop.js
Uncaught ReferenceError: Property 'require' doesn't exist
    at global (forLoop.js:3:14)
```

code example:

## The Expected Behavior
The code runs

**Comment by ljharb** [comment]
Why would require exist? that's a node thing, as is process.. I'd expect you to have to bundle for hermes.

**Comment by matthewmturner** [comment]
@ljharb oh thanks for that info, didnt know that but it makes sense. im still new to the JS ecosystem and learning whats part of standard and whats specific to different components :)

maybe im missing it but are their instructions somewhere about bundling for hermes?

**Comment by tmikov** [comment]
FWIW, you can enable CommonJS mode in Hermes by passing the `--commonjs` flag. This will enable `require`, as well as a subset of ES6 module support, but even then you won't be able to "require" JSON data.

**Comment by ljharb** [comment]
@tmikov is that a hermes limitation? in node you can certainly require JSON.

**Comment by matthewmturner** [comment]
@tmikov Thanks much for that info. How would you recommend I read json from a file into an Object with Hermes?

**Comment by tmikov** [comment]
@ljharb yes, the Hermes CommonJS/mini-ESM implementation is different from Node's, it aims to be completely static, i.e. all sources must be passed to the compiler at the same time and are resolved at compile time. There is technically nothing preventing us from supporting JSON files, but:
1. At the time we didn't even realize it was possible, IIRC, the CommonJS "spec" didn't mention it.
2. Since it is completely static, it is easy enough to just prepend `module exports = ` and use `require` as normal.
3. Nobody actually uses the Hermes CommonJS implementation in production, since React Native has its own bundlers...

**Comment by tmikov** [comment]
@matthewmturner Hermes doesn't provide utilities to read or write files, since those are outside of the scope of a JS engine. With that said, if the JSON file is available, you can prepend `module.exports = ` in the beginning and use `require` normally:

```
$ cat data.json
module.exports = { "a" : 10 }

$ cat main.js
var data = require("data.json");

$ hermes --commonjs main.js data.json -emit-binary -out=main.hbc

$ hermes main.hbc
```

Alternatively, Hermes also contains an unsupported tool with a subset of Node functionality in https://github.com/facebook/hermes/tree/main/tools/node-hermes . You might be able to use it, but it is **completely unsupported**.

**Comment by matthewmturner** [comment]
@tmikov apologies for the delay getting back.  thank you very much for providing that example and additional information.

One more quick question, I'm comparing performance of hermes to node and hermes is WAY faster.

Just testing a simple loop:

```
// forLoop.js

let n = 0;
for (let i = 0; i < 100000; i++) {
    n += 1;
}
```

<img width="761" alt="image" src="https://user-images.githubusercontent.com/22136083/212956799-43fdffd4-c023-4fda-b5af-8b6f9460c78e.png">

Is this an apples to apples comparison?  From what i saw in the hermes [docs](https://hermesengine.dev/docs/building-and-running) it looks like running `hermes forLoop.js`. would execute the input script, right?  Is hermes really that much faster or am I missing something here?

I'm relatively new to JS ecosystem so apologies if I'm missing something obvious here.

**Comment by tmikov** [comment]
@matthewmturner you are measuring Node's startup time, even if you run the same test with an empty .js file, you will get similar number. Hermes is indeed optimized for very fast startup, especially when running from precompiled bytecode. But for actual sustained performance for computation tasks, you will find v8 (NodeJS) much faster, perhaps 10x.

**Comment by matthewmturner** [comment]
@tmikov okay thanks for that info.  but just reiterate and make sure i am understanding completely.  the comparison i did is actually apples to apples in the sense that node and hermes are each performing the same task(i.e. they both executed javascript file), its just that hermes is optimized for fast startup which is why its so much faster in this super simple case.

I might be pushing it here but is there a way to run js through hermes post startup(of course i would look to do the same on node side)? i think this would be closer to real life scenario that were trying to benchmark for (i.e. a long running application).

thanks!

**Comment by matthewmturner** [comment]
Oh and I'm actually working towards comparing Hermes to JavaScriptCore and V8 directly. Just been using node as a testing ground. Ultimately this will be Hermes vs JSC vs V8

**Comment by tmikov** [comment]
@matthewmturner just run Node and Hermes with an empty file, measure the startup time and subtract it after from the real measurement. When testing Hermes, don't forget to run precompiled bytecode.

**Comment by matthewmturner** [comment]
@tmikov makes sense, thanks. and is the reason we run hermes with precompiled bytecode because that is how it actually works in react native? i.e when running a react native app hermes doesnt need to compile / interpret javascript?

**Comment by tmikov** [comment]
@matthewmturner Hermes was literally developed and exists in order to execute bytecode. It can also run JS directly from source, but that is only for convenience and will likely be slower.

**Comment by matthewmturner** [comment]
@tmikov understood, thank you. your guidance here has been invaluable and is greatly appreciated.

**Comment by vibhor-d11** [comment]
> how can we set commonJs flag while making our custom hermes runtime with 
` runtime_ = facebook::hermes::makeHermesRuntime();` and will it work with using require to load images etc?

**Comment by tmikov** [comment]
@vibhor-d11 I am sorry to say, CommonJS is no longer supported by Hermes. We had to disable it, since a feature that is not used by RN does not get any testing.
