### ISSUE TITLE
Debug builds extreeeemly slow with RN 0.71.0

### ISSUE THREAD

**Issue by tapz** [facebook/hermes#894]
## Bug Description

With RN 0.71.0 the application startup time is like 10x more than before and the UI reacts to touch about 10x slower than before. Before Hermes was slow, now it's super slow. Is there a way to enable hermes only for production builds as it's totally unusable with debug builds?

- [X] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 
React Native version (if any): 0.71.0
OS version (if any): Android 13
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64

## Steps To Reproduce

1. Start an app
2. Tap something on the ui.

code example:

**Comment by jpporto** [comment]
Hi,

This is an RN integration [issue](https://github.com/facebook/react-native/issues/35828).

John Paul
