### ISSUE TITLE
What is the release schedule of the project?

### ISSUE THREAD

**Issue by gaodeng** [facebook/hermes#90]
How do we use the latest improvements in hermes in the RN project?

**Comment by darekg11** [comment]
I do not know if this is the right way but what I am doing is that I am including `hermes-engine` in `dev-dependencies` and then in my `android/app/build.gradle` I am doing:  
```
project.ext.react = [
    entryFile: "index.js",
    enableHermes: true,  // clean and rebuild if changing
    hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
]
```
and
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermes-engine/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}
```
note that I am referencing `hermes` from `node_modules` instead of `react-native`

Woud love to hear if this is the correct way.

**Comment by mhorowitz** [comment]
We have not formalized a release schedule for Hermes yet.  We will try to release before each RN release, so RN can track Hermes changes without any extra effort.  So the best way to use the latest Hermes will be to use the latest React Native.

The latest version of Hermes today is v0.1.1.  The instructions given by @darekg11 above should work to use it with RN v0.60.5.  Once RN v0.61 is released, that should include the build.gradle changes above, but you will still need to update the version of hermes-engine in RN's package.json file, in the dependencies section.

If you want to use a newer version of Hermes than the latest release, you can download a recent build from CircleCI.  The process is a bit manual, and we can't really support it, but if you want to experiment, here's what you do.

1. https://circleci.com/gh/facebook/hermes/tree/master shows all the builds.  Find the most recent "npm" build (listed in the third column) and click on the number in the second column (`#458` is the latest right now).
2. This will take you to a URL like https://circleci.com/gh/facebook/hermes/458.  Manually append `#artifacts` to the URL
3. Under "Test Summary" a file tree will appear.  Drill down to `tmp/` -> `hermes/` -> `output/` until you see hermes-engine-v...tar.gz.  Note that the version number here is misleading; this is actually the version of the most recent release, although this is likely to be newer.  We'll try to improve this.
4. Change your app's package.json to point to this downloaded file.

Now you should be able to build your app with the new version of Hermes.  There is a caveat which is that you'll still be using the original version of React Native, which may not be compatible.  If you have issues building or running your app, you may need to [build Hermes and React Native from source](https://github.com/facebook/hermes/blob/master/doc/ReactNativeIntegration.md), which is a longer process.
