### ISSUE TITLE
hermes compile into WebAssembly ?

### ISSUE THREAD

**Issue by kimown** [facebook/hermes#91]
Like https://github.com/mbbill/JSC.js, and can execute bytecode  in browser?

**Comment by mhorowitz** [comment]
As far as I know, nobody has built anything like this for Hermes.  Looks like it could be a fun project for someone!

If this sort of thing is interesting to you, you may also be interested in BinaryAST.  This is a project to move parsing (but not compilation) to the server for browsers.  https://blog.cloudflare.com/binary-ast/ discusses this in more detail.
