### ISSUE TITLE
Is this a performance issue？

### ISSUE THREAD

**Issue by zjyyyyy123** [facebook/hermes#913]
## Bug Description

When I use the same version (v0.12.0) of hermes to interpret the A.js file, there is a noticeable performance difference.

**source of difference：**

1. Provided code for linux platform (https://github.com/facebook/hermes/releases/download/v0.12.0/hermes-cli-linux-v0.12.0.tar.gz)

2. Compile the source code according to the steps in the readme (https://github.com/facebook/hermes/releases/download/v0.12.0/hermes-cli-linux-v0.12.0.tar.gz)

**Different performance:**

==================hermes by build========================

real    0m1.507s
		user    0m1.506s
		sys     0m0.004s

==================hermes by linux========================

real    0m0.026s
		user    0m0.023s
		sys     0m0.004s

A.js：

```
var NISLFuzzingFunc = function (e, t, n) {
    'use strict';
    for (var INDEX = 0; INDEX < 1000; INDEX++) {
         var r = function () {
                for (var e = [], t = 0; t < 256; ++t)
                    e.push('%' + ((t < 16 ? '0' : '') + t.toString(16)).toUpperCase());
                return e;
            }()
    }
};
var NISLParameter0 = [
    null,
    362341217,
    false,
    function () {
        this.n = this.hg = this.Gm = this.ia = null;
    },
    88.2411919433889,
    [
        'C5A.SsK\'qME nU[d}v.pKUMDoAgA9lBaUwD%=`@\\JDup.WehGr5!s\\(VJ%kB]kzkzcsG[l%[PzXrFk0#T&j>c]l-?ZEESb\\=(2ioq9f4"P2%0{0S@R',
        undefined,
        ':^pr+}B,ye!U{%`B<DQcO%GcYeNb`C2HH',
        undefined,
        null,
        [
            0.6725845080018623,
            -1.0025030223410145,
            71952530.76152323,
            -56520.34315609283
        ],
        false,
        -103867,
        null
    ]
];
var NISLParameter1 = 'K._.g(?Vkyt\\u!AM)aTJ`';
var NISLParameter2 = '\'4qhBan9"i&"LM.VN\\UTdgL f5Czy,;6P]qNa!{7$L54NP!N\\[bUDm=w!>9$v(&d{rNrHbd0[l]qH\'z`W3FHhMo%#5:={c]^`fwV$e`Wl4rruc6DOnf=02q#Jd\\Vvzn';
var NISLCallingResult = NISLFuzzingFunc(NISLParameter0, NISLParameter1, NISLParameter2);
print(NISLCallingResult);
```

`

Hermes version: v0.12.0
		OS version (if any): linux
		Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): Linux version 5.4.0-131-generic (buildd@lcy02-amd64-092) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))

## Steps To Reproduce

**1.command：**

time ./hermes-0.12.0/build/bin/hermes -w  A.js

 time ./hermes-v0.12.0/hermes -w  $1

**2.result：**

real    0m1.507s
		user    0m1.506s
		sys     0m0.004s

real    0m0.026s
		user    0m0.023s
		sys     0m0.004s

## The Expected Behavior

I think the ideal result should be that the time difference between two Hermes running files from different sources is not much different

**Comment by tmikov** [comment]
The first binary must be a debug build.

**Comment by zjyyyyy123** [comment]
Could you please tell me why debug build is needed? In other words, what is the difference between the debug build and other versions?thanks~🙂

**Comment by zjyyyyy123** [comment]
By the way,Is the **debug build** you speak of compiled with the following command.
"cmake -S hermes -B build_release -G Ninja -DCMAKE_BUILD_TYPE=Release
 cmake --build ./build_release"

**Comment by zjyyyyy123** [comment]
As far as I know, Debug is usually called a debug version, which contains debugging information and does not make any optimizations, which is convenient for programmers to debug programs. Release is called a release version, which is often optimized to make the program optimal in code size and running speed, so that users can use it well.

But the first version I show is indeed a **debug build**.I use the command to build it-'**cmake -S hermes -B build -G Ninja**'.I'm wondering if I'm not understanding the meaning of the command.Thank you~

**Comment by neildhar** [comment]
@zjyyyyy123 By default, if `-DCMAKE_BUILD_TYPE` is not specified, we produce a debug build. If you'd like a release build, you can add `-DCMAKE_BUILD_TYPE=Release`.

If you're interested in the exact CMake invocation we use for our CLI release, you can view that in our CI config here (note that most of these flags pertain to creating a statically linked executable, which may not be of interest to you): https://github.com/facebook/hermes/blob/e816a65a4ce729ff9892b33d927791e67b121698/.circleci/config.yml#L118-L121

**Comment by zjyyyyy123** [comment]
Thanks for your reply, I think my problem has been solved :)
