### ISSUE TITLE
crypto.getRandomValues support (compatibility with uuid 7.x, nanoid, etc.)

### ISSUE THREAD

**Issue by LinusU** [facebook/hermes#915]
## Problem

Today, almost all JavaScript environments supports a way to get cryptographically secure random data: `crypto.getRandomValues`. This has led many libraries to switch away from the insecure `Math.random` to this `crypto.getRandomValue`. This is supported in all modern browsers, Node.js, Deno, etc.

When using these libraries inside of Hermes, they do not work. There is a (react native specific) polyfill available: https://github.com/LinusU/react-native-get-random-values

But having to add a polyfill isn't a great user experience.

## Solution

I think that we should add support for `crypto.getRandomValues` directly into Hermes. This way we could ensure that a performant implementation is always available for this libraries to use.

I would be happy to submit a PR for this, with some guidance!

## Additional Context

I originally proposed adding this to React Native a long time ago: https://github.com/facebook/react-native/pull/20686

There is also some discussion here: https://github.com/expo/expo/issues/7209, https://github.com/expo/expo/issues/17270

I think that it's even more relevant now, since e.g. Node.js has added this, and it's even more widespread now since most JS libraries aren't written with React Native in mind.

**Comment by LinusU** [comment]
@tmikov sorry for not responding earlier. Your reasoning makes sense, thank you for taking the time to post it 👍

**Comment by paulmillr** [comment]
To reconsideration, additional points in #1003
