### ISSUE TITLE
Not able to build on windows

### ISSUE THREAD

**Issue by SergiOnGit** [facebook/hermes#92]
I follow building on windows instructions:

- git -c core.autocrlf=false clone https://github.com/facebook/hermes.git
- hermes/utils/build/build_llvm.py --build-system='Visual Studio 16 2019' --cmake-flags='-A x64' --distribute
- hermes/utils/build/configure.py --build-system='Visual Studio 16 2019' --cmake-flags='-A x64 -DLLVM_ENABLE_LTO=OFF' --distribute
- cd build_release && MSBuild.exe ALL_BUILD.vcxproj /p:Configuration=Release

It throws error on seconds step (Command: hermes/utils/build/build_llvm.py --build-system='Visual Studio 16 2019' --cmake-flags='-A x64' --distribute).

Using git bash.

**Full output:**
`hermes/utils/build/build_llvm.py --build-system='Visual Studio 16 2019' --cmake-flags='-A x64' --distribute
Cloning into 'D:\projects\hermes_workingdir\llvm'...
remote: Enumerating objects: 191753, done.
remote: Counting objects: 100% (191753/191753), done.
remote: Compressing objects: 100% (66125/66125), done.
remote: Total 191753 (delta 137208), reused 160358 (delta 124145), pack-reused 0
Receiving objects: 100% (191753/191753), 101.28 MiB | 4.21 MiB/s, done.
Resolving deltas: 100% (137208/137208), done.
Checking connectivity: 191753, done.
Checking out files: 100% (39256/39256), done.
Checking out files: 100% (19045/19045), done.
Note: checking out 'c179d7b006348005d2da228aed4c3c251590baa3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c179d7b00 [CFG Printer] Add support for writing the dot files with a custom prefix.
[detached HEAD a28c10fa0] Patch by Hermes build script
 6 files changed, 13 insertions(+), 2 deletions(-)
CMake Error at CMakeLists.txt:39 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "D:/projects/hermes_workingdir/llvm_build_release/CMakeFiles/CMakeOutput.log".
Source Dir: D:\projects\hermes_workingdir\llvm
Using Build system: Visual Studio 16 2019
Build Dir: D:\projects\hermes_workingdir\llvm_build_release
Build Type: MinSizeRel
Cloning LLVM into D:\projects\hermes_workingdir\llvm
+ C:\Program Files\Git\mingw64\bin\git.EXE -c core.filemode=false -c core.autocrlf=false clone --shallow-since 2018-10-08 https://github.com/llvm-mirror/llvm.git D:\projects\hermes_workingdir\llvm
+ C:\Program Files\Git\mingw64\bin\git.EXE -c core.filemode=false -c core.autocrlf=false checkout c179d7b006348005d2da228aed4c3c251590baa3
+ C:\Program Files\Git\mingw64\bin\git.EXE -c core.filemode=false -c core.autocrlf=false diff-index --quiet HEAD
+ C:\Program Files\Git\mingw64\bin\git.EXE -c core.filemode=false -c core.autocrlf=false apply --ignore-space-change --ignore-whitespace D:\projects\hermes_workingdir\hermes\utils\build\llvm-changes-for-hermes.patch
+ C:\Program Files\Git\mingw64\bin\git.EXE -c core.filemode=false -c core.autocrlf=false -c user.name=nobody -c user.email='nobody@example.com' commit -a -m Patch by Hermes build script
CMake flags: -A x64 -DLLVM_TARGETS_TO_BUILD= -DCMAKE_BUILD_TYPE=MinSizeRel -Thost=x64 -DLLVM_INCLUDE_EXAMPLES=Off -DLLVM_VERSION_PRINTER_SHOW_HOST_TARGET_INFO=Off -DPYTHON_EXECUTABLE=C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe
CMake version:
b'cmake version 3.15.2\n\nCMake suite maintained and supported by Kitware (kitware.com/cmake).\n'
+ C:\Program Files\CMake\bin\cmake.EXE -G Visual Studio 16 2019 D:\projects\hermes_workingdir\llvm -A x64 -DLLVM_TARGETS_TO_BUILD= -DCMAKE_BUILD_TYPE=MinSizeRel -Thost=x64 -DLLVM_INCLUDE_EXAMPLES=Off -DLLVM_VERSION_PRINTER_SHOW_HOST_TARGET_INFO=Off -DPYTHON_EXECUTABLE=C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe
Traceback (most recent call last):
  File "hermes/utils/build/build_llvm.py", line 204, in <module>
    main()
  File "hermes/utils/build/build_llvm.py", line 180, in main
    cwd=args.llvm_build_dir,
  File "D:\projects\hermes_workingdir\hermes\utils\build\common.py", line 75, in run_command
    return subprocess.check_call(cmd, stdout=sys.stdout, stderr=sys.stderr, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '-G', 'Visual Studio 16 2019', 'D:\\projects\\hermes_workingdir\\llvm', '-A', 'x64', '-DLLVM_TARGETS_TO_BUILD=', '-DCMAKE_BUILD_TYPE=MinSizeRel', '-Thost=x64', '-DLLVM_INCLUDE_EXAMPLES=Off', '-DLLVM_VERSION_PRINTER_SHOW_HOST_TARGET_INFO=Off', '-DPYTHON_EXECUTABLE=C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\python.exe']' returned non-zero exit status 1.`

Please help to solve!

**Comment by haozhun** [comment]
Your paste has a line: "could not find any instance of Visual Studio."

Do you have Visual Studio installed? It is required for building Hermes from source on Windows. Does the Visual Studio version matches the Generator you're using (`Visual Studio 16 2019`)?

I'd like to remind you that (which is also available in this repo's README)

> If you're interested in using Hermes in a new or existing React Native app, you do not need to follow this guide or have direct access to the Hermes source. Instead, just follow [these instructions to enable Hermes](https://facebook.github.io/react-native/docs/hermes).

**Comment by SergiOnGit** [comment]
I have visual studio installed. Before i install it there was other error. Okey i need hermes for new react native application and you say i dont need to follow this guide necause i have direct access to the hermes source but probles is that when i enable hermes in rn app build fails and error is that it can't open hermes.exe and can you help me here?

**Comment by SergiOnGit** [comment]
> In your new React Native project, can you run a `npm install hermesvm@0.1.1` and try again?
> 
> React Native 0.60.5 still uses the deprecated package name `hermesvm`, which did not have the latest bugfixes for Windows. I just published 0.1.1 containing some missing DLLs for Windows, which may have been the cause of your problem.
> 
> RN 0.61.0 will migrate completely to `hermes-engine`, where this is not an issue.

Still the same error. is `npm install hermesvm@0.1.1` enough?Because it doesn't work.

**Comment by mhorowitz** [comment]
We believe this is fixed with the migration to hermes-engine.  Please reopen if you still have issues.
