### ISSUE TITLE
Supported Language Features

### ISSUE THREAD

**Issue by Norfeldt** [facebook/hermes#921]
## Description

I am aware that there is https://hermesengine.dev/docs/language-features 

Before Hermes I burned my fingers using notation like `10_000 `or `Intl`. But is there a way for me to be warned by either TS or eslint?

I'm using `babel-preset-expo` and my tsconfig looks like:

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "jsx": "react",
    "strict": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"]
    },
    "types": ["node", "jest"]
  }
}
```

Should I set the target to `ES2015` ???

-----------------------

BTW perhaps it should be considered if Hermes should be listed on MDN like node and deno is

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

<img width="1157" alt="Screenshot 2023-02-24 at 10 35 20" src="https://user-images.githubusercontent.com/678806/221144121-9b638441-c25d-4602-ab57-0d3bd2f0ad5f.png">

**Comment by tmikov** [comment]
Hi, this is certainly a good idea, but unfortunately not something that we can help with...

FWIW, a lot of these features will be supported in the next major releases of Hermes, so you will not need warnings.
