### ISSUE TITLE
Terminating JS Execution

### ISSUE THREAD

**Issue by jacobp100** [facebook/hermes#929]
I've maintain a [web-worker](https://github.com/jacobp100/react-native-webworker) package for React Native that used to just spin up a new bridge, but I recently added a "light" mode that just spins up JSC or Hermes directly

For my use-case on this package, I have a calculator app that has things like summations and expensive operations, so it's relatively easy to write an equation that'd take a long time to finish - so I need a way to cancel them

My current solution is to add the `-emit-async-break-check` flag when compiling and then call `_runtime->watchTimeLimit(0)` to cancel the execution

Is this the best approach for this, or is there a more optimised way of doing this?

I noticed that when I added the flag, my byte-code skyrocketed from 10kb to 170kb (no typo - 17x increase). Is this expected - or is this possibly turning on additional flags I may be able to turn off?

**Comment by neildhar** [comment]
Thanks for reporting this. Could you share a repro for the JS you are compiling and the compilation command? That will help us investigate the problem.

Also, note that there is currently no thread-safe way to interrupt execution from another thread (although there should probably be one). `watchTimeLimit` may not be invoked from another thread, since it modifies runtime state in unsafe ways.

If you're imposing a fixed time limit, could you set the `watchTimeLimit` with a non-zero value before execution starts?

**Comment by jacobp100** [comment]
Yep! You can grab a copy of that code here:-

https://github.com/jacobp100/jacob-does-code/blob/master/assets/technicalc/dist/worker.min.js

Using the version of Hermes in react native 0.71, I see a 17x increase when adding the async break checks

I don’t know a fixed time before running - it’s only when a loading spinner shows up and the user hits ‘cancel’

Can I call `triggerTimeoutAsyncBreak` instead? How bad would it be to call it regardless - the alternative is spinning a computation in the background 🤣

**Comment by tmikov** [comment]
@jacobp100  When I compile with and without -emit-async-break-check, both versions are around 155KB, the -emit-async-break-check is only slightly larger.

I am not sure how you are getting 17KB bytecode from a 107KB minified input JS file. Can you double-check that?

**Comment by jacobp100** [comment]
Sorry yes - it looks like you're right. I'm not sure how I ended up with a 10kb file - I was pretty shocked too since the minified one was 100kb. Running now I get 171kb vs. 172kb - negligible.

**Comment by tmikov** [comment]
171KB seems high. I am getting 155KB and about 120KB if I strip the backtrace information. What is the exact command you are using?

**Comment by jacobp100** [comment]
The increase is coming coming from using the React Native bundler -

```
yarn react-native bundle --dev false --assets-dest ./ios --entry-file worker.js --platform ios --bundle-output ./ios/worker.jsbundle
```

Bumps it from 110kb JS to 118kb.

```
./ios/Pods/hermes-engine/destroot/bin/hermesc -emit-binary -emit-async-break-check ./ios/worker.jsbundle -out ./ios/worker.jsbundle
```

Which gives 170kb. Interestingly if you add the `--minify false` to the React Native bundler, it increases this size to 172kb. I'm not sure if that's expected - there might be some optimisations in how it generates the bundle runtime causing that.

I think in my case I probably don't need to bundle, because it's already a bundled file. But it's quite nice to be able to use the React Native bundle loading code, which does on the fly compilation in development - and also I think for most users of the web worker package, they'd need to bundle their worker.

What are your thoughts of making `triggerTimeoutAsyncBreak` a public function? Maybe by another name - JSC calls this `notifyNeedTermination` - I guess that makes it clear it's an async process. I'd be happy to submit a best effort PR - C++ is still very new to me though - but it looks easy enough.

**Comment by jacobp100** [comment]
I've added a PR for the termination method

Sorry for all the confusion with bundle sizes too - I figured out what went wrong: I was working in both my calculator project and the web worker library - I managed to mix up the JS bundles between the two, and the latter is just a _hello world_ bundle.
