### ISSUE TITLE
hasIndices flag for regex

### ISSUE THREAD

**Issue by roryabraham** [facebook/hermes#932]
## Problem

We were trying to use a regex with the `-d` / `hasIndices` flag, and noticed that it worked on web but not iOS/Android. I then discovered that it looks like this flag is just not yet implemented in the Hermes engine: https://github.com/facebook/hermes/blob/417190297242f14fed540378390d28926c2a7f7e/include/hermes/Regex/RegexTypes.h#L213-L343

## Solution

Implement the `-d` / `hasIndices` flag for Hermes regex.

## Additional Context

Our use case for the `-d` flag is described [here](https://github.com/Expensify/App/pull/15611#pullrequestreview-1322663118)

**Comment by roryabraham** [comment]
This was implemented in https://github.com/facebook/hermes/pull/968 and should land in the next hermes release I think?

**Comment by roryabraham** [comment]
https://github.com/facebook/hermes/commit/2afc7b09ffc74201b4dd530d9414b48e61a5196f does not appear to be included in a release yet, but hopefully soon 🙂

**Comment by fbmal7** [comment]
@roryabraham This feature will be in 0.73.
