### ISSUE TITLE
Explanation of the objects in the heap snapshot summary

### ISSUE THREAD

**Issue by Chris-Guy** [facebook/hermes#936]
## Description

Hello!

I am using the heap snapshot on my 0.69 React Native app (the feature is awesome!), but I am finding it hard to know what kind of objects are represented in the summary tab, notably "CodeBlocks", "RuntimeModule" and "Environment".
See below screenshot:

![image](https://user-images.githubusercontent.com/6816661/224114515-1ab404b6-a1de-4d65-abe1-9fe3bfbfb80c.png)

For example for RuntimeModule, it looks like it is a collection of "CodeBlocks", but I don't much more detailed information.

![image](https://user-images.githubusercontent.com/6816661/224114835-65d31a1b-f4a7-48eb-9724-d61113f7b57d.png)

Can you explain more what it is? Is it possible to get more info on which part of the JS code has constructed these objects?
This could be added in the Memory Profiler section of the documentation (https://hermesengine.dev/docs/memory-profilers/)

**Comment by tmikov** [comment]
A CodeBlock is the memory representation of the metadata for a JS function bytecode. It doesn't contain the bytecode, just describes it. There is a 1-to-1 correspondence between a JS function in the source code and a CodeBlock, but in some cases CodeBlocks can be created lazily.

**Comment by avp** [comment]
The linked Memory Profilers page has some discussion of what Environment is.

`RuntimeModule` and related concepts are more thoroughly explained in the VM docs: https://hermesengine.dev/docs/vm#runtime
