### ISSUE TITLE
How to use Map in Hermes?

### ISSUE THREAD

**Issue by iampennyli** [facebook/hermes#952]
I have written a demo as follows.

<img width="337" alt="截屏2023-03-31 11 31 06" src="https://user-images.githubusercontent.com/14218414/229015935-4eeba732-3fca-49dc-962f-b509af8abd02.png">

It's very simple. I just converted a JavaScript object to a JavaScript Map and returned it.

Afterward, I used the API provided by the Hermes SDK to execute the code, retrieve the 'testMap' function, call it to get the returned Map data and iterate through the Map to print all the items.

<img width="789" alt="截屏2023-03-31 11 30 26" src="https://user-images.githubusercontent.com/14218414/229016031-c7832c8b-1437-40f8-a958-26da16ba18a8.png">

When I ran this code and used the 'getPropertyNames' API to retrieve the array, the length of the array was 0, meaning that no data was retrieved.

However, when I changed the Map in the JavaScript code to an Object, I was able to retrieve all the items in the Object when running the code.

<img width="311" alt="截屏2023-03-31 11 28 33" src="https://user-images.githubusercontent.com/14218414/229015637-8936e5bb-b820-4864-9bf7-f226e902639e.png">

The result printed on the console is as follows:

<img width="97" alt="截屏2023-03-31 11 29 29" src="https://user-images.githubusercontent.com/14218414/229015753-3b61230c-c825-4f0e-bef5-4a4650ebf0f5.png">

I noticed that the [Language Features](https://hermesengine.dev/docs/language-features) of Hermes support Map, but I couldn't find any definitions related to Map in the JSI types provided by the Hermes SDK (so I had to use the Object type for checking). Is there something wrong with the way I am using it?

Hermes SDK v0.12.0

**Comment by tmikov** [comment]
`getPropertyNames()` returns an array of property names. As you can see here, Map entries are not properties: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map . You can query the entries by using [Map.prototype.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/entries).

JSI doesn't have any Map-specific support, Map methods can be called like any other JS object methods.

**Comment by iampennyli** [comment]
> `getPropertyNames()` returns an array of property names. As you can see here, Map entries are not properties: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map . You can query the entries by using [Map.prototype.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/entries).
> 
> JSI doesn't have any Map-specific support, Map methods can be called like any other JS object methods.

Great reply, thanks！
