### ISSUE TITLE
Array.prototype.reverse() inconsistent results

### ISSUE THREAD

**Issue by Georgezxh** [facebook/hermes#973]
## Bug Description
Hermes version: 0.12.0

When executing the following code, I found the result of hermes is different from other js engines (such as V8 in Chrome, ChakraCore in Edge).

## code example
```
let arr = [];
arr[1000] = 321321;
let proto = {};
Object.defineProperty(proto, 0, {get: function() {
    arr[2000] = 12222223456;
    return 123;
},set: function() {
}});

arr.__proto__ = proto;
Array.prototype.reverse.call(arr);
Array.prototype.reverse.call(arr);
print(arr);
print(arr[2000]);
```

## Output
[object Array]
123

## The Expected Behavior
[object Array]
12222223456

**Comment by tmikov** [comment]
I tested this with several engines and they all print the same result as Hermes.

If you still believe this is a bug, please feel free to re-open and point to the relevant part of the spec describing the correct behavior.
