### ISSUE TITLE
Inconsistent behavior in localeCompare

### ISSUE THREAD

**Issue by Georgezxh** [facebook/hermes#975]
## Bug Description
'a' is before 'A', so the first result should be negative number.
When adding parameter{ sensitivity: 'base' }, 'a' should be equal 'A', so the second result should be 0.

Hermes version:0.12.0

## code example:
```
var a = 'a'; 
var b = 'A'; 
print(a.localeCompare(b));
print(a.localeCompare(b, 'en', { sensitivity: 'base' }));
```
## Output
-1
-1
![image](https://user-images.githubusercontent.com/50438846/233784168-0e094fb1-31cb-4f84-8a52-922dacfceb88.png)

## The Expected Behavior
-1
0

**Comment by tmikov** [comment]
This works in the most recent version of Hermes on MacOS. So, can you please provide the following information:
- What version of Hermes?
- What platform?
- Are you certain that Hermes is configured with Intl (`echo 'print(Intl)' | hermes -`)

**Comment by Georgezxh** [comment]
Sorry. My version is the latest and os platform is ubuntu 20.04. However the HERMES_ENABLE_INTL is off. Thanks.
