### ISSUE TITLE
Hermes crashes when call AggreageError constructor.

### ISSUE THREAD

**Issue by JimWongM** [facebook/hermes#977]
## Bug Description

Hermes crash when I run test.js below. The reason may be the handler count exceeds the handlesLimit(48). I don't understand why so many handlers need to be created to call AggregateError constructor.

This bug only exists in the debug version, ```handlesLimit``` does not exist in the release version.
```
//include/hermes/VM/HandleRootOwner.h
#ifndef NDEBUG
  /// Maximum number of handles the scope is allowed to allocate in debug mode.
  unsigned const handlesLimit_;
  /// Number of currently allocated handles.
  unsigned numAllocatedHandles_{0};
#endif
```

StackTrace:
```
hermes: /home/wjm/hermes/hermes/include/hermes/VM/HandleRootOwner.h:445: hermes::vm::PinnedHermesValue *hermes::vm::GCScope::newPinnedHermesValue(hermes::vm::HermesValue): Assertion `getHandleCountDbg() < handlesLimit_ && "Too many handles allocated in GCScope"' failed.
```

Hermes version: ab9110de7d37375982785ef674d86679093831cd
React Native version (if any):
OS version (if any):
Platform: x86_64

## Steps To Reproduce

Hermes should be compiled in Debug mode.
```./hermes test.js```

code example:
```
function main(){
AggregateError(("64").padEnd("64"));
}; main();

```
## The Expected Behavior
V8 does not crash, but Hermes crashes.

**Comment by tmikov** [comment]
Thank you for catching this! It is very similar to https://github.com/facebook/hermes/issues/976 . It is not a problem in production and should be easy to fix.

**Comment by JimWongM** [comment]
Thanks for your quick reply.
