### ISSUE TITLE
Garbage Collector not picking up high memory pressure when memory is allocated in native HostObjects

### ISSUE THREAD

**Issue by chrfalch** [facebook/hermes#982]
### Background
There are multiple reports about memory issues in Hermes that seems to be caused by or be related to the garbage collector in Hermes not picking up native allocations done in C++ based HostObjects. 

A host object can allocate memory using malloc or other mechanisms, and the Garbage won't see this memory. This again causes the host object to be considered too small to be garbage collected and for performance reasons will be kept alive.

We're seeing this extensively in our React Native library `@shopify/react-native-skia` where the Skia API is implemented in C++ as Host Objects using JSI.

### Example
An example is our image component where we allocate and load images that can be of any size. The Hermes Garbage Collector will only see our image component (which is only pointed to by the Javascript engine, we don't keep any internal registries of objects - they're always returned and kept alive by JS) as a super small JS object and never deallocate this. 

We've used some tricks like providing hooks that cleans up the allocated memory to make this work, but some of our objects are not exposed through hooks and will therefore not be cleaned up by GC.

### Testing
We've tested these things switching back and forth between JSC and Hermes which verifies that this is an issue.

### References
Here are some references to other issues in the Hermes repo that might be related:

- [[Hermes] : leak in hermes when using rxjs](https://github.com/facebook/hermes/issues/922#issuecomment-1444591872)
- [fetch() BlobModule.java memory leak still exists on hermes-engine 0.9.0](https://github.com/facebook/hermes/issues/653)
- [Memory consumption on iOS](https://github.com/facebook/hermes/issues/878)
- [Out of Memory Issue](https://github.com/facebook/hermes/issues/637)

We've also seen some references in other repositories like this one from @Kudo in `react-native-v8`:

- [fetch() BlobModule.java memory leak fix not working if enable v8 js engine](https://github.com/Kudo/react-native-v8/issues/36)

In @shopify/react-native-skia  we have multiple issues regarding this and are constantly fixing new ones (and trying to change anti-patterns that allocate too many times like in animations):

- [Memory Leak when Navigating on iOS](https://github.com/Shopify/react-native-skia/issues/1403)
- [Mount/unmount of a Canvas element causes a memory leak](https://github.com/Shopify/react-native-skia/issues/1475)

### Alternative Solutions
There are several ways to move forward to solve this issue, the first one being us library developers being better at not using anti-patterns where we're not cleaning up after us. This is however not always easy, and a lot of the native code implementing HostObjects are doing so with the assumption that if you let Javascript / Hermes manage an object's lifespan everything should be good.

We can also look into expanding the jsi::HostObject interface to expose information about how much memory an object has allocated which can then be picked up by the garbage collector and used when calculating which objects we should free.

The garbage collector might need to look into not only its own allocated memory, but also the total memory used by the current process.

**Comment by tmikov** [comment]
I am not sure this qualifies as a bug, but it is indeed a practical issue that we need to address.

AKAIK, Java JNI provides no way to handle this. .NET, on the other hand has this: https://learn.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure 

Internally Hermes has a way for objects to report native memory allocations to the GC, so perhaps we need to expose it ass a HostObject API.

**Comment by tmikov** [comment]
@chrfalch how is this problem when using JSC instead of Hermes?

**Comment by chrfalch** [comment]
I agree that this is more a design / api issue than a bug, but seems like it should be addressed since it often results in unclear memory situations.

JSC seems to deallocate objects when memory is high even for jsi::HostObjects that allocates natively.

**Comment by tmikov** [comment]
@chrfalch you wrote that the problem disappeared when you switched your code to JSC. Are you using a JSC specific-API to notify it of memory pressure?

**Comment by chrfalch** [comment]
@tmikov JSC seems to run the garbage collector more frequently, and also seems to take the total memory pressure of the app into consideration when doing garbage collection (if I'm not mistaken totally). We're not using any JSC-specific APIs - we observe in Xcode and Android Studio that when running the app under JSC it will run garbage collection more often. 

We have a test where we allocate an image of a specific size on each frame - where the allocation is happening in C++ from inside a jsi::HostObject. Under JSC the memory is stable (not increasing) when run at 60fps - while on Hermes the memory is growing linearly and eventually causes the app to crash with an OOM error. 

When inspecting this in Xcode's memory graph we can verify a high number of image wrapping jsi::HostObjects not being released on Hermes, while they are released when using JSC. 

The only thing we do to compare this is to switch on/off hermes in the React Native application.

**Comment by tmikov** [comment]
@chrfalch have you tried invoking `gc()` periodically? Even if it turns out that it is impractical, at least it will provide conclusively what the problem is.

This is interesting, if JSC is running its GC so frequently, it must be consuming more power. I don't think hooking into the total memory consumption of the app is a valid approach and I doubt that JSC does it, because there are no guarantees that the memory pressure is related to the garbage collected heap.

**Comment by chrfalch** [comment]
@tmikov Yes, invoking `gc` periodically seems to help - I know some developers / users have added calls to `gc` on unmount to help with this issue.

Unfortunately I'm not sure about why JSC works here - could it be that it doesn't necessarily run more often, but it is triggered in a different way? I'm just speculating - we're seeing Hermes happily keeping hundreds of jsi::HostObjects alive even though each one of them has natively allocated several megabytes of memory - while JSC manages to detect this and clear out those objects. 

(jsi::HostObjects are created in a loop allocating a chunk of memory for images in this example, the only reference to the native objects are through `jsi::Object::createFromHostObject`).

**Comment by neildhar** [comment]
It is possible that JSC either tracks the overall memory pressure in the app, or just has a significantly smaller young generation region. One test to distinguish the two is to increase the memory associated with each HostObject by 10x or more, which results in more memory pressure for fewer actual allocated objects. If JSC continues to perform similarly, it suggests that it is tracking the overall memory consumption in the app.

RN [has a mechanism](https://github.com/facebook/react-native/blob/97b270253a80dca0a8fa7cd43e6a43fc13141d57/packages/react-native/ReactCommon/react/bridgeless/ReactInstance.cpp#L391) for dealing with memory pressure on Android by forcing a GC, it might also be worthwhile to explore something similar on iOS, to at least mitigate the worst case of an OOM.

**Comment by chrfalch** [comment]
It looks like JSC is tracking the total memory pressure in the app - making both small and large allocations in our jsi::HostObjects shows the same behaviour. It is a bit unscientific of me to say this - what we're seeing is basically that JSC is cleaning up jsi::HostObjects (containing both small and large allocation) so that memory stays low while Hermes is not doing it when those objects allocate internally. It is hard to tell what's triggering this since the objects are garbage collected pretty fast.

I've seen the code you referred to in RN, but that is for really low memory situations only - the garbage collection is not run by RN other than when the app is on the verge of collapsing into an OOM.

A problem with the approach of emitting GC calls when memory is high is that then we've already put the app in a state where it is consuming too much memory and it will be more likely closed by the OS when task switching etc - what we'd need would be a way to tell the Hermes garbage collector about our allocations - either explicitly or implicitly - or make the garbage collector be a bit more aggressive - ie. do garbage collection more often.

**Comment by neildhar** [comment]
Could you share the heap size that Hermes observes when your overall memory consumption is high? You can obtain this from JS using `HermesInternal.getInstrumentedStats()`.

**Comment by tmikov** [comment]
`HermesInternal.getInstrumentedStats()` is available by default in Hermes. You can just call it.

**Comment by chrfalch** [comment]
Ah... of course, I was trying to call it from C++. Javascript it is.

This is a test where we're allocating an image inside a jsi::HostObject 60 times pr. second. The screenshot is from Xcode and should show the memory usage from Xcode running the debugger and in the log window we see the reports from calling 
`HermesInternal.getInstrumentedStats()` at regular intervals (10 times pr. second):

<img width="478" alt="image" src="https://github.com/facebook/hermes/assets/875252/52285c1a-d21c-4396-bd46-19eda8377218">

**Comment by chrfalch** [comment]
Not sure if these numbers makes any sense - if you have more specific needs like “allocate 100 mb internally and then run getInstrumentStats” i can do that as well.it even looked like calling getInstrumentStats affected the memory usage on iOS after som more testing here.

**Comment by neildhar** [comment]
The relatively small JS heap (12MB) suggests that the ratio of external allocations to JS allocations is huge, and is likely the reason for the discrepancy you're seeing. The Hermes heap operates at a fairly coarse granularity of 4MB segments, so for very small heaps, our GC doesn't run as frequently as it might in other engines.

Dealing with really small heaps is something we want to improve on in the future. It is likely that JSC is just more aggressive when dealing with very small heaps, and so the short lived objects you allocate get reclaimed much more quickly.

This is not to say that Hermes would perform better if the volume of JS memory was significantly larger, but rather that I would expect JSC's memory advantage to diminish.

One aggressive strategy you could try (if this is all you're using the `HermesRuntime` instance for) is to set the initial heap size to something like 5MB, and the max heap size to 8MB, which would increase collection frequency. You can see an example of how we do that when producing a RuntimeConfig:
https://github.com/facebook/hermes/blob/89f41f61ee1ea8c6e8db90752260e2181d1273ad/tools/hvm/hvm.cpp#L118-L121

**Comment by chrfalch** [comment]
Thanks for the suggestion, @neildhar - Our main problem is that we're creating a library that is used by a lot of people (React-Native Skia) so it would be hard to enforce such configuration changes. We're looking into creating patterns for disposing our internally allocated memory using things like hooks where we can invalidate/dispose on unmount f.ex.

**Comment by wcandillon** [comment]
To provide additional context regarding this issue, it has compelled us to eliminate any JSI allocations during animation. This decision is beneficial not just because of the issue at hand but also because it enhances speed.

However, I'd like to shed light on some of the challenges we've faced in this context:
1. **Animated Images**: For every frame, a new SkImage (Skia Image) object is allocated by its API. To ensure this functions properly with Hermes, we have to explicitly delete the preceding SkImage upon assigning a new one.
2. **Paths and Matrices Animations**: In RN Skia, paths and matrices are represented as JSI host objects. We strive to avoid allocations here as well. We collaborated with [https://github.com/software-mansion/react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) to mutate a host object and subsequently notify the animation system about the mutated value (by default, value changes are based on the object's identity alteration). For functions that execute intricate transformations (like path interpolation), we've ensured no new host objects are allocated.

**Comment by tmikov** [comment]
@wcandillon the conceptual issue here is that Hermes uses memory pressure (the amount of allocated memory) to make decisions when to perform garbage collection, but it has no way of knowing how much additional native memory has been allocated. Hermes cannot track malloc usage (none of the JS engines do). Note that Hermes does not leak memory, it simply postpones running the GC until it decides it is needed. 

Generally speaking, when dealing with native resources, it is recommended to free the native resource explicitly when you are done with it, because garbage collection is unpredictable and should not be relied on for freeing native resources timely.

For example, see this StackOverflow answer about Java. It talks about files, but native memory is really the same thing: as far as the GC is concerned, it is a native resource that the GC knows nothing about:
https://stackoverflow.com/a/51685719

So, the solution you have implemented to delete every image explicitly is the conceptually correct solution.

**Comment by chrfalch** [comment]
Looks like this one addresses this issue with a solution that will be exactly what we need: https://github.com/facebook/hermes/commit/aae2c4260781178d7b2ca169811b3bfca9f924d2

Awesome!

**Comment by neildhar** [comment]
@chrfalch glad to hear that, closing this issue since the API has been added, and should be available in the next release of RN. Please try it out and let us know if you run into any issues, or are still observing high memory consumption.

**Comment by chrfalch** [comment]
Will do! Looking forward to test it.

**Comment by wcandillon** [comment]
@neildhar is there a flag we can use to check if the API is available or not? We should just check on the React Native version? That would be 0.74.0?

**Comment by chrfalch** [comment]
I don't think you'll find a flag - this is a method defined in a header file and linked when building - either you have it or you don't - and then it won't compile it you try to use it. 
Maybe it is possible to use some preprocessor tricks using the React Native Version number to perform some clever c++ tricks. @wcandillon

**Comment by neildhar** [comment]
Hey @wcandillon, it's difficult to know what might be happening without more information from your application or a standalone repro. If the amount of memory being retained in native is similar to the amount of JS memory allocated, you are right that the GC should be kicking in sufficiently frequently.

Some things that come to mind:
1. You could try capturing a heap snapshot from Hermes to see how the HostObjects are continuing to be retained.
2. I don't fully follow how this is structured, but is it the case that many JS objects retain some (much larger) shared state? It is possible that a small number of objects survive for a longer time, which may be keeping this larger state alive.
3. Could you share more information about the memory consumption and GC count trends reported by `getInstrumentedStats`?
4. Are you using WeakMap? There is a known issue in WeakMap that was fixed relatively recently.

**Comment by wcandillon** [comment]
Thank you for your reply.

1. What would be the best way for you to share a reproduction an React Native example app? If yes, can this process be done privately? Are there some test cases I could contribute that could try to reproduce the mentioned behaviour?
2. I would like to check two things:
-  Is invoking `gc()` supposed to be equivalent of seeing `js_numGCs` increased (meaning that Hermes has done a new garbage collection)? If yes, I can attest that I am seeing very different behaviour.
- The many JS host objects don't retain any larger shared state (they are all very small). Again invoking `gc()` periodically yields the expected result. Adding some "fake" memory pressure to each host object, yields the correct result as well.
3. About the heap snapshot, could you provide me some information on how I could help you investigate this behaviour?
4. We are not using WeakMap
5. Are you aware of APIs/Libraries using `setExternalMemoryPressure()` maybe it would shed some light on how we could leverage it more successfully.

**Comment by migueldaipre** [comment]
> > Are you using WeakMap? There is a known issue in WeakMap that was fixed relatively recently.
> 
> @neildhar Could you please link to the PR that fixed it? We're also suffering from "memory leaks" (or rather insufficient memory deallocations) in Reanimated and we're using `WeakMap` to cache `jsi::HostObject`s. I've tried using `setExternalMemoryPressure` but with no luck.

I think the fix was in this [commit](https://github.com/facebook/hermes/commit/e7b2abefabb6a9671e1d30d7af08cd1f32c9a670)

**Comment by tmikov** [comment]
@wcandillon I realized that I don't understand what the actual problem you are having is. Can you explain it again, from first principles, ignoring the conversation that happened?

What exactly is the bad behavior you are observing? For now let's ignore guesses of why it is happening, I would like to understand the exact symptoms.

**Comment by wcandillon** [comment]
I hope the following help and meets your expectations.

We run a 3d scene in React Native with Hermes.
On each frame we create:
* a dozen of pure JS objects (array buffers that represent 4x4 matrices). 
* a dozen of JSI host objects that represent encoded commands to be sent to the GPU. All the heavy GPU duty stuff is done in advance. On every new frame, we just need to send 
* Letting the example run on a device will eventually cause the app to freeze due to the large memory pressure (> 1GB). We can easily debug that the objects created at frame #1 are still alive one hour later.
* Invoking `gc()` at a regular interval (we randomly decided on 3 seconds) makes the example run smoothly. Invoking `gc()` too much visibly slows down the app.
* Using `setExternalMemoryPressure` is not helpful as the objects are very lightweight (~800 bytes). And in fact we can confirm that the data sent to the GPU on each frame is indeed very small. Increasing `setExternalMemoryPressure` to 10kb per object doesn't seem to change the observed behaviour.   Increasing `setExternalMemoryPressure` to 100kb per object triggers the garbage collector pretty quickly.

**Comment by tmikov** [comment]
@wcandillon thanks! So, around the time the app crashes or freezes, how many of these objects do you have? Assuming 1 GB of consumed RAM and setExternalMemoryPressure(800) per object, that is about 1.3 million objects. Does that sound right and can you confirm it?

Do these objects also retain any GPU resources or are they purely CPU RAM?

**Comment by wcandillon** [comment]
@tmikov That's correct. For instance, with 10k host objects created, the app memory usage is not that big at all yet. it only after a while that things spawn of out control. 

These objects don't retain any GPU resources (e.g shared buffers). We were careful to select an example simple enough. where on each frame we only send GPU commands.

With React Native Skia we were always able to circumvent this issue by offering declarative constructs (e.g. React components and hooks).  However in this particular case, we don't have control over the API. It is a W3C standard and there is an expectation that copy/pasting an example from the Web should work on React Native without any extra changes.

**Comment by tmikov** [comment]
@wcandillon do you have a more precise number of the alive host objects, shortly before a crash, than my 1.3 million guess?

**Comment by wcandillon** [comment]
We finally implemented `setExternalMemoryPressure` in RN Skia (about time hey?) and I can report that this has fixed a couple of memory issues (either related to memory overflow on Android or due to safe use of dispose() method which now is a noop).
