### ISSUE TITLE
Invalid Time Value when using Hermes Engine [iOS/Android]

### ISSUE THREAD

**Issue by ucheNkadiCode** [facebook/hermes#986]
## Bug Description
Specifically if I have  hermes enabled in iOS or Android, this code fails

```
 uniqueDates.forEach((date, index) => {
      const workoutsOfDate = filter(
        userProfile.workoutsCompleted,
        (item) => {
          return format(new Date(item.dateCompleted), "MM/dd/yy") === date;
        }
      );
```
All of the dates getting passed in are in the format of `"2023-04-28T07:07:24.650Z"`

I'm using `filter` from lodash and `format` from date-fns which is expecting a Date object. Unless Hermes actually interacts with Lodash or date-fns, I doubt that is the cause.

The variable `date` being passed into the function is already formatted in a "MM/dd/YY" fashion

## Steps To Reproduce

Get a date such as `"2023-04-28T07:07:24.650Z"` then say new Date("2023-04-28T07:07:24.650Z") anywhere in your code. 

This crashes with error `invalid time value`

If I change my ios or Android projects back to hermes_enabled = false then clean and rebuild my project, this same code works.

There could be an issue with the Hermes date parser. The other java engine works perfectly.

This was enough for me to disable Hermes

- [x ] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: I'm not sure. It's included in React
React Native version (if any): 0.71.7
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.6.2 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.7 => 0.71.7

**Comment by tmikov** [comment]
Just tried it with top of tree Hermes CLI as well as the [Hermes playground](https://hermesengine.dev/playground/). They both work as expected with the following code:
```
print(new globalThis.Date("2023-04-28T07:07:24.650Z"));
```

Are you sure this isn't a Date polyfill?

**Comment by ucheNkadiCode** [comment]
I’m not sure what a date polyfill is. But when I turn off Hermes it starts working

**Comment by tmikov** [comment]
Can you please attach the JS stack trace of the exception?

**Comment by ucheNkadiCode** [comment]
Sorry, feel free to close this issue. I simply chose to turn off Hermes and my code is working on both platforms.

**Comment by joseocabarcas** [comment]
I have the same problem in React Native with Hermes enabled when use `new Date('2022/07/11')` this return NaN. I think the problem is character `/` because when use `new Date('2022-07-11')` work

**Comment by neildhar** [comment]
@joseocabarcas The best way to get consistent behaviour across JS engines with regards to parsing dates would be to use ISO 8601 (e.g. "2022-07-11" as you observed), since that is laid out in [the spec](https://262.ecma-international.org/12.0/#sec-date-time-string-format). Other formats are implementation dependent.
