### ISSUE TITLE
Support for `URL`

### ISSUE THREAD

**Issue by itsezc** [facebook/hermes#987]
## Problem

A lot of NPM packages rely on the `URL.protocol` method to dictate various functionalities related to network connections i.e. for instance, the SurrealDB JS library

## Solution

Adding support for `URL` would allow for advanced functionalities within packages like SurrealDB JS, among others.

## Additional Context

N/A

**Comment by tmikov** [comment]
Hi, URL is not part of the JS spec, it a web API provided by the integrator of the JSVM (the web browser, NodeJS, etc). We periodically get requests like this and do appreciate that it would be convenient to provide APIs like this "out of the box". However it is not practical for our team to maintain an ever expanding set of Web APIs, which are not in our area of expertise.

I have previously suggested that it might make sense to create a separate project with a repository of common non-EcmaScript APIs.

**Comment by tmikov** [comment]
FYI, https://github.com/facebook/hermes/discussions/1072 .
