### ISSUE TITLE
React-Native Android: [Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting number.

### ISSUE THREAD

**Issue by stefandbd** [facebook/hermes#990]
## Bug Description
Happening only on React-Native on Android:

[Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting number.
com.facebook.hermes.intl.JSRangeErrorException: Invalid number value !
RangeError: com.facebook.hermes.intl.JSRangeErrorException: Invalid number value !

Hermes version: 0.11
React Native version (if any): 0.70.6
OS version (if any): Android 13, API 33
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): M1

## To Reproduce

`import {FormattedNumber, useIntl} from 'react-intl';`

```
                  <FormattedNumber
                      maximumFractionDigits={2}
                      value={40.5}
                      style="currency"
                      currency="GBP"
                  />
```

**Have to mention that if I remove style="currency" the error is gone - but of course it doesn't show anymore the GBP currency sign.**

## Polyfills integrated in index.js

```
import '@formatjs/intl-getcanonicallocales/polyfill';
import '@formatjs/intl-locale/polyfill';
import '@formatjs/intl-numberformat/polyfill';
import '@formatjs/intl-numberformat/locale-data/en';
import '@formatjs/intl-datetimeformat/polyfill';
import '@formatjs/intl-datetimeformat/locale-data/en';
import '@formatjs/intl-datetimeformat/add-all-tz';
```

## Bundle

Tried both options:

```
// def jscFlavor = 'org.webkit:android-jsc:+'
def jscFlavor = 'org.webkit:android-jsc-intl:+'
```

Raised this bug on formatjs -> but they responded it is a hermes bug: https://github.com/formatjs/formatjs/issues/4096

**Comment by tmikov** [comment]
We are really not experts in all these packages and polyfills. So can you please narrow this down to one or two lines of JavaScript code, invoking the broken with API with fixed arguments, to demonstrate the error?

**Comment by iway1** [comment]
I think Hermes should not crash when a 0 is passed to `maximumFractionDigits` this should probably be reopened

**Comment by jdconley** [comment]
> I think Hermes should not crash when a 0 is passed to `maximumFractionDigits` this should probably be reopened

I just hit this as well. So does this mean we can't format numbers with no fraction digits with Intl?

**Comment by antoinerousseau** [comment]
I found a workaround: just add `minimumFractionDigits={0}` too!

```tsx
<FormattedNumber
  value={42.42}
  style="currency"
  currency="eur"
  minimumFractionDigits={0}
  maximumFractionDigits={0}
/>
```

**Comment by rdnsan** [comment]
> I found a workaround: just add `minimumFractionDigits={0}` too!
> 
> ```tsx
> <FormattedNumber
>   value={42.42}
>   style="currency"
>   currency="eur"
>   minimumFractionDigits={0}
>   maximumFractionDigits={0}
> />
> ```

this work for me, thanks!
