### ISSUE TITLE
let declaration should declare a block-scoped local variable 

### ISSUE THREAD

**Issue by JimWongM** [facebook/hermes#993]
## Bug Description

Hermes outputs different results with v8, JSC.

Hermes version: 3d8da3d
React Native version (if any):
OS version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

```./hermes test.js```

code example:

test.js
```
for(let a=0;a<3;a++){
    for(let a=0;a<3;a++){
        print(a)
    }
    print(a)
}
```

Output:
```
0
1
2
3
```

## The Expected Behavior
Correct Result:
```
0
1
2
0
0
1
2
1
0
1
2
2
```

**Comment by tmikov** [comment]
https://github.com/facebook/hermes/blob/main/doc/Features.md
