### ISSUE TITLE
Is it possible to react-native integrate custom hermes build in linux arm aarch64? 

### ISSUE THREAD

**Issue by magbicaleman** [facebook/hermes#995]
## Problem
- The main goal is to build android *.app or *.apk using gitlab cli on linux-arm.
- The reason I'm trying to build a custom version of hermes is because I'm getting the following error:

```
  * What went wrong:
  [RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets'.
  [RUN_GRADLEW] > OS not recognized. Please set project.react.hermesCommand to the path of a working Hermes compiler.
```
- Which seems to be coming from this block of code:
  - https://github.com/facebook/react-native/blob/81e297403714c6a62e7a8a70a1cc685542d5767d/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/PathUtils.kt#L180

Following [these instructions](https://github.com/facebook/hermes/blob/main/doc/ReactNativeIntegration.md) I'm expiring the following:

When I run `(cd $HERMES_WS_DIR/hermes/android && ./gradlew githubRelease)` I get the following error:

```
51 29.56 A problem occurred configuring project ':cppruntime'.
#51 29.56 > Failed to notify project evaluation listener.
#51 29.56    > NDK not configured. Download it with SDK manager. Preferred NDK version is '21.1.6352462'. 
#51 29.56    > Task with name 'assembleRelease' not found in project ':cppruntime'.
```

When I run `(cd $HERMES_WS_DIR/build_release && ninja github-cli-release)` I get the following error:  
`ninja: error: unknown target 'github-cli-release'`

## Additional Context

- Did not get any errors when building based on these instructions
```
RUN cmake -S hermes -B build_release -G Ninja -DCMAKE_BUILD_TYPE=Release
RUN cmake --build ./build_release
```
  - https://github.com/facebook/hermes/blob/main/doc/BuildingAndRunning.md

**Comment by tmikov** [comment]
Let me see if I understand the problem: you want to build a RN app on Linux-ARM, but the RN distribution doesn't carry provide the CLI compiler (`hermesc`) for that architecture. Is that correct?

So it seems that you don't need a custom version of Hermes, you just need the compiler for your host architecture. As you said, you are already able to compile it.

I wonder, can you simply set `project.react.hermesCommand` to the path to `hermesc` which you compiled?

It also looks like https://github.com/facebook/hermes/blob/main/doc/ReactNativeIntegration.md is outdated, but you shouldn't need it in this case.

**Comment by magbicaleman** [comment]
@tmikov thank you very much for the reply. Really appreciate it, I was able to get past that Hermes error now encountering new error:

``` 
What went wrong:
  [RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets'.
  [RUN_GRADLEW] > OS not recognized. Please set project.react.hermesCommand to the path of a working Hermes compiler.
 ```

**New Error**; going to start looking into

```
[RUN_GRADLEW] Execution failed for task ':app:mergeReleaseResources'.
[RUN_GRADLEW] > Multiple task action failures occurred:
[RUN_GRADLEW]    > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
[RUN_GRADLEW]       > AAPT2 aapt2-7.4.1-8841542-linux Daemon #0: Daemon startup failed
[RUN_GRADLEW] This should not happen under normal circumstances, please file an issue if it does.
[RUN_GRADLEW]    > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
[RUN_GRADLEW]       > AAPT2 aapt2-7.4.1-8841542-linux Daemon #3: Daemon startup failed
[RUN_GRADLEW]         This should not happen under normal circumstances, please file an issue if it does.
[RUN_GRADLEW]    > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
[RUN_GRADLEW]       > AAPT2 aapt2-7.4.1-8841542-linux Daemon #2: Daemon startup failed
[RUN_GRADLEW]         This should not happen under normal circumstances, please file an issue if it does.
[RUN_GRADLEW]    > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
[RUN_GRADLEW]       > AAPT2 aapt2-7.4.1-8841542-linux Daemon #1: Daemon startup failed
[RUN_GRADLEW]         This should not happen under normal circumstances, please file an issue if it does.
```

**Comment by tmikov** [comment]
We on the Hermes team are not well versed with the React Native build, but I wouldn't be surprised if there are other x86-64 binaries that it relies on.

Does it work if you enable JSC instead of Hermes?

**Comment by magbicaleman** [comment]
@tmikov It does not work with `JSC` instead of `Hermes`. Looking into this thread:
- https://issuetracker.google.com/issues/227219818

Going to close the issue since my original post was resolved. Thank you again.

**Comment by tmikov** [comment]
@magbicaleman ah, so the problem is that the Android NDK doesn't support arm-linux. Wow, that sucks.

I wonder, would it be possible to use qemu-linux-user to get the whole thing working. Apple, for all their problems, did a great job with Rosetta.

**Comment by deelo55** [comment]
Trying to build expo via EAS on linux here, has anyone managed to get it working?

**Comment by jabedzaman** [comment]
> Trying to build expo via EAS on linux here, has anyone managed to get it working?

got solutions???

**Comment by HasanAlyazidi** [comment]
@magbicaleman  have you had success building a RN app on Linux ARM64
